### PR TITLE
add symbolic-icons used by gsconnet-extension

### PR DESCRIPTION
**Pull request by Muqtxdir**
added:

- [x] org.gnome.Shell.Extensions.GSconnect-symbolic (_symlink_)
- [x] laptop-symbolic
- [x] phonelink-symbolic
- [x] sms-symbolic

refined:

- [x] tv-symbolic
- [x] display-projector-symbolic

reduced svg sizes in phosh-dir

### CODE REVIEW

**Comment by Jupi007** [comment]
Thanks @Muqtxdir

Everything look very good, except the **display-projector-symbolic** icon. Very honestly I was preferring the old version.
This one looks like a screen suspended on the ceiling 😅

**Comment by Muqtxdir** [comment]
ok, I'll change the display-projector-symbolic

**Comment by Jupi007** [comment]
Thanks :)

**Review by Jupi007 — APPROVED** [review]
LGFM :+1: 

Thanks @Muqtxdir

**Comment by 3v1n0** [comment]
Mhmhm... It looks like this broke the symlink generation, I'd probably add a CI job to ensure this always work, given that it's fast enough.

```bash
git bisect run bash -c 'cd icons/src/symlinks/ && ./generate-symlinks.sh --variant default'

e489886410ef33606b4187736a08f9d2489bb0ea is the first bad commit
commit e489886410ef33606b4187736a08f9d2489bb0ea
Author: Muqtadir <muqtadir5555@gmail.com>
Date:   Sun Mar 20 20:08:25 2022 +0530

    add symbolic-icons used by gsconnet-extension (#3510)
    
    * Added symbolic-icons used by GSconnect and refined the existing ones.
    
    * revert display-projector-symbolic

 .../devices/display-projector-symbolic.svg         |  11 +-
 icons/Yaru/scalable/devices/laptop-symbolic.svg    |   1 +
 .../scalable/devices/phonelink-ring-symbolic.svg   |   1 +
 icons/Yaru/scalable/devices/tv-symbolic.svg        |   5 +-
 .../scalable/phosh/feedback-quiet-symbolic.svg     |   2 +-
 ...g.gnome.Shell.Extensions.GSConnect-symbolic.svg |   1 +
 .../Yaru/scalable/phosh/phone-docked-symbolic.svg  |   4 +-
 .../phosh/screen-rotation-portrait-symbolic.svg    |   2 +-
 icons/Yaru/scalable/phosh/sms-symbolic.svg         |   7 ++
 .../scalable/phosh/torch-disabled-symbolic.svg     |   2 +-
 .../Yaru/scalable/phosh/torch-enabled-symbolic.svg |   2 +-
 .../default/devices/display-projector-symbolic.svg |  91 +-------------
 .../scalable/default/devices/laptop-symbolic.svg   |   1 +
 .../default/devices/phonelink-ring-symbolic.svg    |   1 +
 icons/src/scalable/default/devices/tv-symbolic.svg |  68 +---------
 ...g.gnome.Shell.Extensions.GSConnect-symbolic.svg |   1 +
 icons/src/scalable/default/phosh/sms-symbolic.svg  | 138 +++++++++++++++++++++
 icons/src/symlinks/generate-symlinks.sh            |   2 +-
 icons/src/symlinks/symbolic/phosh.list             |   2 +
 19 files changed, 164 insertions(+), 178 deletions(-)
 create mode 100644 icons/Yaru/scalable/devices/laptop-symbolic.svg
 create mode 100644 icons/Yaru/scalable/devices/phonelink-ring-symbolic.svg
 create mode 120000 icons/Yaru/scalable/phosh/org.gnome.Shell.Extensions.GSConnect-symbolic.svg
 create mode 100644 icons/Yaru/scalable/phosh/sms-symbolic.svg
 create mode 100644 icons/src/scalable/default/devices/laptop-symbolic.svg
 create mode 100644 icons/src/scalable/default/devices/phonelink-ring-symbolic.svg
 create mode 120000 icons/src/scalable/default/phosh/org.gnome.Shell.Extensions.GSConnect-symbolic.svg
 create mode 100644 icons/src/scalable/default/phosh/sms-symbolic.svg
 create mode 100644 icons/src/symlinks/symbolic/phosh.list
bisect run success
```

**Comment by 3v1n0** [comment]
Handled by commit eb28b5947644ad57a78f6573ce53f30069b6b6de (and ensured by 53da6c3858e0a53a9b3d48f3f69cd35fce3dbc64)

**Pull request merged**
