### PR TITLE
New sound for email notifications

### PR DESCRIPTION
**Pull request by madsrh**
A suggestion for a new email notification sound. Although it doesn't fit with the current wooden sounds, I find it very refreshing, but potentially also more annoying.

This is from [Ubuntu Touch 13.10](https://launchpad.net/ubuntu/+source/ubuntu-touch-sounds/13.10.1) - yeah 👴

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1187`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1187` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
I see what you mean by more "annoying" :)

**Comment by madsrh** [comment]
LOL Was that a -1 @clobrano?

**Comment by clobrano** [comment]
Yes, sorry ;D

**Pull request closed without merging**
