### PR TITLE
TESTING PR: More contrast for context menus

### PR DESCRIPTION
**Pull request by madsrh**
More contrast for context menus and popovers 🙈 

This might be a bit too much but IMO the backgrounds in master still blend a bit together 🤷‍♂ 

Left is master and right is `lighten(bg_color, 2%)`

image

image

image

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
LGTM, changes in colours are mostly the best and safest changes :)
And it still has contrast on both bgcolor and basecolor
(Just woke up because my daughter ran screaming into our bedroom... Nightmare)

**Comment by Feichtmeier** [comment]
Ah wait... About the dark popovers. I'm not sure. Do you see that the buttons are now the same colour again? :)

**Comment by madsrh** [comment]
I see your point. Also I've noticed that the checked radiobuttons, especially on hover, blend.

I added popovers to align the two (menu and popover), but we could just change $menu_color only

**Comment by Feichtmeier** [comment]
Yeah better keep popovers as they are, they are also matched in the shell

**Comment by madsrh** [comment]
Like this @Feichtmeier ?

**Pull request merged**
