### PR TITLE
[bionic] snapcraft.yaml: better versioning

### LINKED ISSUE #1534: Please give better version number to the Bionic snap (stable and edge)
The Bionic snap has a constant version number 0.1 for both the stable and edge channels.
Please give better versions to distinguish between them, and to let users know that the theme is being updated without looking to the publishing date.

### PR DESCRIPTION
**Pull request by clobrano**
Replace hard-coded versioning with automatic one based on git

New versioning will be "Major.minor", where Major is the latest tag in
the branch and minor the number of commits since the latest tagged one.

closes #1534

### CODE REVIEW

**Comment by didrocks** [comment]
Nice that snapcraft has that feature now! Great work :+1:

**Comment by clobrano** [comment]
:D but it's not working yet. Apparently `git` is not available in the image at that stage. I'm working on it

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1558`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1558` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1558`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1558` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
The current PR use `version: git` as well as gnome-calculator, the result is

    communitheme (edge/yaru-pr1558) 0+git.0e9a95a4

while gnome calculator shows a version like `3.34.0+git.xxxxx`. So it seems that this specific update does not see the bionic tags (r29). Probably it's just because it's a snap generated for testing? Would it work once merged in bionic branch?

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1558`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1558` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
It's working now, see "installed version" from this PR

image

**Pull request merged**
