### PR TITLE
Fix menu button hover

### LINKED ISSUE #1036: GtkToolbar button styling problems
1) the hover effect differs between the dark and the light variant (light is basically the normal buttons hover, but dark is flat and almost black)
peek 2018-12-12 10-16

2) the dark background hover is very strong (if we end up with a flat hovering or not, the dark backdrop looks like you teleport the backdrop button to the foreground :D )
peek 2018-12-12 10-08

3) Maybe we should compare it to the active effect in both variants

### PR DESCRIPTION
**Pull request by clobrano**
Add a specific check in hover to adapt bg color for menu buttons
use boders_color for borders in backdrop:hover

closes #1036 

peek 2018-12-13 17-28

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1042`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1042` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Comparing to normal buttons in the dark theme
peek 2018-12-13 17-45

**Comment by Feichtmeier** [comment]
Ahhh I think I know why... could it be that the $menu_color is pretty damn dark in the dark theme now? ;D Do we use the $menu_color for the :active effect?

**Comment by clobrano** [comment]
Yes, the base color is different, but I can have a look at the active.
Consider anyway that only the hover effect is 3D in toolbars, the rest is
flat since the ".flat" class is set

**Comment by clobrano** [comment]
We probably can't have the same, because of the dark colors, however, does this look better?

peek 2018-12-14 20-07

**Comment by Feichtmeier** [comment]
Oh yes, a lot! Don't you think? :D Gj!

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1042`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1042` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
But you have forgotten the backdrop :angel: 
image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1042`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1042` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
image
Perfetto! :)
Imho rdy to merge

**Comment by Feichtmeier** [comment]
Hmmm maybe the foreground checked could be a bit darker now that you introduced the new menuflag 
Like a darker border and a tiny bit darker BG 

I know very picky nitpicking but if you are working at this right now why not :D

**Comment by clobrano** [comment]
I made a little tweak for the color, but darker would be basically the same we had at the beginning

**Comment by Feichtmeier** [comment]
Yeah dark themes are a nightmare to style : /
I think this is better what do you think? Prefer this or prev commit?

**Pull request merged**
