### PR TITLE
Fix cursors shape and colors

### LINKED ISSUE #2923: Aubergine spinner could need an outline
@Benni3-1415 

I really enjoy the aubgergine spinner, but because it has a purple border it can look smaller than it actually is. Could you try to make it have a white outline?

https://user-images.githubusercontent.com/15329494/122654116-6313ec80-d149-11eb-89a1-7b609615a682.mp4

### PR DESCRIPTION
**Pull request by Jupi007**
Fix cursors shape and colors.

Capture d’écran du 2021-06-21 20-48-21

- Drop purple spinner (replaced by dark gradient background) ;
- Revert main cursor arrow shape.

Related to  #2925
Closes #2923 #2920

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thank you very much @Jupi007 !

And thanks @Benni3-1415 , please don't feel bad for the cursor shape, we really appreciate your contributions and keep the pointer!

**Comment by Feichtmeier** [comment]
Tested it locally @Jupi007 - works!

I just think that it still needs outline like the original suru cursor
grafik

**Comment by Jupi007** [comment]
> Tested it locally @Jupi007 - works!
> 
> I just think that it still needs outline like the original suru cursor
> grafik

I agree, will do this tomorrow :)

**Comment by Jupi007** [comment]
@Feichtmeier done:

Capture d’écran du 2021-06-22 11-40-27

**Comment by Feichtmeier** [comment]
Thank you @Jupi007 ! 🧙🥳

**Pull request merged**
