### PR TITLE
gnome-shell: Update theme for GNOME 46

### PR DESCRIPTION
**Pull request by 3v1n0**
Based on #4010

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Awesome thank you!

I guess @Muqtxdir and or @Jupi007 don't have time to look over the symbolics?

**Comment by 3v1n0** [comment]
Well there may be but I feel that's fine for now, so I'd land this asap.

**Comment by Feichtmeier** [comment]
okay only the toggle and process SVGs need fixing. Can I fix this now and send you the SVGs?

**Comment by Feichtmeier** [comment]
okay, doing it now

**Comment by Muqtxdir** [comment]
hi @3v1n0 

gimme couple of minutes I'll update yaru symbolics and push to this branch

**Comment by 3v1n0** [comment]
@Muqtxdir the files were already auto-generated, not sure if we need something else :)

**Comment by Feichtmeier** [comment]
Sorry for the noise everyone, chatted to muq and marco and everything is fine 🌈 
Thanks for the work marco!

**Comment by 3v1n0** [comment]
Cool, let's merge this then :)

**Comment by Muqtxdir** [comment]
yeah, apologies for the noise! thanks

**Pull request merged**
