### PR TITLE
Add audio-speakers icon

### LINKED ISSUE #1948: Missing icon for sound device
## Actual Behavior

Capture d’écran du 2020-02-19 19-05-57

## Steps to Reproduce the Problem

  1. Open Gnome-settings
  1. Go to bluetooth
  1. Connect a sound device

Tested on 19.10, I will test on master with my 20.04 VM.

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Closes #1948

### CODE REVIEW

**Comment by madsrh** [comment]
Nice work @Jupiter007-43

**Comment by Jupiter007-43** [comment]
Capture d’écran du 2020-02-24 11-29-19

**Comment by Feichtmeier** [comment]
Now we have them both in legacy and device directories. :) Could you remove them from legacy?

**Comment by Jupiter007-43** [comment]
Ok, should I remove input-gaming icon from legacy too?

**Comment by Feichtmeier** [comment]
@Jupiter007-43 yes please make another PR for that. I merge this one now since everything looks good - thank you very much :+1:

**Comment by ubuntujaggers** [comment]
Hi guys,

We could do with another PR to make the drop shadows match the other Yaru icons:

image

@Jupiter007-43 @Feichtmeier

**Comment by Jupiter007-43** [comment]
I'll do it tomorrow. Right now I can't get the master branch with my awesome Internet connection (9.00 KiB/s)...

**Comment by Jupiter007-43** [comment]
#1991

**Comment by Jupiter007-43** [comment]
#1992

**Pull request merged**
