### PR TITLE
Mate: blueman icons

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Does someone want to give this a try on Ubuntu Mate?  I never worked out how to do the virtual machine :(

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Can't get bluetooth to run either on my vm
But I noticed that one of the bluetooth menu entries is still missing
grafik

**Comment by ubuntujaggers** [comment]
The firewall one?

**Comment by Feichtmeier** [comment]
Oh yeah this one is also missing.
But I mean bluetooth manager and bluetooth adapters :)

**Comment by ubuntujaggers** [comment]
Try now for those two...

**Comment by Feichtmeier** [comment]
looks goos ty

**Pull request merged**
