### PR TITLE
build: deduplicate meson.build and introduce Flavours

### PR DESCRIPTION
**Pull request by clobrano**
- default, light and dark themes are now built as Yaru _flavours_. It is easier now to introduce new flavours with different colorschemes
- deduplicate all the common meson.build code. The build instructions are all in `gtk/src/meson.build` file.
- deduplicate files: most of the original files are in the **default** flavour, while **light** and **dark** flavours have simlinks, however `gtk-dark.scss` for **default** and **light** flavours are symlink to `dark/gtk.scss` to have the same "prefer-dark" look and feel.

~~- replace `gresource` binary with actual assets and css files: this is a side effect of building all the files in the same directory (`gtk/src`). In place than a gresource binary, this change installs the actual `gtk.css`, `gtk-dark.css` and all the assets under `/usr/share/themes/<theme>`.~~ 

^ Fixed thanks to @jhenstridge hint and @3v1n0 meson.build in gnome-shell, used as reference

**NOTE**: For testing, I renamed the project **YaruFlavours**, so that in Tweaks you should see the entries *YaruFlavours*, *YaruFlavours-dark*, *YaruFlavours-light* alongside the usual Yaru to simplify the comparison. Before merging, I will change it back to Yaru.

Closes:  #1814
Closes:  #1331

### CODE REVIEW

**Comment by jhenstridge** [comment]
If you can keep the gresource files, please do.  It massively reduces the number of files an application needs to open on start.

You can use the `.gresource.xml` file to map files to different paths within the resulting `.gresource` file.  We already use that to rename the CSS files in master:

    <file alias="gtk.css">gtk-generated.css</file>
    <file alias="gtk-dark.css">gtk-dark-generated.css</file>

The same can be done for the other assets if the paths in the source tree don't match what you want in the final install.

**Comment by clobrano** [comment]
Thanks @jhenstridge! I saw something similar made by @3v1n0 in latest gnome-shell meson script and I'll try here as well

**Comment by clobrano** [comment]
Hey @didrocks, let me know if you have time to review this, or if you feel we can merge it right away. I used it quite a lot, and it seems to work fine

**Comment by clobrano** [comment]
Alright, I'm going to merge this 🤞

**Comment by chrisjbillington** [comment]
With this change the Arch AUR packages are no longer able to build. Fix is in #2206

**Pull request merged**
