### PR TITLE
Icon theme: adding phone with improved proportions and reflections

### PR DESCRIPTION
**Pull request by ubuntujaggers**
It was easier to close the previous PR and start again from master because the source-symbolic was out of date.  I've made the reflections less dramatic and made two of the icons slimmer.  @Feichtmeier, I'll make an icon for the one your phone uses...  think we have to make sure any commonly plugged-in devices have a full colour icon.

image

image

image

### CODE REVIEW

**Comment by madsrh** [comment]
Spot on @ubuntujaggers 💪

**Comment by Feichtmeier** [comment]
Nice!
No problem don't worry about that Samsung that's basically a separate issue. Sorry for derailing the main point of your pr :)

**Comment by ubuntujaggers** [comment]
I can't cherry pick this because there's a conflict on source-symbolic in Bionic somehow...

**Comment by Feichtmeier** [comment]
Yes you need to cherry pick the remmina removal commit first :) then cherry pick this one after

**Comment by ubuntujaggers** [comment]
Aha!  Will do  :)

**Pull request merged**
