### PR TITLE
Mate: full colour icons for remaining categories

### PR DESCRIPTION
**Pull request by ubuntujaggers**
How's this? The new ones should be...

Education:

image

Office:

image

Other:

image

Sound and Video:

image

System:

image

### CODE REVIEW

**Comment by flexiondotorg** [comment]
Thanks @ubuntujaggers :heart: 

**Please don't merge this!** I'm including these changes in a branch I'm preparing :smiley:

**Comment by flexiondotorg** [comment]
Here is my PR that includes all of the above:

  * https://github.com/ubuntu/yaru/pull/2691

**Comment by flexiondotorg** [comment]
This PR can be closed now :smiley:

**Comment by Initu** [comment]
The category Applications-Science icon is missing

**Pull request closed without merging**
