### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by madsrh**
> ...if you would like to support development by making a donation you can do so here...

I doubt making donations to Sam will support the development of this project :smile: 

* Added usage examples to the symlink readme
* Removed donations to Sam from the readme
* Added SVG file with color palette from Gusbemacbe in Yaru++

On the todo list is still to edit the AUTHORS

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Everything okay here with this file @madsrh ?
image
Maybe it's just github

**Comment by madsrh** [comment]
No, out should be able to view that.

**Comment by Feichtmeier** [comment]
Is this our color palette from https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.20/_ubuntu-colors.scss ?
(updated on the design fest)

**Comment by madsrh** [comment]
Let's just remove it for now and I'll add one in a separate PR later

**Pull request merged**
