### PR TITLE
Gtk4: yaru upstream sync with tweak fixes

### PR DESCRIPTION
**Pull request by Feichtmeier**
- rename _headerbar.scss to _inverted-headerbar.scss to prevent name confusion with the widget file
- keep upstream scale+switchslider colors, since buttons do not have a shadow at all now, this fits a bit better
- remove OSD scale special styling, no longer needed
- adapt the whole _colors file to upstream, keep our _primary / secondary accent color idea for now
- remove the HC variant from colors, since we currently just use the upstream HC theme
- add the big bunch of upstream changes to buttons and the headerbar
- keep the inverted headerbar for now ...

some pictures for @madsrh and @clobrano and whoever can not build gtk4 atm :)
grafik
grafik

inverted version still alive and rocking :roll_eyes: 
grafik

dark theme - the real star :star:  of this change
grafik
grafik

stuff is changing daily

### CODE REVIEW

**Review by Jupi007 — APPROVED** [review]
Look good for me 👍

The only thing I found are links in dark theme. Maybe too dark?

Capture d’écran du 2021-06-12 11-42-52

Make them a bit brighter could be great IMO

Anyway good work. Thanks @Feichtmeier.
Can I push to this branch? I'd like to do some simplification on the inverted headerbar.

**Comment by Feichtmeier** [comment]
oh yeah, indeed - I should change back to what we've had!

**Comment by Feichtmeier** [comment]
>  Can I push to this branch? I'd like to do some simplification on the inverted headerbar.

gogo :)

**Review by Jupi007 — APPROVED** [review]
Perfect!

**Pull request merged**
