### PR TITLE
Add missing view-sidebar symbolic icon

### LINKED ISSUE #2400: Missing evince icon: view-sidebar-symbolic
grafik

https://gitlab.gnome.org/GNOME/evince/-/blob/master/data/icons/scalable/actions/view-sidebar-symbolic.svg

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Capture d’écran du 2020-10-09 13-39-57

Closes #2400

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thank you @Jupiter007-43 !

I think you need to add it to source-symbolic first and then export the symbolic :smiley_cat:

**Comment by Jupiter007-43** [comment]
In fact @ubuntujaggers and me have agreed to don't use the source-symbolic file and direct put svgs into Suru folder.
But if ofc if it's needed to use it there's no problem 😌

**Comment by Feichtmeier** [comment]
Oh?
I missed this then!
So why does it still exist then?

**Comment by Jupiter007-43** [comment]
Just in case we want to reuse it, but I don't know if that decision is still relevant today. 🤔

**Pull request merged**
