### PR TITLE
Added mimetype icon for Scala files

### PR DESCRIPTION
**Pull request by madsrh**
https://en.wikipedia.org/wiki/Scala_(programming_language)

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Looks like expected and no issues on the screenshot (untested) :+1:

**Comment by Muqtxdir** [comment]
Hi @madsrh,

I noticed that **text-x-scala.svg** has two Pictograms Layers

- Pictograms1 has the **Scala-mimetype** 
- Pictograms has the **Log-mimetype** (Although this layer is hidden)

**Screenshot:**
Screenshot from 2020-07-13 17-24-31

Thanks!

**Comment by madsrh** [comment]
Nicely spotted. Can you delete that layer and make a PR?

**Comment by Muqtxdir** [comment]
Ok, Fine

**Comment by Feichtmeier** [comment]
Is this visible in the icon?

**Comment by Muqtxdir** [comment]
> Is this visible in the icon?

No, it is not visible in icon (just present as extra layer in .SVG file)

**Comment by Feichtmeier** [comment]
@Muqtxdir okay thanks, I'm just asking because we prepare a yaru release for Ubuntu 20.04.1 and every change we want to get it is extra work on launchpad. Being lazy so it's cool to postpone this (very correct) fix for focals next point release :)

**Pull request merged**
