### PR TITLE
Add icon superimposing Firefox on a squircle

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Hi all,

I don't think we ever made a firm decision on which Firefox to use, so I've done the least controversial one, which is the Firefox logo on a plain white squircle.  Let me know if you'd rather have a different one, happy to do more work on it.

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Nice! Can you also add Thunderbird? I think then we have them all :) 
In a future PR
I like this, let's wait for @madsrh and @clobrano

**Comment by ubuntujaggers** [comment]
> Can you also add Thunderbird? I think then we have them all :)
> In a future PR
> I like this, let's wait for @madsrh and @clobrano 

Yep, no probs - whatever gets accepted/merged for Firefox, I'll do Thunderbird the same way  :)

**Comment by clobrano** [comment]
It looks good :+1:

**Comment by mivoligo** [comment]
I've just started Ubuntu and was thinking it's a bug. It looks kind of out of place in my dock next to other icons.
zrzut ekranu z 2018-12-06 13-04-29

**Comment by clobrano** [comment]
Maybe it's also because being the squircle white the normal light effects
of the borders aren't visible

**Comment by ubuntujaggers** [comment]
I think he's right, it looks a bit rubbish in that screenie. Let me try one of the colours when I get home shortly.

**Comment by ubuntujaggers** [comment]
Do either of these look better:

ff pale blue

ff pale yellow

Both squircles are colours from the Suru palette.  We have to get this one right because it's Firefox, so I'm happy to do more work.

**Comment by clobrano** [comment]
I prefer the second, which is close to the auto generated one

Il giorno gio 6 dic 2018, 18:50 ubuntujaggers <notifications@github.com> ha
scritto:

**Comment by ubuntujaggers** [comment]
Yes, the second colour is a bit more neutral without being white or grey.  Happy to change/commit/push if others feel the same.

**Comment by madsrh** [comment]
@ubuntujaggers could you post a mockup/screenshot with the icon in the dock?

**Comment by ubuntujaggers** [comment]
image

Not sure I've quite nailed it...

**Comment by dedricbrayon** [comment]
Android:
screenshot_20181110-121825_samsung experience home

iOS:
1200x630wa 1 1

Firefox about dialog:
screenshot from 2018-12-06 20-01-57

**Comment by Feichtmeier** [comment]
I think adapting to iOS/ANdroid is a very good idea

**Comment by clobrano** [comment]
I agree. That dark blue is beautiful

Il giorno gio 6 dic 2018, 20:10 Feichtmeier <notifications@github.com> ha
scritto:

**Comment by ubuntujaggers** [comment]
If we go for the Android/iOS blue (which has a _lot_ of advantages in terms of respecting the brand) it might be an idea to soften the Suru highlight so it isn't so jarring on a dark squircle.

Also I had another go at the orange background, both are shown here:

image

**Comment by ubuntujaggers** [comment]
@feichtmeier dark one with softer highlight?

**Comment by clobrano** [comment]
>@c-lobrano, you felt it was so dark that it looked like a normal Firefox icon, I assumed that was a negative but actually I wonder if I misinterpreted you? i.e., did you like this version?

I forgot :D, you're right

**Comment by ubuntujaggers** [comment]
image
?

**Comment by Feichtmeier** [comment]
I would prefer the dark purple background overall other because
1) it is the same on iOS/Android
2) it has a great contrast against a) blue and b)orange in the firefox logo

**Comment by madsrh** [comment]
I agree with @Feichtmeier +1 dark purple background works best IMO

**Comment by ubuntujaggers** [comment]
Super - @Feichtmeier, @madsrh, @clobrano, how about this for the final version:

final dark blue ff

image

**Comment by ubuntujaggers** [comment]
Okay, I pushed the dark blue version  :)

**Comment by ubuntujaggers** [comment]
@Feichtmeier, do I do a new PR now or do you just merge the dark blue one?

**Comment by Feichtmeier** [comment]
Yes you need to make a new Pull Request :)

**Comment by ubuntujaggers** [comment]
Done! https://github.com/ubuntu/yaru/pull/1030

**Pull request merged**
