### PR TITLE
Refresh Libreoffice app icons

### LINKED ISSUE #3801: New LibreOffice icons
At the LibreOffice Design team, we have created [new app- and file icons](https://github.com/LibreOffice/core/commit/b24dfa7ef93bc31ed9ccfb3e3472109bbd384b15) for the upcoming 7.5 release, which will be released in February 2023 and will be included in Ubuntu 23.04 Lunar. Please consider refreshing the Yaru-style icons to match. Since we don’t drink the “Please don’t theme our apps!” Kool-Aid, we encourage icon developers to be creative in theming our software :)

### PR DESCRIPTION
**Pull request by Jupi007**
### New writer app icon:

Capture d’écran du 2023-02-19 17-29-45

### New calc app icon:

image

### New main app icon:

image

### New math app icon:

image

### New base app icon:

image

### New draw app icon:

image

### New impress app icon:

Capture d’écran du 2023-02-19 21-39-35

Closes #3801

### CODE REVIEW

**Comment by madsrh** [comment]
Have not tested but these look great @Jupi007

**Comment by Jupi007** [comment]
image

**Review by Muqtxdir — APPROVED** [review]

**Comment by madsrh** [comment]
> ...the main app icon kinda looks weird out of all because it doesnt have any pictogram

I agree but same for upstream 🤷‍♂️

image

**Comment by Jupi007** [comment]
I wanted to have your opinion on this and  I completely agree with you

But I don't have any better idea, except leave the white section, but then it looks out of place among the filled other icons 🤷‍♂️

**Comment by Jupi007** [comment]
Let's merge this, and let's see how it feels in a daily usage 🙂

Other topic: the mimetype icons. Imo, we should keep the white page inside the coloured border. So we have a clear difference between app and file icons.
And it looks more like a document with the white part.
But there's still some colour and pictogramme sync needed I will do.

Wdyt @madsrh @Muqtxdir ?

**Comment by madsrh** [comment]
> And it looks more like a document with the white part.

Exactly! With the updated pictogram this will be spot on 👌 

Thank you

**Pull request merged**
