### PR TITLE
Blue focus

### PR DESCRIPTION
**Pull request by Feichtmeier**
Testing PR for blue focus + solid focus ring + no margin
Basically everything, everywhere the same blue focus ring 

@matthewpaulthomas are you able to test this via snap or via the branch?

@madsrh @clobrano @godlyranchdressing @ubuntujaggers opinions, opinions, etc. :)

Never ending story :) 
Eventually closes https://github.com/ubuntu/yaru/issues/845
and 
closes https://github.com/ubuntu/yaru/issues/844

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Shall I merge your branch into this?

**Comment by godlyranchdressing** [comment]
This is to have the focus ring be the same between the shell and GTK apps, right? I think the orange works better with the darker shell as it really pops out at you, but the blue works just fine too. I may just have to get accustomed to it.

Good ole I can live with it change.

**Comment by clobrano** [comment]
Let's merge mine and rebase this

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr971`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr971` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
This needs a fix: 
image

@clobrano any idea where this is styled?

**Comment by Feichtmeier** [comment]
Needs fix
image

**Comment by Feichtmeier** [comment]
Needs fix
image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr971`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr971` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr971`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr971` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
> This needs a fix:
> image
> 
> @clobrano any idea where this is styled?

here
https://github.com/ubuntu/yaru/blob/7cc63d96f0b8bc55d5db7517c574bd9fec22d9d0/gtk/src/light/gtk-3.20/_common.scss#L385

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr971`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr971` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
With a solid line, it might be better to have the ring around button border, like in entries, rather inside

**Comment by clobrano** [comment]
Suggested-action buttons are a bit hard to see with this focus ring

image

**Comment by Feichtmeier** [comment]
I agree, red and green buttons need to be an exception. Either way

**Comment by madsrh** [comment]
> I agree, red and green buttons need to be an exception. Either way

+1 
Perhaps ListBox is an exception too?

image

The plan is to do this for all elements, right? Focus ring for checkboxes, sliders, tabs, etc.

**Comment by Feichtmeier** [comment]
@madsrh tbh after trying this branch since yesterday on my host I am less and less exited about the blue focus ring. I think the color mismatch to the always present orange is too much. But let's wait some more days of mpt finds time to test it.
I was quiet happy with the focus ring since we changed the default button since the double border was my biggest concern. 
I could however be more happy if we would change the transparent orange when selecting buttons in the header bar to either a opague orange explicitly there or to white.

**Comment by matthewpaulthomas** [comment]
> @matthewpaulthomas are you able to test this

Unfortunately my Yaru test machine stopped booting and needs a new SSD. So please don’t block on me.

**Comment by Feichtmeier** [comment]
@matthewpaulthomas no hurry :)

**Comment by Paz-it** [comment]
How about making it transparent? :smiling_imp: , Joke aside, I would say leave it orange.

**Comment by Feichtmeier** [comment]
Lol that's strange. Because I made the orange branch out of the blue branch, this PR is "merged" :D

**Pull request merged**
