### PR TITLE
WIP: Add Gtk-4.0 support

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Capture d’écran du 2021-02-01 16-05-48
Capture d’écran du 2021-02-01 16-06-05
Capture d’écran du 2021-02-01 16-06-12

Capture d’écran du 2021-02-01 16-08-03
Capture d’écran du 2021-02-01 16-08-10
Capture d’écran du 2021-02-01 16-08-17

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thank you very much for helping me on the build <3 Some day I eventually need to learn meson a bit better 👼 

Nice, you've also added the default theme!
Could you eventually mark all changes regions in _drawing and _common ? I missed to do this on this quick PoV
The easiest way to do this is for me was to copy the upstream files and replace the yaru dir, then slowly reverting each line but then also put the "yaru change" comment behind or above

**Comment by Jupiter007-43** [comment]
> Could you eventually mark all changes regions in _drawing and _common ? I missed to do this on this quick PoV

Ofc 👌

**Comment by Jupiter007-43** [comment]
Looking at Gtk-widget-factory everything looks OK now.
It should be great to found some Gtk4 apps for testing.

**Comment by Feichtmeier** [comment]
Will test it tomorrow

**Review by Feichtmeier — APPROVED** [review]
After some conversations and fixes via telegram this is good to merge :bowing_man: 
Thank you very much @Jupiter007-43 
If you found out the exact trick to install gtk4 into your system you could maybe update the contributing page with a little gtk4 help section :)

**Comment by Jupiter007-43** [comment]
> If you found out the exact trick to install gtk4 into your system you could maybe update the contributing page with a little gtk4 help section :)

Of course!

**Pull request merged**
