### PR TITLE
Adding new battery symbols with ten divisions

### LINKED ISSUE #1482: symbolic: battery level icons
Upstream commit in adwaita-icon-theme:
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/377044f755c3ec994f661d787f50e633487b929d

Upstream added more battery level icons (10% steps) to better represent the battery status.

Is this change also needed in Yaru?

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Closes #1482.  I've unplugged my laptop  :)  but am making the PR now in case someone knows a clever way to test it without waiting for hours while the battery drains.  They certainly have the same names as Gnome's new ones.

image

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
It's not using them  :(  Are we expecting Gnome to use these already or is it for a coming update?

**Comment by Feichtmeier** [comment]
I will test it tomorrow!

**Comment by Feichtmeier** [comment]
All icons are are pulled :+1: 
grafik
Must be something with gnome shell

**Comment by Amr-Ibra** [comment]
The new icons depend on the newest gnome-shell:
https://gitlab.gnome.org/GNOME/gnome-shell/commit/bd18313d125aa1873c21b9cce9bbf81a335e48b0

**Comment by ubuntujaggers** [comment]
Brilliant, so we're ready :)

**Pull request merged**
