### PR TITLE
Removed unused defs

### LINKED ISSUE #2571: Svgs have unused definitions
Many of the svgs in the icon theme have unused definitions in them, which can safely be removed and save file size. They can be cleaned up in Inkscape via `File > Clean Up Document`, or cleaned up with `inkscape --vacuum-defs --export-filename=./filename.svg ./filename.svg`. If anyone's interested, I'll recursively do this later and submit a pull request.

### PR DESCRIPTION
**Pull request by Dragon8oy**
Same as the previous attempt at a pull request, before I messed it up...
2.6MB saved
Closes #2571

### CODE REVIEW

**Comment by Jupi007** [comment]
Hi @Dragon8oy,
thanks for this :)
Sorry for the very long wait.
I'll review your PR.

**Review by Jupi007 — APPROVED** [review]

**Comment by Muqtxdir** [comment]
Hi @Jupi007,

Since this PR was produced before fixing #2630 issue. Does this mean it also displays corrupt SVGs on Ubuntu 18.04? (Asking because gtk-common-themes uses core18)

**Comment by Jupi007** [comment]
Hi @Muqtxdir,
you're right to have thought about it.
But I don't think so because this PR doesn't modify any scalable icons.
However I'll test on 18.04 to check if everything is all right.

**Comment by Feichtmeier** [comment]
I think you mean 20.04 @Muqtxdir , right?

**Comment by Muqtxdir** [comment]
No, I think I've confused you here @Feichtmeier, we need to test this in **Ubuntu 18.04** because that is what is used for `core18` snap. So if it works on **Ubuntu 18.04** it'll have no issues with all `core18` based snaps (ex vscode and snap-store)

**Comment by Jupi007** [comment]
Checked svgs with 18.04, and there's no problem 🎉

**Pull request merged**
