### PR TITLE
Support Gnome 3.32 apps icon name changes

### LINKED ISSUE #1274: late GNOME 3.32 icon name changes
There were some GNOME 3.32 app releases yesterday (with no previous 3.31 releases) that changed the app icon name.

- preferences-desktop-font → org.gnome.font-viewer
- gnome-characters → org.gnome.Characters
- applets-screenshooter → org.gnome.Screenshot

Except for gnome-screenshot, these releases also adapt to the new GNOME menu guidelines so I think we do need to do these updates.

I have pushed the updated package versions for these apps to Debian experimental. We should land the Yaru update in Disco before we sync those app updates to Disco so that the apps continue to have their intended app icons.

/cc @seb128

### PR DESCRIPTION
**Pull request by clobrano**
- preferences-desktop-font → org.gnome.font-viewer
- gnome-characters → org.gnome.Characters
- applets-screenshooter → org.gnome.Screenshot

closes #1274

### CODE REVIEW

**Comment by clobrano** [comment]
@jbicha

**Comment by clobrano** [comment]
> We should land the Yaru update in Disco before we sync those app updates to Disco so that the apps continue to have their intended app icons 

My understanding was the opposite. In any case this change is supposed to support both names

**Comment by jbicha** [comment]
Here you go if you want to test the new app versions:

https://launchpad.net/~jbicha/+archive/ubuntu/temp332/+packages

**Comment by seb128** [comment]
Can we get this reviewed/merged/landed in disco? The sooner we unblock the app updates the better since we prefer to get longer testing

**Comment by clobrano** [comment]
I had the time to test only Baobab, but it works fine, so we can merge it now for me

**Comment by clobrano** [comment]
Test completed on other applications as well, everything looks fine, merging it now

**Pull request merged**
