### PR TITLE
Lighten dark theme success_color

### PR DESCRIPTION
**Pull request by Jupiter007-43**
### Adwaita

Capture d’écran de 2020-08-04 21-14-10

### Before

Capture d’écran de 2020-08-04 21-16-18

### After

Capture d’écran de 2020-08-05 12-45-01

### CODE REVIEW

**Comment by Feichtmeier** [comment]
I always thought that is is too dark :shrug: 


could you check
-  how it looks in the shell? for example the dock badges?
I like to keep both color files as much in sync as possible
- does this change anything else in the gtk theme?

**Comment by Jupiter007-43** [comment]
>  for example the dock badges?

Badges are red on my computer:

Capture d’écran du 2020-08-05 13-04-09

This affect the levelbar:

Capture d’écran du 2020-08-05 13-11-51

Capture d’écran du 2020-08-05 13-10-18

But the contrast is also better here.

**Comment by Feichtmeier** [comment]
I think the level bar change is good, but wait for @clobrano and/or @madsrh opinion here.

Ah yeah... currently you only see the green badges in the ubuntu session which you dont change with the yaru meson build : (

**Comment by clobrano** [comment]
It looks good to me 👍

**Comment by madsrh** [comment]
Much better 👌

**Comment by Jupiter007-43** [comment]
Great!
I tested some apps which use this color and I think it's okay!

**Comment by Feichtmeier** [comment]
Cool, glad we have suggested_bg_color detached from success_color so I think it should be okay!
Stuff that is dangerous is when it is connected to borders. Like progressbgcolor and suggestedbgcolor

**Pull request merged**
