### PR TITLE
Revert "Remake shutdown icon"

### PR DESCRIPTION
**Pull request by clobrano**
Reverts ubuntu/yaru#1063

as discussed

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1080`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1080` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by eaglersdeveloper** [comment]
😨

**Comment by eaglersdeveloper** [comment]
But why is my icon thinner than others? Outline width is 1 pixel like in other icons.

**Comment by eaglersdeveloper** [comment]
I can fix it

**Pull request merged**
