### PR TITLE
rendered all cursors and symlinked them

### PR DESCRIPTION
**Pull request by Muqtxdir**
closes issue #2888:  the wait-cursors were not being changed even after following all the instructions from [cursors-README](https://github.com/ubuntu/yaru/blob/master/icons/src/cursors/README.md). 

***changed-files***
- all files under `/Suru/cursors` are rendered again
- symlinked all cursors according to [cursors.list](https://github.com/ubuntu/yaru/blob/master/icons/src/symlinks/fullcolor/cursors.list)

***screen-record:***
Peek 2021-06-17 23-44

*also @Benni3-1415, really liking the new-changes to the cursor-theme*

### CODE REVIEW

**Comment by Jupi007** [comment]
How did you do 😲
I tried some days (weeks) ago but I couldn't do it.
Big thanks :)

**Comment by Feichtmeier** [comment]
Thanks @Muqtxdir how did you do it? xD

**Comment by Muqtxdir** [comment]
Hi @Jupi007, @Feichtmeier 

well, that was a quick merge :)

The issue was that the cursors were not at all symlinked to their counterparts, they were copy files. so I deleted them and rendered from scratch and symlinked the files from cursors.list and et voila, it worked

**Comment by Jupi007** [comment]
Okay, that's good to know!
Maybe update the readme and add some lines about this, what do you think of?

**Comment by Muqtxdir** [comment]
sure, I'll do that :+1:

**Pull request merged**
