### PR TITLE
icons - add application/x-sharedlib alias for x-executable

### LINKED ISSUE #2203: ELF application/x-sharedlib executables currently shown with generic text file icon
First off, thanks for your work on this nice icon theme

## Expected Behavior
`application/x-sharedlib` ELF executables displayed with the default executable gear style icon

## Actual Behavior
`application/x-sharedlib` executables are displayed with the generic text file icon

so_executable_icons_yaru_2004

When in a project folder with a user-compiled executable, the icon doesn't make it obvious that it's an executable file despite being an ELF with 0744 executable permissions.

## Steps to Reproduce the Problem

  1. `nautilus /usr/bin/`
observe the icons of the executable files in the directory (see screenshot above)

## Software that presents the issue

- Name: Ubuntu
- Version: 20.04

## Yaru version

20.04.7

Upstream issue: https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/44

### PR DESCRIPTION
**Pull request by wesinator**
should fix #2203

### CODE REVIEW

**Comment by clobrano** [comment]
I really appreciate bugs opened with a PR associated 👍
I'll test it today, but to me it looks good already

**Comment by Feichtmeier** [comment]
Thanks @wesinator !

I think you've missed to add the src file :D 
Gj on adding the symlink anyways and thanks again

**Comment by clobrano** [comment]
Isn't the source file the same as application executable?

**Comment by Feichtmeier** [comment]
Woops, sorry. Symlinks :face_with_head_bandage: :+1: 
Everything is fine then

**Comment by wesinator** [comment]
> Woops, sorry. Symlinks face_with_head_bandage +1
> Everything is fine then

Oops, I misread and added text files not symlinks :zany_face: 
Rebuilding with actual symlinks using `find icons/ -name application-x-sharedlib.png -exec ln -fsT application-x-executable.png {} \;`

**Comment by clobrano** [comment]
I just noticed :wink:, no problem. You could have used also `generate-symlink.sh` script

**Comment by clobrano** [comment]
Looks good, thanks!

**Pull request merged**
