### PR TITLE
Cherry pick #1368

### PR DESCRIPTION
**Pull request by iainlane**
As mentioned on https://github.com/ubuntu/yaru/issues/1370

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Shall set push the other 🍒 ourself or will you do that?

**Comment by iainlane** [comment]
I think the other one Carlo mentioned is already in disco actually (feel free to double check), and I didn't add #1302 since it doesn't seem right for a stable update

**Comment by Feichtmeier** [comment]
And this one?
https://github.com/ubuntu/yaru/pull/1335

**Comment by iainlane** [comment]
Didn't see that one mentioned, sorry. Feel free to propose a PR and file
a Launchpad bug. :-)

On Thu, May 23, 2019 at 08:50:53AM -0700, Feichtmeier wrote:
> And this one?
> https://github.com/ubuntu/yaru/pull/1335
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ubuntu/yaru/pull/1373#issuecomment-495276734

-- 
Iain Lane                                  [ iain@orangesquash.org.uk ]
Debian Developer                                   [ laney@debian.org ]
Ubuntu Developer                                   [ laney@ubuntu.com ]

**Comment by clobrano** [comment]
Okay, merging this then

**Pull request merged**
