### PR TITLE
Updated firmware icon

### PR DESCRIPTION
**Pull request by madsrh**
Second attempt 🤦‍♂ 

Updated the firmware icon with the Stuart magic

### CODE REVIEW

**Comment by clobrano** [comment]
How could I test this? :)

**Comment by madsrh** [comment]
Sorry I didn't know. I decided to include it because it is also found in the Adwaita icon theme.

Can we fake a firmware update?

https://gitlab.gnome.org/GNOME/gnome-software/uploads/d34554c7a0b43f9469023abc8022790b/Screencast_from_03-29-2018_12_10_59_AM.webm

**Comment by clobrano** [comment]
I don't know, but maybe we can find an icon viewer like the one for symbolic icons

**Comment by Feichtmeier** [comment]
I think I can test it, I have a pending firmware update which I dont want to install :D

**Comment by Feichtmeier** [comment]
image
Works :+1:

**Pull request merged**
