### PR TITLE
Updating symbols for Tweaks and Configurator

### LINKED ISSUE #2111: Adjust configurator-app-symbolic to match its icon configurator-app
`configurator-app-symbolic` does not match its icon `configurator-app`.

[configurator-app-symbolic](https://github.com/ubuntu/yaru/blob/master/icons/Suru/scalable/apps/configurator-app-symbolic.svg)
grafik

[configurator-app](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/apps/configurator-app.svg)
grafik

### LINKED ISSUE #2112: Adjust tweaks-app-symbolic to match its icon tweaks-app
`tweaks-app-symbolic` does not match its icon `tweaks-app`.

[tweaks-app-symbolic](https://github.com/ubuntu/yaru/blob/master/icons/Suru/scalable/apps/tweaks-app-symbolic.svg)
grafik

[tweaks-app](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/apps/tweaks-app.svg)
grafik

### PR DESCRIPTION
**Pull request by ubuntujaggers**
image

image

image

image

Closes #2111 
Closes #2112

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Very nice @ubuntujaggers !
Do you prefer to merge symbolic icons in bits or do you want to fix those two symbolic icon issues in this branch?
https://github.com/ubuntu/yaru/issues/2077
https://github.com/ubuntu/yaru/issues/2073

**Comment by ubuntujaggers** [comment]
Happy to fold those into this branch 👍

**Comment by ubuntujaggers** [comment]
I've pushed some icons that would close #2077, but only if they look good in context.  How do I get the new Gnome clocks...?

image

image

image

**Comment by Feichtmeier** [comment]
I think they look good, let's see how we can test this

**Comment by ubuntujaggers** [comment]
Can @real-amano try the branch?

**Comment by real-amano** [comment]
Yep. Those look fine. Thank you very much for your work

**Comment by ubuntujaggers** [comment]
@real-amano if you've got them in the app, do you mind doing a screenshot for this PR?

**Comment by real-amano** [comment]
I do not mind ;)

grafik

**Comment by ubuntujaggers** [comment]
Doesn't look bad! Should we merge?

**Pull request merged**
