### PR TITLE
close_btn_backdrop_color_and_hover

### PR DESCRIPTION
**Pull request by Feichtmeier**
Fixing the request for hover colors of window controls in the backdrop + permanent grey for the close button in the backdrop
@madsrh @clobrano @clobrano feel free to merge/request changes

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr401`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr401` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
It make sense to have all the widgets react on hover:backdrop

**Comment by Feichtmeier** [comment]
Yes I just don't want to destroy your button function css Kung Fu. Feel free to fetch/pull this branch and work on it! Then you can close this PR and make a new one

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr401`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr401` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr401`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr401` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Pull request merged**
