### PR TITLE
Use background property to set insertion-cursor icon

### LINKED ISSUE #945: touch screen caret is stretched horizontally
## Expected Behavior

The caret shown in response to touch screen action in an entry widget should be displayed without distortion.

## Actual Behavior

The caret is stretched horizontally:

image

It seems that GTK expects the image asset used for the caret to have the same dimensions as the `text-select-start` and `text-select-end` assets (which is the case for Adwaita).  We're using the `slider-horz-scale-has-marks-above` asset as the caret, which is somewhat narrower.

## Steps to Reproduce the Problem

  1. Run `GTK_DEBUG=touchscreen gtk3-widget-factory` (or any other GTK app) so the mouse is treated like touch screen input.
  1. Use the mouse to position the caret in one of the text entries with the overlay 

## Specifications

This is with `yaru-theme-gtk` version 18.10.6.

### PR DESCRIPTION
**Pull request by clobrano**
-gtk-icon-source uses the same properties (-GtkWidget-text-handle-width/height)
to set both text-selection icons and insertion-cursor icons, but since the two
kind of icons differ in size in Yaru, the latter looks stretched.

Using background-* CSS properties instead, to set the proper icon sizes.

closes #945

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr997`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr997` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
image
 
I think it works =)

**Comment by clobrano** [comment]
It looks a bit misaligned

Il giorno sab 1 dic 2018, 11:12 Feichtmeier <notifications@github.com> ha
scritto:

**Comment by clobrano** [comment]
caret

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr997`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr997` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Pull request merged**
