### PR TITLE
Reduce the darkness of dark var undershoots + refactoring

### PR DESCRIPTION
**Pull request by Feichtmeier**
peek 2018-12-15 00-13

Reduced the darkness of undershoot bg resulting in a better look, especially in the backdrop 
+ minor refactoring of the variable

### CODE REVIEW

**Comment by Paz-it** [comment]
Noooo, Please :cry: 
I love this - You did it so nice @Feichtmeier , replaced the ugly dots and now you want to kill it :0 
+1 with @madsrh  making it taller .

**Comment by madsrh** [comment]
> Noooo, Please 😢
I love this - You did it so nice Feichtmeier , replaced the ugly dots and now you want to kill it

No one is killing anything @Paz-it 😄 As you can see in the screenshot above, the change is very minimal 😉

**Comment by Paz-it** [comment]
Good!!! :woman_facepalming:  
It was one of  many @madsrh  superb ideas and implemented so well by @Feichtmeier .

**Comment by madsrh** [comment]
> It was one of many @madsrh superb ideas...

I think this was @Feichtmeier idea ;)

**Comment by Feichtmeier** [comment]
Yes I think I can make them 1px taller let me try

**Comment by Feichtmeier** [comment]
Huh this is strange

when I add another pixel the top undershoots just... vanish O.o
image
:thinking:

**Comment by Paz-it** [comment]
Maybe you need to add the 1px only to the '-y' ?

**Comment by Feichtmeier** [comment]
No idea how I can extend the undershoots paste 2px. Maybe it is some technical limitation due to adwaita using the dashed line previously (they use the box-shadow now, too ;) )
So I would like to merge this now - okay @madsrh @clobrano ?

**Comment by madsrh** [comment]
@Feichtmeier if it's not possible, then it's fine 👍

**Pull request merged**
