### PR TITLE
Simpler cursor shape / Correct cursor color

### LINKED ISSUE #2779: Cursor animation with outdated color.
The color of the cursor animation is blue and does not match the color of the system.  My suggestion is to change the color to Purple (Ubuntu standard) and green (Ubuntu-MATE).

### LINKED ISSUE #2874: Link select cursor in .svg cursor sheet has swapped gradient colors
Issue's title says _almost_ it all, so have this image.
hedj

### PR DESCRIPTION
**Pull request by Benni3-1415**
# Simpler cursor shape
### Default cursor
- Remove the arrow line at the bottom of the default cursor
- Increase the size by `1px`
- Move the cursor and the _hotspot_ on both axes `1px` towards the corner

Simpler design for the default cursor
Simpler concept design for the default cursor (24px)")

#### Benefits
It's an easier to understand the cursor without the irritating details at the bottom.
This design looks more modern and is also used by Adobe:
The cursor of Adobe Illustrator

### Hand cursors
Increasing the radii of the fingers to remove the vertically line between them.

##### Pointer hand
The radii of the fingers are slightly larger because the index finger is smaller.
Adjusted the back of the hand, the index finger and the _hotspot_ upwards by `1px`, because the back of the hand is much bigger in the grap version.

Simpler design for the hand cursors
Simpler design for the hand cursors (24px)")

#### Benefits
The cursor has less irritating details.
This design looks more modern and is a little more consistent.

### Zoom cursors
Remove the white circle and color the symbol white:
zoom-in-design zoom-out-design

#### Benefits
It's more consistent with the theme, because
- no other cursor has a large white face
- the default line-width of `2px` is no longer interrupted by the dark outline (`1px`)
- the white `+` or `-` fits with the white triangle in the pencil cursor

#### Mimetype
Replace the cursor and remove the border:

mimetype

#### Benefits
- its consistent
- white on light gray is senseless

[go to Discussion >](https://github.com/ubuntu/yaru/discussions/2867#discussion-3383130)

# Correct cursor color

### Color the _watch_ cursors in the secoundary color

[more information >](https://github.com/ubuntu/yaru/issues/2779)

---

Closes #2779
Closes #2874

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thanks for the PR - did you forget to render the images? Tried this locally and nothing changed =)

However, after staring at the pictures for some days, I like it more and more. At first I thought "nice pointer" but "oh that's a snow-glove" but it is a good abstraction and the curve makes it look so abstract that it can't be considered a snow glove I think.

Let's see what the others say and I need to check why the change does not show up for me :)

**Comment by Benni3-1415** [comment]
I deleted the affected PNGs and executed the `render-xuesors.py` script.

What about the other suggestions I added today (4-finger hand and zoom-cursor), should I also implement them in this PR?

**Comment by Feichtmeier** [comment]
Let's wait for the rest of the gang. @ubuntu/yaru-team

**Comment by Jupi007** [comment]
I pretty much like your new hand, but the 4 finger hand is a bit too much crazy imo 😄
About the zoom-cursor, your proposal looks better because it is more consistent.

**Comment by ubuntujaggers** [comment]
About to try...

**Comment by ubuntujaggers** [comment]
Arrow looks very nice :) I like current but I like this one as well, so no preference.

In terms of the grab hand, the lack of fingers makes me think of this:

image

Rather than this:

image

But I certainly don't feel strongly about it, it's a nice clean design :+1:

**Comment by madsrh** [comment]
I do like the arrow but I'm actually very happy with the current pointer 🤷‍♂️

The grab hand here is too simplified IMO. Here we're almost back to the initial issue raised by MPT. I would prefer more details like the one currently in master
https://github.com/ubuntu/yaru/pull/2848

**Comment by godlyranchdressing** [comment]
The cursor design I think is something that should stay conservative but even with that in mind, I do like the pointer, and I really like the hand up until it starts to curl in. The lack of detail when it comes to the clenched fingers makes it look odd, and I keep seeing a frog wearing glasses haha. But I very much like the gradient effect.

**Comment by madsrh** [comment]
> ... keep seeing a frog wearing glasses haha

LOL 🐸

Nice to hear from you again Mr. Dressing 👋

**Comment by Feichtmeier** [comment]
Wb @godlyranchdressing !!!

Alright then it's only the pointer and the zoom cursor :)

**Comment by clobrano** [comment]
Welcome back @godlyranchdressing!

My 2 cents. I do like the arrow more +1 for me

**Comment by Benni3-1415** [comment]
> The grab hand here is too simplified

I have a compromise for the hand cursor:
hand-design2 hand-design2-low

The 24px version needs more fine tuning.

**Comment by godlyranchdressing** [comment]
@madsrh @Feichtmeier @clobrano thank you guys 😅

> > The grab hand here is too simplified
> 
> I have a compromise for the hand cursor:
> hand-design2 hand-design2-low
> 
> The 2px of the middle finger are in the 24px image blurred, because the finger is `0.5px` above the others.
> If the middle finger is `1px` above the others it looks like a triangle with a too big finger at the top (trying to compensate only makes it worse)!

@Benni3-1415 I'd like to see the triangle still, I adjusted the height a tiny bit more to see what the triangle might look like but I think it looks alright, and I don't see it. Of course, maybe I did it differently from what you did. 

testing

I think the grabbing icon on its own will always look a bit odd without seeing it shift from the hand to the grab so it could be that the triangle might look fine in action.

**Comment by Benni3-1415** [comment]
> I'd like to see the triangle still
### My triangle:
hand-design2-triangle

**Comment by Benni3-1415** [comment]
### Mimetype
Replace the cursor and remove the border (white on light gray is senseless):
[Current version >](/ubuntu/yaru/blob/master/icons/src/fullcolor/mimetypes/image-x-cursor.svg "yaru/icons/src/fullcolor/mimetypes/image-x-cursor.svg")
new version

Would it be too much out of context to understand?

**Comment by Jupi007** [comment]
> ### Mimetype
> 
> Replace the cursor and remove the border (white on light gray is senseless):
> [Current version >](/ubuntu/yaru/blob/master/icons/src/fullcolor/mimetypes/image-x-cursor.svg)
> new version
> 
> Would it be too much out of context to understand?

Nice catch, because that looks consistent.
Maybe add another cursor in addition, like the hand one, or maybe make the current arrow bigger 🤔

**Comment by Benni3-1415** [comment]
> ... maybe make the current arrow bigger ...

the _old_ one or the _new_ one?

**Comment by Jupi007** [comment]
> the _old_ one or the _new_ one?

The new one, sorry 😓
I should have said: _make the only arrow bigger_.

**Comment by godlyranchdressing** [comment]
> > I'd like to see the triangle still
> 
> ### My _triangle_:
> 
> hand-design2-triangle
> The _old_ cursor had the same finger length, but it wasn't noticable.
> 
> Which one is better, the blurred or the triangular?

I think the triangle looks good.

**Comment by Benni3-1415** [comment]
> Maybe add another cursor in addition, like the hand one, or maybe make the current arrow bigger

Having multiple cursors in the file icon would make it look like an entire cursor theme ...

Good Idea, the cursor looks a little lost ...
Is this size good?:
mimetype

---

I'm working on the hand cursor (_triange_) is there anything I should change before committing?

**Comment by Jupi007** [comment]
That looks much better now :)
I just have a last little suggestion: the three smaller size looks misaligned vertically due to a visual illusion, I think it could looks better if you move them down a bit.

**Comment by Benni3-1415** [comment]
> the three smaller size looks misaligned vertically due to a visual illusion, I think it could looks better if you move them down a bit.

They are actually a bit bigger than in the prewiew ...
With correction:
mimetype

**Comment by Jupi007** [comment]
Perfect ! 😃

**Comment by Benni3-1415** [comment]
The compromise for the pointer hand cursor:
hand-pointer-high
hand-pointer

The radii of the fingers are slightly larger because the index finger is smaller.
I've also adjusted the back of the hand and the index finger upwards by `1px`, because the back of the hand is much bigger in the grap version.

---

The grap cursor is ready to be committed.

**Comment by ubuntujaggers** [comment]
Hi @Benni3-1415 , just a small note - looks like the pointing finger one has an upside-down gradient (lighter at the top) - the other cursors are lighter at the bottom, which matches the theme icons 👍

**Comment by ubuntujaggers** [comment]
Looks like the upside-down gradient was in the original!! Now is the perfect time to fix it 🙂

**Comment by Benni3-1415** [comment]
I thought it was on purpose ...

**Comment by ubuntujaggers** [comment]
These designs look good to me, how do we all feel about merging into master?

**Comment by elioqoshi** [comment]
We are likely getting rid of the aubergine so we will need to revisit the loading spinner probably.

**Comment by Feichtmeier** [comment]
> We are likely getting rid of the aubergine so we will need to revisit the loading spinner probably.

Okay - orange or rather monochrome? Check out
#2923

**Pull request merged**
