### PR TITLE
phosh symbolics + missing symbolics

### PR DESCRIPTION
**Pull request by Muqtxdir**
### phosh symbolics:
added the following icons under `phosh` using [`phosh gitlab`](https://gitlab.gnome.org/World/Phosh/phosh/-/tree/main/data) as reference:

- [x] feedback-quiet-symbolic.svg
- [x] phone-docked-symbolic.svg
- [x] phone-undocked-symbolic.svg
- [x] screen-rotation-landscape-symbolic.svg
- [x] screen-rotation-portrait-symbolic.svg
- [x] swipe-arrow-symbolic.svg
- [x] torch-disabled-symbolic.svg
- [x] torch-enabled-symbolic.svg

### missing symbolics (wip):
I don't know how we missed these icons but I double-checked only `status` and `devices` and found these missing will look into other directories later:
- [x] computer-fail-symbolic.svg
- [x] screen-shared-symbolic.svg
- [x] bluetooth-disconnected-symbolic.svg

### modified symbolics:
I modified/updated few symbolics to make them simpler:
- [x] computer-symbolic.svg
- [x] folder-download-symbolic.svg
- [x] bluetooth-* (_aligned them so that disconnected and others look similar_)

### updated index/script

- [x] added `legacy` _(i remember @Feichtmeier used to mention some Yaru battery icons were not displayed, turns out legacy was not present in `index.theme` and i think this was causing the use of adwaita battery icon in #3258 even though the icons are present)_
- [x] added `phosh` to `index.theme` and `render-symbolic-icons.sh` for now until #3116 is done

@giovannicaligaris could you please try this branch and share whether the battery issue that you mentioned in #3258 is resolved or not? and also share if you find any missing icons that i may have not included

### CODE REVIEW

**Comment by giovannicaligaris** [comment]
Resolved.

**Comment by giovannicaligaris** [comment]
Gnome Usage can't find an icon on Mobian, it relies on the symbolic icon. To get the correct icon I had to make a symbolic link of gnome-usage.png and name it org.gnome.Usage.png

**Comment by vitalkanev** [comment]
https://github.com/ubuntu/yaru/pull/3260#issuecomment-990911106

So it appears that the Camera app uses upstream icon. Maybe adding symlink to such is a good idea? I don't have a test machine nearby, so I can't figure out the icon name. Is it `org.gnome.Camera` or something?

**Comment by Muqtxdir** [comment]
> [#3260 (comment)](https://github.com/ubuntu/yaru/pull/3260#issuecomment-990911106)
> 
> So it appears that the Camera app uses upstream icon. Maybe adding symlink to such is a good idea? I don't have a test machine nearby, so I can't figure out the icon name. Is it `org.gnome.Camera` or something?

I'll look into camera icon later today

**Comment by Muqtxdir** [comment]
@vitalkanev the camera-app used by phosh is [`pinhole`](https://gitlab.gnome.org/jwestman/camera) and is not a `gnome-core` app , so it is better to first approach/ask the app-developer about the permission for including Yaru icon. (_see: #2196 for more details_)

**Comment by Muqtxdir** [comment]
@giovannicaligaris could you please try to build from this branch again and share whether the icons for **calls** and **chatty** are displayed properly? if all gnome-core apps icons are used and you don't find any missing icons then I think this can be merged

**Comment by giovannicaligaris** [comment]
@Muqtxdir I am actually using Droidian, which is a fork of Mobian. In this case Pinhole is the camera app and it also comes with Firefox-esr.

**Review by Jupi007 — COMMENTED** [review]
@Muqtxdir I have some questions:

- Why did you modified `computer-symbolic` and `folder-download`?
- And also `edit-undo` and `edit-redo` which both looks better like this, but shouldn't this be moved to another PR?
- Same for `bluetooth` icons, I see you realigned them to the left, which is good, but maybe doing this in another PR?
- `swipe-arrow-symbolic` is full white. It is intentional?
- Maybe add some rounding on `torch-*` icons?

I would prefer keep the _one PR_ for _one kind of modification_ methodology. I hope you understand 🙂

**Comment by Muqtxdir** [comment]
> Why did you modified computer-symbolic and folder-download?

I modified `computer-symbolic` to make it look similiar to `desktop-symbolic` and `computer-fail-symbolic`. the `folder-download` was modified to look `document-save-symbolic` and the fullcolor `folder-download`

> And also edit-undo and edit-redo which both looks better like this, but shouldn't this be moved to another PR?
Same for bluetooth icons, I see you realigned them to the left, which is good, but maybe doing this in another PR?

yes, it makes sense for them to be in their other respective PRs, I kept them all in here because they were used by phosh and wanted it to be easier to try for @giovannicaligaris 

> swipe-arrow-symbolic is full white. It is intentional?

the upstream icon is white, so i followed the same.

> Maybe add some rounding on torch-* icons?

ok thanks for the suggestion, I'll round them 

> I would prefer keep the one PR for one kind of modification methodology. I hope you understand

I'm sorry for the confusion, I'll organize them properly moving forward

**Comment by Jupi007** [comment]
> I modified `computer-symbolic` to make it look similiar to `desktop-symbolic` and `computer-fail-symbolic`. the `folder-download` was modified to look `document-save-symbolic` and the fullcolor `folder-download`

Imo, it's more `desktop-symbolic` and `computer-fail-symbolic` which need too looks like `computer-symbolic`, because this last icon is an original Yaru icon. And it's normal that `folder-download` is different from `document-save-symbolic`  😉

> yes, it makes sense for them to be in their other respective PRs, I kept them all in here because they were used by phosh and wanted it to be easier to try for @giovannicaligaris

I understand :+1:  Don't bother you to make another PR for this. Your modifications are okay :)
Like this @giovannicaligaris will be able to test everything in the same time.

> the upstream icon is white, so i followed the same.

Symbolic icons are always recoloured, I think you can safely use the same grey as the other symbolics.

> ok thanks for the suggestion, I'll round them

:+1: :)

> I'm sorry for the confusion, I'll organize them properly moving forward

As I said upper, don't bother you to make another PR only for this. Just revert your changes to `folder-download` and `computer-symbolic` (if you want, you can also sync `desktop-symbolic` and `computer-fail-symbolic` with it).

But please, make several PRs the next time. It's really simpler to review 😉

**Comment by Muqtxdir** [comment]
ok @Jupi007 thanks for the review!

**Review by Jupi007 — APPROVED** [review]
Perfect :smiley: 

Thanks @Muqtxdir :muscle:

**Comment by giovannicaligaris** [comment]
Should keep testing from the missing_options branch or will it be pushed to master?

**Comment by Muqtxdir** [comment]
> Should keep testing from the missing_options branch or will it be pushed to master?

I am merging this branch, other remaining components can be added later on. Thanks @giovannicaligaris and @Jupi007 for trying out and reviewing them

**Pull request merged**
