### PR TITLE
Replace audio-volume-change with a shorter sound, ...

### PR DESCRIPTION
**Pull request by Feichtmeier**
... resulting in not clipping when pressing volume buttons extensively

Finishing https://github.com/ubuntu/yaru/pull/1127
Closes https://github.com/ubuntu/yaru/issues/1111

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1132`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1132` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
I bet it's not the only sound, but from the mads sound I tried it is. The reason for the clipping must be something with the length of the sound. Depending on how much time @madsrh currently has we could either keep this opened and try other short sounds or merge it and make another testing PR when mads has time for this. But at least we have a "bug"-free sound set in master :) (which we have otherwise totally)

**Comment by clobrano** [comment]
Sounds good

**Comment by madsrh** [comment]
TBH that sound was only to test a REALLY short file. IMHO we should go with the old one. This one doesn't fit with the other sounds.

**Comment by Feichtmeier** [comment]
@madsrh hm but can't you create another sound that is short enough to not clip yet sounds like the other wooden sounds? :thinking:

**Comment by Paz-it** [comment]
I can't reproduce that clipping issue in my side.

**Comment by Feichtmeier** [comment]
I can reproduce it on several machines
You need to use your mouse wheel or fastly press the volume buttons

**Comment by Feichtmeier** [comment]
If we are all -1 for this explicit sound then no need to take this commit into the history :) Maybe @madsrh comes up with a short alternative to the current sound some day ^^

**Comment by madsrh** [comment]
Sorry for not replying. Sure, I'll look into it

**Pull request closed without merging**
