### PR TITLE
add icons required by org.gnome.Software

### PR DESCRIPTION
**Pull request by Muqtxdir**
### symbolic-icon-list:

- [x] adaptive-symbolic.svg
- [x] app-installed-symbolic.svg (_symlinked to `emblem-default-symbolic.svg`_)
- [x] app-remove-symbolic.svg
- [x] chat-none-symbolic.svg
- [x] chat-symbolic.svg
- [x] cigarette-none-symbolic.svg
- [x] cigarette-symbolic.svg
- [x] desktop-symbolic.svg
- [x] explore2-symbolic.svg
- [x] external-link-symbolic.svg
- [x] flag-outline-thin-symbolic.svg
- [x] graveyard-symbolic.svg
- [x] heart-filled-symbolic.svg
- [x] money-none-symbolic.svg
- [x] money-symbolic.svg
- [x] nudity-none-symbolic.svg
- [x] nudity-symbolic.svg
- [x] org.gnome.Software-symbolic.svg
- [x] padlock-open-symbolic.svg
- [x] pub-symbolic.svg
- [x] safety-symbolic.svg
- [x] sign-language-symbolic.svg
- [x] strong-language-none-symbolic.svg
- [x] strong-language-symbolic.svg
- [x] test-pass-symbolic.svg
- [x] violence-none-symbolic.svg
- [x] violence-symbolic.svg

### fullcolor-icon-list:
- [x] org.gnome.Software.svg (_refresh the current icon_)
- [x] org.gnome.Software.Create.svg 
- [x] org.gnome.Software.Develop.svg
- [x] org.gnome.Software.Learn.svg (_symlinked to accesories-text-editor_)
- [x] org.gnome.Software.Play.svg (_symlinked to games-app_)
- [x] org.gnome.Software.Socialize.svg
- [x] org.gnome.Software.Work.svg (_symlinked to to-do-app_)
- [x] system-component-addon.svg
- [x] system-component-application.svg
- [x] system-component-codecs.svg
- [x] system-component-driver.svg
- [x] system-component-firmware.svg
- [x] system-component-input-sources.svg
- [x] system-component-language.svg (_symlinked to preferences-desktop-locale_)
- [x] system-component-os-updates.svg
- [x] system-component-runtime.svg

### CODE REVIEW

**Comment by Muqtxdir** [comment]
@LinuxLlama @Jupi007 since you both are on the latest build of `gnome-software`  would you take a look at this branch ?

**Comment by LinuxLlama** [comment]
I've been using it for a while; it looks great overall! I couldn't find any missing iconography. The only possible thing I could note is the up-to-date splash. Should this be yaruified?

Screenshot from 2021-08-31 11-48-01

**Comment by Muqtxdir** [comment]
> The only possible thing I could note is the up-to-date splash. Should this be yaruified?

Sorry to disappoint here.`gnome-software` actually has `up-to-date.svg` embedded as resource file in the [`gs-updates-page.ui`](https://gitlab.gnome.org/GNOME/gnome-software/-/blob/main/src/gs-updates-page.ui). However it could be patched/modified in ubuntu to make use of the icon present in any given icon-theme but it's better if this was changed in upstream since people use yaru on other distributions as well

**Comment by Muqtxdir** [comment]
merging then, thanks to everyone who tried this branch :+1:

**Pull request merged**
