### PR TITLE
Prepare for ubuntu release 20.04.2

### PR DESCRIPTION
**Pull request by 3v1n0**
Let me know if this is fine to release as it is up to commit e402f7b8.

Please don't merge anything before this, or let me know in case so I can rebase.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Nothing urgent on my list that would be ready now. Eventually @ubuntujaggers has something in the pipeline?

**Comment by Feichtmeier** [comment]
@3v1n0 one thing... Which version of gnome shell well you put in now? Because the keyboard had a change to use symbolic icons instead of assets. This needs also a change to the theme

**Comment by ubuntujaggers** [comment]
I've got some near future bits for templates, the rest of the spring clean, and legacy buttons - will we get chance to do them after?

**Comment by 3v1n0** [comment]
> @3v1n0 one thing... Which version of gnome shell will you put in now? Because the keyboard had a change to use symbolic icons instead of assets. This needs also a change to the theme

It would be 3.35.91, from what I see it seems to work properly with current master right now, but we have time to fix it later if I'm missing something

**Comment by Feichtmeier** [comment]
Alrighty, then!
I need to apply the fix later then, it's nice that they remove more and more assets from shell :+1:

**Comment by Feichtmeier** [comment]
@3v1n0 

Okay we have some changes in master - please rebase!
(And really make sure that your version of gnome shell doesnt have the on screen keyboard asset change it, otherwise I need to make a change to the theme)

**Pull request merged**
