### PR TITLE
Adding revised version of quadrapassel based on madsrh's mockup

### PR DESCRIPTION
**Pull request by ubuntujaggers**
image

Hope that worked!

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1120`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1120` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Nice one!

image

**Comment by eaglersdeveloper** [comment]
What about icon with multi-colored tiles?

quadrapassel-app

**Comment by Feichtmeier** [comment]
I'd prefer the commited icon - I'd say merge it if you tested it @clobrano

**Comment by clobrano** [comment]
I agree. Merging

**Comment by eaglersdeveloper** [comment]
Hardly in tetris all tiles will be the same color.

**Comment by clobrano** [comment]
It is an icon, not a screenshot

**Pull request merged**
