### PR TITLE
colors: use brighter background for hover elements

### PR DESCRIPTION
**Pull request by clobrano**
All popover in both gtk and shell use bg_color (#F7F7F7), while the
context menu is using base_color (#FFFFFF).

Use bg_color for context menu as well (also has better contrast over
Nautilus notebook wich is pure white

see: #1832

### CODE REVIEW

**Comment by madsrh** [comment]
🙈 It's actually the (#F7F7F7) I don't like. Better (#FAFAFA) everything or as @Feichtmeier just suggested [here](https://github.com/ubuntu/yaru/issues/1832#issuecomment-590813601), white. What do you think?

**Comment by clobrano** [comment]
Let's try with FAFAFA

**Comment by clobrano** [comment]
With the new organization of the shell files, the background is based on bg_color (instead that on osd colors for example), so using FAFAFA we're introducing a new color not belonging to the palette. I'm not against, I just want you to know :)

**Comment by clobrano** [comment]
wait, there is a problem with the dark variant

**Comment by clobrano** [comment]
@madsrh have a look :wink:

**Comment by madsrh** [comment]
+1 I think this is good. Are you also +1 @Feichtmeier / @friendlyapple?

**Comment by Feichtmeier** [comment]
I need to test it - it's for both shell and gtk, right?

**Comment by madsrh** [comment]
okay, **EDIT:** I tried this before "Merge branch 'master' into sync-context-menu-color-with-popover" but now it looks like the shell is F7F7F7 again 🤷‍♂

**Comment by Feichtmeier** [comment]
Gtk looks good I think - but I am still not sure if the menu really needs to be #fafafa as well :thinking: 
@clobrano I think you need to change this here
https://github.com/ubuntu/yaru/blob/sync-context-menu-color-with-popover/gnome-shell/src/gnome-shell-sass/widgets/_popovers.scss#L8
to ```#fafafa```

**Comment by madsrh** [comment]
Doh, I forgot to restart the shell 🤦‍♂ 


image

**Comment by Feichtmeier** [comment]
It's still f7f7f7 in the shell @madsrh - you can even see it in your sceenshot :D 
We should be able to use lighten for it just to avoid introducing another hex in there:
image

**Comment by madsrh** [comment]
> you can even see it in your sceenshot :D

I think it's an optical illusion 👁👁 I've used the picker and it checks out. Below I've cut out a piece of the shell and moved it over the popover 🤷‍♂ It's the same background

image

**Comment by Feichtmeier** [comment]
Oh... lol! I am an idiot again :D 

So carlo changed the whole bg_color for the shell :man_shrugging: I don't think that this makes much of a different, since there is not much more visible in the shell than this

I think this looks better overall. The contrast between the calendar and the cards on top if it is enough
The only thing that could not provide from this is the on screen keyboard and buttons, because the hover effect is already almost invisible. This reduces the hover difference for elements that use button(normal) -> button(hover) even more
If you are okay with this I am, too. Otherwise maybe better change the color in _popovers.scss

**Comment by clobrano** [comment]
> Otherwise maybe better change the color in _popovers.scss

I prefer to change bg_color, since in popover everything is related to this color, so the change this way is minimal

**Comment by Feichtmeier** [comment]
Okay, I think the contrast is still fine for the calendar:

```#f7f7f7```
Screenshot from 2020-02-27 15-02-51
```#fafafa```
Screenshot from 2020-02-27 15-04-25

But the hover effect for the keyboard buttons is basically gone: 
Screenshot from 2020-02-27 15-08-03

We could fix this later then, explicitly for the keyboard. So no matter how you do it, there is diff :smile:

**Comment by Feichtmeier** [comment]
Okay, I think the contrast is still fine for the calendar:

```#f7f7f7```
Screenshot from 2020-02-27 15-02-51
```#fafafa```
Screenshot from 2020-02-27 15-04-25

But the hover effect for the keyboard buttons is basically gone: 
Screenshot from 2020-02-27 15-08-03

We could fix this later then, explicitly for the keyboard. So no matter how you do it, there is diff :smile:

**Comment by Feichtmeier** [comment]
Yeah me too! 
Just wanted to remind (me at least) to check the keyboard hover :+1:

**Comment by clobrano** [comment]
> Otherwise maybe better change the color in _popovers.scss

I prefer to change bg_color, since in popover everything is related to this color, so the change this way is minimal

**Pull request merged**
