### PR TITLE
Made message dialog all white

### LINKED ISSUE #698: Revert dialogues back to the upstream design
The current dialogues are styled like "classic" dialogues or to look more "generic".

While we had a big discussion about this already (and even a poll) I want to be annoying again and propose that we should revert this styling back to look more like the upstream dialogues.

Pros:
- upstream designers had big discussions about this and it is definitely a design decision to reduce the dialogues on simply the buttons, we want to be as close to upstream as possible anywhere else (I don't want to count the upstream adaptions but they should be quiet numerous) so we could do this here, too
- LibreOffice was pretty proud about having native dialogues finally implemented and with styling them back to the generic look, we somehow "ruin" this milestone
- beside upstream decisions when you look to the dialogues as if you never seen a dialogue before (to reduce the bias) then it is pretty clear what you want to do: press this button OR press that button so there shouldn't be a dire need for a titlebar since you should answer to the questions the dialogue asks you and not drag him around (EDIT: dragin is still possible with CSD dialogues)
- opinion: the upstream dialogues look more "modern"/minimal designed
- the upstream design looks like the GNOME shell dialogues - and we use the light dialogues now in the shell - having a white gtk dialogue and a white shell dialogue could be more usable for the average user who doesn't care if it is GNOME Shell or a gtk window wanting him to proceed/click

Cons:
- Some people want to drag the dialogue around (EDIT: dragin is still possible with CSD dialogues)
- Yaru could like to be on par with the rest of dialogues outside of GNOME

@godlyranchdressing @madsrh @clobrano @luxamman

Sorry for opening this barrel again, but I think if we have the possibility to stick to upstream we should do this.

Current yaru gtk dialogues: 
peek 2018-08-09 14-24
Adwaita gtk dialogues:
peek 2018-08-09 14-14
peek 2018-08-09 14-28

Yaru Shell dialogues:
peek 2018-08-09 14-26

### PR DESCRIPTION
**Pull request by clobrano**
closes #698

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr719`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr719` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Looks good, but is it just me or did you also notice that it isn't centered? 📏 

untitled-1

**Comment by clobrano** [comment]
That's because the text it's centered on the area below the titlebar. I'll add some padding :+1:

**Comment by clobrano** [comment]
Ah, but there's a problem adding unconditional padding, since *sometimes* a title IS present and the padding isn't necessary

image

**Comment by clobrano** [comment]
> Can you reduce the gap between the buttons and move them down a little bit to the bottom?

The padding between the buttons is the one used everywhere, however I actually move the buttons up respect normal, but just because I felt it looked better. Is there a specific reason you think it's better to lower them?

**Comment by Paz-it** [comment]
@clobrano , I see what you mean, It make sense. I think I had the shell in mind ans thought it coould be nice to have these a bit look alike :smile  but looking at it again it's not going to be as beautiful anyway :cry

**Comment by Feichtmeier** [comment]
Merging this now after general agreement on the look. 
Thanks @clobrano :tada:

**Pull request merged**
