### PR TITLE
Adding new legacy full colour actions with proper template

### LINKED ISSUE #2669: "Legacy icons" aren't Free Desktop compliant or done properly
We've got a lot of legacy colour icons which look pretty good, but I think we need to pause and do them properly (I'm not including the LibreOffice icons because those exist in their own sort of bubble).

The icons in question don't get exported from Src like our other colour icons because they're not the same sizes (22px is one that gets used).  Also there are duplicate icons instead of symlinks.  I can do the symlinks, but if I make a full colour icon template to put in Src with 22px and any extra sizes, can someone make the script work with it?

Also, we call them "legacy icons", but it's basically just colour icons with names from the following list, which people will use in their apps:

https://specifications.freedesktop.org/icon-naming-spec/latest/ar01s04.html

We don't have to worry about stuff like mimetypes and apps because we already have good coverage (bigger than the list).  However, actions and categories in Suru are typically symbols.  Now we're in the business of having full colour versions of the actions, I think we should use the Free Desktop spec as a checklist and do them properly in _all_ sizes, with a script to export the pngs, and with symlinks for names that aren't part of the spec but still get used.

I can start by making the Src template with the extra sizes, but can anyone help with updating the script so it exports the extra sizes when they're present?  Then I can start working down the list and turning all those existing 16px icons into full templates, and any of our icon designers are welcome to help with that :)

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Draft PR for working on the new legacy actions.

My process is:

- Remove an icon from the 16px folder of Legacy 
- Make a full version using the new template in this branch and put it in Actions
- **EDIT:** If the old icon was duplicated under different names, update the symlink list and generate the symlinks

These are the Actions in the Free Desktop spec:

- [x] address-book-new
- [ ] application-exit
- [x] appointment-new
- [ ] call-start
- [ ] call-stop
- [x] contact-new
- [x] document-new
- [x] document-open
- [x] document-open-recent
- [x] document-page-setup
- [x] document-print
- [x] document-print-preview
- [x] document-properties
- [x] document-revert
- [x] document-save
- [x] document-save-as
- [x] document-send
- [ ] edit-clear
- [x] edit-copy
- [x] edit-cut
- [x] edit-delete
- [x] edit-find
- [x] edit-find-replace
- [x] edit-paste
- [x] edit-redo
- [x] edit-select-all
- [x] edit-undo
- [x] folder-new
- [x] format-indent-less
- [x] format-indent-more
- [x] format-justify-center
- [x] format-justify-fill
- [x] format-justify-left
- [x] format-justify-right
- [ ] format-text-direction-ltr
- [ ] format-text-direction-rtl
- [x] format-text-bold
- [x] format-text-italic
- [x] format-text-underline
- [x] format-text-strikethrough
- [ ] go-bottom
- [ ] go-down
- [ ] go-first
- [ ] go-home
- [ ] go-jump
- [ ] go-last
- [ ] go-next
- [ ] go-previous
- [ ] go-top
- [ ] go-up
- [x] help-about
- [x] help-contents
- [x] help-faq
- [ ] insert-image
- [ ] insert-link
- [ ] insert-object
- [ ] insert-text
- [ ] list-add
- [ ] list-remove
- [x] mail-forward
- [x] mail-mark-important
- [x] mail-mark-junk
- [x] mail-mark-notjunk
- [x] mail-mark-read
- [x] mail-mark-unread
- [x] mail-message-new
- [x] mail-reply-all
- [x] mail-reply-sender
- [x] mail-send
- [x] mail-send-receive
- [ ] media-eject
- [ ] media-playback-pause
- [ ] media-playback-start
- [ ] media-playback-stop
- [ ] media-record
- [ ] media-seek-backward
- [ ] media-seek-forward
- [ ] media-skip-backward
- [ ] media-skip-forward
- [ ] object-flip-horizontal
- [ ] object-flip-vertical
- [ ] object-rotate-left
- [ ] object-rotate-right
- [ ] process-stop
- [ ] system-lock-screen
- [ ] system-log-out
- [ ] system-run
- [ ] system-search
- [ ] system-reboot
- [ ] system-shutdown
- [ ] tools-check-spelling
- [ ] view-fullscreen
- [ ] view-refresh
- [ ] view-restore
- [ ] view-sort-ascending
- [ ] view-sort-descending
- [ ] window-close
- [ ] window-new
- [ ] zoom-fit-best
- [x] zoom-in
- [ ] zoom-original
- [x] zoom-out

Closes #2669

### CODE REVIEW

**Comment by Amr-Ibra** [comment]
I support getting rid of the "legacy" naming altogether and name the template by its nature, full-color action icons, following what elementary OS icons, KDE Breeze icons and Humanity do. Legacy is very Adwaita-specific.

**Comment by ubuntujaggers** [comment]
Little sneak preview of a new message in Evolution:

image

I took the opportunity to align undo/redo with the LibreOffice theme :+1:

**Comment by Jupi007** [comment]
> I took the opportunity to align undo/redo with the LibreOffice theme +1

Great!

Btw, I see that this list of missing icons is very huge. Do you need some help?

**Comment by ubuntujaggers** [comment]
If you've got time that would be great - can you push to this branch?

**Comment by Jupi007** [comment]
> If you've got time that would be great - can you push to this branch?

I think yes. I'll try to have a look tonight.
Oh, and to avoid any git push clash, I'll tell you what I would work on.

**Comment by ubuntujaggers** [comment]
BTW, for the larger actions, I've settled on flat (larger versions of the 16px) unless it's basically re-using an app icon as a button - looks better so far, but we can rethink if we regret it!

**Comment by ubuntujaggers** [comment]
I've redesigned the mail reply icons to match the symbolics:

image

**Comment by Feichtmeier** [comment]
@ubuntujaggers great work so far 👍 
When it comes to baseplate-less full color icons without an outline, I would double check how they look on the dark them, I fear this could eventually not work

**Comment by ubuntujaggers** [comment]
> @ubuntujaggers great work so far 
> When it comes to baseplate-less full color icons without an outline, I would double check how they look on the dark them, I fear this could eventually not work

Yep, agree - they all need testing against both :+1: medium coloured lines stand out on both.

**Comment by Jupi007** [comment]
@ubuntujaggers I'll have a try with **document-page-setup**

**Comment by ubuntujaggers** [comment]
> BTW, for the larger actions, I've settled on flat (larger versions of the 16px) unless it's basically re-using an app icon as a button - looks better so far, but we can rethink if we regret it!

...and for the ones that re use a full Yaru icon, I'm doing flat for sizes 16-24px at the minute.

**Comment by Jupi007** [comment]
@ubuntujaggers Little suggestion for **mail-inbox** and **mail-outbox** icons: what do you think of, instead use an emblem, having a big arrow which go inside (for inbox) and outside (for outbox) the box?
I think it could have a better visual impact like that.

**Comment by Jupi007** [comment]
@ubuntujaggers I will do **mail-read**, **mail-unread**, **mail-mark-important**.

**Comment by ubuntujaggers** [comment]
> @ubuntujaggers Little suggestion for **mail-inbox** and **mail-outbox** icons: what do you think of, instead use an emblem, having a big arrow which go inside (for inbox) and outside (for outbox) the box?
> I think it could have a better visual impact like that.

Definitely, do you want to have a go?  Only caveat is it has to be fully legible in 16px, because the only place I've seen it in the wild is Evolution sidebar:

image

**Comment by Jupi007** [comment]
> Definitely, do you want to have a go? Only caveat is it has to be fully legible in 16px, because the only place I've seen it in the wild is Evolution sidebar:

I will try 👍

**Comment by ubuntujaggers** [comment]
> @ubuntujaggers I will do **mail-read**, **mail-unread**, **mail-mark-important**.

For the emblem style ones (circle with symbol) I've literally just done fully flat at all sizes, so you might be able to use something like cancel as a template for mail-mark-important.

**Comment by ubuntujaggers** [comment]
This is really bumming me out - look at the Evolution top bar:

image

I've done flat designs for mail-delete and mail-archive, but the app seems determined to use the (non-flat) app icons in those positions.  If anyone can see a way to get round this, I'd be v grateful!

**Comment by Feichtmeier** [comment]
Eventually something with the index?

**Comment by Jupi007** [comment]
Capture d’écran du 2021-03-01 19-49-23

@ubuntujaggers ?

**Comment by Jupi007** [comment]
> This is really bumming me out - look at the Evolution top bar:
> 
> image
> 
> I've done flat designs for mail-delete and mail-archive, but the app seems determined to use the (non-flat) app icons in those positions. If anyone can see a way to get round this, I'd be v grateful!

It indeed use the wrong icon (looks like **backups-app** I think). But looking at Gtk-inspector the icon name is mail-archive. 🤔
Honestly, I don't know what's happening here.

**Comment by Feichtmeier** [comment]
Maybe a wrong or broken symlink?

**Comment by Jupi007** [comment]
@ubuntujaggers The trash button use the **user-trash** icon:

**Comment by Jupi007** [comment]
**Mail-unread** and **mail-read**:

Capture d’écran du 2021-03-02 22-08-21
Capture d’écran du 2021-03-02 22-08-40

**Comment by ubuntujaggers** [comment]
I love mail-read and mail-unread :smile: Only concern is that, at 16px, the star isn't really visible as a star, because it's too small (and two low contrast colours isn't great for discerning the detail).

image

How about just the sealed envelope at the smallest size?  I mean, if you haven't opened it, you haven't read - I think the meaning would be obvious, especially contrasted with the mail-read one.

In terms of inbox and outbox:

image

In this case the coloured arrow is nice and visible because it's on top of a white area, but one advantage of having an emblem is it means we don't have to worry about cases where the arrow will be on a colour instead.  E.g., I don't think this would work as well with a big arrow:

image

And there's a bit of a lack of unity if we have two different arrow styles on the Evolution side bar:

image

I slightly prefer all arrows to be the same. So I think the big arrow inbox/outbox look good in isolation, but the jury's out for me. The advantage of having emblem arrows is that they'll be equally clear on top of any 16px icon :thinking:

**Comment by Feichtmeier** [comment]
What about just a yellow, flat dot on the envelop for unread in small sizes?

**Comment by Jupi007** [comment]
> I love mail-read and mail-unread smile Only concern is that, at 16px, the star isn't really visible as a star, because it's too small (and two low contrast colours isn't great for discerning the detail).
> 
> image
> 
> How about just the sealed envelope at the smallest size? I mean, if you haven't opened it, you haven't read - I think the meaning would be obvious, especially contrasted with the mail-read one.

You're right, the contrast is bad. Here is three another design:

- Transparent outline: Capture d’écran du 2021-03-03 12-37-26
- Yellow dot: Capture d’écran du 2021-03-03 12-40-28
- Or nothing: Capture d’écran du 2021-03-03 12-40-57

---

About the in/outbox icons: these arrows look indeed a bit out of place among the others. I'll revert my changes.

**Comment by ubuntujaggers** [comment]
Yellow dot is quite cute, let's try that for a bit and see how we like it :)

**Comment by Jupi007** [comment]
> Yellow dot is quite cute, let's try that for a bit and see how we like it :)

Let's go!

**Comment by ubuntujaggers** [comment]
Looking at Evolution, if apps are going to mix app icons and actions in their UIs, we should probably not have flat @22 and 24 for these generic Free Desktop ones and copy the app style instead.  I'll change some I've done that are flat in the larger sizes :+1:

**Comment by Amr-Ibra** [comment]
The `mail-mark-junk` and `mail-mark-notjunk` both look like warning signs and not really something related to emails.

The Humanity icons, as seen in Evolution 3.36 on Ubuntu 20.04, give a better signal to what the two icons actually do.

junk_notjunk

**Comment by Feichtmeier** [comment]
Found one that hasn't been on our radar yet, new tab symbolic should prbly also have a coloured version for mate at least
grafik

**Comment by ubuntujaggers** [comment]
Is this more intuitive for mail-mark-junk and mail-mark-notjunk?

image

image

???

**Comment by Amr-Ibra** [comment]
> Is this more intuitive for mail-mark-junk and mail-mark-notjunk?

Yes, they look better in my opinion. Let's see what the others say.

**Comment by Jupi007** [comment]
> Is this more intuitive for mail-mark-junk and mail-mark-notjunk?

Looks much better 👍

**Comment by ubuntujaggers** [comment]
Just pushed a new icon and realised we have conflicts.  Not sure why but will rebase on Master and do a new PR once the icon set is finished, unless anyone can see what's wrong?  I'm always rubbish at understanding conflicts!

**Comment by Feichtmeier** [comment]
I think you would need to resolve the conflict by always taking the version from your branch

Could you check telegram btw? xD Need your help on cursors

**Comment by Jupi007** [comment]
Resolved conflicts 😁

**Comment by ubuntujaggers** [comment]
Thank you!!

**Comment by ubuntujaggers** [comment]
Hi guys,

How does everyone feel about merging this so far into Master?  It's not complete, but every time I'm using Master and go into (say) my e-mail client, I feel like it's a mess.  If we merge this branch into Master, we can do some focussed work on the icons in the set that people don't like (I'm sure there'll be some!) in time for the next release, as well as the missing icons that we encounter most often.

**Comment by madsrh** [comment]
Please merge +1 😀
@ubuntu/yaru-team ?

**Comment by Muqtxdir** [comment]
+1 from me  as well

**Comment by ubuntujaggers** [comment]
The first time you build from Master:

- Switch to another icon theme
- sudo rm -r /usr/share/icons/Yaru
- cd ~/yaru/build && sudo ninja install && git status
- Switch back to Yaru icons

**Pull request merged**
