### PR TITLE
Gnome-software: remove css except green counter

### LINKED ISSUE #2941: GNOME Software 40-41 inconsistencies with Adwaita
**Application:** gnome-software
**Version:** 41~alpha-0.20210701git839e7b0.fc34
**System:** Fedora 34 (Workstation Edition)
**Yaru:** 21.04.1-109-g3b9b1ffa

The latest development version of GNOME Software has some issues with the Yaru theme. Notice the lack of a border around the installed section:

Screenshot from 2021-07-01 08-23-38
Screenshot from 2021-07-01 08-23-52

The updates section has some unusual styling which is also present in the current stable release. The header background should match the rest of the box:

Screenshot from 2021-07-01 08-23-22
Screenshot from 2021-07-01 08-24-01

I'm able to test the new software design using a COPR repository on Fedora 34. [Here's the link for anyone interested.](https://copr.fedorainfracloud.org/coprs/mcrha/gnome-software-devel/)

### PR DESCRIPTION
**Pull request by Feichtmeier**
Eventually
Closes #2941 

@LinuxLlama could you test this branch here?
Option 1 was to remove all css we've put into our _apps for the old gnome software. If this does not fix the issues, I'll just re-insert their app specifc css with yaru colors in here.

### CODE REVIEW

**Comment by LinuxLlama** [comment]
Unfortunately, it seems like nothing changed with this patch :/

Screenshot from 2021-07-02 09-25-48
Screenshot from 2021-07-02 09-25-54

**Comment by Feichtmeier** [comment]
Also for the updates page? @LinuxLlama

**Comment by LinuxLlama** [comment]
Luckily, an update just popped up. It works!

Screenshot from 2021-07-02 12-03-15

**Comment by Feichtmeier** [comment]
Thanks  @LinuxLlama !

**Pull request merged**
