### PR TITLE
Added missing-image symbolic

### LINKED ISSUE #1150: Missing image icon in small size looks bad

### PR DESCRIPTION
**Pull request by madsrh**
(hopefully) fixes #1150

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1229`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1229` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
There is something wrong with the label, can't check now but will tomorrow

**Comment by Feichtmeier** [comment]
Why did you alter this "window-new" label? :thinking: 
https://github.com/ubuntu/yaru/pull/1229/commits/c4813c4d67ef084d660b0a42125b8456c48209bf#diff-e4811c671a8b559dd78365abaa48cb6aR10226
Was it forgotten? Irritates me a bit, sorry for becoming a little nervous and paranoid at the end of the cycles :laughing: 

Was that branch based on master? Because the annoying thing with the symbolic icons is, that you can't just work with different branches and merge in any order like you wish because there are no dedicated src folders for all the different icons, it is just one big svg which get's teared apart by the script and each object is exported with the object-id as the icon name :face_with_head_bandage: 
So wrong merging can happen very quickly.

**Comment by madsrh** [comment]
> Why did you alter this "window-new" label?

Yes, it was forgotten at first. It had some weird label and the other icons have real names.

> Was that branch based on master?

Yes, but I'll pull down a fresh latest and push another version (without the renaming of _window-new_)

**Comment by clobrano** [comment]
> Was that branch based on master?

It looks it misses only latest merge of dropbox icon

**Comment by clobrano** [comment]
> Yes, but I'll pull down a fresh latest and push another version (without the renaming of _window-new_)

I guess you did it right adding the name, otherwise how can we render only the new image? The ruby scripts needs the image name, or it renders all of them

**Comment by Feichtmeier** [comment]
Tested the snap on my host  - it looks like some bit is still missing:

image

**Comment by Feichtmeier** [comment]
Ah yeah ofc, you still need to render the icon with the script =)

**Comment by clobrano** [comment]
That gtk error looks very weird

**Comment by clobrano** [comment]
I tried rendering the svg, but I couldn't make it work anyway. The colored image is shown instead

**Comment by Feichtmeier** [comment]
Pulled the branch, let me see

((( yes we should look into the theme parsing error ^^)))

**Comment by clobrano** [comment]
> ((( yes we should look into the theme parsing error ^^)))

which I don't have :)

**Comment by Feichtmeier** [comment]
Ruby extract script worked for me:

image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1229`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1229` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
The script worked for me too, is the icon used then?

**Comment by Feichtmeier** [comment]
Uhhh still won't work on my host. Checked the location of image-missing-symbolic.svg in a different icon theme... and SOMEHOW ... it is there placed in "actions" -.-'

image


But!

image-missing is not being used! Because I am probably stupid!

I think what happens is:

Window has no icon -> window.png/svg is being used
Window.svg is missing -> image-missing is being used

:man_facepalming: sorry, it was me who came up with this unfinished idea!

So everything is working fine for image-missing.svg

However, we need an icon for window.svg =D

**Comment by clobrano** [comment]
Sorry, it is not completely clear. What's the correct folder for `image-missing-symbolic.svg` and `window.svg`?

**Comment by Feichtmeier** [comment]
Full colour image-missing is correctly placed inside status. The symbolic icon should be also be placed inside status, yet it is not working for the gnome-shell panel even after shell restart :man_shrugging: 

But while checking in other icon themes I found out that they provide a "window.svg" icon which is then being used in the panel if no icon is provided. But we dont have this icon, thus it is missing and thus shell takes up image-missing :face_with_head_bandage: 

I can not verify the folder for image-missing-symbolic because the icon themes I tested all have window.svg and so no fallback is happening
I see what happens when I remove that icon ...

**Comment by clobrano** [comment]
> But while checking in other icon themes I found out that they provide a "window.svg" icon which is then being used in the panel if no icon is provided. But we dont have this icon, thus it is missing and thus shell takes up image-missing face_with_head_bandage

alright, but where is placed that `windows.svg`? Or, which icon themes you used, so that I can try myself?

**Comment by Feichtmeier** [comment]
Tried flat-remix, la capitaine and papirus

Flat-remix placed it in actions/scaleable/ :man_shrugging:  and papirus in /16x16/actions and 22x22/actions and 24x24/actions :face_with_head_bandage:

**Comment by Feichtmeier** [comment]
We could symlink from window-new-symbolic.svg to window-symbolic.svg and see if that works

**Comment by clobrano** [comment]
I am trying to copy Mads icon in other locations, but no luck yet

**Comment by clobrano** [comment]
I made some tests, but no luck. Basically at some point, using `window.svg` I made to have the symbolic icon on the panel, however the same icon was in the dock as well :-1: 
Moreover, using icon browser I can see which icon is taken for image-missing: `image-missing.png` seems to have precedence over `image-missing-symbolic.svg`, then, when I removed all the copies of `image-missing.png`, the system fall-backs to the one from Humanity (for both panel and dock), as you can see here

image

**Comment by madsrh** [comment]
Wow, sorry for causing all this trouble 😥

**Comment by clobrano** [comment]
Not your fault @madsrh, it's a weird behavior I think

**Comment by Feichtmeier** [comment]
@madsrh did everything correct, it's just awkwardly used in gnome-shell. :man_shrugging: 
We could merge it imho after resolving the conflicts

**Comment by madsrh** [comment]
Can we close this one?

**Comment by clobrano** [comment]
I would like to keet it, at least because the icon looks very good. I fixed the conflict, and it should all be good now

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1229`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1229` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Unless #1245 already includes this missing-image

**Comment by clobrano** [comment]
closing this since it's content is in #1245 as well

**Pull request closed without merging**
