### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by Jupi007**
- [x] Drop inverted screenshots from README ;
- [x] drop snap build status shield ;
- [x] update screenshots.

### CODE REVIEW

**Comment by Muqtxdir** [comment]
maybe update the screenshots as well?

**Comment by Jupi007** [comment]
Indeed, will do it :)

**Comment by Feichtmeier** [comment]
ahhh long overdue :D
I think you can also remove the snap build status shield

**Comment by Jupi007** [comment]
## New screenshots:

Capture d’écran du 2021-10-03 14-00-01
Capture d’écran du 2021-10-03 14-00-15
Screenshot from 2021-10-03 14-01-44
Screenshot from 2021-10-03 14-03-19
Screenshot from 2021-10-03 14-03-55
Screenshot from 2021-10-03 14-07-54
Screenshot from 2021-10-03 14-05-03

**Pull request merged**
