### PR TITLE
Draft PR for folded corners on text icons

### LINKED ISSUE #2268: Enhance the current curl or add a paper fold on file icons
**This issue is for discussing enhancing curl at the bottom of the mimetype icons or adding a paper fold at the top!**

image
_Enhanced, Fold and current_ 👆 

For a long time now, I've found the paper curl at the bottom of the mimetype icons to be too subtle. At the moment, the current curl is only present at 256 px (and above ofc). 
The fold would be a clear distinction between the application and file icons.

Adding the top fold, is a very controversial suggestion and it's also a massive amount of work to adapt the current 54 icons. A less intrusive suggestion is to increase the current curl.

In no particular order, here's document icons from OSX, Windows, Humanity, Adwaita, Papirus and Yaru 📄 

image

### PR DESCRIPTION
**Pull request by ubuntujaggers**
- I've tried to pick up all the white notepad-style icons, but I've probably missed a couple

- There were a lot of "symlinks" that were actually copies of .pngs with a different name - I've fixed this wherever I found it (at least I think I have!)

- So far, richer apps like Libre Office haven't been done, especially since the top right corner is an iconic part of the design

Before:

image

After:

image

Give it a whirl and let me know a) what you think and b) if you find any problems!

Closes #2268

### CODE REVIEW

**Comment by madsrh** [comment]
I've only tried this PR for a short time but I really like it @ubuntujaggers 🎉 

The only minor "problem" I experience is that sometimes I come across a file, that makes me wonder: "_Why does/doesn't this file have a curl_?". I imagine that we might spend much time discussing which files should have a curl (not that you didn't do a smashing job with this PR) - it's just that, having no curl would solve this 😄 

I DO like the look and I'm keen to hear what the others think!

**Comment by ubuntujaggers** [comment]
We can definitely add more - I might have simply missed some! Stick the names of candidates in here 👍

**Comment by Feichtmeier** [comment]
> I've only tried this PR for a short time but I really like it @ubuntujaggers tada
> 
> The only minor "problem" I experience is that sometimes I come across a file, that makes me wonder: "_Why does/doesn't this file have a curl_?". I imagine that we might spend much time discussing which files should have a curl (not that you didn't do a smashing job with this PR) - it's just that, having no curl would solve this smile
> 
> I DO like the look and I'm keen to hear what the others think!

I think only things that have text-readable-by-humans in them, should have the curl.
Everything else, i.e. not-readble-by-humans/binary/archives/packages should NOT have a curl. (imo :) )

**Comment by Jupiter007-43** [comment]
> I think only files that have text-readable-by-humans in them should have the curl.
> Everything else, i.e. not-readble-by-humans/binary/archives/packages should NOT have a curl. (imo :) )

That is also my opinion, only humans-readable files should have a curl.

**Comment by madsrh** [comment]
> I think only files that have text-readable-by-humans in them should have the curl.

Sorry, I'm confused. You mean also files like CSS, HTML, JS,...?

IMO files like Rich Text files - which can't be read in e.g. Gedit, but still have human-readable-text when opened in the associated application - should have a curl. But something like SystemD files which contain plain text, perhaps shouldn't 🤷‍♂️ 

image

**Comment by Jupiter007-43** [comment]
> Sorry, I'm confused. You mean also files like CSS, HTML, JS,...?

IMO they should have a curl (at least all **text-x-***** mimetype should have one).

**Comment by Feichtmeier** [comment]
Yes all text files

**Comment by ubuntujaggers** [comment]
What about PDFs?

**Comment by madsrh** [comment]
> What about PDFs?

Fold

**Comment by Feichtmeier** [comment]
Missing mimetypes where I think we need a fold, because can be opened by a text editor/IDE and then read by humans:

- all LO docs
- all x-office docs
- arduino
- html template (not sure on this one, i cant find it, is this binary?)
- all ms office docs

**Comment by Jupiter007-43** [comment]
Html template are just like html++ (human readable so). Here is a bit of Twig:

```twig
{%- block time_widget -%}
    {%- if widget == 'single_text' -%}
        {{ block('form_widget_simple') }}
    {%- else -%}
        {%- set vars = widget == 'text' ? { 'attr': { 'size': 1 }} : {} -%}
        {% set attr = attr|merge({class: (attr.class|default('') ~ ' select-time')|trim}) %}
        <div {{ block('widget_container_attributes') }}>
            {{ form_widget(form.hour, vars) }}{% if with_minutes %} : {{ form_widget(form.minute, vars) }}{% endif %}{% if with_seconds %} : {{ form_widget(form.second, vars) }}{% endif %}
        </div>
    {%- endif -%}
{%- endblock time_widget -%}
```

**Comment by ubuntujaggers** [comment]
I'm trying to work out how to do the LO mimetypes with a folded corner - what do you think of this:

**Current**

image

image

**Suggested**

image

image

**Comment by Jupiter007-43** [comment]
It looks very great!

**Comment by Feichtmeier** [comment]
Looks cool!
But while you're on it... Can you maybe modernize the pictogram inside? I think the LO guys said that we can do what we want

**Comment by ubuntujaggers** [comment]
Hi guys,

image

image

??

**Comment by ubuntujaggers** [comment]
Hi guys,

Try now for the Libre Office mimetypes :+1:

**Comment by ubuntujaggers** [comment]
Microsoft Office now added :+1:

**Comment by ubuntujaggers** [comment]
Just pushed pdf:

image

image

image

**Comment by madsrh** [comment]
It's ready for 21.04 😅 looks great @ubuntujaggers 🎖️

**Comment by Jupiter007-43** [comment]
Tested and honestly it's very very great 👍
But IMO some more icons should have a folded corner:

- json
- perl
- shell-script
- yaml
- html-template

Maybe also add a template to make it easier to create new icon.

**Comment by ubuntujaggers** [comment]
Good point, I'll add them :+1:

**Comment by ubuntujaggers** [comment]
Okay, try now :+1:

**Comment by Jupiter007-43** [comment]
Tested, you did an huge work 😳

You should also fold these ones (and that's it I think):

- application-json
- application-pgp-keys
- application-x-ipynb+json
- application-x-rss+xml

**Comment by ubuntujaggers** [comment]
> Tested, you did an huge work 
> 
> You should also fold these ones (and that's it I think):
> 
> * application-json
> * application-pgp-keys
> * application-x-ipynb+json
> * application-x-rss+xml

Should be done now :+1:

**Comment by Feichtmeier** [comment]
Heroic task @ubuntujaggers 💪 
Ready to merge? (no hurry, just nothing to do ^^)

**Comment by ubuntujaggers** [comment]
I would be happy to merge - lots of time before next release to spot/fix any errors with them 👍

**Pull request merged**
