### PR TITLE
Updated version of source-symbolic.svg with symbols for Suru apps and the Adwaita-style "select all" action

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Hi all,

Think this has to be one PR because it's just a series of edits to the same big file.

My revised version of source-symbolic.svg includes:

- An icon for "edit-select-all" using the motif from Adwaita, which was the least unpopular option.  I've redrawn the perimeter so the corners look better when you view it at the intended 16px - this is achieved by having diagonal gaps, which I took from @eaglersdeveloper 's design.

image

image

- Symbols for all the Suru apps.  There's no reason why we can't improve these further and add any I missed.  Also, I redrew accessories-text-editor and image-viewer so they look more like the full colour icons in Suru:

image

image

Let me know if there are any problems!  It's a big svg with lots of intricate parts, so hopefully I didn't cock anything up...

### CODE REVIEW

**Comment by eaglersdeveloper** [comment]
They will be good, if you add shape to all application icons.

**Comment by Feichtmeier** [comment]
@ubuntujaggers thank you very much!

To make those wonderful icons work we need to

1) run extract-symbolic-icons.rb
2) write down symlinks in yaru/icons/src/symlinks/symbolic/apps.list then run ./generate-symlinks.sh
Then... there are somehow waaaaay too much symlinks created. Even when you add a argument when you run the script :man_shrugging: 

Also you need to make sure that really all icons are 1) grouped and that group is correctly named and in the correct layer (apps)  (rightclick-> move to layer -> apps)
image

Alternatively since you already did a shitload of work, I could make a new branch and pull your changes into it and then try to make it work?
To test it, you would need to add some lines into the SASS code of the shell anyways. You decide

**Comment by ubuntujaggers** [comment]
I think all icons I added are already grouped and in the correct layer, "apps" for all of them except the select all action, but I will check I didn't miss any. Then I will get on my laptop and follow your instructions :)

**Comment by Feichtmeier** [comment]
after
sudo ninja install
and icon change forth and back thunderbird still has no symbolic icon, aswell as gnome-tweaks, gnome-weather and system-monitor

I wanted to check if you extracted all icons and ran the extract script which threw the following error

```bash
yaru@yaru:~/yaru/icons/src/scalable$ ./extract-symbolic-icons.rb
Rendering from icons in ./source-symbolic.svg
Going through layer 'status'
 -- software-installed already exists
 -- network-wired-offline already exists
 -- battery-full already exists
 -- battery-good already exists
 -- battery-low already exists
 -- battery-empty already exists
 -- battery-caution already exists
 -- bluetooth-active already exists
 -- bluetooth-disabled already exists
 -- mail-unread already exists
 -- dialog-question already exists
 -- dialog-error already exists
 -- dialog-warning already exists
 >> skipping icon 'dialog-information-alt'
 -- dialog-password already exists
 -- security-low already exists
 -- security-high already exists
 -- security-medium already exists
 -- starred already exists
 -- non-starred already exists
 -- semi-starred-rtl already exists
 -- semi-starred already exists
 -- changes-prevent already exists
 -- changes-allow already exists
 -- view-private already exists
 -- network-cellular-signal-none already exists
 -- network-cellular-signal-weak already exists
 -- network-cellular-signal-ok already exists
 -- network-cellular-signal-good already exists
 -- network-cellular-signal-excellent already exists
 -- network-cellular-offline already exists
 -- network-cellular-signal-none-secure already exists
 -- network-cellular-signal-weak-secure already exists
 -- network-cellular-signal-ok-secure already exists
 -- network-cellular-signal-good-secure already exists
 -- network-cellular-signal-excellent-secure already exists
 -- network-wireless-hotspot already exists
 -- audio-volume-high already exists
 -- audio-volume-medium already exists
 -- audio-volume-low already exists
 -- audio-volume-muted already exists
 -- network-cellular-4g already exists
 -- network-cellular-3g already exists
 -- network-cellular-gprs already exists
 -- network-cellular-hspa already exists
 -- network-cellular-edge already exists
 -- network-cellular-connected already exists
 -- microphone-sensitivity-high already exists
 -- microphone-sensitivity-medium already exists
 -- microphone-sensitivity-low already exists
 -- microphone-sensitivity-muted already exists
 -- printer-error already exists
 -- printer-warning already exists
 -- printer-printing already exists
 -- network-transmit-receive already exists
 -- network-receive already exists
 -- network-transmit already exists
 -- network-idle already exists
 -- media-playlist-repeat already exists
 -- media-playlist-no-repeat already exists
 -- media-playlist-repeat-rtl already exists
 -- media-playlist-no-repeat-rtl already exists
 -- media-playlist-repeat-song already exists
 -- media-playlist-repeat-song-rtl already exists
 -- media-playlist-shuffle already exists
 -- media-playlist-shuffle-rtl already exists
 -- media-playlist-consecutive already exists
 -- media-playlist-consecutive-rtl already exists
 -- display-brightness already exists
 -- keyboard-brightness already exists
 -- alarm already exists
 -- appointment-missed already exists
 -- appointment-soon already exists
 -- rotation-locked already exists
 -- rotation-allowed already exists
 -- view-wrapped already exists
 -- view-wrapped-rtl already exists
 -- call-missed already exists
 -- mail-read already exists
 -- mail-attachment already exists
 -- mail-replied already exists
 -- weather-clear already exists
 -- weather-cloudy already exists
 -- weather-overcast already exists
 -- weather-showers-scattered already exists
 -- user-available already exists
 -- user-invisible already exists
 -- user-idle already exists
 -- user-busy already exists
 -- user-away already exists
 -- user-status-pending already exists
 -- user-offline already exists
 -- avatar-default already exists
 -- battery-full-charging already exists
 -- battery-good-charging already exists
 -- battery-low-charging already exists
 -- battery-caution-charging already exists
 -- battery-empty-charging already exists
 -- battery-full-charging already exists
 -- weather-fog already exists
 -- weather-storm already exists
 -- weather-few-clouds already exists
 -- weather-windy already exists
 -- weather-snow already exists
 -- weather-clear-night already exists
 -- weather-few-clouds-night already exists
 -- weather-severe-alert already exists
 -- weather-showers already exists
 -- task-past-due already exists
 -- task-due already exists
 -- channel-secure already exists
 -- channel-insecure already exists
 -- touchpad-disabled already exists
 -- night-light already exists
 -- user-trash-full already exists
 -- battery-full-charged already exists
 -- network-wired-no-route already exists
 -- network-error already exists
 -- network-wired-disconnected already exists
 -- network-cellular-acquiring already exists
 -- network-wired-acquiring already exists
 -- network-cellular-no-route already exists
 -- battery-missing already exists
 -- folder-open already exists
 -- folder-drag-accept already exists
 -- folder-visiting already exists
 >> skipping icon 'network-wireless-signal-excellent-alt'
 >> skipping icon 'network-wireless-signal-good-alt'
 >> skipping icon 'network-wireless-signal-ok-alt'
 >> skipping icon 'network-wireless-signal-weak-alt'
 >> skipping icon 'network-wireless-offline-alt'
 >> skipping icon 'network-wireless-signal-none-alt'
 >> skipping icon 'network-wireless-no-route-alt'
 >> skipping icon 'network-wireless-acquiring-alt'
 >> skipping icon 'network-wireless-connected-alt'
 >> skipping icon 'network-wireless-signal-excellent-secure-alt'
 >> skipping icon 'network-wireless-signal-good-secure-alt'
 >> skipping icon 'network-wireless-signal-ok-secure-alt'
 >> skipping icon 'network-wireless-signal-weak-secure-alt'
 >> skipping icon 'network-wireless-signal-none-secure-alt'
 -- network-wireless-encrypted already exists
 -- dialog-information already exists
 -- network-vpn-acquiring already exists
 -- network-vpn already exists
 -- software-update-available already exists
 -- software-update-urgent already exists
 -- thunderbolt-acquiring already exists
 -- process-working already exists
 -- network-wireless-signal-good already exists
 -- network-wireless-signal-ok already exists
 -- network-wireless-signal-weak already exists
 -- network-wireless-signal-none already exists
 -- network-wireless-offline already exists
 -- network-wireless-signal-excellent-secure already exists
 -- network-wireless-signal-good-secure already exists
 -- network-wireless-signal-ok-secure already exists
 -- network-wireless-signal-weak-secure already exists
 -- network-wireless-signal-none-secure already exists
 -- network-wireless-signal-excellent already exists
 -- network-wireless-acquiring already exists
 -- network-wireless-no-route already exists
 -- network-wireless-connected already exists
Traceback (most recent call last):
        12: from ./extract-symbolic-icons.rb:81:in `<main>'
        11: from /usr/lib/ruby/2.5.0/rexml/element.rb:394:in `each_element'
        10: from /usr/lib/ruby/2.5.0/rexml/element.rb:927:in `each'
         9: from /usr/lib/ruby/2.5.0/rexml/xpath.rb:68:in `each'
         8: from /usr/lib/ruby/2.5.0/rexml/xpath.rb:68:in `each'
         7: from /usr/lib/ruby/2.5.0/rexml/element.rb:927:in `block in each'
         6: from ./extract-symbolic-icons.rb:84:in `block in <main>'
         5: from /usr/lib/ruby/2.5.0/rexml/element.rb:394:in `each_element'
         4: from /usr/lib/ruby/2.5.0/rexml/element.rb:927:in `each'
         3: from /usr/lib/ruby/2.5.0/rexml/xpath.rb:68:in `each'
         2: from /usr/lib/ruby/2.5.0/rexml/xpath.rb:68:in `each'
         1: from /usr/lib/ruby/2.5.0/rexml/element.rb:927:in `block in each'
./extract-symbolic-icons.rb:87:in `block (2 levels) in <main>': undefined method `value' for nil:NilClass (NoMethodError)
```

Looking into the ~/yaru/icons/Suru folder
image
There are still icons and symlinks missing in apps aswell as no updated edit-select-all icon 

I think there are still some errors in that big SVG file and after we fixed them, we need to write down a bunch of symlinks (weather-app -> gnome-weather... tweaks-apps -> gnome-tweaks) and then extract the icons an then create symlinks

**Comment by ubuntujaggers** [comment]
Argh, sorry, I haven't done the script yet - I literally just fixed the graphical errors in the SVG that I'd pushed to my fork so there wasn't a wrong version in the PR, I haven't completed the whole process yet.

**Comment by ubuntujaggers** [comment]
Aha!  I **believe** I've discovered the error and it's something that exists in the upstream svg too (I also think I know why this hasn't been a problem before).

This is from the ReadMe:

_"extract any new symbolic icons from the source SVG by passing the icon name to this script: ./extract-symbolic-icons.rb <icon-name>
or, if run generally, this script will look through the entire source file to render any new icons (**if a new icon does not have a correct label the script will fail**)"_

Looking at your output, @Feichtmeier, the Ruby script is going through the "icons" (= named object groups) in the same order as if you click on one in Inkscape and repeatedly hit Tab to go to the next one.

So, we can see exactly what icon it failed at.  It's an icon for a speaker/volume glyph with a yellow warning sign.  This hasn't been named (it's still got the default label of _[hash symbol]g2444_ and I believe that's why the script failed before it had even got to the end of the status icons.  It found one without a valid label.

Result = none of the rest of the icons and symlinks (including our new ones) were made because the script fell over before it finished the status icons.

Because this nameless group exists all the way upstream, I'm guessing it hasn't been noticed or fixed before because people have been extracting new icons individually, by name, and it's a while since anyone tried to run the script over the whole svg?  I'm guessing it's a while since this many were added at once.

First things first: I will see if I can work out what the offending status icon should be called and fix the version of source-symbolic in the PR.  But it may be there are other invalid icon names that come out of the woodwork now, simply because it's the first time in a while that the whole file has been processed.  It may be that the quickest way to identify invalid icon names is looking at the xml for the svg in notepad, I'll give it a shot.

**Comment by ubuntujaggers** [comment]
Okay, this is a pain.  This is from the XML for the last icon that the script was able to process:

<g
       transform="matrix(0.16666667,0,0,0.16666667,1144.3097,-280.0843)"
       id="g2445"
       style="display:inline;stroke-width:6"
       **inkscape:label="network-wireless-connected"**>

As far as I can see, the emboldened property of _inkscape:label_ is missing entirely from the icon that comes next and caused the script to fail.

I was hoping it would be there with _inkscape:label="something invalid"_ so we might be able to ctrl-f through the XML for more examples of the same problem and check there weren't any.  But it's not that simple.

So, in short: regardless of whether you use the new version of source-symbolic, the one that's already Yaru, or the one from upstream Suru, I think the Ruby script will fail at the same point if you try to process the whole file, rather than pointing to a specific named icon.

It's very easy to fix this one icon, but, if we do that and run the script, it might still fail if it encounters the same problem later in the file, and I haven't yet discovered an easy way to check the XML for other instances of it.

Two possible approaches:

- Click on every icon individually in Inkscape, including old ones, and eyeball the properties;
- Fix this one icon, run the script, and hope it works - if not, check where it failed and make another fix.

**Comment by Feichtmeier** [comment]
Ah thanks for investigating!!!

I wonder when this happened. I am very sure that I have run this script before :thinking:  without errors but... that does not matter now, we just need it fixed + all your shiny new icons!

I would really vote for a deeper fix, so we fix it now and have it fixed "forever"
Since it is still your branch you decide which fix you prefer :dancing_men:

**Comment by ubuntujaggers** [comment]
Okay - looks like the offending icon was added upstream in a commit on 31 August, so the script wouldn't have errored at this point until Yaru took it, I think on 3 September?

I've checked the properties of every group in Inkscape and, unless I missed one, all the others have valid names.  I gave the nameless symbol a label of "volume-warning" (because it's 🔊 + ⚠) and will push it now.

**Comment by ubuntujaggers** [comment]
Script is working now! Still running :)

**Comment by Feichtmeier** [comment]
Yep awesome @ubuntujaggers just tried it :)
Libreoffice, Firefox, archive manager, thunderbird, gnome-mines work so far
Other apps that need a symlink don't work like gnome-system-monitor (installed the deb, the snap doesnt work either way :face_with_head_bandage: ) and gnome-tweaks (configurator-app)

Gnome apps not working could also come from "wrong" symlinks since gnome renamed there apps to... org.gnome.XXX and so on
But the symlink lists in the symbolic folder are pretty empty either way

**Comment by ubuntujaggers** [comment]
I haven't committed any of the new individual icons (I've had to make some further amendments to the source file and re-run the script repeatedly) **but** I finally have all the individual icons now looking correct locally when I view them individually  :)

I haven't yet run the symlink script because I've been ironing out creases in the big svg but I'll try that next.

**Comment by ubuntujaggers** [comment]
Okay, I'm afraid I'm a bit lost.

"write down symlinks in yaru/icons/src/symlinks/symbolic/apps.list then run ./generate-symlinks.sh
Then... there are somehow waaaaay too much symlinks created."

I ran the script and it seemed to "do something" but apps.list hasn't changed?

I've got as far as having a fully fixed version of source-symbolic and alllllllllll the individual new icons in the scalable apps folder (plus the new select-all in actions) which I'm happy to commit/push to this PR.  But I'm a bit bewildered by this symlink bit  :thinking:

**Comment by Feichtmeier** [comment]
Only commit the new symlinks. Somehow that script is not working as expected or I did not understand it correctly. No matter which arguments I use, it still  creates too many symlinks. 
Did you install some git UI yet? It is a lot easier to only commit individual files and revert the rest (or... not really easier... but maybe a bit more resistant against user errors)

**Comment by Feichtmeier** [comment]
@ubuntujaggers one thing I did not understand... why do you want to install the snap on cosmic? Remove that snap and reboot into the ubuntu session
then
sudo apt install git meson sassc libgtk-3-dev gtk-3-examples
gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true
git clone https://github.com/ubuntu/yaru
cd yaru
meson install --prefix=/usr
cd build
sudo ninja install
reboot
log into Yaru session

No need for the snap for you :dancer:

**Comment by ubuntujaggers** [comment]
> Only commit the new symlinks. Somehow that script is not working as expected or I did not understand it correctly. No matter which arguments I use, it still creates too many symlinks.

Well I now know why I'm confused - I don't think I know what a symlink looks like or where it goes, I can't see anything new after I run it.  I know what a symlink does (and why) but is it a file with an extension?  Is it a hidden file?

I thought the script was meant to be adding new entries to that file called "apps.list" but I realise now that makes no sense - because I couldn't commit only the new symlinks, if they were just entries in the same single file.

I've been clicking around the Suru folders but can't see what a symlink actually is?  Sorry, I'm not very technical  :)  and at least I will know how to do it myself next time.

Also, big thanks for the instructions on how to get/test the latest Yaru - I just knew that the snap stopped working when I upgraded to Cosmic.  Switching to edge channel (and the PR-specific channels) was the only way I knew how to try new features  :)

**Comment by ubuntujaggers** [comment]
Ohhhh I get it. They look like normal svgs in file manager but have a little "redirection arrow" on the icon to show it's a link.

**Comment by Feichtmeier** [comment]
It's basically just a pointer to the real icon
So when you change the icon all symlinks change

Yes, you first put links on the list
Then run the script
Then or creates tooooo much symlinks and you only commit the new ones

We could also consider just to use
```bash
 ln -s
```
And update the lists just in case the script is used by anyone in the future xD

**Comment by ubuntujaggers** [comment]
_"Yes, you first put links on the list"_

Ah, that's the missing ingredient.  I didn't get any new symlinks because I didn't add anything to the list.  Sorry.

**Comment by ubuntujaggers** [comment]
Okay, so the current symbolic/apps.list has about half a dozen entries of the format:

system-file-manager**-symbolic.svg** org.gnome.Nautilus**-symbolic.svg**

The corresponding line in the (much fuller) fullcolor/apps.list file is:

system-file-manager**.png** org.gnome.Nautilus**.png**

So, I think the right thing to do is to clone all the entries from fullcolor/apps.list into symbolic/apps/list, but replace all instances of **.png** with **-symbolic.svg** when I do.

For instance:

tweaks-app.png gnome-tweak-tool.png

becomes:

tweaks-app-symbolic.svg gnome-tweak-tool-symbolic.svg

...and then the symlinks for symbolic app icons should be identical to the symlinks for their full colour counterparts.

@Feichtmeier: before I press the red button and make all these symlinks, does that sound like the right thing to do?

**Comment by Feichtmeier** [comment]
This sounds good!
But I think it is "configurator-app-symbolic.svg" or am I wrong?
Sorry for the late reply, kinda done for today :dizzy:

**Comment by ubuntujaggers** [comment]
**I haven't tested this,** I will try to follow @Feichtmeier's steps above tomorrow unless someone beats me to it!

This has turned into a monster - I created the PR when I thought it would just be one file (source-symbolic) so hopefully this is okay.  **Let me know if not.**

"This branch has conflicts" = source-symbolic.svg.  As discussed, I changed the thinner system-shutdown glyph to the old (bolder) one so this conflict should be fine.

I ran the two scripts and got **a lot** of new icons and new symlinks for apps.  I only committed/pushed the new icons and new symlinks.  Result: the app symbols should now have complete parity with the full colour symbol apps, down to stuff like _seahorse-symbolic.svg_ being a symlink to _passwords-app-symbolic.svg_, exactly like the full colour counterparts.  So, I think the symbolic coverage of apps is now as complete as the full colour icon set  :)

Here's the complete list of changes:

SURU/SCALABLE/APPS

Committed/pushed the following icons and symlinks:

git add accessories-calculator-symbolic.svg
git add accessories-camera-symbolic.svg
git add accessories-character-map-symbolic.svg
git add accessories-text-editor-symbolic.svg
git add address-book-app-symbolic.svg
git add amazon-store-symbolic.svg
git add applets-screenshooter-symbolic.svg
git add apport-symbolic.svg
git add aptdaemon-download-symbolic.svg
git add backups-app-symbolic.svg
git add baobab-symbolic.svg
git add bash-symbolic.svg
git add bijiben-symbolic.svg
git add ca.desrt.dconf-editor-symbolic.svg
git add calculator-app-symbolic.svg
git add calendar-app-symbolic.svg
git add calendar-symbolic.svg
git add camera-app-symbolic.svg
git add cheese-symbolic.svg
git add clock-app-symbolic.svg
git add configurator-app-symbolic.svg
git add dconf-editor-symbolic.svg
git add deja-dup-symbolic.svg
git add disk-usage-app-symbolic.svg
git add disk-utility-app-symbolic.svg
git add documents-app-symbolic.svg
git add docviewer-app-symbolic.svg
git add ebook-reader-app-symbolic.svg
git add empathy-symbolic.svg
git add eog-symbolic.svg
git add error-app-symbolic.svg
git add evince-symbolic.svg
git add evolution-symbolic.svg
git add filemanager-app-symbolic.svg
git add file-roller-symbolic.svg
git add firefox-symbolic.svg
git add gallery-app-symbolic.svg
git add games-app-symbolic.svg
git add gedit-symbolic.svg
git add gksu-root-terminal-symbolic.svg
git add gnome-aisleriot-symbolic.svg
git add gnome-books-symbolic.svg
git add gnome-calculator-symbolic.svg
git add gnome-calendar-symbolic.svg
git add gnome-characters-symbolic.svg
git add gnome-clocks-symbolic.svg
git add gnome-contacts-symbolic.svg
git add gnome-control-center-symbolic.svg
git add gnome-disks-symbolic.svg
git add gnome-documents-symbolic.svg
git add gnome-help-symbolic.svg
git add gnome-logs-symbolic.svg
git add gnome-mahjongg-symbolic.svg
git add gnome-maps-symbolic.svg
git add gnome-mines-symbolic.svg
git add gnome-music-symbolic.svg
git add gnome-photos-symbolic.svg
git add gnome-screenshot-symbolic.svg
git add gnome-sudoku-symbolic.svg
git add gnome-system-monitor-symbolic.svg
git add gnome-terminal-symbolic.svg
git add gnome-tweak-tool-symbolic.svg
git add gnome-usage-symbolic.svg
git add gnome-weather-symbolic.svg
git add help-app-symbolic.svg
git add help-browser-symbolic.svg
git add help-symbolic.svg
git add image-viewer-app-symbolic.svg
git add image-viewer-symbolic.svg
git add internet-chat-symbolic.svg
git add internet-mail-symbolic.svg
git add internet-web-browser-symbolic.svg
git add libreoffice-base-symbolic.svg
git add libreoffice-calc-symbolic.svg
git add libreoffice-draw-symbolic.svg
git add libreoffice-impress-symbolic.svg
git add libreoffice-main-symbolic.svg
git add libreoffice-writer-symbolic.svg
git add log-viewer-app-symbolic.svg
git add logviewer-symbolic.svg
git add mail-app-symbolic.svg
git add maps-app-symbolic.svg
git add mediaplayer-app-symbolic.svg
git add messaging-app-symbolic.svg
git add multimedia-audio-player-symbolic.svg
git add multimedia-photo-manager-symbolic.svg
git add multimedia-photo-viewer-symbolic.svg
git add multimedia-video-player-symbolic.svg
git add music-app-symbolic.svg
git add nautilus-symbolic.svg
git add notes-app-symbolic.svg
git add office-address-book-symbolic.svg
git add office-addressbook-symbolic.svg
git add office-calendar-symbolic.svg
git add org.gnome.bijiben-symbolic.svg
git add org.gnome.Bijiben-symbolic.svg
git add org.gnome.Books-symbolic.svg
git add org.gnome.Calculator-symbolic.svg
git add org.gnome.Calendar-symbolic.svg
git add org.gnome.Cheese-symbolic.svg
git add org.gnome.clocks-symbolic.svg
git add org.gnome.Clocks-symbolic.svg
git add org.gnome.Contacts-symbolic.svg
git add org.gnome.DejaDup-symbolic.svg
git add org.gnome.Disks-symbolic.svg
git add org.gnome.Documents-symbolic.svg
git add org.gnome.Empathy-symbolic.svg
git add org.gnome.Epiphany-symbolic.svg
git add org.gnome.Evince-symbolic.svg
git add org.gnome.Evolution-symbolic.svg
git add org.gnome.Games-symbolic.svg
git add org.gnome.Gedit-symbolic.svg
git add org.gnome.Maps-symbolic.svg
git add org.gnome.Music-symbolic.svg
git add org.gnome.Nautilus-symbolic.svg
git add org.gnome.Photos-symbolic.svg
git add org.gnome.Podcasts-symbolic.svg
git add org.gnome.PowerStats-symbolic.svg
git add org.gnome.Rhythmbox-symbolic.svg
git add org.gnome.Sudoku-symbolic.svg
git add org.gnome.Todo-symbolic.svg
git add org.gnome.Totem-symbolic.svg
git add org.gnome.tweaks-symbolic.svg
git add org.gnome.Tweaks-symbolic.svg
git add org.gnome.Usage-symbolic.svg
git add org.gnome.Weather.Application-symbolic.svg
git add org.gnome.Weather-symbolic.svg
git add org.gnome.Yelp-symbolic.svg
git add packages-app-symbolic.svg
git add passwords-app-symbolic.svg
git add podcasts-app-symbolic.svg
git add power-statistics-symbolic.svg
git add preferences-desktop-keyboard-symbolic.svg
git add preferences-desktop-symbolic.svg
git add preferences-system-symbolic.svg
git add rhythmbox-symbolic.svg
git add root-terminal-app-symbolic.svg
git add scanner-symbolic.svg
git add screenshot-app-symbolic.svg
git add seahorse-symbolic.svg
git add session-properties-symbolic.svg
git add settings-app-symbolic.svg
git add shotwell-symbolic.svg
git add software-properties-gtk-symbolic.svg
git add software-properties-symbolic.svg
git add software-updater-symbolic.svg
git add sudoku-app-symbolic.svg
git add system-file-manager-symbolic.svg
git add system-help-symbolic.svg
git add system-monitor-app-symbolic.svg
git add system-settings-symbolic.svg
git add system-software-install-symbolic.svg
git add system-software-update-symbolic.svg
git add terminal-app-symbolic.svg
git add terminal-symbolic.svg
git add text-editor-symbolic.svg
git add thunderbird-symbolic.svg
git add to-do-app-symbolic.svg
git add totem-symbolic.svg
git add tweaks-app-symbolic.svg
git add ubiquity-symbolic.svg
git add update-manager-symbolic.svg
git add update-notifier-symbolic.svg
git add usage-app-symbolic.svg
git add usb-creator-gtk-symbolic.svg
git add utilities-system-monitor-symbolic.svg
git add utilities-terminal-symbolic.svg
git add weather-app-symbolic.svg
git add webbrowser-app-symbolic.svg
git add web-browser-symbolic.svg
git add welcome-app-symbolic.svg
git add x-office-address-book-symbolic.svg

*Not* committed because they already existed in scalable/apps:

ubuntusoftware-symbolic.svg
system-users-symbolic.svg
software-store-symbolic.svg
software-center-symbolic.svg
softwarecenter-symbolic.svg
preferences-desktop-locale-symbolic.svg
preferences-desktop-online-accounts-symbolic.svg
preferences-desktop-wallpaper-symbolic.svg
preferences-system-details-symbolic.svg
preferences-system-devices-symbolic.svg
preferences-system-network-symbolic.svg
preferences-system-notifications-symbolic.svg
preferences-system-power-symbolic.svg
preferences-system-privacy-symbolic.svg
preferences-system-search-symbolic.svg
preferences-system-sharing-symbolic.svg
preferences-system-time-symbolic.svg
preferences-ubuntu-panel-symbolic.svg
preferences-desktop-display-symbolic.svg
org.gnome.Software-symbolic.svg
multimedia-volume-control-symbolic.svg
goa-panel-symbolic.svg
gnome-software-symbolic.svg
gnome-power-manager-symbolic.svg
config-users-symbolic.svg

SCALABLE/ACTIONS

git add edit-select-all-symbolic.svg

I've also pushed new versions of symbolic/apps.list and source-symbolic.svg.

Lastly, @Feichtmeier: dunno what configurator is (as distinct to tweaks) but in Suru it seems to be two different icons.

**Tweaks**

image

**Configurator**

image

...so the new symbolic app icons also distinguish:

**Tweaks**

image

**Configurator**

image

**Comment by Feichtmeier** [comment]
Alright I think I've got it locally, will push a new branch where the conflict is resolved + your new icons + the thick shutdown icon

**Comment by Feichtmeier** [comment]
Sorry for the silly branch name, just got it working so I though I keep the branch :)
Closing this now! Thank you very much for your hard work @ubuntujaggers

**Pull request closed without merging**
