### PR TITLE
Infobar enhancement

### PR DESCRIPTION
**Pull request by Feichtmeier**
Closes https://github.com/ubuntu/yaru/issues/789

image

image

peek 2018-09-06 19-43

image

@clobrano @madsrh

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr791`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr791` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
@Feichtmeier I love the light theme buttons 🎉  but the dark isn't working IMO.

The active buttons background up against the purple is just really hard on the eyes. 
image
And when I look at the Restore button, it looks like it's transparent / cut out. It doesn't look super disabled too me.

Could we add a border for better contrast with the infobar background? and would a semi transparent button perhaps look more disabled?
image

**Comment by Feichtmeier** [comment]
image

**Comment by clobrano** [comment]
It looks good, except the pressed effect on light variant seems too similar to hover, while in dark variant the difference is stronger and I like it more.
I am not 100% sure we can replace such a huge tweaking in drawing.scss

**Comment by Feichtmeier** [comment]
I can change the active effect for light np

**Comment by Feichtmeier** [comment]
peek 2018-09-07 10-05

**Comment by Feichtmeier** [comment]
I double check tonight if I find any other mistake before merging

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr791`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr791` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Paz-it** [comment]
Tested, Looks good! :dancer:

**Pull request merged**
