### PR TITLE
Add MS Publisher and QEMU disk image mimetype icons

### PR DESCRIPTION
**Pull request by Dragon8oy**
image
image

### CODE REVIEW

**Comment by Jupiter007-43** [comment]
Thanks @Dragon8oy !
Could you try to reduce a bit the pictogram size of 48, 32, 24px versions, IMO it is too high actually.

**Comment by Jupiter007-43** [comment]
@Feichtmeier Should we create two issue for each icons?

**Comment by Feichtmeier** [comment]
Yeah why not :)

**Comment by Dragon8oy** [comment]
image
Is this better? 48px might need to be a little smaller

**Comment by Jupiter007-43** [comment]
> 48px might need to be a little smaller

+1 indeed, and it will be fine after imo.

**Comment by Dragon8oy** [comment]
That should be okay, let me know if it needs more tweaking

**Comment by Jupiter007-43** [comment]
Everything looks perfect, I don't have any more suggestion.
Thanks @Dragon8oy !

**Comment by Jupiter007-43** [comment]
Is everyone Ok for merging?

**Pull request merged**
