### PR TITLE
remove orange in window_controls assets

### PR DESCRIPTION
**Pull request by Muqtxdir**
### TO-DO:

- [x] ***unity***: remove orange in `window-control:close` and adapt remaining `window-controls` to gtk3-syling
- [x] ***metacity***: remove orange in `window-control:close` and adapt remaining `window-controls` to gtk3-syling
- [x] ***xfwm4***: remove orange in `window-control:close` and adapt remaining `window-controls` to gtk3-syling

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Tyvm! I still need to ask upstream if they can remove the styling from min and max but if they won't the work to adapt this again is doable or better get to know it before?

**Comment by Muqtxdir** [comment]
sure, if they don't remove it for min max. I'll add circles to them as well

**Comment by Feichtmeier** [comment]
After re-thinking this for a while:

- in ambiance we had the three buttons all with a background, the close button highlighted with orange, all three buttons were "3d" looking
- in yaru we removed the 3d effect and the background from the min max buttons
- now we have no bg on min max, but a gray disk on the close butoon... the contrast (not in terms of brightness) between the min max and the close button is now so minimal that it can be indeed mistaken as a hover or focus effect

So ... I would suggest to keep the gray for all three buttons, just like upstream - WDYT @ubuntu/yaru-team ?

**Comment by Jupi007** [comment]
I'm okay for this :+1:

**Comment by Muqtxdir** [comment]
im also okay for the change of adding backgrounds to all window-controls (_makes it close to libadwaita_)

**Comment by Feichtmeier** [comment]
Ok done in #3276

**Comment by Muqtxdir** [comment]
thanks @Feichtmeier and @Jupi007 for unifying the look, I'll make similar changes to this branch tomorrow 👍

**Comment by Muqtxdir** [comment]
@Feichtmeier and @Jupi007 could anyone of you have a look at this when free.

**Comment by Jupi007** [comment]
Everything looks good for me.
I just have a little optimization tip: can you symlink `mate` **metacity** assets to `default` one (to avoid duplicated stuff)?

**Comment by Muqtxdir** [comment]
ok, thanks for the suggestion. I'll look into this tomorrow 👍

**Comment by Jupi007** [comment]
Nice, thanks :)

**Review by Jupi007 — APPROVED** [review]
LGFM :+1: 

Thanks @Muqtxdir !

**Pull request merged**
