### PR TITLE
Make focus border for entries always the same color in dark and light

### PR DESCRIPTION
**Pull request by Feichtmeier**
@clobrano @madsrh @godlyranchdressing please test and say if you like it/agree

Imho that dark orange looks strange in the dark theme
That function may work in adwaita with their blue, but it looks washed out in our color theme (imho)

Makes not much sense to provide screenshots as PEEK always changes the color a tiny bit :man_shrugging:

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@clobrano if you agree we could also remove all the occurences in common, but if you want to keep it for a bit "less upstream diff" I understand

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1043`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1043` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Looks good, I just need to get used to it, since a color so bright in dark variant makes the border pops out a lot more

**Comment by madsrh** [comment]
image

image

I didn't noticed that these weren't the same color, but now that you mention it, it's pretty easy to see the difference. 
> Imho that dark orange looks strange in the dark theme

I find the contrast when using the "full orange" a bit eye jaring at first, but it makes sense that these should be the same color 👍  As a famous software engineer once said:

> ...a color so bright in dark variant makes the border pops out a lot more

**Pull request merged**
