### PR TITLE
Add printer-network icon

### LINKED ISSUE #1908: Wrong icon for network print
The icon for network print is missing and revert to symbolic.

In gnome-settings :

Capture d’écran du 2020-02-13 18-54-42

And CUPS panel :

Capture d’écran du 2020-02-13 18-55-16

By the way emblems wrong too (issue ?).

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Adding icon for printer network

Capture d’écran du 2020-02-14 13-13-49

closes #1908

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thanks!.
I'll test this later. Need to plug the printer into my wife's computer and share it on the network to test this

**Comment by madsrh** [comment]
Great work @Jupiter007-43 🎉 But I can't test this but +1 from me!

**Comment by clobrano** [comment]
image

it works, well done!

**Comment by ubuntujaggers** [comment]
Great work!

**Comment by Jupiter007-43** [comment]
Yes, it looks beautiful !

**Pull request merged**
