### PR TITLE
color update for gtk 3 and gtk 2 assets

### PR DESCRIPTION
**Pull request by clobrano**
Closes: #1730 
Closes: #1939

TODO
- [ ] dark/gtk2.0 are too old, requires deep rework

### CODE REVIEW

**Comment by Feichtmeier** [comment]
omg... selfslapping... just wasted two hours of my life doing exactly the same thing... :| How far are you? Maybe I can at least share the work

**Comment by clobrano** [comment]
Ready for review, but I'd  really appreciate some help @ubuntujaggers for the dark/gtk-2.0 assets-external.svg has old text-selection assets

image

the right one (light variant) is

image

**Comment by Feichtmeier** [comment]
@clobrano 
Looks good so far,
menu bullets look like gtk
also the aubergine sliders and checks :+1: 
The only thing missing is that new checkmark here 
image

**Comment by ubuntujaggers** [comment]
Tomorrow I'll take a break from legacy icons and tick these assets off

**Comment by Feichtmeier** [comment]
Ah one thing, I am not sure if we should make those "Border less" OSD bullets and checks for gtk2 at all
Because they are used in weird places we would not call menus:
image

maybe we better make them all purple + white?

**Comment by Feichtmeier** [comment]
omg sorry missclick

**Comment by clobrano** [comment]
Yeah, I am not that good at shaping on inkscape :sweat: 
can we update this in a next PR? :smile:

**Comment by clobrano** [comment]
> Ah one thing, I am not sure if we should make those "Border less" OSD bullets and checks for gtk2 at all
> Because they are used in weird places we would not call menus:
> image
> 
> maybe we better make them all purple + white?

uhm, right, I didn't observed this in the app I was using as reference

**Comment by Feichtmeier** [comment]
Sure just merge if you think we are one step closer to the goal.
No need to block this

**Comment by clobrano** [comment]
which app is that, btw?

**Comment by Feichtmeier** [comment]
Inkscape settings

**Comment by clobrano** [comment]
> Ah one thing, I am not sure if we should make those "Border less" OSD bullets and checks for gtk2 at all
> Because they are used in weird places we would not call menus:
> image
> 
> maybe we better make them all purple + white?

this seems to happen only for radio buttons, I wonder why, but it needs a redesign, because a grey border does not fit very well, nor a pich dark since it doesn't have enough contrast with the bg :(

**Comment by clobrano** [comment]
How does this look?
image

**Comment by Feichtmeier** [comment]
Disabled :smile: 
I would just leave them purple for gtk2

**Comment by clobrano** [comment]
They have the same color as the labels, so everything should seem disabled, but ok

**Comment by Feichtmeier** [comment]
Let's wait for @madsrh , was just my impression, doesn't mean that this is reality

**Comment by madsrh** [comment]
Hey, [this](https://github.com/ubuntu/yaru/pull/1963#issuecomment-592151172) doesn't look great 🤔 but [this](https://github.com/ubuntu/yaru/pull/1963#issuecomment-592458520) looks perfect 😃 

+1 from me

**Comment by clobrano** [comment]
Alright, merging then, thanks!

**Pull request merged**
