### PR TITLE
Add text-x-patch mimetype icon

### LINKED ISSUE #2341: Missing icon .patch files (text/x-patch)
Mimetype **text/x-patch** (.patch and .diff)

A proposal icon:

Capture d’écran du 2020-09-01 13-10-38

Related to #2334

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Capture d’écran du 2020-09-16 20-00-27

Closes #2341
Related to #2334

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
Hmm... I think the pale plaster is a bit hard to see on the bright lines?

**Comment by Jupiter007-43** [comment]
> Hmm... I think the pale plaster is a bit hard to see on the bright lines?

I'm searching some other colors, this version is indeed hardly readable.
@madsrh suggested to use darker color (https://github.com/ubuntu/yaru/issues/2341#issuecomment-693579640).

**Comment by madsrh** [comment]
>  I think the pale plaster is a bit hard to see on the bright lines

This was what I was trying to say 😅 The icon is great @Jupiter007-43 but I personally prefer the darker version.

**Comment by Jupiter007-43** [comment]
> This was what I was trying to say sweat_smile The icon is great @Jupiter007-43 but I personally prefer the darker version.

Me too. Sorry, I was very busy with the LO icons so I didn't updated this PR.

**Comment by Jupiter007-43** [comment]
Capture d’écran du 2020-09-23 13-19-05

Updated version.

**Comment by madsrh** [comment]
I prefer this version 👌

**Comment by madsrh** [comment]
Are we waiting for a +1 from @ubuntujaggers ?

**Comment by Jupiter007-43** [comment]
> Are we waiting for a +1 from @ubuntujaggers ?

It's not really necessary, but as I do stupid things sometimes 😅, I prefer that he check my work before merging.

**Pull request merged**
