### PR TITLE
Style tag labels

### PR DESCRIPTION
**Pull request by Feichtmeier**
Closes https://github.com/ubuntu/yaru/issues/983

But I need to test this on my host first, so far only tested on 3.30 files

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr985`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr985` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Doesnt affect 3.36, which is good - maybe unnecessary because we could fix it in one branch for both nautilus versions

**Comment by Feichtmeier** [comment]
image

SHall I merge this @madsrh @clobrano ?
Or do you want to try it first?

**Comment by madsrh** [comment]
LGTM

**Comment by clobrano** [comment]
let me try it first

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr985`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr985` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
This is going to work on 3.30 only, right? 3.28 should stay the same?

**Comment by Feichtmeier** [comment]
Yes I have no idea how to theme 3.26 tag labels. Actually I was looking to fix the 3.26 labels and then stumbled upon the stretched look of the 3.30 ones.

**Comment by clobrano** [comment]
Could I suggest to make the close button responsive to hover? I believe the following line would do fine

    .entry-tag {
      ...
      &.button:hover {color: white;}
    }

**Comment by Feichtmeier** [comment]
peek 2018-11-23 15-58
I won't tell anymore that you missed the space after the semicolon!!!!!!!1111 ;D ;D

**Comment by clobrano** [comment]
> I won't tell anymore that you missed the space after the semicolon!!!!!!!1111 ;D ;D

there's no space needed :p

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr985`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr985` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Pull request merged**
