### PR TITLE
Add gtksourceview mate and mate-dark variants

### PR DESCRIPTION
**Pull request by Jupi007**
Add `gtksourceview` **mate** and **mate-dark** variants.

### CODE REVIEW

**Comment by clobrano** [comment]
Sorry for the delay @Jupi007.
While I think this change is working fine, I am concern over setting style changes inside a build script

**Comment by Jupi007** [comment]
It's indeed a bit weird to put styling inside the build script.
I can fix that, but on the other hand it will duplicate files (I'm actually using symlinks).

Btw we have the same situation in the metacity PR #3235

**Comment by clobrano** [comment]
I think in this case it's ok to have duplicate files

**Comment by Jupi007** [comment]
Fixed, merging?

**Review by clobrano — APPROVED** [review]

**Comment by Jupi007** [comment]
I'll also remove styling from meson files in the metacity PR.

**Pull request merged**
