### PR TITLE
Add VS Code workspace to .gitignore

### PR DESCRIPTION
**Pull request by elsiehupp**
Adding this lets individual developers save personalized VS Code workspace configuration files within the project directory (which is the norm).

### CODE REVIEW

**Comment by clobrano** [comment]
Hey, thank you for the PR. I'd say VS code is pretty popular and it does not hurt to block list it, however I think that there might be a better option. GIT allows to setup a global gitignore file (litteraly `.gitignore_global`) under your `$HOME` directory which adds block list items without polluting the specific projects.

**Comment by Feichtmeier** [comment]
Personally I also always include vscode stuff in gitignore https://www.toptal.com/developers/gitignore helps a lot
Often if I create templated projects in java and dart a .gitignore is auto created and already includes .vscode etc

**Comment by clobrano** [comment]
Yeah, but with the global gitignore you can add vscode stuff only once for any project you're working on

**Comment by Feichtmeier** [comment]
Sounds like the perfect solution if you know this exists. Maybe for people that don't, vscode in the yaru gitignore is the "safe" way to prevent people to commit this stuff =)

**Comment by clobrano** [comment]
Yeah, it's for people that don't know this that I wrote it XD
vscode adds itself to gitignore because it doesn't know where the global gitignore is, but Ok if you want to add .vscode no big deal

**Comment by Feichtmeier** [comment]
No hard feelings either :)
I think often vscode asks in a newly opened dir if you want to add the .vscode folder into the workspace or not

**Comment by elsiehupp** [comment]
One reason to use the per-repository `.gitignore` for the VS Code workspace is that there are plausible reasons for certain repositories to want to include it. I’ve set up a global `.gitignore` previously, though, so I could look into adding this to it, as well.

**Comment by Feichtmeier** [comment]
@clobrano what shell we do with this?

**Comment by clobrano** [comment]
I don't think we need this, I prefer the global gitignore way

**Pull request closed without merging**
