### PR TITLE
Stylize Universal Access toggles

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
Before:

Control bar in Unity 8:

After:

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thanks for the PR. 

Well that's strange, my main host uses the snap and uses the correct toggles:
screenshot from 2018-07-28 15-00-50

**Comment by eaglersdeveloper** [comment]
Suddenly it depends on a system language?

**Comment by clobrano** [comment]
> Suddenly it depends on a system language?

I hardly believe that. What surprises me the most the most is that you needed to add the asset yourself

**Comment by clobrano** [comment]
Damn, I merged it by mistake :man_facepalming:

**Comment by Feichtmeier** [comment]
Revert it if it is unnecessary :)

**Pull request merged**
