### PR TITLE
New rubbish bin: pale tub, green logo, papers in disarray

### PR DESCRIPTION
**Pull request by ubuntujaggers**
From @madsrh suggestion:

image

image

image

I think this is the least controversial design we've had so far, and the UI freeze is looming.  Feel free to test/merge!

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1237`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1237` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
About the original problem (mismatched symbolic): how about just the recycling logo?

**Comment by Feichtmeier** [comment]
Looks good, and nice idea with the recycling glyph as the symbolic icon

**Comment by clobrano** [comment]
I really like the non empty bin now :D

**Comment by madsrh** [comment]
I am very happy with this one @ubuntujaggers :tada: 
Have you considered a slightly darker green to give it some more contrast (especially at small sizes)? Maybe it's only me - it might be a bad idea, so let's just git (_see what I did there_ 😆) this one merged.

gif

**Comment by Feichtmeier** [comment]
Darker green looks indeed better

**Comment by ubuntujaggers** [comment]
image

??  That's the next darker green from the Suru palette.

**Comment by ubuntujaggers** [comment]
Pushed the darker one - test and merge if you like it, or I can put it back if you change your mind  :)

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1237`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1237` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
image
image

Looks good! Can we merge this @madsrh @clobrano ?

**Comment by madsrh** [comment]
It really does 😁🎉 Yes please

**Comment by clobrano** [comment]
Looks good :)

**Pull request merged**
