### PR TITLE
Added icons for list-add and list-remove in Yaru style

### PR DESCRIPTION
**Pull request by madsrh**
Inspired by Stuarts document-new icon, I tried to make list-add and list-remove in Yaru style. Not sure it's an improvement 😄 

Inspiration:
image

Current:
image

Suggestion:
image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Awesome!

**Comment by Feichtmeier** [comment]
(if you tested it, feel free to merge with squash and merge)

**Comment by Feichtmeier** [comment]
Did it work @madsrh ?

**Comment by madsrh** [comment]
It works fine but I've only seen it in Inkscape

**Comment by Feichtmeier** [comment]
@madsrh well that means that it works :) Thank you!

**Pull request merged**
