### PR TITLE
Initial Look for watch standby and watch progress cursors

### PR DESCRIPTION
**Pull request by ochi12**
Suggested task from @Muqtxdir  linking to . 

This PR is a continuation of the issue raised in  
 
Changes include  simpler spinner design based on 

## Screen Cast
[image](https://github.com/user-attachments/assets/c59a4ad2-7321-4507-a402-e64583ae5847) 
[image](https://github.com/user-attachments/assets/4e1531a2-ec9d-4f43-a0bf-edd3a9845560)

### CODE REVIEW

**Comment by ochi12** [comment]
@Muqtxdir  the progress animated cursor at the 24x24 size is an issue for me. 1px is too small, 2px is fine but is not a pixel fit this it looks good on sizes greater than 24 x 24. I can't force it for a 3 pixels gap, it will result to large looking gaps for cursor size greater than 24x24.

**Comment by Feichtmeier** [comment]
wow I wouldnt have thought that this looks indeed better !

**Comment by Muqtxdir** [comment]
thanks, I'll checkout your branch locally and see

**Comment by ochi12** [comment]
I still can't find the problem that causes the `wait` animated cursor to jitter

[Screencast from 2024-11-18 19-37-57.webm](https://github.com/user-attachments/assets/0f85a8a3-c9d3-45ad-b0d9-f3b9952fadc3)

**Review by Muqtxdir — APPROVED** [review]
thanks!

**Pull request merged**
