### PR TITLE
Mimetypes with logos

### PR DESCRIPTION
**Pull request by ubuntujaggers**
WIP - feel free to test and see how you feel :+1: 

image

### CODE REVIEW

**Comment by madsrh** [comment]
Nice @ubuntujaggers 👌 Can't wait to try this

**Comment by Jupiter007-43** [comment]
Tested and adopted!
It's really better (very sharp) than the old version with just the text.
Good job 👍

**Comment by Feichtmeier** [comment]
Looks cool and I think people will understand it faster than text.
The java cup is a bit too far too the bottom isn't it?

**Comment by ubuntujaggers** [comment]
You're right @feichtmeier, and I need to work on the pixel fitting - the steaming cup is very much a WIP! Will finish soon 👍

**Comment by ubuntujaggers** [comment]
I haven't forgotten these, I'll have some time soon 👍

**Comment by ubuntujaggers** [comment]
Ready for final decision :+1: 

image

**Comment by madsrh** [comment]
Final decision is GO! 🎉

**Pull request merged**
