### PR TITLE
Style rename popups

### PR DESCRIPTION
**Pull request by Feichtmeier**
- taken from https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/675
- closes https://github.com/ubuntu/yaru/issues/1526

### CODE REVIEW

**Comment by 3v1n0** [comment]
Also update the upstream file :)

But anyways.... Probably better to keep this in hold for a bit, since it will be changed soon again very likely. See this [MR's diff](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/720/diffs#diff-content-d27519967b4ac5df7ae7d6279de3e5ec655a72bf).

**Comment by Feichtmeier** [comment]
@3n1n0 is this pr still needed?

**Comment by 3v1n0** [comment]
Ouch yes, but it should be adapted to https://gitlab.gnome.org/GNOME/gnome-shell/blob/3.34.1/data/theme/gnome-shell-sass/_common.scss#L613

I think we should SRU this indeed too

**Comment by clobrano** [comment]
I'm deeply sorry, but it was easier to open a new PR (#1572) than rebase this one

**Pull request closed without merging**
