### PR TITLE
kde/plasma cursor support

### LINKED ISSUE #2921: yaru cursors: kde/plasma support
**Expected Behavior**

For all cursors to properly display, in a KDE plasma behavior

**Actual Behavior**

Key components and symbolic links are missing that KDE plasma expects

**Steps to Reproduce the Problem**

1. Use KDE Plasma
2. Install the yaru cursor theme
3. Enable the cursor theme
4. Observe missing icons, falling back to the breeze cursors

**Yaru version**

```
20.04.11.1
```

**Missing Icons**

Thus far, I've been able to identify the following missing symbolic links:

missing file | should link to
------------|----------
pointing_hand | pointer
whats_this | help
half-busy | progress
ibeam | text
split_v | row-resize
split_h | col-resize
size-ver | default
size-hor | default
size-fdiag | default
forbidden | no-drop
closedhand | dnd-move
wait | watch

The following files are present in the breeze cursor directory, but not in Yaru, and I have not been able to identify which files they should point to yet:

```
center_ptr
color-picker
down-arrow
draft
grab
left-arrow
openhand
right-arrow
up-arrow
wayland-cursor
x-cursor
```

I hope it's possible for these symbolic links to be created, in order to be able to fully use the Yaru cursor theme within KDE Plasma.

### PR DESCRIPTION
**Pull request by Muqtxdir**
This PR symlinks the following missing cursors files (*Taking symlink-link names from **KDE's Breeze***)

- [x] pointing_hand 
- [x] whats_this
- [x] half-busy
- [x] ibeam
- [x] split_v
- [x] split_h
- [x] size-ver
- [x] size-hor
- [x] size-fdiag 
- [x] forbidden
- [x] closedhand
- [ ] center_ptr 
- [x] color-picker
- [x] down-arrow
- [x] draft
- [x] left-arrow
- [x] right-arrow
- [x] up-arrow
- [x] wayland-cursor 
- [x] x-cursor

### additional:

- <s> Update cursors.list with new symlinks</s> 

- [x]Bring all symlinks under `x11-make.sh` and `w32-make.sh`  

Closes #2921

### CODE REVIEW

**Comment by Muqtxdir** [comment]
Brief-overview of what's changed in this PR:

- Removed [`cursors.list`](https://github.com/ubuntu/yaru/blob/master/icons/src/symlinks/fullcolor/cursors.list) as it failed to produce proper symlinks for both **_x11_** and **_w32_** generated cursors. ( _happened in this issue: #2888_
- Bring in all the symlinks under `x11-make.sh` and `w32-make.sh `
- Make **Yaru-cursors** compatible with use on KDE's Plasma-environment by adding the missing cursors to the set ( _see PR: #2944_) and with necessary symlinks ( _this PR_)

**Comment by Muqtxdir** [comment]
@Benni3-1415 and @Jupi007 could you try-out this branch when free?

**Comment by Jupi007** [comment]
Ofc :)
Will take a look tomorrow 👍

**Comment by jbouter** [comment]
I'm currently on holiday, but will definitely check when I return! :-)

**Review by Jupi007 — APPROVED** [review]
LGFM 👍

**Pull request merged**
