### PR TITLE
Add folder icons for Dropbox

### PR DESCRIPTION
**Pull request by madsrh**
Add folder icons for Dropbox

image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1230`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1230` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Nice work @madsrh!
Should it work out of the box, or there's some work to be done? I only installed the PR and I don't see the new icon

**Comment by Feichtmeier** [comment]
Looks very nice

**Comment by madsrh** [comment]
>  I only installed the PR and I don't see the new icon

😞 

Hmm, @Feichtmeier do you have the Dropbox icon?

**Comment by clobrano** [comment]
@madsrh, this means you did nothing more to make it work on you machine?

**Comment by Feichtmeier** [comment]
Doesnt show up in my VM neither. The name is correct, I checked papirus and it is named the same. BUT it does not work with papirus neither. So there is prbly something not working with dropbox :thinking:

**Comment by madsrh** [comment]
> this means you did nothing more to make it work on you machine?

No, but this an old machine 18.04 so maybe I did something in the past. 
I just tried it on a fresh and have the same issue as you guys

**Comment by clobrano** [comment]
Agree, we can manage it as bug later

**Pull request merged**
