### PR TITLE
Added mimetype icon for Docker

### PR DESCRIPTION
**Pull request by madsrh**
Like the mimetype icon for Dart in #2273, support for this file type is still missing in Ubuntu. Hopefully @didrocks can help here :angel: 

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Looks really good. Just one question, is this for docker files, that describe where to download the docker image and so on, or is this for the actual container images?

**Comment by madsrh** [comment]
Ahh, I see where you're going. I'm thinking this is the container image, so it should probably look like the other image icons, right?

**Comment by Feichtmeier** [comment]
We still don't have a guideline for container images, but maybe adapt this one to your new snap mimetype, which does not havea white background

**Comment by ubuntujaggers** [comment]
Brand for this one does seem to be blue on white:

image

So might be fair?

**Comment by ubuntujaggers** [comment]
Are we happy to merge this? 👍

**Comment by madsrh** [comment]
> Are we happy to merge this? 👍

I am 😄 We can just merge this now althought we haven't heard back from @didrocks

**Pull request merged**
