### PR TITLE
Add symlink for update-notifier icon

### LINKED ISSUE #2720: Missing symlink for update-notifier
image

image

### PR DESCRIPTION
**Pull request by Jupi007**
@madsrh Can you test this please?

Closes #2720

### CODE REVIEW

**Comment by Feichtmeier** [comment]
I don't know why but we had this once in yaru: https://github.com/ubuntu/yaru/pull/1002
then removed it again because 🤷 
but a different symlink
I think there was some problem 🤔 too long ago 👴

**Comment by madsrh** [comment]
Thanks for looking into this @Jupi007 but sadly I still see the old icon. I've been sitting waiting for the update notifier to pop up (I don't know how to trigger it) and I noticed something weird. The label in the dock - when hovering over the icon - says _update notifier_ but it's the "system program problem detected" dialog that opens 🤷‍♂️ (not apport)

image

**Comment by Jupi007** [comment]
@madsrh When the window pop again, can you look at the System monitor and maybe try to locate the process name?

**Comment by madsrh** [comment]
Like this @Jupi007 ?
image

**Comment by Jupi007** [comment]
> Like this @Jupi007 ?

Yes @madsrh. So the process name is the same.
Strange thing, on my computer, the good icon is used by system-monitor:

Capture d’écran du 2021-03-21 19-38-55

**Comment by madsrh** [comment]
This was a clean VM but maybe I messed something up somehow. Let's close this if no one else can confirm 🤷‍♂️

**Comment by Jupi007** [comment]
Sorry I expressed myself badly.
In fact, with master it use the Humanity icon, and using this branch it use the Yaru one. So I think we should merge.

**Pull request merged**
