### PR TITLE
Yaru bigger buttons

### PR DESCRIPTION
**Pull request by clobrano**
Draft project to compare standard Yaru with a Yaru that uses upstream button sizes.

This PR installs a project called YaruBigBoss :sweat_smile: in three variants (default, light, dark), so it is easier to compare with standard Yaru (which is not overwritten)

### CODE REVIEW

**Comment by clobrano** [comment]
did anyone test this? 😄

**Comment by Feichtmeier** [comment]
Not yet sorry, I will later!

**Comment by Feichtmeier** [comment]
Works 👍 🚀 
image

Now what is the plan with this? 😆

**Comment by clobrano** [comment]
😄 it has no purpose except let @madsrh and @ubuntujaggers compare current Yaru with this one

**Comment by ubuntujaggers** [comment]
I actually forgot I had the big buttons for a while so if there's a big supportibility reason i wouldn't mind. I'll build it again tonight 👍

**Comment by madsrh** [comment]
Sorry for not getting around to testing the earlier 😬 This is pretty cool @clobrano You're great with names 😆 

It seems unnecessary huge at first, but after a while I didn't notice it. I still prefer the current Yaru sizes though. Are the diff from Adwaita causing issues or do you just prefer big button (and big shadows) yourself? 😀

**Comment by clobrano** [comment]
Honestly, I don't like it 😆
On 12" screen is terrible, but it was suggested by @Feichtmeier to overcome some button issues, so I provided a test branch

**Comment by Feichtmeier** [comment]
Yeah I also don't like it visually. I think we should postpone it as long as we can. Depending on the future of gtk apps we might need to do it anyways. It's a one line change sooooo let's wait. I think

**Comment by Feichtmeier** [comment]
> Sorry for not getting around to testing the earlier grimacing This is a pretty cool way to compare @clobrano and you're great with names laughing
> 
> It seems unnecessary huge at first, but after a while I didn't notice it. I still prefer the current Yaru sizes though. Are the diff from Adwaita causing issues or do you just prefer big button (and big shadows) yourself? grinning

Just to clarify: our sizes are fine as long as people do not put Adwaita-only-sized widgets into the headerbar and stick with common widgets like buttons, entries and so on. See #2060

**Comment by Feichtmeier** [comment]
Shall we close this then @clobrano ? If no one likes it visually :shrug:

**Pull request closed without merging**
