### PR TITLE
Removing Remmina icons from Yaru

### LINKED ISSUE #1643: Remmina custom emblems icons not found when using Yaru
## Actual Behavior

We have a strange behavior with the latest versions of Remmina (see #1180 for remmina discussion).

We install our custom icons under hicolor/scalabale/emblems. (and actions as well)
Using the Yaru icon theme, default on Ubuntu 19.10, those icons are not visible:

image

With any other icon theme we don't have issues

image

## Steps to Reproduce the Problem

  1. Install a avanilla ubuntu 19.10
  2. Install latest remmina.

```
sudo add-apt-repository ppa:remmina-ppa-team/remmina-next-daily
sudo apt-get update
```

  3. test with different themes (create new profiles in remmina, all protocol icons are the same)

## Software that presents the issue

- Name: Remmina
- Version: 1.3.6

## Yaru version

Please report the Yaru version in your system using one of the following commands

* If you installed Yaru from PPA

```
Package: yaru-theme-icon
Version: 19.10.4
Priority: optional
Section: misc
Source: yaru-theme
Origin: Ubuntu
Maintainer: Ubuntu Desktop Team <ubuntu-desktop@lists.ubuntu.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 67.2 MB
Homepage: https://community.ubuntu.com/c/desktop/theme-refresh
Task: ubuntu-desktop-minimal, ubuntu-desktop
Supported: 9m
Download-Size: 10.9 MB
APT-Manual-Installed: no
APT-Sources: http://ch.archive.ubuntu.com/ubuntu eoan/main amd64 Packages
Description: Yaru icon theme from the Ubuntu Community
 This is the theme that is shaped by the community on the Ubuntu hub.
 .
 This package contains the icon theme
 .
 If you want to follow development, more information here:
 https://community.ubuntu.com/c/desktop/theme-refresh.

```

Thanks!!!

cc: @madsrh @Feichtmeier @giox069

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Test it first - for me the icon has turned back to:

image

...and this is after I uninstalled/reinstalled it from Software Centre.  Closes #1643.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thanks!

I guess I need to somehow get an really up to date version of remmina to be sure we don't end up with that transparent icon again. I'll try the snap or build from master

**Comment by Feichtmeier** [comment]
Okay I failed to build it from master, BUT

Your Yaru icon is definitely the upstream icon
https://gitlab.com/Remmina/Remmina/blob/master/data%2Fdesktop%2Fscalable%2Fapps%2Forg.remmina.Remmina.svg

I guess it didn't make it into the version which landed in 19.10
I'll check the snap and / or the ppa

**Comment by Feichtmeier** [comment]
Works! Found some daily ppa for remmina and removed the yaru icon folder before building again from this branch :+1: 

Thanks @ubuntujaggers !

grafik

**Comment by ubuntujaggers** [comment]
Magic, shall I merge? I can always send the app symbol upstream if they want it.

**Comment by Feichtmeier** [comment]
Yes good idea

**Comment by antenore** [comment]
@ubuntujaggers yes please! We always love contributions 😃

**Pull request merged**
