### PR TITLE
Fix default decoration windowcontrols sizes

### PR DESCRIPTION
**Pull request by 3v1n0**
Helps with rendering of #3876

### CODE REVIEW

**Comment by Jupi007** [comment]
@3v1n0 isn't this bug affecting Gtk3?

**Comment by 3v1n0** [comment]
I'm not aware of any application using these kind of decorations in gtk3,
as client-side should not use this, while server-side are all gtk4
nowadays.

Il lun 3 apr 2023, 22:04 Paul Kepinski ***@***.***> ha
scritto:

**Review by Jupi007 — APPROVED** [review]
Okay, I didn't understood that now SSD decorations are using Gtk4.
This is the reason why this problem dates from 23.04

This is fine so 👍

**Comment by Muqtxdir** [comment]
I think software properties and updater also have this issue on xorg session, so it kinda affects gtk3 as well

**Comment by Jupi007** [comment]
> I think software properties and updater also have this issue on xorg session, so it kinda affects gtk3 as well

This is why I was also thinking that it is affecting Gtk3 🤔

**Comment by 3v1n0** [comment]
> I think software properties and updater also have this issue on xorg session, so it kinda affects gtk3 as well

Yes, but those are all server-side decorations, and using gtk4 now. In fact, when running under wayland with CSD, they work fine.

**Comment by 3v1n0** [comment]
You can see the differences here (this is under wayland):

Server-side in front, client-side (gtk4) in the back:
image

The other way around:
image

The one in the front is csd, gtk4
image


I've changed the sizes to be consistent, however... In headerbar the window buttons are 24px, while in the csd/serverside normal decorations we use 22px buttons.

I think this is acceptable because the size of the container is also different, but I'm not sure we want to fix this too (in another MR though).

**Pull request merged**
