### PR TITLE
removed text-x-plain.svg and text-x-cobol.svg

### PR DESCRIPTION
**Pull request by Muqtxdir**
Hi,

This PR removes **text-x-plain.svg** (*symlink already exists in mimetypes.list*) and **text-x-cobol.svg** (*added symlink to **text-x-script.svg** in mimetypes.list*)

#### screenshots:

Thanks!

### CODE REVIEW

**Comment by Muqtxdir** [comment]
just noticed that, ***text-x-script*** was not rendered with the new fold, so rendered it again

**Comment by Jupi007** [comment]
Nice catch for text-x-plain and the unrendered script icon @Muqtxdir, but I don't think that a good idea to drop the cobol icon by symlink it.
Cobol has a very special syntax and it's really not related to scripts.

**Comment by Muqtxdir** [comment]
sorry, I thought they were supposed to look the same. I'll close this branch and repush it

**Comment by Jupi007** [comment]
Don't be sorry, I think it's normal you don't know what is Cobol 😉

**Pull request closed without merging**
