### PR TITLE
remove third party gnome app overrides

### LINKED ISSUE #2196: Non-core app icon overrides
## Expected Behavior

Only GNOME core apps or pre-installed apps have themed icons.

## Actual Behavior

It was brought to my attention that Transmission's icon is being overridden by Yaru. That's a bit odd, because it's very far from being a core app and not pre-installed (as far as I know). I had a quick look at the repository and found a few other apps in the same situation:

Edit by @Feichtmeier :
- ~~Transmission~~ --> Got OK from the devs
- [ ] Remove Games symlink
- [ ] Remove Podcasts symlink
- [ ] Remove Notes/Bijiben symlink
- [ ] Remove Books symlink
- [ ] Remove Evolution symlink
- ~~Remove Todo symlink~~ --> Preinstalled
- ~~Rhythmbox~~ --> Preinstalled
- ~~Tweaks~~ --> I think we need to keep this, because it's an elemental app for the desktop, yet not pre-installed

If any of these come pre-installed on Ubuntu feel free to ignore, but for the others it would be good if Yaru wouldn't override their icons. I'm aware that the definition of what is and isn't a core app can be unclear in some cases, but hopefully [this initiative](https://discourse.gnome.org/t/official-proposal-how-we-define-gnome-software/3371) will help improve this in the future.

### PR DESCRIPTION
**Pull request by alatiera**
These are third party gnome apps that are not shipped by default.

Close #2196

### CODE REVIEW

**Comment by alatiera** [comment]
Please also backport this to 20.04

**Comment by Feichtmeier** [comment]
hi, thanks for the pull request.
Removing the symlinks should be enough. We have generic apps and then symlink them to the gnome apps.

**Comment by alatiera** [comment]
Like this? The script seems to produce a lot of noise atm (see below) over here, but I hope I got it right. Thanks for the review and the pointers.

```
...
?? Suru/scalable/actions/mail-spam-symbolic.svg
?? Suru/scalable/actions/media-eq-symbolic.svg
?? Suru/scalable/actions/pan-end-symbolic-rtl.svg
?? Suru/scalable/actions/pan-start-symbolic-rtl.svg
?? Suru/scalable/actions/selection-end-symbolic-rtl.svg
?? Suru/scalable/actions/selection-start-symbolic-rtl.svg
?? Suru/scalable/apps/config-users-symbolic.svg
?? Suru/scalable/apps/org.remmina.Remmina-symbolic.svg
?? Suru/scalable/apps/software-center-symbolic.svg
?? Suru/scalable/apps/softwarecenter-symbolic.svg
...
```

**Comment by Feichtmeier** [comment]
Ah that was fast, thanks!
I think you've did it right, need to check out the branch locally though to be sure.

**Comment by ubuntujaggers** [comment]
I'll test the branch when I'm home on Monday 👍

**Comment by ubuntujaggers** [comment]
Sorry for delay testing/merging this, will do it asap 👍

**Comment by ubuntujaggers** [comment]
This looks good to me locally, can I merge @Feichtmeier ?

**Pull request merged**
