### PR TITLE
Add libreoffice icons

### LINKED ISSUE #1815: Suggestion: create a yaru libreoffice icon theme
This is not a bug, but I thinks it should be great to have a yaru icon theme for libreoffice, which actually looks very inconsistent with the rest of the OS :

Elementary icons looks too much "Elementary"
elementary

Breeze icons (which at the moment seems to me to be the most neutral) looks too much "KDE"
breeze

And Colibre icons are just too "Windows" 😈
colibre

I know it's a lot of work, so this is just a suggestion.

### PR DESCRIPTION
**Pull request by Jupiter007-43**
⚠ Fat PR!

Just add all icons from my own repository to the Yaru's one into a `libreoffice-icons` folder.
I don't know how to create a meson file to build and install the icon pack, but I can help you.

Closes #1815

### CODE REVIEW

**Comment by clobrano** [comment]
> I don't know how to create a meson file to build and install the icon pack

Me neither, also not 100% sure this is the correct way to go. Are the icons for the libreoffice deb package?

**Comment by Jupiter007-43** [comment]
> Are the icons for the libreoffice deb package?

Yes, there are the svgs source into the src folder, and the generated pngs into the png folder. It's these pngs who are zipped and put into the Libreoffice system folder (the zip is also used for the deb).
I haven't added the zip yet because I don't know how will be create the build script.

**Comment by Jupiter007-43** [comment]
After a few search, I finally created a meson build file (and it work!).

**Comment by Jupiter007-43** [comment]
If someone want to check the meson file, here is the procedure for installing a libreoffice icon theme:
- create a zip with all images inside named `images_*.zip` with * the name of the icon theme.
- put it into the libreoffice config folder: `/usr/share/libreoffice/share/config/`
- then symlink this file into `/usr/lib/libreoffice/share/config/`

I used a bash script for create symlink because meson doesn't support this feature natively.

**Comment by clobrano** [comment]
> 
> 
> > Are the icons for the libreoffice deb package?
> 
> Yes, there are the svgs source into the src folder, and the generated pngs into the png folder. It's these pngs who are zipped and put into the Libreoffice system folder (the zip is also used for the deb).
> I haven't added the zip yet because I don't know how will be create the build script.

I meant, we're supposed to ship libreoffice icons with Yaru deb? I thought it was up to LO to do so?

If not, we shall build it in a dedicated deb package

**Comment by Jupiter007-43** [comment]
🤔 I think that it need to be ship with LO, which generate the libreoffice-style-yaru package.

**Comment by Feichtmeier** [comment]
Can't wait to test this! Still unimaginable how much work you've put into this!

I agree with carlo though, that we should not put this into the yaru repository. Maybe we can make another repository under github.com/ubuntu namespace? Now that you are part of the yaru-team here on GitHub, I think you should be allowed to transfer your repository from your namespace into the Ubuntu namespace. @Jupiter007-43 
The work you've put into this branch into the meson script should also be included afterwards ofc

**Comment by Jupiter007-43** [comment]
> Can't wait to test this! Still unimaginable how much work you've put into this!

The number of icons still scares me today! I can't figure out how I could have done all of this. 😅

> I agree with carlo though, that we should not put this into the yaru repository. Maybe we can make another repository under github.com/ubuntu namespace? Now that you are part of the yaru-team here on GitHub, I think you should be allowed to transfer your repository from your namespace into the Ubuntu namespace. @Jupiter007-43
> The work you've put into this branch into the meson script should also be included afterwards ofc

I really know nothing about deb packages so if you say that we need to create a new repository I trust in you. 👍
But I don't have any right access, so if a manager could do the transfer, it should be very great!

> Edit: the problem is that you can install ubuntu without libre office. And if the LO icons are tied to the yaru package, don't know if this will work out. But I am a complete newbie to how debian packages and debian meta packages work in Ubuntu, so could be totally the wrong thought and it could work here in the yaru repository

I totally understand the problematic.
I think we should ask to a deb specialist, maybe @Hellsworth could help we?

**Comment by clobrano** [comment]
We still build separated debs for icons, gtk theme and shell theme, so - eventually - we could build libreoffice ones.
If so, however, I would prefer a git submodule more than include under Yaru, otherwise we should download all the 5k icons every time we clone the project for the first time 😄

**Comment by Jupiter007-43** [comment]
> If so, however, I would prefer a git submodule more than include under Yaru, otherwise we should download all the 5k icons every time we clone the project for the first time smile

Very pertinent observation (especially if you have a _**great**_ connection 😑)! So the best way is a new repo. 👍
I close this PR.

**Pull request closed without merging**
