### PR TITLE
Polari icon

### PR DESCRIPTION
**Pull request by Feichtmeier**
Using this app quiet often and thought it's time for a suru icon

Upstream icon:
image

Suru icon:
image

@clobrano @madsrh you decide ^.^

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1101`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1101` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by eaglersdeveloper** [comment]
This is a third-party app.

**Comment by Feichtmeier** [comment]
So? What's the deal?
I agree with @ubuntujaggers that we could provide icons for gnome apps.
Upstream changes the icon set, so why can't we change our icon set?
It's open source. As long as @ubuntujaggers and me are willing to provide a full set of let's say all of these icons here: http://jimmac.musichall.cz/stuff/icon-revolution/

I don't see the problem apart from work. Which you don't need to provide of you don't want to.

**Comment by eaglersdeveloper** [comment]
Because this is their applications, their icons.
Let's also modify beyond recognition and give Skype, Viber, WhatsApp, Spotify and over999 icons (sarcasm).

Canonical is a middle-market company, not small business. Ubuntu is the most popular Linux distribution.

Such action will humiliate Canonical, because nobody does that.

**Comment by Feichtmeier** [comment]
No, we were talking about gnome applications (open source), not commercial and/or closed source applications with officially branded icons.
I'm kinda done discussing this stuff with you over and over. Could you just stay away from this repository for a while? It's getting really annoying.
Don't panic over canonical, that's neither your nor my business.

**Comment by Feichtmeier** [comment]
@eaglersdeveloper
Also what's the difference to podcasts and chess? Right there is none. Both are gnome apps and both are not pre installed. Exactly like polari.

**Comment by Paz-it** [comment]
I would suggest, if I may, that the bg will be Gray and the pictogram will keep the same colors (green/white). that way visibility will improve.

**Comment by Feichtmeier** [comment]
Thought about this too! I think you are right. That brown on white is bad

**Comment by eaglersdeveloper** [comment]
@Feichtmeier, SMS app icon in different OSes is also different. Polari is the brand.

**Comment by Feichtmeier** [comment]
@eaglersdeveloper it is as much as a brand as gnome-podcasts or gnome-chess or rhtyhmbox or shotwell. It is not a brand as far as I know. It is the icon of an open source GNOME application licenced under the GPL. GNOME app icons are not protected to any change as far as I know. 
By this logic we could remove **ALL** app icons from Yaru. 
Because ubuntu uses **only** GNOME apps except thunderbird, firefox and LO-suite. 

Third-party =/= brand =/= GPL licenced =/= copyright protected
Those are all different topics and you are throwing them together all the time.

Why would this icon be allowed since 10 years if it is not allowed to change the icon of a GNOME app:
image
(gnome-files / nautilus)

Or this icon:
image
(gnome-terminal)

**Comment by ubuntujaggers** [comment]
I'm very much in favour of doing Suru icons for all the apps in the link 👍  I mean, Gnome are doing it for their theme and it's allowed in the licence, so...  let the Inkscape commence  🍾 🙂 

This is a good clear vector - I'd also like to see a version with the colours suggested by @Paz-it and wonder if the hash symbol could also be included at the smallest sizes?  It's a simple enough glyph that it should be possible to make it legible.

**Comment by Feichtmeier** [comment]
@ubuntujaggers like this?

image

**Comment by madsrh** [comment]
> I would suggest, if I may, that the bg will be Gray and the pictogram will keep the same colors (green/white). that way visibility will improve.

I agree, but I think there's already enough icons with gray background. So what I liked about @Feichtmeier first suggestion was that is was very colourful which I feel is a part of the suru style too.
I do like the ash version about too. Perhaps the icon itself (the green part) could be slightly larger?

**Comment by Feichtmeier** [comment]
The first suggestions is basically the message-app icon with a different BG and a hashtag instead of the two lines.
I think if we make it bigger we could consider to make a more drastic change to this messages-app"fork" to make it look different than messages

**Comment by clobrano** [comment]
I'd say the first proposal was better to me :)

**Comment by Feichtmeier** [comment]
Alrighty, then it's ready to merge, except @ubuntujaggers disagrees strongly here?

**Comment by Feichtmeier** [comment]
A don't merge, I would like to improve the symbolic icon I've committed. The roundness of the hashtag lines make them look blurry when scaled down to a small size like in the shell panel

**Comment by ubuntujaggers** [comment]
Original icon looks nice to me, I was just curious to see the other way too :)

**Comment by ubuntujaggers** [comment]
Re: symbolic icon being blurry, it looks like the nodes do not lie exactly on pixel boundaries when displayed at 16px.  The result is you get pixels that are halfway tones, in places where a crisp boundary would be clearer (this is like the French flag problem!).  This will affect any 16px design, whether symbolic or colour.  E.g.

image

If you haven't tried this already, it might be worth having a go at the following:

- Zoom right in on the 16px graphic so it's as big as possible in your Inkscape view;
- Press # to make the grid visible so you can see exactly what the whole pixels will be when it renders;
- Select node tool:
image
- Click on your hash symbol snap each node to a whole pixel intersection like so (just using a random shape here for illustration purposes):

**Before:**

image

**After:**

image

Before you start moving the nodes, for some shapes, it works better if you select the object and choose "Path" --> "Object to Path" from the menu bar, to convert it to something that will let you freely and individually move each node.  This is because text objects don't have nodes and geometric shapes like rectangles have small numbers of nodes that resize the whole shape when you try to move them (because it keeps it as a rectangle, which is fine if that's what you want).  But if you convert it to a path, you get something that looks exactly the same but is just made up of nodes that you can edit individually.

Actually, I've just realised I can save/open/investigate your copy of source-symbolic from the commits - the bottom rounded rectangle is between pixels at this size:

image

So what you can do is play with the graphic to make something that aligns with the pixels as closely as possible:

image

**Before:**

image

**After:**

image

**Comment by Feichtmeier** [comment]
That looks like what I thought!
Now with your new super powers on github could you pull this branch here, apply your changes and push the branch again? :D

**Comment by ubuntujaggers** [comment]
No probs, I have a couple of quick chores to finish for today and then I'll have a go  :)

**Comment by ubuntujaggers** [comment]
First thing I'm doing is installing Git Kraken, I didn't get chance over Christmas but if I'm going to be working with branches it will probably help me not break anything.

**Comment by ubuntujaggers** [comment]
Okay, I can see it will take me a little time to get to grips with Gitkraken  :rofl: 

For now: apologise for Git newbie questions...  I've worked out how to clone the Yaru repo onto my PC and be on the IconTheme_polari branch:

image

...and now I can see/load/edit your Polari files and edited version of source-symbolic locally.

My understanding is that I can edit, commit and push source-symbolic as normal from this point and it will work - **I just wanted to check that's right before I actually do it** because this is my first time not working on my own fork!

Also, there's a giant tick (check mark) in source-symbolic covering some of the actions that isn't in my fork - presume I can just repair that while I'm changing the Polari symbol?

**Comment by Feichtmeier** [comment]
Yes you can edit and commit and push like always. What check mark Oo

**Comment by ubuntujaggers** [comment]
Just here:

image

**Comment by ubuntujaggers** [comment]
Hooray!  I did it :fireworks: 

I took the tick out, it seemed to have been added to one of the groups by mistake somewhere along the way.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1101`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1101` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
Ah, another possible slight problem: some of the app icons in the latest source-symbolic have wandered to non-integer positions when they were rearranged to make room for Polari - I'm not sure that matters though because they export as new svgs rather than pngs?

**Comment by Feichtmeier** [comment]
Holy crap. Thanks

**Comment by ubuntujaggers** [comment]
I don't believe the icon positioning was a significant problem, they still export as 16x16 svgs, there's a bit of a minor advantage in having them at integer pixel positions because it means when you view the big svg in Inkscape at 100% size you see them perfectly clearly so can judge exactly how they will look when they're live.  So it's a minor bit of housekeeping  :)

That should be done now:

image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1101`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1101` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Works! Let @madsrh and/or @clobrano merge it eventually

**Comment by Paz-it** [comment]
I'm late to the party :smile:  ..TBH, I would have preferred the ash color but if most of you like it, I do too.
I really admire @ubuntujaggers   graphic skills, wow!

**Comment by Feichtmeier** [comment]
@madsrh @ubuntujaggers we could also chose a darker green (maybe a suru green? this one is the original green from the icon), which would be the third option :D 

@ubuntujaggers could you execute any of those three options and commit it?

**Comment by madsrh** [comment]
> we could also chose a darker green (maybe a suru green? this one is the original green from the icon), which would be the third option :D

How does the Suru green look? 🎨 
I think using the original green from the icon has a branding value - even if we make it a tiny bit darker

**Comment by Feichtmeier** [comment]
No idea about the hex values but that's from suru guidelines
image

Ubuntu green is
#3EB34F

**Comment by clobrano** [comment]
Only as reference, here is the autogen icon with the script

org gnome polari

**Comment by ubuntujaggers** [comment]
> 
> 
> @madsrh @ubuntujaggers we could also chose a darker green (maybe a suru green? this one is the original green from the icon), which would be the third option :D
> 
> @ubuntujaggers could you execute any of those three options and commit it?

Yep  👍  early next week, got a busy Monday/Tuesday but can have a go Tuesday night.

**Comment by madsrh** [comment]
Sorry, I'm unsure about this icon after seeing @clobrano comment 🤦‍♂️ 
I really like the icon by @Feichtmeier but maybe the scripted version is less confusing to the users. The scripted icon looks fine, so perhaps there's no reason to create a suru styled version. The user will still see/know the original icon from Software 🛍 and from other distros or icon themes. I know that this has been discussed and that the logic could apply a ton of icons, so I'm merely sharing my point of view.

image

**Comment by Feichtmeier** [comment]
That's happening for every icon @madsrh
Check them all :)
That's happening for every single gnome icon

**Comment by ubuntujaggers** [comment]
First trying @madsrh idea of a darker green derived from the upstream colour:

image

@madsrh @Feichtmeier @clobrano  Do you like this or want to try a Suru palette colour?

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1101`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1101` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
I like this!

**Comment by ubuntujaggers** [comment]
@madsrh @Feichtmeier  Ahh, I forgot to commit the pngs, should I reopen this PR and commit them or have they been done already?

**Comment by Feichtmeier** [comment]
Make a new PR :)

**Comment by Feichtmeier** [comment]
From the same branch

**Pull request merged**
