### PR TITLE
Reduce the pictogram on Contacts icon

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
Pictogram on the current icon looks very too big :(

Before:
Снимок экрана от 2019-04-26 15-42-43

After:
Снимок экрана от 2019-04-26 15-51-17

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
Yep, agreed :) Do you have time to edit the colour SVG and MAKE a PR?

**Comment by eaglersdeveloper** [comment]
This is pull request :)

Снимок экрана от 2019-04-26 19-09-33

**Comment by ubuntujaggers** [comment]
Lol!! What a doofus, I was on my phone and thought it was an issue :)

**Comment by ubuntujaggers** [comment]
Looks great to me :)

**Comment by eaglersdeveloper** [comment]
Will somebody merge this PR?

**Pull request merged**
