### PR TITLE
Issue2034/shell slider borders

### PR DESCRIPTION
**Pull request by clobrano**
shell/slider: revert upstream change to yaru style

- changed border color to pre-rebase since current one is too strong against panel background
- use new progress_border_color from gtk and adapt the overdriver border color to it.
- on the slider, don't use the same color for background and border

Closes: #2034

image
image

Note: this might be a little tricky to test on dark shell because the new meson build does not symlink anymore Yaru-dark shell. I've already asked @3v1n0 if there is a reason not to symlink, and if not, the fix should be easy. Anyway if you don't see any difference in the dark shell, try to double check the symlink and do it manually eventually.

### CODE REVIEW

**Comment by clobrano** [comment]
updated the handle's borders as in gtk

**Comment by Feichtmeier** [comment]
Looks good from your pictures, but I can't test it locally since I don't know how to set the $variant to dark manually :) any tips?

**Comment by clobrano** [comment]
Can't you install user themes?

**Comment by Feichtmeier** [comment]
Alright I'll try later or tomorrow, if you successfully tested it yourself (which I guess, since there are screenshots xD) you could also just merge it

**Pull request merged**
