### PR TITLE
mimetype application-x-theme

### PR DESCRIPTION
**Pull request by Muqtxdir**
Change of icon name in Baseplate form 'application-x-ms-dos-executable' to 'application-x-theme'

Issue No: #2241 
This is my first Pull-request, Please check it

### CODE REVIEW

**Comment by clobrano** [comment]
Hi @Muqtxdir, thanks for taking time to contribute to Yaru! Much appreciated.

I wonder why the size of the files has changed so much. @ubuntujaggers could you double check please?

**Comment by ubuntujaggers** [comment]
I've now got a local version of @Muqtxdir's branch that doesn't have the errors when the script runs - can I push it, Muqtxdir?

**Comment by Muqtxdir** [comment]
Yes

**Comment by ubuntujaggers** [comment]
Try now?

**Comment by Muqtxdir** [comment]
@ubuntujaggers Yes, it is fixed

**Pull request merged**
