### PR TITLE
New symbolic icons for every preinstalled application

### PR DESCRIPTION
**Pull request by Feichtmeier**
Continuation of https://github.com/ubuntu/yaru/pull/1082

- jaggers new symbolic app icons
- new edit-select-all icon
- brings back symbolic app icons for messages and .app-menu
- conflicts resolved concerning the broken big symbolic file
- fat/thick shutdown icon included

Closes https://github.com/ubuntu/yaru/issues/1073

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1094`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1094` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
Thanks for finishing this and posting the gif @feichtmeier! They look as good as I hoped, and we can always improve or change individual icons in response to feedback. Next I'll sort out Firefox.

**Comment by ubuntujaggers** [comment]
Before merging: I think I (somehow?!) committed a symlink that is already in Yaru (not sure how) - wanted to highlight this in case we need to remove it before merging, I know you said it would cause errors @Feichtmeier.  It is:
  
system-file-manager-symbolic.svg ( --> filemanager-app-symbolic.svg)

So might be worth specifically checking the symbol for File Manager works?

**Comment by Feichtmeier** [comment]
Works :)

image

**Pull request merged**
