### PR TITLE
WIP: Use $progress_bg_color for all spinners

### PR DESCRIPTION
**Pull request by Feichtmeier**
- [ ] use purple for the plus symbols
- [ ] render all cursors
- [x] adapt gtk4

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@Jupi007 pushed the changed to the plus symbols, could you render it again please? Doesn't work for me :S

**Comment by Jupi007** [comment]
> @Jupi007 pushed the changed to the plus symbols, could you render it again please? Doesn't work for me :S

It's done!
But it is strange that it doesn't work on your side. Did you remove the bitmap you want to rerender before running the script?

**Comment by Muqtxdir** [comment]
@Jupi007 this-screenrecord is on latest-commit of this branch. the progress cursor still is not colored with **$progress_bg_color**, is this a case of render-issue or a missing-symlink?
Peek 2021-04-15 15-03

**Comment by Feichtmeier** [comment]
I think we need to re-create this PR after #2848 lands, closing this

**Pull request closed without merging**
