### PR TITLE
phosh: auth_sim_icon 

### PR DESCRIPTION
**Pull request by Muqtxdir**
Hi @giovannicaligaris could you please build from this branch and see whether this resolves issue: #3257

### CODE REVIEW

**Comment by Jupi007** [comment]
@Muqtxdir I don't think it will works because you only modified the icons inside `/src`, without build them.

Also, why did you modified the battery icon? :thinking:

**Comment by Muqtxdir** [comment]
oh I'll push them, I did not modify battery weird that it shows up

**Comment by giovannicaligaris** [comment]
Working.

**Review by Jupi007 — APPROVED** [review]
LGFM :+1: 

The battery icon doesn't matter, as it didn't changed anything.

**Comment by giovannicaligaris** [comment]
Battery icon on lockscreen looks great, but is different from the toolbar.

**Comment by Jupi007** [comment]
> Battery icon on lockscreen looks great, but is different from the toolbar.

Yes, but this is another problem.
It looks like we miss some battery icon.
@Muqtxdir can you investigate?

**Comment by Muqtxdir** [comment]
>Yes, but this is another problem.
It looks like we miss some battery icon.
@Muqtxdir can you investigate?

I'll look into this but I think you can merge this. @giovannicaligaris could you open an issue for this one. I think there are many more icons that phosh uses that are not present in yaru.

**Pull request merged**
