### PR TITLE
Test branch for legacy button colour icons

### LINKED ISSUE #1965: Provide legacy, full color action icons
Those icons are visible in Inkscape, they are ofc visible somewhere else, but since it is such a popular app, I think this is a very solid goal and the actual icons to draw are not so many:

image
- [x] **edit-redo (icon)**
- [ ] redo (symlink)
- [ ] gtk-redo-ltr (symlink)
- [ ] stock_redo (symlink)

__________________________________________________

image
- [x] **edit-undo (icon)**
- [ ] undo (symlink)
- [ ] gtk-undo-ltr (symlink)
- [ ] stock_undo (symlink)

__________________________________________________

image
- [x] **go-up (icon)**
- [ ] up (symlink)
- [ ] gtk-go-up (symlink)
- [ ] stock_up (symlink)

__________________________________________________

image
- [x] **go-down (icon)**
- [ ] down (symlink)
- [ ] gtk-go-down (symlink)
- [ ] stock_down (symlink)

__________________________________________________

image
- [x] **go-bottom (icon)**
- [ ] bottom (symlink)
- [ ] gtk-goto-bottom (symlink)
- [ ] stock_bottom (symlink)

__________________________________________________

image
- [x] **go-top (icon)**
- [ ] top (symlink)
- [ ] gtk-goto-top (symlink)
- [ ] stock_top (symlink)

__________________________________________________

image
- [x] **edit-copy (icon)**
- [ ] editcopy (symlink)
- [ ] gtk-copy (symlink)
- [ ] stock_copy (symlink)

__________________________________________________

image
- [x] **edit-paste (icon)**
- [ ] editpaste (symlink)
- [ ] gtk-paste (symlink)
- [ ] stock_paste (symlink)

__________________________________________________

image
- [x] **edit-cut (icon)**
- [ ] editcut (symlink)
- [ ] gtk-cut (symlink)
- [ ] stock_cut (symlink)

__________________________________________________

image
- [x] **document-properties (icon)**
- [ ] gtk-properties (symlink)
- [ ] stock_file-properties (symlink)
- [ ] stock_properties (symlink)

__________________________________________________

image
- [ ] **gconf-editor (icon)**
- [ ] gconfeditor (symlink)
- [ ] administration (symlink)
- [ ] control-center2 (symlink)
- [ ] drakconf (symlink)
- [ ] gkdebconf (symlink)
- [ ] gkdebconf-icon (symlink)
- [ ] gnome-desktop-config (symlink)
- [ ] paprefs (symlink)

__________________________________________________

image
- [ ] **rotate (icon)**
- [x] **object-rotate-left (icon)**
- [x] **object-rotate-right (icon)**

__________________________________________________

image
- [x] **object-flip-vertical (icon)**
- [x] **object-flip-horizontal (icon)**
__________________________________________________

image

- [x] **zoom-in (icon)**
- [x] **zoom-out (icon)**
- [x] **zoom-fit-best (icon)**
- [x] **zoom-original (icon)**

### PR DESCRIPTION
**Pull request by ubuntujaggers**
I've created this new branch that's the same as master with a load of legacy icons to use as buttons in apps.  Please have a go of the branch using apps like Inkscape.  I'll update it as I work on the icons :+1: 

Eventually

Closes #1965

### CODE REVIEW

**Comment by Feichtmeier** [comment]
grafik

Looks really good!
:clap: 

found some missing in inkscape in "align and distribute"
and
evolution preferences

**Comment by ubuntujaggers** [comment]
> evolution preferences

Weirdly these don't seem to be humanity actions :thinking: 

I did some more work on Evolution and will do Inkscape alignment ones next :+1:

**Comment by Feichtmeier** [comment]
Maybe they are hardcoded or come to from adwaita. But I think they are maybe okay to skip

**Comment by ubuntujaggers** [comment]
I've started doing the alignment icons for Inkscape:

image

**Comment by ubuntujaggers** [comment]
Okay, have a go now - this is distribute and align in Inkscape:

image

...and Evolution is looking very Yaru now as well:

image

:+1:

**Comment by ubuntujaggers** [comment]
Hi guys,

Does anyone object to me merging?

**Comment by Feichtmeier** [comment]
Really nice @ubuntujaggers !
Feel free to merge and thanks for this huge work

**Pull request merged**
