### PR TITLE
New application-x-trash mimetype that's consistent with the clock on image-loading

### PR DESCRIPTION
**Pull request by ubuntujaggers**
We used a turn-back-the-clock glyph, but I later realised that there's already an icon with a clock glyph on it, called image-loading:

image

So, I've redrawn application-x-trash to use exactly the same clock and simply add a rewind arrow:

image

Also, IMO the glyph now looks a bit more Suru than the previous icon I drew because the glyph isn't as bold at the smaller sizes.

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1119`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1119` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
I like this more, because it is a real circle :)

I am just wondering about the commits? 🤔  Is this from the same branch as the polari branch?
There are no conflicts being displayed or anything, just wondering

**Comment by ubuntujaggers** [comment]
I believe I committed them from a different branch for just this icon called IconTheme_x-application-icon

**Comment by Feichtmeier** [comment]
> I believe I committed them from a different branch for just this icon called IconTheme_x-application-icon

Ah okay :) Could you make a new branch and only commit this new icon+pngs?
You need to switch to master first, pull the recent changes, and then create the new branch so it is based on master

**Comment by ubuntujaggers** [comment]
Okay - this (here) is a new branch for these icons, but I didn't do the step where I should have switched to Master first. I'll try again when I'm on my laptop :)

**Comment by Feichtmeier** [comment]
I just don't know enough about git
Maybe it does not matter (there are no conflicts or anything) 
Maybe @clobrano knows more :thinking: :thought_balloon: ?

**Comment by clobrano** [comment]
I can check it in an hour, sorry

On 16 Jan 2019 18:52, "Feichtmeier" <notifications@github.com> wrote:

I just don't know enough about git
Maybe it does not matter (there are no conflicts or anything)
Maybe @clobrano <https://github.com/clobrano> knows more 🤔 💭 ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ubuntu/yaru/pull/1119#issuecomment-454875158>, or mute
the thread

**Comment by clobrano** [comment]
Okay, basically the last three branches (polari, quadrapassel and this one) are each on top of the previous one, but I tried a merge in master and everything went fine, probably because the changes are limited to icons  :+1:

Just for reference, this is what I do for creating a development branch (sorry it's command line, but any front-end is able to do the same):

    git checkout master
    git pull
    git checkout -b <new-branch-name>

first and second line is to update local master branch to the latest development and create a new branch (last line) on top of it

when you want to propose a PR do this **once**

    git push --set-upstream origin <new-branch-name>

for all the next changes in the same branch just do

    git push

hope this can help :smile:

**Comment by ubuntujaggers** [comment]
@clobrano Yes, very helpful!!  I realise now that I was just making branches of branches, which wasn't what I intended.  I'll follow those steps exactly next time :+1:

**Comment by Feichtmeier** [comment]
Sooo mergymergo @clobrano ?

**Comment by clobrano** [comment]
Yes :+1

**Pull request merged**
