### PR TITLE
Default button and outline style

### PR DESCRIPTION
**Pull request by Feichtmeier**
Closes https://github.com/ubuntu/yaru/issues/306

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr695`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr695` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
It looks nice actually, but the hover effect is missing
orange label turns black on hover and the selection ring totally covers the hover effect of the button (box-shadow an bottom border)

**Comment by Feichtmeier** [comment]
peek 2018-08-08 13-47
peek 2018-08-08 13-46

Which one for the hover color?

The the hover shadow for the focused buttons is  still visible:
peek 2018-08-08 13-48

**Comment by Feichtmeier** [comment]
@clobrano or we use a 15% darken for the orange:

peek 2018-08-08 13-51

**Comment by clobrano** [comment]
Normal button's label do not change color on hover, so I'd keep the same orange as well. I still see the box-shadow effect hard to see with the new selection ring, but I like it more now than in master

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr695`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr695` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr695`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr695` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
peek 2018-08-08 14-12

**Comment by Feichtmeier** [comment]
Deleted all old pictures so no none becomes confused : D

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr695`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr695` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr695`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr695` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@clobrano it's -3px margin, focus color now. So the only difference to master is the orange color instead of the dark border . Feel free to merge

**Comment by clobrano** [comment]
LGTM :+1: thanks!

**Pull request merged**
