### PR TITLE
Updated cursor readme

### PR DESCRIPTION
**Pull request by madsrh**
This took me a while to figure out, so I added a short description to the readme.

### CODE REVIEW

**Comment by madsrh** [comment]
[Comixcursors](https://gitlab.com/limitland/comixcursors) has also got a nice html test side shipped with their theme. Perhaps we could include it too?

**Comment by clobrano** [comment]
The test is amazing, good idea! It also shows how our cursors are not always well aligned :thinking: 
I also think it could be helpful to add brief description o the test and how to use it in cursor's README.md, what do you think?

**Comment by madsrh** [comment]
Like this:

**CSS Cursors test**
The csscursors.html let's you see your browser's cursor style and where the HOTSPOT is simply by hover over the boxes containing the CSS cursor name. In CURSORNAMES.md you'll find the naming specification and a description of the cursors.

**Comment by clobrano** [comment]
Yes, it looks good

**Pull request merged**
