### PR TITLE
New icons for LibreOffice Main, Writer, Calc, Impress and Draw

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Hi,

Here are the LibreOffice icons, as follows:

**libreoffice-main**

image

**libreoffice-writer**

image

**libreoffice-calc**

image

**libreoffice-impress**

image

**libreoffice-draw**

image

**libreoffice-base**

libreoffice-base

Happy to do further revisions on these if they don't look as good as hoped in testing, or to have them retired in favour of the upstream icons superimposed on a squircle (e.g., script solution when ready).

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Nice! Thank you!

**Comment by Feichtmeier** [comment]
Works!
But you missed libreoffice-base xD
image

Btw when you are finnished do this to render the images:

```bash
cd ~/yaru/icons/src/fullcolor/
sudo apt install optipng
python render-bitmaps.py libreoffice-calc
python render-bitmaps.py libreoffice-draw
python render-bitmaps.py libreoffice-impress
python render-bitmaps.py libreoffice-main
python render-bitmaps.py libreoffice-writer
```
python render-bitmaps.py libreoffice-base

**Comment by ubuntujaggers** [comment]
@Feichtmeier 

"But you missed libreoffice-base xD"

Aha, so I did!  I will do that promptly tomorrow and update the PR.  I'm quite happy with how those look in the app grid so that's good to see.

Thanks for the instructions - if I render the images here should I commit each of the pngs too?

**Comment by eaglersdeveloper** [comment]
Hi, @ubuntujaggers.
I like your work, but these are third-party applications.
It is unlikely that they will be included in Yaru.

**Comment by Feichtmeier** [comment]
@eaglersdeveloper we talked about this on the hub and decided to include them as wet checked the licenses

**Comment by Feichtmeier** [comment]
No, only preinstalled apps. LO, Thunderbird and Firefox are missing.
Do you read the hub?
Also, we really appreciate your icon contributions but we don't appreciate the way you troll every pull request. It's becoming very annoying.

**Comment by Feichtmeier** [comment]
@ubuntujaggers yay works + looks great
image
The name libreoffice-main is correct :) check in /usr/share/icons/hicolor/

**Comment by Feichtmeier** [comment]
Merging since mads and carlo already gave their :+1: in the OP
Thank you very much @ubuntujaggers

**Comment by ubuntujaggers** [comment]
> Don't know how to start only the main window though 🤷‍♂️

Running "libreoffice" in Terminal opens the main window apparently, which is why I wondered if that's what the icon should be called...

**Comment by meetdilip** [comment]
Nice work +1

**Pull request merged**
