### PR TITLE
Add icon for java archive mimetype

### LINKED ISSUE #1374: Icons for application/x-java-archive and application/x-java is same.
## Icon Request

If you're filing an issue for a missing icon provide the following in your request:

Request to Change file icon type for 'Java-Archive(jar)' files.
Icons for 'application/x-java' and 'application/x-java-archive' files and same. It would be better if 'application/x-java-archive' have some kind of differentiation to indicate it is an archive.

Thanks!

### PR DESCRIPTION
**Pull request by madsrh**
Fixes #1374 

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Build from YOUR FORK :P and it works ! :+1: 

One thing, as a java dev IRL, that bums me is that you can not say from the icon that it is related to java.
There are java archives but there are also java archive you can run as an "app" (java -jar filename)

So it would be neat if you could get the java glyph somehow inside the icon :see_no_evil:

**Comment by madsrh** [comment]
Great feedback @Feichtmeier 
Or add the text as suggested in the issue perhaps?

**Comment by Feichtmeier** [comment]
Done :)

**Comment by Feichtmeier** [comment]
Works :+1: 
image

**Pull request merged**
