### PR TITLE
Non-uniform icon for Ubiquity

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Arguably not very exciting, it's just the one we had on a circle rather than a squircle.

Don't know how to test this one  :\  Tried sudo apt install ubiquity, it downloaded about a gig of stuff and then I couldn't find an app!

image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1224`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1224` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Important first impression when one installs Ubuntu!

I like that circle! 
The only idea I have is one we already discussed back in time when you had your big PR for 18.10: let the pen draw a CoF (not cradle of filth... circle of friends =) )?

Other than that I'd to instant-merge that. But better wait for @madsrh and @clobrano since it's an important app.

**Comment by madsrh** [comment]
I think this icon could be improved further or maybe even rethought 🙊  
You can easily see the pen, but it isn't obvious that it's a drive. And if it is a harddrive, why make it round?

**Comment by ubuntujaggers** [comment]
I could just stick a Circle of Friends on the existing Disk Utility app, maybe?

**Comment by madsrh** [comment]
> I could just stick a Circle of Friends on the existing Disk Utility app, maybe?

Maybe that would work better, but there might be an issue with using a logo in an icon that way. I'm +1 but I'll tag @matthewpaulthomas to hear his thoughts.

**Comment by eaglersdeveloper** [comment]
Maybe better to use computer with download icon like Startup Disk Creator icon?

**Comment by clobrano** [comment]
I agree with @madsrh. This shape might recall more a DVD burner, and the circle of friends has some precise usage guidelines, I don't know if we're allow to break them for this reason.

**Comment by ubuntujaggers** [comment]
@eaglersdeveloper that's a nice easy option, could just recycle the same arrow on top of the mimetype

**Comment by ubuntujaggers** [comment]
As per @eaglersdeveloper idea:

image

Probably quite a safe option if we don't come up with something we like better?

**Comment by madsrh** [comment]
@ubuntujaggers :tada: Much better!

Are you sure about the color of the "emblem"? Just wondering if green or orange would be better, but just nitpicking really.

**Comment by ubuntujaggers** [comment]
@madsrh I just nicked it as it was from the USB creator, which is now unchanged from Suri! No personal preference on the colour :)

**Comment by clobrano** [comment]
I was just about to suggest orange :)

**Comment by ubuntujaggers** [comment]
White on orange:

image

Orange on white (IMO this doesn't work so well on top of the pale object and in terms of legibility at smaller sizes):

image

**Comment by madsrh** [comment]
@https://github.com/ubuntujaggers if it's not too much trouble, could you share images of the green version too? IMO the orange could be mistaken for red = "danger" or maybe it's just this screen 😀

**Comment by ubuntujaggers** [comment]
@madsrh 

image

??

**Comment by madsrh** [comment]
Thank you (that was fast)! 
I prefer the green but I'm fine with the orange also.

**Comment by Paz-it** [comment]
Orange on pale circle is the most elegant IMHO ...

**Comment by eaglersdeveloper** [comment]
Try to use hard disk icon from "devices" folder

**Comment by Feichtmeier** [comment]
I would not use the green badge because it is so close to the new notification badge.

Considering we are using blue for a progress maybe our Ubuntu blue would fit best

**Comment by ubuntujaggers** [comment]
> Try to use hard disk icon from "devices" folder and blue color for download emblem.

image

??

I'm probably more in favour of using the blue because it's consistent with USB creator and doesn't clash with any other emblems.  I'm not sure about the hard disk device icon in general but don't mind that either.

**Comment by madsrh** [comment]
> Try to use hard disk icon from "devices" folder and blue color for download emblem.

I don't like this device icon so I perfer the first suggestion. And @Feichtmeier is right about color - let's go with blue 👍 

"Now installing Fedora" 😂😂 just kidding

**Comment by clobrano** [comment]
Danger maybe is too much, but "pay attention" wouldn't be wrong

**Comment by ubuntujaggers** [comment]
Okay, got some non-graphics chores to do today, but will push disk utility + blue arrow tonight or tomorrow so we've at least got something better in the branch  :)

**Comment by madsrh** [comment]
>  ...so we've at least got something better in the branch

:tada: 👍 

Just for comparison 👇 Again, I'm good with all three suggestions (just a quick mockup so don't mind 
the imperfections)


qweqwe

**Comment by Feichtmeier** [comment]
@ubuntujaggers thank you! I think we also need a new symbolic icon then, now that the whole symbol is different. Maybe just the emblem-arrow-circle for the symbolic icons?

**Comment by ubuntujaggers** [comment]
image

Pushed  :)

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1224`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1224` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Awesome thank you @ubuntujaggers !

Merging after testing later today (if no-one has any veto?)

**Comment by ubuntujaggers** [comment]
Yep, got to pop to shops (boooo) but will do it in an hour or two.

**Comment by ubuntujaggers** [comment]
> @ubuntujaggers thank you! I think we also need a new symbolic icon then, now that the whole symbol is different. Maybe just the emblem-arrow-circle for the symbolic icons?

Pushed this, as per suggestion:

image

Is that okay?

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1224`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1224` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
image

image


Sexy! Can I merge this?

**Comment by matthewpaulthomas** [comment]
> I'll tag @matthewpaulthomas to hear his thoughts.

Sorry I was on holiday! Given how few people have seen what’s inside a hard disk case, and how many computers now use SSDs instead, I think it would be better to avoid a disk platter, at least for anything that isn’t specifically about disks. (The Windows and macOS installer icons don’t include a disk platter — and even gnome-disk-utility upstream doesn’t, showing a disk case instead.)

However, most Ubiquity users aren’t launching it from its icon in the first place (and aren’t running other apps at the same time that they need to switch between), so it doesn’t matter so much what its icon is.

**Comment by madsrh** [comment]
Thanks for the reply @matthewpaulthomas

Do you have any thoughts regarding the arrow? https://github.com/ubuntu/yaru/issues/1261

**Pull request merged**
