### PR TITLE
Ubuntu Mate: full colour icon for preferences-desktop-display

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Does this work?

image

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
Oops, just spotted an error - pushing a correction.

**Comment by ubuntujaggers** [comment]
Fixed :+1:

**Comment by Feichtmeier** [comment]
Looks really cool

**Comment by Jupiter007-43** [comment]
Beautiful 😍

**Review by Feichtmeier — APPROVED** [review]

**Comment by Feichtmeier** [comment]
@ubuntujaggers would be cool to get this all into master as well at some point

**Pull request merged**
