### PR TITLE
Add mime type icon for .flac

### PR DESCRIPTION
**Pull request by madsrh**
I forgot to add the flac icon to audio files. I've tried to create a symlink again.

image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1168`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1168` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by eaglersdeveloper** [comment]
Change font to Ubuntu

**Comment by Feichtmeier** [comment]
I am pretty sure this is the ubuntu font :)
image

**Comment by eaglersdeveloper** [comment]
Are you really sure?

**Comment by Feichtmeier** [comment]
No! :laughing: You were right
To say it with the wise words of a person that writes so many blog posts: mea culpa! :roll_eyes: :laughing:

**Comment by madsrh** [comment]
Good spotted @eaglersdeveloper

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1168`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1168` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Hmmmm that is not working for me
Maybe that mimetype has a different name?

image

**Comment by madsrh** [comment]
Maybe I've messed up the symlink again?

Hmm, I pushed the diff after running the script but I don't know why the 'desktop.ini' is changed.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1168`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1168` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Works! But! The border looks very thick

image

image

**Comment by clobrano** [comment]
I tried to just re-render the file and it looks fine now :thinking: 

image

can I commit this?

**Comment by madsrh** [comment]
I have no idea what I did wrong but if they look fine now, yes let's merge it

**Comment by vitalkanev** [comment]
NO due to my review

**Comment by madsrh** [comment]
> NO due to my review

@vitalkanev ?

**Comment by clobrano** [comment]
@vitalkanev, I can't find you review, where is it?

**Comment by vitalkanev** [comment]
https://github.com/ubuntu/yaru/pull/1168#pullrequestreview-201918910

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1168`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1168` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
> Nice thanks!
> But what about the other sizes? Are they fine?

They should be, please test to be 100% sure. I just re run render-bitmaps and committed all the changes

**Comment by clobrano** [comment]
> [#1168 (review)](https://github.com/ubuntu/yaru/pull/1168#pullrequestreview-201918910)

That's weird. I am the only one or the link toes not point to anything?

**Comment by Feichtmeier** [comment]
Nope, for me too. No review

**Comment by vitalkanev** [comment]
I am on mobile so, try scrolling up until something that says "(Me) started a review"

**Comment by clobrano** [comment]
> I am on mobile so, try scrolling up until something that says "(Me) started a review"

I can see @Feichtmeier review message

image

but there seems to be nothing from you (no "Started a review" at all)

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1168`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1168` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Works 
image
image

**Pull request merged**
