### PR TITLE
ShellTheme: default to the dark shell theme (system theme)

### PR DESCRIPTION
**Pull request by Feichtmeier**
- keep both of the system themes useable
- the default system theme is now "dark"
- since the GNOME desktop has no official way to swap the application theme together with the system theme,
defaulting to the dark system theme should be less invasive for the users
if they work late and switch to the dark application theme via the system settings
- Ubuntu provides (in opposite to default GNOME) a way to switch the application themes
between a mixed, a light and a dark application theme since Ubuntu 20.04
- the light system theme is still useable with the unoffical way of installing the
user-themes gnome shell extension and then switching to the "Yaru-light" shell theme in gnome-tweaks

Related to #2644 problem 4b

Anyone or all of you please let us know what you think about this :+1: :-1: 
@cassiocassio @didrocks @kenvandine 

Before:
lightshell

After:
darkshell

Using the dark application theme from the Ubuntu settings with the current shell theme:
Screenshot from 2021-02-15 14-21-08
Screenshot from 2021-02-15 14-21-01

Using the dark application theme from the Ubuntu settings with the proposed shell theme:
Screenshot from 2021-02-15 14-30-18
Screenshot from 2021-02-15 14-30-20

### CODE REVIEW

**Comment by cassiocassio** [comment]
Sorry, late to this.
+1 the dark panels as children of the dark dock, etc

@Feichtmeier do loop in @waynecrosby for colour / brand eyeballs, and @elioqoshi for UX thoughts

Question: this UX of this is not improvable without underlying changes to the way System and Application themes interact?

**Comment by Feichtmeier** [comment]
@cassiocassio thank you very much for replying

> Question: this UX of this is not improvable without underlying changes to the way System and Application themes interact?

Ubuntu provides it's own system theme over the default gnome system theme, which is loaded via a special Ubuntu session.
There are theoretically two themes installed for the system: light and dark
But with the default system settings without unofficial modifications, it is only possible to change the application themes from mixed/light/dark
Not the system theme. The system theme always stays the same (In 20.04 and 20.10 it's light)
This pull request would change it to dark

**Comment by Feichtmeier** [comment]
@cassiocassio 
For more information and a analysis of the Ubuntu theme situation we would appreciate if you could take a look at: https://github.com/ubuntu/yaru/issues/2644

**Comment by elioqoshi** [comment]
@Feichtmeier Thanks for the very detailed analysis! 

> Not the system theme. The system theme always stays the same (In 20.04 and 20.10 it's light)
This pull request would change it to dark

I am not sure if I understand the proposed solution right. 
This PR would change the light system theme (which is actually mixed) to a proper dark theme when the dark theme is selected in Ubuntu by the user?

**Comment by Feichtmeier** [comment]
> @Feichtmeier Thanks for the very detailed analysis!
> 
> > Not the system theme. The system theme always stays the same (In 20.04 and 20.10 it's light)
> > This pull request would change it to dark
> 
> I am not sure if I understand the proposed solution right.
> This PR would change the light system theme (which is actually mixed) to a proper dark theme when the dark theme is selected in Ubuntu by the user?

Hi @elioqoshi :wave: thanks for replying

The issue I linked summarized several issues.

The gnome desktop has no official way to flip all of the themes from light to dark.
So the current Ubuntu features a mixed application theme with a dark headerbar (many of the Ubuntu developers and users explained to me that this comes from the historical fact that it has always been this way and this is the default Ubuntu look) and the rest of the application window to be white.
The system theme however (different technology than the applications) has currently a white popovers, white dialogs and white notifications. 
If this pull request would be merged, it would change all of the _system_ theme parts to be dark. 
To what theme the applications should default to, is not changed in this pull request but is indeed still part of the discussion. It is a very confusing situation. :smiley: 

I think that when we change the system theme to be dark always, we still do not feature a global dark/light toggle, but when a user works at night, and switches the application theme to be dark via 
grafik
this system setting view
then the dark popups won't annoy so much as the opposite situation, where the user uses the light theme at day and a very dark system part pops above the light window. Which is still not perfect but maybe less annoying.

**Comment by iainlane** [comment]
Can you please confirm that by the term system theme you mean the GNOME Shell theme, and not the GTK theme which applications are using? Pretty sure that's right from looking at the diff.

I don't personally understand the term 'system theme', so I want to be clear exactly what the proposal is here. (Maybe some screenshots in the OP which show the *same* view but before & after would be helpful?)

**Comment by Feichtmeier** [comment]
@iainlane 
yes, I only use the term "system theme" because the designers are probably not familiar with whats gnome-shell and what's gtk
It's clear from the commit and PR name :)

**Comment by Feichtmeier** [comment]
@cassiocassio @elioqoshi updated with better screenshots

**Comment by elioqoshi** [comment]
@Feichtmeier thanks, the new screenshots provide better context! I'm aware of what's gtk and gnome-shell and we might want to use the same definitions across parties to make sure we are on the same page maybe.

I'm recently joined Canonical (although I used to be a Fedora Ambassador and am familiar with GNOME) so please excuse me if I need a bit more time to get my head into this topic, it seems rather complex indeed. I'd love to help out on Yaru and eventually also facilitate some collaboration with GNOME (who I know is eager to improve the desktop experience).

What you suggested makes a lot of sense. Just to confirm, if the user has a light theme enabled, the gnome-shell theme would be still dark right? In this case, you are suggesting a low-hanging fruit solution for now, as properly solving the dark/light theme experience will need to be worked on in the longer-term, right?

**Comment by Feichtmeier** [comment]
> @Feichtmeier thanks, the new screenshots provide better context! I'm aware of what's gtk and gnome-shell and we might want to use the same definitions across parties to make sure we are on the same page maybe.
> 
> I'm recently joined Canonical (although I used to be a Fedora Ambassador and am familiar with GNOME) so please excuse me if I need a bit more time to get my head into this topic, it seems rather complex indeed. I'd love to help out on Yaru and eventually also facilitate some collaboration with GNOME (who I know is eager to improve the desktop experience).

Excellent news! Alright, I will stick to the official terms :)

> What you suggested makes a lot of sense. Just to confirm, if the user has a light theme enabled, the gnome-shell theme would be still dark right? In this case, you are suggesting a low-hanging fruit solution for now, as properly solving the dark/light theme experience will need to be worked on in the longer-term, right?

Confirmed. When the user switches to a different gtk theme in the gnome control center appearance tab (which is not included in vanilla gnome and is an Ubuntu addition) the shell theme does not change.

One part of the bad dark/light situation is the absence of a global desktop theme toggle. And this can and should be worked on upstream. As far as I tried to follow the conversations between the gnome designers, the gtk maintainers and the gnome shell maintainers, this is a hot topic for them too with no current solution.

The other part is the default gtk theme, which is not really a light theme and which causes glitches in some gtk applications, but I know that this is most likely only my opinion, and maybe @clobrano 's , so I think this is not ideal to default to. But this is not part of this issue so let's keep it out - I would really love if we could talk about this though, does not need to be for this release, but just in general. Issue https://github.com/ubuntu/yaru/issues/2644 describes most of the situation. I'll ping didier to include you in the yaru team so you can answer on this issue, since I locked it for now to team members only

**Comment by waynecrosby** [comment]
@Feichtmeier Thanks for all your work on this, it's great! I helped out the Yaru/Desktop teams on the last couple of releases from a design/brand stand point and the issues you have raised were apparent then. I'd be happy to help out too moving forward. There doesn't seem to be a simple fix to the GNOME and GTK visual differences and the coding side is even more complex. I know there was talk of looking at other solutions but I'm not sure from a business perspective how far they went? The lack of control using GNOME is a real frustration and if we can look to a long term fix that would be amazing.

**Comment by elioqoshi** [comment]
@Feichtmeier Great! Yeah, a dark gnome shell theme on a light gtk theme is likely a better experience than the opposite (as it was mentioned in the other discussion, people are used to have dark window bars and other menu bars in an otherwise light desktop (and it might actually be a viable idea to keep this as a 3rd option once proper dark and light theming is available).

> I would really love if we could talk about this though, does not need to be for this release, but just in general. Issue #2644 describes most of the situation. I'll ping didier to include you in the yaru team so you can answer on this issue, since I locked it for now to team members only

Same here. Feel free to loop me in and I will do my best to contribute. Thank you!

**Comment by Feichtmeier** [comment]
> @Feichtmeier Thanks for all your work on this, it's great! I helped out the Yaru/Desktop teams on the last couple of releases from a design/brand stand point and the issues you have raised were apparent then. I'd be happy to help out too moving forward. 

Hi @waynecrosby :wave: - We've met last year in London! :) (Frederik here)

> There doesn't seem to be a simple fix to the GNOME and GTK visual differences and the coding side is even more complex. I know there was talk of looking at other solutions but I'm not sure from a business perspective how far they went? The lack of control using GNOME is a real frustration and if we can look to a long term fix that would be amazing.

From our side we tried to stick to gnome as much as possible (except the inverted headerbar in the default theme) while still trying to satisfy the branding needs of the Ubuntu desktop. Sometimes it's tough but mostly it kinda works out.
Apart from us, I don't think there was any movement on the gnome side when it comes to a theming api.
I try to stay in touch with the gnome designers and contribute in terms of helping out to get stuff done, but their position to overwriting the gnome aesthetics did not change much, though they are maybe a little bit more open minded now compared to some years ago.
Or what did you mean with other solutions? (Sorry I am not a native english speaker and sometimes I miss the tiny information between the lines or don't get the full context)

**Comment by waynecrosby** [comment]
@fredldotme Hi Frederik! Sorry recognise your name, hope you are well. :)
Yeah I don't think the GNOME designers were looking to a theming api any time soon which is a shame. Got my wires crossed with the other solution, I was thinking about when we looked at Flutter (around the same time as the last release), but this was for our Apps and not the desktop, sorry.

**Comment by Feichtmeier** [comment]
@waynecrosby I am fine, hope you too?
I think you linked the wrong person :smile_cat: 

Speaking of flutter - got my hands a bit dirty here as well https://github.com/ubuntu/yaru.dart/pull/9

**Comment by vladimir-se** [comment]
The dark theme is cool!

**Pull request merged**
