### PR TITLE
Yarufy EarTag Icon

### PR DESCRIPTION
**Pull request by ochi12**
I tried to be as close as possible to the original design of eartag icon while still following most of Yaru's design guidelines.  

## Tasks:
- [x] finished initial designs
- [x] emailed eartag repo owner [knuxify](https://github.com/knuxify)
- [x] Permission granted 
- [x] finalized symbolic icon.

### screenshot:
Screenshot from 2024-11-21 22-25-26

### CODE REVIEW

**Comment by ochi12** [comment]
The music note in the symbolic icon seems to be unnecessary I might consider just going for a solid symbolic with the original silhouette.

**Comment by Jupi007** [comment]
Great!
But imo without the music note, it looks too much like a padlock 🤔

**Comment by Muqtxdir** [comment]
nitpick: could the music note be similar to yaru's music note as well?

**Comment by ochi12** [comment]
> Great! But imo without the music note, it looks too much like a padlock 🤔

Lol I notice that now

**Comment by ochi12** [comment]
> nitpick: could the music note be similar to yaru's music note as well?

I'll consider that

**Comment by ochi12** [comment]
> Great! But imo without the music note, it looks too much like a padlock 🤔

fixed.
Screenshot from 2024-12-05 15-18-44

**Review by Muqtxdir — APPROVED** [review]
thanks! love the new icon's look :smiley:

**Review by Jupi007 — APPROVED** [review]
Awesome work, thanks a lot @ochi12 :+1:

**Pull request merged**
