### PR TITLE
Add support for GS42 - upstream sync

### PR DESCRIPTION
**Pull request by Jupi007**
Add support for **Gnome Shell 42** _- still compatible with 40_.

Please test this and report your comments here.
The most noticeable change is an _huge increase_ of padding...

Capture d’écran de 2022-01-16 11-40-27

Related to #3311

### CODE REVIEW

**Comment by Muqtxdir** [comment]
I tried out this PR and found some issues:
- screen-keyboard in Light (_OSK_): Unreadable in Yaru-light
Screenshot from 2022-01-16 20-23-17
- sliders in Light: The slider knob is indistinguishable in Yaru-light
Screenshot from 2022-01-16 20-27-57
- Calendar/Notification Popover: Shadows and borders look weird in Yaru-light, especially the clear all button
Screenshot from 2022-01-16 20-42-52
- Running Application indicator in Dock: white color is used as indicator instead of orange
Screenshot from 2022-01-16 20-25-45

**Comment by Jupi007** [comment]
Thanks for the review @Muqtxdir :+1: 

I did the sync without testing, because I left home right away.
Now I'm back, I'll fix all problems.

**Comment by Jupi007** [comment]
@Muqtxdir I should have fixed all the problems you mentioned.

**Comment by Muqtxdir** [comment]
all the light-theme issues described above are gone now. Thanks @Jupi007

**Comment by Jupi007** [comment]
Thanks for the review @Muqtxdir 
Using the dark theme, I didn't noticed any issues.

I think we can merge.
If we need to tweaks those new change, we'll doing this in others PRs.

@Feichtmeier It is ok for you?

**Comment by Feichtmeier** [comment]
Yes! Tyvm! (checked the commits but didn't test it but since muq tested it I think you can merge)

**Pull request merged**
