### PR TITLE
Ubiquity

### PR DESCRIPTION
**Pull request by Feichtmeier**
Closes: https://github.com/ubuntu/yaru/issues/676

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr694`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr694` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@madsrh @clobrano 

If you want to test this you need to install

```bash
sudo apt install ubiquity-frontend-gtk

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr694`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr694` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
I like the purple tint quite a lot, however if the installer will show pictures with default wallpaper like the one below, we're going to risk a clash of colors 
image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr694`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr694` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@clobrano @madsrh @eaglersdeveloper 
As cloboano pointed out, the no-go argument for anything but headerbar_bg_color is the slide show.
The dark heading and top properly masks the screenshots.
This was not obvious when we only looked at the first steps before the installation starts.

What I finally fixed is still:
- backdrop colors were not matching our headerbar backdrop color
- the dialog had no border and no margin of the buttons to the edge
- the EMPTY dots had a strange color, so I made them very transparent blue

I'd say let's merge this into master now :man_shrugging:

**Comment by clobrano** [comment]
LGTM :+1: :)

**Pull request merged**
