### PR TITLE
Issue1380/fix hdyleaflets

### LINKED ISSUE #1380: Hdyleaflet selection mode not styled
image

We need to dig more into that hdyleaflet stuff and check how adwaita does it, since more and more gnome apps are going to have that desktop/mobile interface

### PR DESCRIPTION
**Pull request by clobrano**
Rework of PR #1382 

- [x] headerbar color
- [x] hdyleaflet headerbar separator
- [x] selection mode buttons
- [x] titlebuttons
- [x] standard separator
- [ ] border-radius on small window
- [x] hydleaflet glitch

closes #1380

### CODE REVIEW

**Comment by clobrano** [comment]
Some pictures of current work

image
image
image
image

image
image
image
image

**Comment by Feichtmeier** [comment]
Awesome! Thank you!

There is still a little glitch in hdyleaflet selection mode when first child and last child are both visible
grafik
:D

**Comment by Feichtmeier** [comment]
One more thing: the orange circle is drawn on hover and close on the green, I would drop it completely in selection mode. Orange on the green is a hard combination :D

**Comment by clobrano** [comment]
> One more thing: the orange circle is drawn on hover and close on the green, I would drop it completely in selection mode. Orange on the green is a hard combination :D

I actually keep it on purpose. I agree that having the orange always visible is too much, but on hover it seems a good balance.

Working on the other glitch

**Comment by Feichtmeier** [comment]
Can't we go with transparency white circles instead? Really weird colour combination

**Comment by clobrano** [comment]
Transparency looks a bit too soft for me. Does orange on hover really too much? :thinking:

**Comment by Feichtmeier** [comment]
Transparentize white 0.9 looked okay to me. But I don't want eh... How was that metaphor... Let us die on this hill? XD

**Comment by Feichtmeier** [comment]
It's not the important. At least the orange stays orange and thus it would make sense.

**Comment by Feichtmeier** [comment]
@clobrano the issue is not only in selection mode :(
grafik

**Comment by clobrano** [comment]
I see, this is why I kept the checkbox unchecked. I am about to push a fix for this, but the `border-radius` of shrinked hydleaflet is still unsolved.
I saw your PR used `first/last/only-child`, but the same didn't work here - so far - and looking at the inspector the `hydleaflet headerbar`s actually do not disappear from CSS nodes, they're just invisible, so the property `first/last/only-child` doesn't actually change

**Comment by Feichtmeier** [comment]
Fucking horror!
Let's see what happens in adwaita, maybe this helps?

**Comment by Feichtmeier** [comment]
Very nice with the box-shadow!
I noticed now the backdrop has become a lot sharper! Also the preview of the dash to dock doesnt have a ultra big scaled top border anymore yay
But yeah the border-radius of the first-child is crap again :(

**Comment by Feichtmeier** [comment]
Also the border-radius is not axed for maxed windows
grafik
And the box shadow also stays

**Comment by clobrano** [comment]
Yep, I imagined the problem with maximized windows only last night after
pushing the change, sorry. It's a bit of a mess, adwaita has nothing
explicit in master to handle hydleaflet.

**Comment by clobrano** [comment]
I will work on this upcoming week, if I can't find a better solution will merge this with a know bug

**Comment by clobrano** [comment]
I still could not find a solution for the border-radius of hdyleaflet when shrinked.The problem is that from a CSS nodes point of view nothing change, so we cannot adapt.
Testing solutions, I noted that basically the only way to fix it is to get rid of the top-highlight, which is the element that makes this glitch visible. The other possible solution - move the top-highlight to at higher level in "window decoration" - fixes the problem, but at this point the top highlight cannot adapt to different headerbar colors (i.e. top-highlight stays grey on green headerbar), which is not acceptable from my point of view and also way more visible than squared border-radius visible only with shrinked hdyleaflet.

**Comment by Feichtmeier** [comment]
Closing this, as it is not happening anymore with new upstream refresh in master

**Pull request closed without merging**
