### PR TITLE
Update render-cursors script for inkscape 1.0

### PR DESCRIPTION
**Pull request by clobrano**
With inkscape 1.0 something changed in the way inkscape runs in background, and it seems than pre-running the script, creating a inkscape thread pool, communicating later the command to execute is not working properly.
As "Dirty Fix"® this commit replaces the inkscape thread pool with a direct call to inkscape with the full command for each rendering.
**Very likely this is slower, a lot**, but it should allow users to continue working with our cursors during a deeper refactory of this script.

### CODE REVIEW

**Comment by Jupi007** [comment]
Thanks a lot @clobrano for working on this ♥

Sadly it seems doesn't working on my computer.
I run `./render-cursors.py source-cursors.svg` and it just open a blank window of Inkscape.

**Comment by clobrano** [comment]
Thanks for testing!
Did you first removed some PNG from bitmaps folders?

**Comment by Jupi007** [comment]
> Did you first remove some PNG from bitmaps folders?

Yes, I removed one.

**Comment by clobrano** [comment]
Weird :thinking: 
Which version of inkscape, and how did you install it?

**Comment by Jupi007** [comment]
Inkscape 1.0.1 (3bc2e813f5, 2020-09-07)
I'm using the deb version.

**Comment by clobrano** [comment]
I tested both snap and deb versions, but they are both 1.0.2, which is the package that goes into 21.04

**Comment by Jupi007** [comment]
I did a `apt full-upgrade`. Inkscape version is still 1.0.1. I'm using 20.10.

**Comment by clobrano** [comment]
The snap version should be 1.0.2, if you could test that we can find out whether is a matter of version or script

**Comment by Jupi007** [comment]
Now it works with the deb (also tried snap) 🎉

Sorry for the merge commit, I clicked on the VS code button for fetching and it does that by itself.

**Comment by clobrano** [comment]
Great 😊

It doesn't seem merged to me (from mobile)

**Comment by Jupi007** [comment]
> It doesn't seem merged to me (from mobile)

No no I misspoke, I doesn't mean that one. It has merged this branch on itself :)

**Comment by clobrano** [comment]
Oh, I see now. No problems 👍

**Comment by Jupi007** [comment]
Thanks a lot @clobrano 💪

**Pull request merged**
