### PR TITLE
update LibreOffice icons

### PR DESCRIPTION
**Pull request by elioqoshi**
new LibreOffice icons as discussed in https://github.com/ubuntu/yaru/issues/2668

Closes https://github.com/ubuntu/yaru/issues/2668

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Looking great @elioqoshi !

I think we need to render them to PNGs first though.

**Review by Jupi007 — CHANGES_REQUESTED** [review]
The SGVs themself looks ok, everything is pixel perfect. No problem here, you did a good work @elioqoshi 👍
But it looks like you removed all Inkscape labels which are required for pngs rendering.
Did you used Inkscape?

**Comment by elioqoshi** [comment]
No I don't use Inkscape, hence I asked for review help :)

**Comment by Jupi007** [comment]
I'll fix all that 😉

**Comment by Jupi007** [comment]
Fixed 🎉
I also updated corresponding mimetype icons.

That looks gorgeous:

Capture d’écran de 2021-03-17 12-01-50

Thanks @elioqoshi !

**Review by Jupi007 — APPROVED** [review]

**Comment by elioqoshi** [comment]
Thanks @Jupi007 for assisting with the conversion :)

**Comment by Jupi007** [comment]
You're welcome @elioqoshi. That was a pleasure :)

**Pull request merged**
