### PR TITLE
Suggested new icon for aisleriot

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Solitaire aka gnome-aisleriot is one of our oldest designs, and IMO it's not the smartest icon in the set.  Just an idea - does anyone think this is an improvement?  It's not the most crucial app but it's one of the defaults, so worth making it as nice as possible :)

**Current**

image

**Proposed**

image

image

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
Now has characters instead of dots on the two largest sizes:

image

image

**Comment by madsrh** [comment]
@ubuntujaggers what do you think about making the separation between the cards a bit stronger?

cards

**Comment by ubuntujaggers** [comment]
Good idea 👍

**Comment by ubuntujaggers** [comment]
Current:

image

**Comment by madsrh** [comment]
I think we can merge this one 👍

**Pull request merged**
