### PR TITLE
Bionic: shelltheme gdm

### PR DESCRIPTION
**Pull request by Feichtmeier**
Cherry-picking and commiting "manually", to adapt the bionic branch to https://github.com/ubuntu/yaru/tree/ShellTheme_GDM

We/I need to test this on our bionic installations, I hope I did not mess up any merge conflict handling

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1360`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1360` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Works, but I don't know if the 2px border is necessary for the squircle :thinking:

**Comment by clobrano** [comment]
It doesn't feel bad though, I let you decide

**Comment by Feichtmeier** [comment]
Okay let's keep them as similar as we can then

**Comment by Paz-it** [comment]
What a nice surprise I've got! I like it very much, thank you!!!

**Pull request merged**
