### PR TITLE
unify all titlebuttons to a soft gray

### PR DESCRIPTION
**Pull request by Feichtmeier**
Screenshot from 2021-12-22 18-49-25
Screenshot from 2021-12-22 18-49-15
Screenshot from 2021-12-22 18-48-26
Screenshot from 2021-12-22 18-48-18

### CODE REVIEW

**Review by Jupi007 — APPROVED** [review]
LGFM :+1:

**Comment by Jupi007** [comment]
What about increase Gtk3 windowcontrols size?
So it looks more like Gtk4.

**Comment by Feichtmeier** [comment]
Yes please, but I have no idea how to do this. Tried some things. Could you push that?

**Comment by Jupi007** [comment]
Done:

Capture d’écran du 2021-12-22 19-14-22

Was _**simply**_ needed to: decrease `$_titlebutton_height` and increase padding 🤪

**Pull request merged**
