### PR TITLE
Make pictogram clearer on Gedit app icon

### LINKED ISSUE #2435: LP#1873365 "gedit icon is too pale"
Reported first on Launchpad at https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1873365

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Closes #2435

Current:

image

image

In this PR:

image

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Hm, I know I am annoying with not liking this pen ^^ but could you try to make less lines which are also darker?

**Comment by clobrano** [comment]
The original bug report takes Evince's icon as example, what do you think about using the same approach with lines color an thickness?

**Comment by ubuntujaggers** [comment]
Apologies for delay, I've been mad busy - I'll have a go this morning :)

**Comment by ubuntujaggers** [comment]
Have a go now:

image

image

image

**Comment by Jupiter007-43** [comment]
Very nice!

**Comment by madsrh** [comment]
This looks good @ubuntujaggers

**Comment by ubuntujaggers** [comment]
I think the lines on the full size version need padding more on the left and right 🤔

**Comment by ubuntujaggers** [comment]
Done:

image

image

Any objections to merging?

**Comment by DoctorRover** [comment]
The updated icon has landed in hirsute. Looks awesome! Thank you! :)

**Pull request merged**
