### PR TITLE
Sync with GNOME 3.32 branch

### PR DESCRIPTION
**Pull request by iainlane**
See https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1829699

There's a couple of upstream commits

> 9d6fcfdc8 switch: Drop separate handling for US
> 5f5a3b78a theme: update toggle switch design

which break toggle switches, e.g. in the VPN menu:

bad

...fixed with this MR

on

### CODE REVIEW

**Comment by iainlane** [comment]
Also this fixes region screenshots (shift-printscreen), didn't realise they were broken :smile: 

https://youtu.be/pSDnHSibYkU

**Comment by clobrano** [comment]
Hey @iainlane, thank you!
I don't have VPN to test this, is it safe to merge this for Disco?

**Comment by iainlane** [comment]
Hey, thanks for the reply.

It's supposed to be. We will indeed want to upload this to disco. Probably not just upload all of master though - maybe we can make a 19.04 branch with selected fixes? (perhaps we should talk about that on IRC)

**Comment by iainlane** [comment]
I guess @3v1n0 could review maybe as he definitely has the VPN dress ;)

**Comment by 3v1n0** [comment]
Confirm it works fine here.

immagine

**Comment by Feichtmeier** [comment]
Thank you guys!!!

**Pull request merged**
