### PR TITLE
New Ubiquity icon

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
Please, don't merge now.
I haven't created symbolic icon.

installer-app

### CODE REVIEW

**Comment by Feichtmeier** [comment]
I prefer the current icon 
image

**Comment by eaglersdeveloper** [comment]
An user won't find out what is this application with this icon and without the app name.

**Comment by clobrano** [comment]
@eaglersdeveloper, your icon suggests more a "download" meaning than install. The current one might be not perfect, but at least suggests an operation on the disks. I agree with @Feichtmeier here

**Comment by Feichtmeier** [comment]
The user won't search for this and even if he would, he will not find it because it is not installed by default anymore after you finished your installation of Ubuntu

You install Ubuntu and this icon is attached to the dock when you have the installer opened from within the live session.

**Comment by eaglersdeveloper** [comment]
But what if the user is for first time launching Ubuntu?

**Comment by Feichtmeier** [comment]
> But what if an user is for first time launching Ubuntu?

@eaglersdeveloper Ubitquity is the window you see when you have a new PC and insert your USB Stick then boot from the usb stick -> ubuntu installation starts and that is basically ubiquity. So if you chose "install ubuntu" you don't have a dock and thus don't even see the icon.
Whereas when you chose "try ubuntu" and THEN in that livesession you see that ubiquity logo on the desktop "Install ubuntu". When you double click it ubiquity opens again etc etc

So seeing three opinions against this I have to close this (though it is a shame, since you invested time into this good looking icon - why don't you ask before? : / )

**Comment by madsrh** [comment]
Would this make it look more like you were installing Ubuntu? 😁  

image

**Comment by eaglersdeveloper** [comment]
An user can press Space, select language and right away load LiveCD
https://losst.ru/ustanovka-ubuntu-18-04

**Comment by eaglersdeveloper** [comment]
In addition, anything can be recorded to a disc, not only Ubuntu.

**Comment by clobrano** [comment]
In any case, your icon doesn't seem to do a better job for me

**Pull request closed without merging**
