### PR TITLE
Links gnome-dev-disk to media-optical

### LINKED ISSUE #2351: Missing symlinks: gnome-dev-disk-dvd-*
grafik
(left side wrong DVD icon, right side a normal yaru CD icon)

I am pretty sure we have an icon for this, just missed some symlinks. List is this, could be partially complete, need to check:

- [ ] gnome-dev-disk-dvdr
- [ ] gnome-dev-disk-dvdrw
- [ ] gnome-dev-disk-dvdram
- [ ] gnome-dev-disk-dvdrom
- [ ] gnome-dev-disk-dvdr-plus

edit: this icon is used when you are in a gnome-boxes VM

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Links gnome-dev-disk-* to media-optical icon.

@Feichtmeier can you test this PR please?

Closes #2351

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thanks for the PR
Tested the branch and sadly, it was not one of the icons you've symlinked
grafik

I search in humanity what this icon is

**Comment by Feichtmeier** [comment]
Maybe
`dvd-unmount`

**Comment by Feichtmeier** [comment]
grafik
It has to be one of these

**Comment by Jupiter007-43** [comment]
I linked all DVD and CD icons I found to media-optical.
Can you retry now?

**Comment by Feichtmeier** [comment]
Yay ! You did it ^^ 

grafik

**Comment by Jupiter007-43** [comment]
Great!

**Pull request merged**
