### PR TITLE
Test: update bionic from master

### PR DESCRIPTION
**Pull request by Feichtmeier**

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1836`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1836` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Could you help me understand how are you proceeding? Is it a merge from master or are you cherry-picking commits?
It could be a good idea to first port to bionic everything before my change to the folder organization, then import that alone and finally continue with the latest bits

**Comment by Feichtmeier** [comment]
:D 
Well, a bit hacky. Was to lazy to cherry-pick all the stuff we did so I've copied the whole icon folder from master, carefully copied _common, _drawing, _colors and _apps (but kept the nautilus desktop)
For the shell I couldn't copy anything I needed to change the code.

Is there a way to do this? Except cherry-picking a looooot of stuff?

**Comment by clobrano** [comment]
Is there anything you don't want to port? Otherwise a merge should be fine

**Comment by Feichtmeier** [comment]
Well the shell is really a problem because many things changed there but I could re-apply that then. Gtk and icons should be fine with a merge

**Comment by ubuntujaggers** [comment]
I have an item on my to-do list to make a Bionic PR for the latest icon changes, but if there's an easier way to do it, I am definitely up for that!

**Comment by Feichtmeier** [comment]
I will try what carlo said soon, this is too weird :D

**Pull request closed without merging**
