### PR TITLE
Icon theme fixed shadow

### LINKED ISSUE #3668: LP#1984167 "Some Yaru icons have bulging shadows"
Reported first on Launchpad at https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1984167

### PR DESCRIPTION
**Pull request by Jupi007**
**Before:**

Capture d’écran du 2022-08-11 12-20-26

**After:**

Capture d’écran du 2022-08-11 13-19-23

Closes #3668

### CODE REVIEW

**Comment by Amr-Ibra** [comment]
Hello, I think this fix has not been applied to the icons in the Yaru-* folders because I can observe the false shadow in the Nautilus icon from Yaru-blue.

**Comment by Jupi007** [comment]
Hi @Amr-Ibra 
Can you provide your Ubuntu version?

**Comment by Amr-Ibra** [comment]
yaru-theme-icon 22.10.3-1 on Debian testing.

**Comment by Jupi007** [comment]
Annoying, this mean Ubuntu 22.10 has been published without grabbing latest patches from master 😕

CC @3v1n0

**Comment by Amr-Ibra** [comment]
I believe that version 22.10.3 has the commits from master already:
https://github.com/ubuntu/yaru/commits/22.10.3
https://github.com/ubuntu/yaru/compare/22.10.3...master

And this MR did not touch the files in the icons/Yaru-* folders.

**Comment by eyelash** [comment]
Was this change really intended? I think the folders look kind of wrong with the shadow instead of the highlight.

grafik

**Comment by Jupi007** [comment]
I agree that this change was not indented, good catch @eyelash :+1:

**Pull request merged**
