### PR TITLE
Add gettext-translation-template icon

### LINKED ISSUE #2338: Missing icon translation template (text/x-gettext-translation-template)
Mimetype text/x-gettext-translation-template

Here is a proposal icon based on my previous html-template icon:

Capture d’écran du 2020-08-31 18-07-26

Related to #2334

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Capture d’écran du 2020-08-31 20-44-03

Closes #2338

Related to #2334

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
I really like this design :+1:  do you think it's possible to make the "A" box stand out more?

Also in the smaller sizes, if you use the blue guide lines as a reference, the pictogram is a tiny bit too high in 48px.

**Comment by Jupiter007-43** [comment]
I darken the A shadow, lighten the background and centered the 48px pictogram:

Capture d’écran du 2020-09-01 14-16-02

**Comment by Jupiter007-43** [comment]
In fact the lighten background and pictogram looks consistent so just darken shadow version:

Capture d’écran du 2020-09-01 14-23-16

**Comment by Jupiter007-43** [comment]
Adjusted version:

Capture d’écran du 2020-09-04 11-56-58

**Comment by Jupiter007-43** [comment]
Can I merge if you're OK with this version @ubuntujaggers ?

**Comment by fitojb** [comment]
The 16 and 24 versions are a bit busy; I’d tone down the graph-paper motif just a notch. In the bigger sizes, I’d make the lines a bit thinner.

**Comment by Jupiter007-43** [comment]
I agree with you about the 16 and 24 versions, but not for the largest size because it will looks blurry when resized by nautilus.

Capture d’écran du 2020-09-09 18-41-08

Is everyone Ok with this version?

**Pull request merged**
