### PR TITLE
WIP: Added fullcolor dialog-warning icon to status

### PR DESCRIPTION
**Pull request by madsrh**
WIP! This still needs some fine tuning. Could you work your magic @ubuntujaggers ?

Screenshot from Evolution:
image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
I could take care of this I think :thinking: 
But we use baseplates for status icons, so if you are okay with a square or a circle, I could do it @madsrh

**Comment by madsrh** [comment]
Oh, you don't want to keep the triangle? ⚠️

**Comment by Feichtmeier** [comment]
No, we don't use triangles for status :) The other danger icon with the "!" also sits on a circle :) (consistency police :policeman: )

**Comment by madsrh** [comment]
Okay, then it's easy copy and paste 👍 Feel free to fix it then.

But I think we should have a triangle shape anyway

**Comment by Feichtmeier** [comment]
Okay, if you think about adding a triangle baseplate, let's wait for @ubuntujaggers opinion and ideas on this

**Comment by clobrano** [comment]
Triangle and Circle have a different meaning IRL, circle is mandatory, triangle is warning. This is not real life, but it makes sense to keep this difference if possible

**Comment by madsrh** [comment]
> Triangle and Circle have a different meaning IRL, circle is mandatory, triangle is warning. This is not real life, but it makes sense to keep this difference if possible

I agree

**Comment by Feichtmeier** [comment]
The logic is unquestionable. It's just that we don't use triangle baseplates.
If you follow a design pattern and/or guidelines and break it too often, maybe you should think about different guidelines then. We only use none baseplate icons for devices. That's all I'm saying

**Comment by clobrano** [comment]
Let's adapt the guidelines to the logic that makes sense then, if it
doesn't work reject it

**Comment by Feichtmeier** [comment]
Hasn't this big fixed? 😆 
🍵 
Lol we are so lazy currently 🤣

**Comment by madsrh** [comment]
I can't check atm but yes. Did you create a separate issue for the icon? @ubuntujaggers will know 👼

**Comment by Feichtmeier** [comment]
Yes, here it is: https://github.com/ubuntu/yaru/pull/2143 👍 
Thanks @ubuntujaggers

**Pull request closed without merging**
