### PR TITLE
Add path-bar buttons without the .linked class to the new styling

### PR DESCRIPTION
**Pull request by Feichtmeier**
Don't remove it to keep 18.04 and gnome-staging 18.10 compatibility

_____

Eventually
Closes https://github.com/ubuntu/yaru/issues/1086

@iainlane could you please test this branch on your disco installation?

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1087`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1087` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by iainlane** [comment]
Thanks. It's better but still not as you were going for:

yaru2

The CSS rules from _common.scss:1679 are being used to draw the background, and the underlines on hover aren't being applied either.

**Comment by Feichtmeier** [comment]
Ah the .flat buttons
Could you try again @iainlane ?

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1087`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1087` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by iainlane** [comment]
noooo

yaru3

**Comment by Feichtmeier** [comment]
okay fuck it I need to install that nautilus from source, too
Or could you update the nautilus in disco? Then i set up a disco VM and look myself

**Comment by Feichtmeier** [comment]
nvm.... 

> To test this, you can install nautilus, ubuntu-settings and gnome-shell-extension-desktop-icons from disco-proposed. Take those packages only, and be sure to disable disco-proposed straight away after installing.

Brb

**Comment by Feichtmeier** [comment]
I make a new branch tomorrow @iainlane

**Pull request closed without merging**
