### PR TITLE
Remake shutdown icon

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
Now this icon looks in the same style as other icons.

system-shutdown-symbolic system-shutdown-symbolic-new

### CODE REVIEW

**Comment by clobrano** [comment]
screenshot from 2018-12-28 14-52-32

I'm the only one who thinks that suru icons look too thin sometimes? :D

**Comment by eaglersdeveloper** [comment]
What's wrong? The line width is 1px, as in all icons.

**Comment by clobrano** [comment]
That's what I meant. I wasn't criticizing this specific icon

**Comment by Feichtmeier** [comment]
I thought the same when trying it on my wife's pc
It's too thin!

**Pull request merged**
