### PR TITLE
Unity/sync

### PR DESCRIPTION
**Pull request by clobrano**
Sync Unity theme with current GTK/Shell Yaru, for what is possible.

### CODE REVIEW

**Comment by clobrano** [comment]
Some screenshoot

image
image
image

For some reason, you need to install light-themes to have fully functional shadows in windows and menus. 
Also, as you can see above, some application adds a titlebar above the headerbar, while others don't.
This happens in Nautilus, but it's worse in gnome-software, where the round left corner is even visible
image

I don't think this is due to Yaru, since happens with other themes too and quite interesting it happens under GNOME too if I switch to Ubuntu session without rebooting

I think I'll try to get into contact with people involved in Unity, but this can be reviewed and merged if you agree

**Comment by Feichtmeier** [comment]
Agreeing totally. Nice work!
I'm tempted to go back to unity now lol

**Comment by clobrano** [comment]
doh, I forgot to change the build script to install the assets

**Comment by fcole90** [comment]
How about removing the glossy effect on the Unity launcher? It makes it feel much more modern. I have seen other themes doing it, like Numix, doing it.

Example of a derivative here: https://www.deviantart.com/chrisfr06/art/Numix-Blue-GTK-Theme-Modded-without-Unity-boxes-450739876

image

**Comment by clobrano** [comment]
Indeed would be better. On my backlog now

**Comment by madsrh** [comment]
Looks good @fcole90 👍 Nice suggestion

**Comment by clobrano** [comment]
@fcole90, please have a look at #1676

**Pull request merged**
