### PR TITLE
Shrink gtk2 icon size in toolbars

### PR DESCRIPTION
**Pull request by Feichtmeier**
Closes https://github.com/ubuntu/communitheme/issues/579

Before:
image

After:
image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/communitheme-pr642`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/communitheme-pr642` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Paz-it** [comment]
@Feichtmeier , Thanks! :dancer:

**Comment by clobrano** [comment]
Aren't those icon a bit too small?
In GIMP pictures it is fine, but the toolbar might be less usable with small icons

**Comment by Paz-it** [comment]
@clobrano , When in use it looks like that : 
screenshot from 2018-07-22 13-45-23
(I hide the header-bars  - I worked to fine tune them in the dark theme but in the original not yet.)

**Comment by clobrano** [comment]
I know, I tested live. I guess it depends on screen size, on 23'' it is not that bad, but on 13'' it's very small

**Comment by Paz-it** [comment]
I changed :
 gtk-large-toolbar=16,16:
To : 
gtk-large-toolbar=18,18:
@clobrano  Is it better in small screen resolution?
screenshot from 2018-07-22 21-42-53

**Comment by clobrano** [comment]
I did not notice there was a difference between large and small toolbar. If that so why not keep large toolbar values as default? It's explicitly decided by the developer that a large toolbar is needed

**Comment by Paz-it** [comment]
I have nothing to say about it. I see a difference and I do it in  my configs for years and many other theme  designers do it as well.  My suggestion - Take it or live it.  Why? - Because it looks nicer saves space and I like it . It doesn't mean you have to like as well. Thanks for testing it.

**Comment by clobrano** [comment]
>  have nothing to say about it. I see a difference

You misunderstood. What I meant is that I did not notice at first that there were two different properties, one for small and one for large toolbars. So having a different size for `gtk-small-toolbar` and `gtk-large-toolbar` makes sense to me.

>  My suggestion - Take it or live it.

PRs are not take it or live it as you said (which is rude, btw), it's a proposal that can be discussed and adapted.

> Many people will appreciate it to be default.

I am sure

> It doesn't mean you have to like it as well.

As a matter of fact, yes we should consider it a valid change

> Thanks for testing it.

And thanks to @Feichtmeier who actually did the PR for you.

However, I don't see the change on GIMP settings icon as shown in [here](https://github.com/ubuntu/communitheme/issues/579#issuecomment-401628856), which I (and @madsrh) really like to have. I think I need to test it further

**Comment by Feichtmeier** [comment]
Yeah that one is missing! @Paz-it are the lines missing for the gimp toolbar? Click on "commits" and click on the one commit and then look at all lines which have a green background

**Comment by Paz-it** [comment]
@clobrano, 
I misunderstood and didn't have intention to be rude.I apologize!  Thanks to you both, @Feichtmeier , In my config the  two first lines are the last so may it's a case sensitive, I mean, sometimes the order do matter. :woman_shrugging: .. I refreshed to edge but let me go to pr642 again to see gimp.   I will update you when I get home soon.

**Comment by clobrano** [comment]
image

**Comment by clobrano** [comment]
Sorry, closed by mistake

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr642`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr642` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
I didn't drop this, I am only having some issue in testing gtk2 changes in Yaru. It seems that changes go to Communitheme folder under /usr/share, but not sure it's a problem in my system or something to open a bug about.

**Comment by clobrano** [comment]
@Paz-it the toolbar

image

**Comment by Paz-it** [comment]
@clobrano : That's my LibreOffice toolbar.. :thinking: 
screenshot from 2018-07-31 22-18-08
@Feichtmeier : - Of course you can. There is not much to understand in gtkrc. All you have to do is to play with sizes of the icons or just change one type of the toolbars and not the other and test to result.

**Comment by clobrano** [comment]
@Paz-it I guess it's the same with symbolic inverted icons. The point is that gtk3 toolbar has icons > 18x18 and I feel this is good. Of course it's my opinion, if there are more people (except the proposer :D) that like it I'll step back with no problem

**Comment by Paz-it** [comment]
18X18 for the large toolbar is fine with me. :) :+1:  ...and the rest can be 16x16. 
The proposer will be silent now. :smile:

**Comment by clobrano** [comment]
> So we agree @clobrano ,

Unless you don't want too reject your own PR, I guess you misunderstood me :D 
I am for keeping current master and reject this, sorry

**Comment by Paz-it** [comment]
I red it twice again and really misunderstood, wow! 
OK. I'll keep silent and wait for others to decide.  
Now it's up to you guys @Feichtmeier @madsrh @godlyranchdressing

**Comment by Feichtmeier** [comment]
Paz you don't know how many of "my" PRs were closed :) it's just the normal workflow here. 
Which line do I need to change for the toolbar and which line needs to be kept for the gimp optimization? I think the gimp icons are really too big.

**Comment by Paz-it** [comment]
@Feichtmeier, No problem with closing. When I said "take or live it" I meant just to say if you don't like it it's okay :D . No hard feelings. 
If you delete this  line : 
gtk-large-toolbar=
it will do it for you.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr642`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr642` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
@Feichtmeier, if the expected change is the one below, it looks good to me :+1: 

image

image

**Pull request merged**
