### PR TITLE
Added drop shadow to slider handle with mark

### LINKED ISSUE #277: Slider handle
The slider handle used for scales with tick marks, has a couple of **very** minor issues:

1. Unlike the other (square-ish) slider handle, it has no shadow
2. As its width is an even number, the point does not align with the tick mark. Perhaps it should be an odd numbered width?

The screenshot below shows a `xmag` capture of `gtk3-widget-factory`

screenshot from 2018-03-23 07-46-49

### PR DESCRIPTION
**Pull request by clobrano**
- assets.svg updated with drop shadow color #D3D3D3 alpha 1, 1px offset
    (verical or horizontal according to the mark direction)
- regenerated pngs with script render-assets.sh
- increased background-size to remove blurriness due to inkscape's
    dropshadow filter increasing assets size when adding the shadow.

closes #277 

thanks @godlyranchdressing!

before
image

after
image

EDIT: it seems that the picture does not show much difference, but there is  :D

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr679`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr679` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Very awesome! I bet you didn't do this all sober, did you? :dancer:

**Comment by Paz-it** [comment]
Awesome indeed! :dancer:

**Comment by clobrano** [comment]
> I bet you didn't do this all sober, did you?

It was easier than you think ;)

**Pull request merged**
