### PR TITLE
Extensions app icon

### PR DESCRIPTION
**Pull request by Feichtmeier**
- copied from application-x-addon
- extracted the PNGs
- symlinked to org.gnome.Extensions
- Add extensions app symbolic icon

Screenshot from 2020-02-27 16-18-42

ToDo:

- [x] render the symbolic icon correctly, I failed again - it looks like it's on the grid but it isnt't. 
@ubuntujaggers please fix :D

### CODE REVIEW

**Comment by madsrh** [comment]
Are you sure you want the mimetype icon and not a dedicated app icon?

**Comment by Feichtmeier** [comment]
Nope, I'm not sure :D
Any idea?

**Comment by madsrh** [comment]
> Any idea?

A very poor mockup. Imagine different colors ofc
image

or perhaps one piece inside a circle
image

**Comment by Feichtmeier** [comment]
I like the first idea!

**Comment by ubuntujaggers** [comment]
I'll do these tasks next because I still haven't worked out how to edit the text selection assets 👍

**Comment by ubuntujaggers** [comment]
@feichtmeier, @madsrh 

I've exported the symbolic.  Do you like this and want me to push to this branch:

extensions

?

Colours have gone a bit "off" because of the compression, but if I push it you can test :+1:

**Comment by Feichtmeier** [comment]
I like it :+1: 
Please push it

**Comment by ubuntujaggers** [comment]
I replaced a random app to test it, looks quite good IMO:

image

image

image

Again, colours are compressed, I'll send the files by chat :+1:

**Comment by Feichtmeier** [comment]
Are those colors from our palette btw?

**Comment by madsrh** [comment]
Could we try some other colors @ubuntujaggers ?

I don't think that these colors signals extension app. It looks a bit, IMHO, like a puzzle game 🧩

**Comment by clobrano** [comment]
What if we use a different color for one piece only? That might suggest the
idea of adding one more piece, that is extending the whole

**Comment by ubuntujaggers** [comment]
How about:

extensions

**Comment by madsrh** [comment]
Much better IMO. How about a darker blue or perhaps the green from the mimetype so there's a link between the two?

**Comment by ubuntujaggers** [comment]
> or perhaps the green from the mimetype so there's a link between the two

You're right, they should be consistent.  How about:

extensions 2

?

**Comment by madsrh** [comment]
Green light from me 😄

**Comment by ubuntujaggers** [comment]
Pushed the green one :+1:

**Comment by ubuntujaggers** [comment]
Pushed the green one :+1:

**Comment by friendlyapple** [comment]
This is a personal opinion but I am not a fan of the puzzle icon compared to other Yaru icons.

**Comment by Feichtmeier** [comment]
Maybe @ubuntujaggers could remove the highlights so the icon is basically only a baseplate plus the drawing on top? 
Maybe this helps

**Comment by madsrh** [comment]
> This is a personal opinion but I am not a fan of the puzzle icon compared to other Yaru icons.

@applefriendly Because of the style? Do you have something else in mind?

**Comment by friendlyapple** [comment]
@madsrh Yes. I don't find the icon as "clean" as the other Yaru icons with the "folded cardboard" effect.

I'm looking on Google for a style idea :)

**Comment by real-amano** [comment]
I guess it is much better than the mimetype icon from before and should be merged in time for Focal. Best is the enemy of better, I guess.

**Comment by friendlyapple** [comment]
@real-amano I also think that the mimetype icon is a bad idea. Now, I think we still have a little time to find an icon.

**Comment by friendlyapple** [comment]
Some ideas (simple icons):

*Click to zoom*

**Comment by real-amano** [comment]
The more I think about it the more I like the full colored version by ubuntujaggers.

Maybe we can tone that down a bit by turning just one piece Grey.

**Comment by Feichtmeier** [comment]
Yeah... let's just take this version we have in this branch.
@ubuntujaggers could you tone down the highlights? So it looks like the puzzle pieces are part of the paseplate rather than on top of it? Or make everything flat except one puttle on top of the others?
And then you would also need to push the recent source-symbolic :see_no_evil: because I am an idiot and merged the other PR before this one (sorry!!!)

**Comment by ubuntujaggers** [comment]
Will do, @feichtmeier

@friendlyapple, you always do very nicely executed svgs in the right style 👍

**Comment by Feichtmeier** [comment]
@ubuntujaggers could you make a new branch with your latest commit?

**Comment by ubuntujaggers** [comment]
Will do tonight, forgot we hadn't finished this 👍

**Pull request closed without merging**
