### PR TITLE
change emblem colors to palette colors

### PR DESCRIPTION
**Pull request by Muqtxdir**
hi, 

This will change a couple of emblem colors to match the palette colors (closes: #1858)

### Screenshots:
- **emblem-list-add** (before and after) 

add

- **emblem-default** (before and after)

default

- **emblem-shared** (before and after)

share

- **emblem-symbolic-link** (before and after)

symbolic

- **emblem-unreadable** (before and after)

close

- **emblem-danger** (before and after)

danger

- **emblem-photos** (before and after)

image

- **emblem-video** (before and after)

video

- **emblem-dialog-question** (before and after)

help

thanks!

### CODE REVIEW

**Comment by Jupiter007-43** [comment]
Nice work.
But should we use gradient for emblem icons 🤔

**Comment by Muqtxdir** [comment]
hi @Jupiter007-43,

I added gradient to **emeblem-photos, emblem-video** and **emblem-dialog-question** to keep it consistent with **image-mimetype** icon, **media-player** icon and **help-app** icon

**Comment by Jupiter007-43** [comment]
> is it against the icon guidelines to add gradient to emblems?

In fact, I really don't know what's our guidelines for emblems 😅, it's just that as there was no gradient before...
@ubuntujaggers what do you think of?

**Comment by ubuntujaggers** [comment]
You're right, emblems are normally flat because they're small. Do we have some examples of these gradient ones in a real context?

**Comment by Feichtmeier** [comment]
I didn't miss the gradients tbh

**Comment by Muqtxdir** [comment]
should I then remove the gradient from **emblem-photos** ,**emblem-video**,**emblem-dialog-question**?

**Comment by Feichtmeier** [comment]
Don't know - @madsrh @ubuntujaggers @Jupiter007-43 ?

**Comment by Jupiter007-43** [comment]
IMO emblems should be flat 😌

**Comment by Feichtmeier** [comment]
Thanks @Muqtxdir - ready to merge?

**Comment by Muqtxdir** [comment]
Removed the gradients and just pushed it 

remove-gradient-from-emblem

**Comment by Muqtxdir** [comment]
> Thanks @Muqtxdir - ready to merge?

yes

**Comment by madsrh** [comment]
Thanks for fixing this @Muqtxdir 👍

**Comment by Jupiter007-43** [comment]
Much better without gradients! Thanks @Muqtxdir 👍

**Pull request merged**
