### PR TITLE
Change the no-notification and no-events icons

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
Changed the no-notification and no-events icons to preferences-system-notifications-symbolic and appointment-symbolic icons respectively from Suru.
But in the notification bar remained old icons. Help wanted.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Great idea.

But I think the no notification icon is a bit misleading. Maybe just add a checkmark? Like 

No notifications
[X]

**Comment by clobrano** [comment]
@eaglersdeveloper could you explain first what problem this PR should fix :)?

**Comment by Feichtmeier** [comment]
Hmmm
Testing the newest cosmic at the moment (it has the yaru theme now by default after updating yay :dancer: )

Anyways,... gnome has updated the "no notifications" icon:

image

Can we close this then? I don't feel that the "no events icon" is that bad

**Comment by clobrano** [comment]
+1 to close it

**Comment by eaglersdeveloper** [comment]
@clobrano, current icons don't look in Suru style.

**Comment by eaglersdeveloper** [comment]
I didn't see an operating system, in which in some hidden place there were old icons.

**Comment by eaglersdeveloper** [comment]
If you are doing a redesign, you should take care that the remnants of the old design aren't preserved.

**Comment by Feichtmeier** [comment]
@eaglersdeveloper 

But the new upstream icon is pretty neutral to our icon theme and an improvement over the current.
Maybe you could limit the PR to the no event icon only and update your initial, pretty confusing post :D 

- what is the state of this PR, would it be ready to merge?
- for what do you need help as you said "help wanted"

How about we close this and you open a dedicated issue where we track this down. I think opening PRs without issues is OK as long as you come up with a solid solution and description

**Comment by clobrano** [comment]
> you are doing a redesign, you should take care that the remnants of the old design aren't preserved.

We aren't redesigning every single bit though. 
I agree with @feichtmeier, either you open a bug explaining what's the issue and say what you can and what cannot do, or open a clear PR which we are needed only for review it

**Comment by clobrano** [comment]
Closing this now, waiting for a PR/BUG that follows [this](https://github.com/ubuntu/yaru/pull/720#issuecomment-414409572) indications

**Pull request closed without merging**
