### PR TITLE
Improve selected row look

### LINKED ISSUE #2954: Global row selection is problematic
The row selection for nautilus and apps with similar layout works.

However it does not work well globally because those rows can be everywhere
grafik
(portal)

grafik
(gnome software)

@Jupi007 do you have any idea how we can limit this to nautilus and gnome control center?

### PR DESCRIPTION
**Pull request by Jupi007**
Improve selected row look:

- Remove the little orange left stripe (except on Nautilus sidebar) ;
- Increase bg contrast.

Capture d’écran du 2021-07-20 19-42-49

Capture d’écran du 2021-07-20 19-43-18

Closes #2954

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Looks good!
How does it look in GCC and the portal app now?

**Comment by Feichtmeier** [comment]
I like it, but let the others check 👍

**Comment by clobrano** [comment]
I understand the problem for #2954, but I think all the selections must be the same, nautilus included

**Comment by Jupi007** [comment]
@clobrano So maybe drop the orange stripe, and make all selections using this soft grey bg (even listviews)?

**Comment by madsrh** [comment]
>  So maybe drop the orange stripe, and make all selections using this soft grey bg (even listviews)?

IF we do that, could we make both have rounded corners? Maybe with slightly more padding to the sides

**Comment by Jupi007** [comment]
> IF we do that, could we make both have rounded corners? Maybe with slightly more padding to the sides

I'd like to say yes because it could look better. But less diff with upstream = less problems.
The rounded corners selected list row is a different widget, which have bigger row + margin + rounded corners.
The only place where we could be able to force border-radius is on nautilus sidebar because it has less scope, and that couldn't brake anything else.

**Comment by Jupi007** [comment]
Rounded corners on nautilus selected row:

Capture d’écran du 2021-07-21 12-17-08

**Comment by clobrano** [comment]
> @clobrano So maybe drop the orange stripe, and make all selections using this soft grey bg (even listviews)?

unfortunately yes :(

**Comment by Jupi007** [comment]
No problem, I'll do it :)

**Comment by Feichtmeier** [comment]
If we remove the stripe, I would keep it simple for now and play safe with the regular gray row, without a border-radius.

**Comment by Jupi007** [comment]
Grey selected row everywhere:

Capture d’écran du 2021-07-26 12-20-37
Capture d’écran du 2021-07-26 12-22-39

**Review by Feichtmeier — APPROVED** [review]
Looking good ☺️

**Pull request merged**
