### PR TITLE
DON'T MERGE - Test PR with five size versions of non-uniform Suru icons

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Try the snap and let me know what you think!

image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Pulled the branch! Looks fantastic:
screenshot from 2019-02-13 09-40-48

I would still love to kill off the squircles again though :man_shrugging: Why keep them? I think 4 sizes is really enough. What's funny is:some icons already look much better with a different form and remind more of the real life pendant they should remind of (rhythmbox>speaker, backups>safe)

**Comment by ubuntujaggers** [comment]
> What's funny is:some icons already look much better with a different form and remind more of the real life pendant they should remind of

**Comment by ubuntujaggers** [comment]
@Feichtmeier, your file manager icon:

image

image

image

48px svg needs tidying up a bit...

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
Here's the non-uniform icon set so far, mixed in with a few of the ones that I'd like to keep as squircles if we give ourselves that option.

48px:

image

256px at 50%:

image

**Comment by Feichtmeier** [comment]
You are on 🔥
The previous nautilus you made was using your baseplate right? I think that looked better
And my personal problem with the Suru squircles is that the border radius is different than the radius of the other two types

**Comment by ubuntujaggers** [comment]
> The previous nautilus you made was using your baseplate right? I think that looked better

We can make a new nautilus based on the first one  👍

> And my personal problem with the Suru squircles is that the border radius is different than the radius of the other two types

Yeah, that difference has always been part of Suru (apps versus mimetypes/recycle bin) but maybe it looks weirder when it's within apps.  Well, we can carry on making new icons and see if we end up redoing all of them, we've got a while before 19.04  :)

**Comment by Feichtmeier** [comment]
Found this sweet snap shopping bag on the Ubuntu Twitter page:
screenshot_20190213-183302_samsung internet

Not the circle but the bag itself looks cool :) just for inspiration

**Comment by ubuntujaggers** [comment]
Got a couple more, I'll soon update the list:

**accessories-address-book** - nice and simple and looks great in this shape:

image

**power-statistics** - ditto:

image

**log-viewer-app** - IMO I've never been keen on the Suru one for this, it's identical to docviewer-app without the letter "A" and is one of multiple icons that all say "click here to look at some docs" without giving you clues as to how they're different.  So, just an experiment, but I put some perforations in the paper to make it look like something a machine would spit out:

image

**preferences-system-network** - this is under categories rather than apps, but we need to do it because it shows up in the app grid:

image

**Comment by Feichtmeier** [comment]
Can't wait to test it :tada: That looks _really_ good!

**Comment by ubuntujaggers** [comment]
> Can't wait to test it  That looks _really_ good!

Unless there are any problems, soon you will be able to try all the icons  :)

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
In terms of having some squircles or no squircles, obviously I will draw whatever's decided, but here's a little bit of food for thought: third party icons will all have different amounts of rounding (including none) on the corners.  IMO this mix looks nice and organic/natural:

image

LO, lang settings and image viewer are all a bit different so none of them looks wrong.  Similar here:

image

Also: where does general design chitchat about these icons go now?  Here or in the issue?  Is the issue purely for admin/tracking work?

**Comment by ubuntujaggers** [comment]
I'm using it myself now, I think logs has come out really nicely with the holes down the sides.

**Comment by Feichtmeier** [comment]
General chit chat is fine here! 

Yes logs looks better this way.

I don't know if it's just the squircle discussion burned into my memories or is really this way or if I only need more time but currently I would vote for ditch the old squircles and replace their baseplate with one of your 4 new. But let's get some more opinions on that!? @madsrh @clobrano

**Comment by clobrano** [comment]
I agree on ending the squircle. The direction is different and better go on.

**Comment by ubuntujaggers** [comment]
> 
> 
> I agree on ending the squircle. The direction is different and better go on.

Just @madsrh to comment, but I feel the pendulum is swinging away from me  :)

**Comment by ubuntujaggers** [comment]
> here is a "mix-Yaru-icons-with-third-party-apps"-screenshot

@Feichtmeier, what size launcher do you have?  For some reason you're getting the 256px versions instead of the 48px versions.  But they look pretty good, so that's heartening to see in terms of eventually switching to one svg  :)

**Comment by madsrh** [comment]
> Just madsrh to comment, but I feel the pendulum is swinging away from me :)

I deliberately didn't comment, because I don't have a strong opinion about this - yet. I can't take such decisions with any mockups 😆 No, seriously I'm neutral here.

**Comment by ubuntujaggers** [comment]
Do we have the svgs for @eaglersdeveloper's software icons?  Whatever happens to the background, we could reuse the pictograms and colour scheme/gradients...

**Comment by Feichtmeier** [comment]
Not until he has committed his work here :)

**Comment by taciturasa** [comment]
Just to butt in - upstream made a conscious decision to not use a folder icon for nautilus since it could cause confusion with an actual folder, even with a color difference. I would recommend looking into using the same file cabinet pattern the new icon uses, or to adding some sort of special signifier like the folder holder on the Windows Explorer icon.

**Comment by taciturasa** [comment]
(Also, I am also all for removing the squircle entirely - internal icons should keep a consistent curve design if we're going mixed shape, imo, esp. since the smaller curves and the larger ones have a very different feel to them.)

**Comment by ubuntujaggers** [comment]
> 
> 
> Just to butt in - upstream made a conscious decision to not use a folder icon for nautilus since it could cause confusion with an actual folder, even with a color difference. I would recommend looking into using the same file cabinet pattern the new icon uses, or to adding some sort of special signifier like the folder holder on the Windows Explorer icon.

Fair point - I'll have a go at doing a filing cabinet when I get chance for discussion (anyone else feel free to have a go too).

**Comment by ubuntujaggers** [comment]
Tonight's haul:

**Amazon**

image

**Apt daemon downloader**

image

**Disk app**

image

**Possible e-book reader app**

image

**Alert**

image

**Comment by ubuntujaggers** [comment]
**Calendar**

image

**Comment by ubuntujaggers** [comment]
First attempt at different shape disk utility suggested by @madsrh:

image

**Comment by Feichtmeier** [comment]
Wow that looks like a real disk! Nice

**Comment by ubuntujaggers** [comment]
This one is in "categories" (not "apps") but shows up in the app grid and has a squircle icon in Suru:

**locale preferences**

image

Also finally tackled a couple I wasn't really looking forward to because they have a lot of elements 😛 

**mail**

image

**maps**

image

**Comment by ubuntujaggers** [comment]
I can't even see a bloody maps app in the software centre!!  Typical!!  :rofl:

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
Couple of screenshots, you should have the snap soon for testing...

**Default launcher so far:**

image

**Some of the new icons on app grid:**

image

image

**And on launcher:**

image

**Comment by ubuntujaggers** [comment]
E-book reader needs more work now I've seen it live.

**Comment by Feichtmeier** [comment]
Kinda funny how  all icons look better with the new shapes :dancer: 
If you are at simple-scan: could we think of an icon redesign? I kinda messed up eaglers idea back then and commited it but the pcictogram itself looks too small this way

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
Loads of new non-uniform icons pushed tonight - not many left to go!

image

image

image

image

image

**Comment by ubuntujaggers** [comment]
> I kinda messed up eaglers idea back then and commited it but the pcictogram itself looks too small this way

@madsrh had a mockup for scanner that I'll try.

I hated the new e-book reader icon so for the time being have done one based on the Suru icon, but making the red lighter so it isn't as stark:

image

image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
More and more icons in this test branch - if you look at the issue we're nearly done:

image

Very few squircles left in the app grid now:

image

image

image

You might notice I've taken this opportunity to experiment with a new design for Mines.  It's not perfect yet but I think it's better.  It actually captures the theme of the game, where the mines are meant to be naval mines (hence spiky balls).

**Comment by Feichtmeier** [comment]
@ubuntujaggers thank you very much!
Could you try the horizontal square for the screenshot tool? A typical desktop nowadays has 16:9 or 16:10 so I think this might fit better :)

**Comment by ubuntujaggers** [comment]
I was fifty fifty on screenshot, I tried square first because it meant I didn't have to reshape the pictogram :) I will try horizontal later to do a comparison. Also have files and software to try different things for. But at this rate I think we will have a pretty solid complete set within a few days.

**Comment by madsrh** [comment]
@Feichtmeier I think it's more about the selection size than the screen size and IMHO it just looks odd with 16:9 - ofc we can always give it a try 😁

@ubuntujaggers could you try to add the symbolic image like this?
https://goo.gl/images/FxDV7T

**Comment by ubuntujaggers** [comment]
@madrsh, as in put something inside the selection?  Yep, we can try that too  :)  And for the oblong version I'll reshape the pictogram a bit if that helps.

Talking of aspect ratios, videos is much better as an oblong so I'm about to push:

image

image

I changed the fold direction on to-do because vertical works better on the tall oblong for this design, imo.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
I just meant that we could use that horizontal shape jaggers uses. Instead of the square. I didn't mean real 16:9...

**Comment by ubuntujaggers** [comment]
@madsrh, attempt at your scanner mockup:

image

image

I think the doc might look a little small...  maybe just put the red line on the docs icon with no surround?

**Comment by ubuntujaggers** [comment]
image

image

??

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Thanks for the updates, @ubuntujaggers ! 

I think the laser should not leak out of the baseplate, or the laser needs to be placed anywhere else but currently it remind me a little bit of the game pong when the active window indicator in the dock sits right upon the edge of the laser xD
image

**Comment by ubuntujaggers** [comment]
Pushed a version that stops at the document edge...

**Comment by madsrh** [comment]
> madsrh, attempt at your scanner mockup:

Not my best idea 🙈 Here's another idea:

image

**Comment by ubuntujaggers** [comment]
> Not my best idea

I don't think I did it very well tbh!  I like the idea of having half of the document dark, I'll take another pass at that.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Speaking of circular webbrowser icons; why didn't [this one](https://www.omgubuntu.co.uk/2017/01/ubuntu-web-browser-app-icon) make it?

**Comment by ubuntujaggers** [comment]
> Speaking of circular webbrowser icons; why didn't [this one](https://www.omgubuntu.co.uk/2017/01/ubuntu-web-browser-app-icon) make it?

Yeah, I loved that icon  :)  I think it slipped between the cracks because it wasn't formally added before Unity 8 and Ubuntu Touch were cancelled?  I really like the symbolism and also the shadow (which we wouldn't have if we just used the pictogram).  If anyone knows where the svg is I'd gladly take it for Yaru.

**Comment by Feichtmeier** [comment]
@ubuntujaggers about the software updater - how about we come back to the humanity design ideas for that one - since we have a circle shape now?
image

**Comment by ubuntujaggers** [comment]
This needs a tiny bit more definition but I don't think it's a bad start:

image

image

**Comment by ubuntujaggers** [comment]
image

image

??

**Comment by Feichtmeier** [comment]
Hmmm could you commit it? I might have an idea for it - I could try to change your SVG, post it here, so you change it "for real" xD

**Comment by ubuntujaggers** [comment]
@Feichtmeier committed...  this commit also includes a first attempt at the paper bag software centre:

image

image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
I think the bag needs the background taking off...

**Comment by madsrh** [comment]
> ...a first attempt at the paper bag software centre

Yes! "The return of the bag" I love it 😃 

> I think the bag needs the background taking off...

+1

@ubuntujaggers  Perhaps if you can make the bag handel like [this one](https://cdn.dribbble.com/users/137405/screenshots/2735878/2.jpg) it can fit (or almost at least) inside the shape.

**Comment by Feichtmeier** [comment]
Wow! Never mind, saw the smaller sizes and imho that's really good @ubuntujaggers :tada: 
I just thought that the arrows should stay inside the circle but we could make an exception for the good here? (the "rule" that the pictogram does not leak out of the baseplate)

**Comment by Feichtmeier** [comment]
Hmmm maybe we should not make it leak out of the baseplate. I brought it up but maybe it was a bad idea. When you comare it to the other circles it is smaller 
image

**Comment by ubuntujaggers** [comment]
Hmm, I think it looks sensible when it's next to normal circle ones in a real context:

image

Here at 50px:

image

It _is_ slightly bigger because the idea was that the arrows are like an emblem that go on/around the normal circle baseplate:

image

...but we can also try resizing it or a few different ideas.

Work on paper bag:

image

image

**Comment by Feichtmeier** [comment]
Could you try to cut at the very edge of the baseplate circle? Sorry for be so annoying 
screenshot_20190219-085001_samsung internet

**Comment by ubuntujaggers** [comment]
Not annoying at all  :)  I'll do it when I get home tonight.

**Comment by ubuntujaggers** [comment]
@Feichtmeier:

image

image

??

**Comment by Feichtmeier** [comment]
I like it - maybe the A is too big now but let's wait for @madsrh and/or @clobrano

**Comment by ubuntujaggers** [comment]
@madsrh 

image

image

??

**Comment by madsrh** [comment]
@Feichtmeier I perfer the arrows outside like:

https://user-images.githubusercontent.com/38893390/52979619-5858b980-33ce-11e9-80a8-4eec7f42e1ad.png

**Comment by clobrano** [comment]
Simplescan is very good. About updater I'm a bit torn, but probably it's better to keep the standard circular shape and inside arrows

**Comment by madsrh** [comment]
> probably it's better to keep the standard circular shape and inside arrows

Okay, I really thinks the half arrow looks odd. Would it be possible to do something like this @ubuntujaggers

https://banner2.kisspng.com/20180312/qyw/kisspng-circle-arrow-vector-circular-arrow-5aa66c5a363a60.2917129915208561542221.jpg

Or with some spacing:

https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRUAE8fXh-eK-hDTqQ0xHrtpb5Vk8MozdCD90sKJqid-lWj5_Sz

**Comment by ubuntujaggers** [comment]
> Okay, I really thinks the half arrow looks odd. Would it be possible to do something like this @ubuntujaggers
> 
> https://banner2.kisspng.com/20180312/qyw/kisspng-circle-arrow-vector-circular-arrow-5aa66c5a363a60.2917129915208561542221.jpg
> 
> Or with some spacing:
> 
> https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRUAE8fXh-eK-hDTqQ0xHrtpb5Vk8MozdCD90sKJqid-lWj5_Sz

Yep, I'll give it a shot  :+1: 

In terms of software centre, I'm working on this remix of the one from Plane and we're talking to the maintainer wfpaisa about it:

image

**Comment by ubuntujaggers** [comment]
Guys,

I'm really happy with this one, what do you think  :)

image

image

image

image

**Comment by ubuntujaggers** [comment]
...and here's the latest default launcher:

image

**Comment by ubuntujaggers** [comment]
I just had to reboot my laptop and the software store icon makes a great impression when I first see it  :)

@madsrh @clobrano @feichtmeier:

image

image

??

**Comment by madsrh** [comment]
Wow, you really work fast @ubuntujaggers 💪

I definitely prefer this one over the cropped arrows

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
Okay, I've ticked all the boxes in the issue except for:

Remmina - this has never had a Suru icon.

Transmission - this has never had a Suru icon and I think some people were upset when I tried to make one (to be fair it was early days for me and it was pretty rubbish).

Startup applications - this has never had a Suru icon, is it a thing?  I can't find it.

There are also some Suru icons that aren't on the list, but I've become a little bit relaxed about these since I discovered that not all of them have an app in Ubuntu.  I think this is because they were inherited from the phone?  There are some squircle apps for preferences and I did some good designs for almost all of them, but there's no corresponding app and I can't get the Suru icons to appear in desktop Ubuntu (the preferences options mostly just have the Settings icon when you navigate to them through the shell).

So...  if the core icon set isn't finished, I think it's very very close  :)

However, we still have some that we may want to improve (I know not everyone was thrilled by the file manager icon, for instance).

I'm going to make a fresh install of Ubuntu on my other laptop and not install or change anything except for cloning and building this branch.  Then we can see exactly how Ubuntu will look out of the box.

**Comment by ubuntujaggers** [comment]
Fresh install:

image

image

image

image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@ubuntujaggers thank you for the new icons!

The software updater could be a perfect match, apart from the quiet large A
Ubuntu software looks very nice but imho it diverges from the other icons quiet strong. That thread looks very realistic and I think we have no other icon that looks this way, but it is surely very nicely made!

**Comment by ubuntujaggers** [comment]
I thought the string was the best bit!!  (I can say that without being vain because I didn't draw it :smile:  ).

In that case, how about:

image

image

I personally prefer the original string, and I don't think it's more realistic that the glasses on doc viewer and the magnifying glasses on various.  **But** if you like the bag we can work on a handle that everyone's happy with  :)

**Comment by ubuntujaggers** [comment]
I found/desquircled the icon for startup apps, it was called "session-properties" for some reason.  So, we've now got a clean sweep on pre-installed apps  :)

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
You know that I am always very positive about changes 😆  but I am really not a fan of this iteration of a shopping bag :(
Maybe we could put the A instead of that arrow? 🙈

**Comment by ubuntujaggers** [comment]
Do you like this change better  :)

Made the "A" a little less "crowded" and got rid of the thin leg:

image

image

**Comment by ubuntujaggers** [comment]
> You know that I am always very positive about changes laughing but I am really not a fan of this iteration of a shopping bag :(
> Maybe we could put the A instead of that arrow? see_no_evil

Okay, we've got three elements in play with this one:

- The bag
- The handle
- The symbol

Are there any bits you'd keep?

**Comment by Feichtmeier** [comment]
It is just me - maybe mads or carlo or eaglers want to share their ideas, too ?

Maybe we could use your previous icon, fold the handle down so it is inside the baseshape
image
And then use one of the new standart baseshapes you've defined?

**Comment by ubuntujaggers** [comment]
We have to get it spot on because it's such an important icon, so even one vote against is too many IMHO for this one.

**Comment by ubuntujaggers** [comment]
> Maybe we could put the A

image

image

?

**Comment by Feichtmeier** [comment]
The top part with the dark fold and that thread-handle still makes my brain think that it is a different icon theme. Could you try to remove the dark fold plus using your origami handle you used in your old bag icon?
(Again: sorry for being so picky and annoying 🙈 )

**Comment by ubuntujaggers** [comment]
image

image

??

I've also been trying some versions with the paper handle but I haven't made it work yet.

**Comment by ubuntujaggers** [comment]
Paper handle on the largest size:

image

**Comment by ubuntujaggers** [comment]
...and a bit of the same detail on the smaller version:

image

**Comment by ubuntujaggers** [comment]
Default launcher with this version:

image

...and in shell search results:

image

...and just in shell with other icons:

image

Any takers?  :)

**Comment by Feichtmeier** [comment]
Ah that's better :) I like it - @madsrh @clobrano ?

**Comment by ubuntujaggers** [comment]
Should we stick the "A" on the globe between them for software and whatever-it-is?  I don't know what the symbolism means for that one in its current form...

**Comment by Feichtmeier** [comment]
I actually thought the same. The globe is completely detached from what the app does (apart that the app connects to the internet? 🌐 xD) 
I think eaglers had it right when he used the A with three different tiny emblems on it

**Comment by ubuntujaggers** [comment]
Okay, what do you think of this - all three icons have exactly the same size and position "A":

image

image

Default launcher:

image

**Comment by Feichtmeier** [comment]
Looks pretty awesome imho

You changed the baseplate for the software icon to have a higher length than height, right? 
Since this already works, might be worth checking if it fits into the baseplate cheese uses

**Comment by ubuntujaggers** [comment]
> Looks pretty awesome imho
> 
> You changed the baseplate for the software icon to have a higher length than height, right?
> Since this already works, might be worth checking if it fits into the baseplate cheese uses

I couldn't quite make it work with the standard baseplate and have the same size/position as the circular ones  :(  but I'll have another look.

**Comment by taciturasa** [comment]
Maybe the arrows on the software update can be made a tad bit thinner? the
A still looks a bit crowded.

**Comment by clobrano** [comment]
I like more the later shopping bag iteration. Maybe because the previous was the only 3D icon in the set and looked out of place

**Comment by ubuntujaggers** [comment]
Improved Mines icon with more definition:

image

**Comment by ubuntujaggers** [comment]
I just saw that mpt put a heart on the latest mockups in the forum thread, which I take as a good sign!

**Comment by ubuntujaggers** [comment]
I've just pushed the current versions of the software icons.  Also did a little work on the smaller software-store sizes so they have similar proportions to the larger icons:

image

**Comment by ubuntujaggers** [comment]
> Maybe the arrows on the software update can be made a tad bit thinner? the A still looks a bit crowded.

I'm not ignoring this - I had a play today but don't have a new version that looks good yet!

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
This looks so good @ubuntujaggers good job!!!
screenshot from 2019-02-22 08-27-07

**Comment by madsrh** [comment]
Sorry for being totally afk for some day. This looks great @ubuntujaggers :tada:

IMHO the` Software & Updates` 🌐 still needs some work.

**Comment by eaglersdeveloper** [comment]
Why didn't you remove Rhythmbox and Shotwell icons?

**Comment by eaglersdeveloper** [comment]
By the way, you can use my Messages, Settings and Music icons.

**Comment by Feichtmeier** [comment]
The shotwell maintainer likes our icon and agreed to ship a Yaru icon.
Rhythm box should be indeed asked

**Comment by ubuntujaggers** [comment]
> Sorry for being totally afk for some day. This looks great @ubuntujaggers tada
> 
> IMHO the` Software & Updates` globe_with_meridians still needs some work.

Tbh I agree, I don't think it's worse than the current Suru one but it's not great or intuitive.

How about this:

image

image

??

**Comment by ubuntujaggers** [comment]
...and how about the same grey for the grey ones:

image

**Comment by Feichtmeier** [comment]
This looks also good, but I think I would prefer the globe+A. Looked a bit cleaner and less busy. But this is also totally fine

**Comment by ubuntujaggers** [comment]
> By the way, you can use my Messages, Settings and Music icons

We sort of went with non-squircle backgrounds instead of no backgrounds...  would you be willing to reconfigure Messages and Music with the new base shapes?

**Comment by Feichtmeier** [comment]
Organizational question:
@clobrano @ubuntujaggers why can't we - when it is ready - merge this branch? Too man new symlinks in the first commit?

**Comment by ubuntujaggers** [comment]
I think I shouldn't have run the symlink script at all in retrospect. All the symlinks were already pointing at the correct source files, I think I just got the names wrong for some of the earliest ones and all the new icons since then have "just worked". It would be a quick job for me to make a branch without all the symlinks, I'd just have to clone master and then add the chosen svgs and run the PNG script only.

**Comment by Feichtmeier** [comment]
Aright! :)

**Comment by madsrh** [comment]
I love the new icons :tada: 

> Software settings is for setting up ppas or other software sources + drivers

The [software globe](https://github.com/ubuntu/yaru/pull/1181#issuecomment-465660341) is still the best suggestion IMHO, but why a globe? It doesn't really illustrate that this is for settings 🤷‍♂️
Not the best solution, but hopefully you can see the idea in this mockup:

image

**Comment by madsrh** [comment]
@ubuntujaggers What about this?
software-mockup

**Comment by taciturasa** [comment]
@ubuntujaggers I really like this idea! But I'd perhaps lose the outline and make the gear background much larger. As mads said, it's kinda cluttered.

**Comment by ubuntujaggers** [comment]
First attempt at @madsrh mockup:

image

image

image

image

**Comment by ubuntujaggers** [comment]
Trying some big gear versions of software-properties tonight - bizarrely they all look worse/more busy than the one with the border.

**Comment by ubuntujaggers** [comment]
I know we want to keep chipping away at some of these icons, but if we put Messages on a square backplate I think we've pretty much got a clean sweep and our initial icon set.  Does anyone feel like we're ready to make the change, and carry on making improvements to the icon set as part of Yaru, rather than working on an experimental side-branch?

**Comment by madsrh** [comment]
> Does anyone feel like we're ready to make the change, and carry on making improvements to the icon set as part of Yaru, rather than working on an experimental side-branch?

**Yes** 😃 Although I wish the guys at Canonical (@8none1 @matthewpaulthomas) would give this new direction their "blessing". After all, they have the final word.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1181`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1181` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
Just pushed the latest version of the icon set including changes to the software icons and (for now) the pedal bin.

**Comment by ubuntujaggers** [comment]
...and I've put the latest screenshots on the forum in case it prompts any responses  :)

**Comment by 8none1** [comment]
The icon preview here:
https://github.com/ubuntu/yaru/pull/1181#issuecomment-463249903
Is very useful!

And the community hub post was indeed helpful.

Since you asked, here's my 2 cents:

The pedal bin is somewhat unclear.  I know what it is, but mainly from reading this thread.
I dont have any better ideas though.

The "Software and Updates" icon is somewhat unclear.  But again, no better ideas.  We really need to get the truncating text issue fixed though :)

However - the whole direction is great.  I really like the icons and I think anything I've mentioned above it just nit picking.

+1 to proceed from my end.

**Comment by clobrano** [comment]
I think we've made this transition clear enough, I take the silence as a good sign 😀 
I'm not sure about the gear icon, but usually @ubuntujagger surprises me, so I'll wait

**Comment by ubuntujaggers** [comment]
@8none1 That's brilliant news, thank you!

Agree on both you points - we still have some creases to iron out  :)

**Comment by ubuntujaggers** [comment]
In terms of admin:

- Do we have all the current (forked) Suru icons saved off somewhere in case there's widespread uproar?

- Do we want one PR per icon (@clobrano?) or can I just make a final branch with a) third party apps removed and b) all the non-uniform app and category icons added and c) no new symlinks and submit a PR for that?

**Comment by clobrano** [comment]
We can tag this repository so that it would be easier to recover forked suru icons. 
Since we have already agreed on most of the icons, we can just make 1 PR for the whole transition 👍

**Comment by ubuntujaggers** [comment]
All default apps so far at 48px:

image

**Comment by Feichtmeier** [comment]
Ah there are conflicts now because icons/src/scalable/source-symbolic.svg was changed in between your PR

**Pull request closed without merging**
