### PR TITLE
Removing Gnome Software symlink and providing a dedicated icon

### LINKED ISSUE #2144: Dash: same icon for snap-store and gnome-software
Hi,
By default Ubuntu 20.04 ships with **snap-store**. The classic **gnome-software** is still available.
If both are installed the dash shows same icon and label _Ubuntu Software_:

dash_50

Of course this is confusing.

No problems with the dock-bar. Each software shows a different icon and label (_Snap Store_ and _Ubuntu Software_):

doc_70

Cheers!

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Hi all,

Could those of you who have two identical software icons please see if you like this branch:

image

image

image

Closes #2144

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
Additional: the pictogram is a flat design - let me know if you think it needs a drop shadow on the blue circle.

**Comment by real-amano** [comment]
I like it. But compared to the other icons in the dock it looks "sharper". Is that just me?

grafik

**Comment by clobrano** [comment]
Before
Screenshot-20200428223830-1920x1080
After
after

also, symbolic icon is different, the "A" for gnome, and a desaturated yaru icon for ubuntu software

@real-amano, to me, it looks brighter, not much sharper, but it might be the screen or the impression

**Comment by ubuntujaggers** [comment]
Hi @Carlo, I believe I removed the symlink for the symbol (although I just realised I need to update the symbolic symlink list) do you still get the wrong symbol if you sudo rm the Yaru icons and do ninja again?

**Comment by clobrano** [comment]
Now gnome software has the "bag" symbolic icon
image

but ubuntu-software has its desaturated icon
image

**Comment by clobrano** [comment]
@ubuntujaggers can I merge this?

**Comment by ubuntujaggers** [comment]
Yes sorry, and if it says "delete branch?" feel free ,👍

**Pull request merged**
