### PR TITLE
Add Chess icon

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
New icon for GNOME Chess:

chess-app

### CODE REVIEW

**Comment by eaglersdeveloper** [comment]
Please, don't merge now

**Comment by madsrh** [comment]
Didn't @ubuntujaggers work on a chess icon?

**Comment by ubuntujaggers** [comment]
I was working on some designs with a chess piece and just couldn't get it to quite work at all sizes - I think this chessboard is iconic enough to stand for chess without a piece on it, and the greys are from the Suru palette.  Also I think this one was accepted upstream  :)

**Comment by Feichtmeier** [comment]
So, @eaglersdeveloper why can't we merge it, Jaggers is okay and peeps like it?

**Comment by eaglersdeveloper** [comment]
I wanted to experiment with the icon, but if you like it, you can merge.

**Comment by Feichtmeier** [comment]
Nono take your time

**Comment by Feichtmeier** [comment]
@eaglersdeveloper are you still working on this?

**Comment by Feichtmeier** [comment]
@eaglersdeveloper are you still working on this? Or shall we merge it?

**Comment by eaglersdeveloper** [comment]
Users might think that this is Сheckers, not Сhess.

**Comment by Feichtmeier** [comment]
What about this one https://github.com/snwh/suru-icon-theme/issues/102#issuecomment-430611274
By @ubuntujaggers

**Comment by ubuntujaggers** [comment]
Possibly the chess piece on @eaglersdeveloper 's background? I wasn't very happy with the piece at smaller sizes, but the top three at least look okay on my phone..

**Comment by Feichtmeier** [comment]
What if you symbolise one of the chess figures from above instead of from the front?

**Comment by eaglersdeveloper** [comment]
OK, merge it. I have no ideas.

**Comment by clobrano** [comment]
Considering what said, this PR is not ready for merging. Closing it for now, do not delete the branch so you can reopen it if you want

**Pull request closed without merging**
