### PR TITLE
Add icon for mimetype ROM files (consoles)

### PR DESCRIPTION
**Pull request by madsrh**
No fancy icon design here. I simply took the controller icon 🎮  from `source-symbolic.svg` to use for the following roms:

**Nintendo:**
 NES ROM (application/x-nes-rom)
 Nintendo DS ROM (application/x-nintendo-ds-rom)
 Nintendo64 ROM (application/x-n64-rom)
 Game Boy ROM (application/x-gameboy-rom)
 Game Boy Advance ROM (application/x-gba-rom)

**Sega:**
 Sega Master System/Game Gear ROM (application/x-sms-rom)
 Genesis ROM (application/x-genesis-rom)

I've added the symlinks in the `mimetype.list` but I couldn't make the script run without fail 😩  This means that the symlinks aren't applied.

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Okay .gb works :) But your GEDIT trick didn't. So I got one from a super legal source...
image

.nds files don't work (guess because of the symlinks?)

Let me check to make the symlink
Yup worked with carlos fancy script change
image
navigate to
yaru/icons/src/symlinks
and run
./generate-symlinks.sh -m application-x-gameboy-rom

**Comment by madsrh** [comment]
👍 Nice

> `./generate-symlinks.sh -m application-x-gameboy-rom`

What's the `-m` ?

**Comment by Feichtmeier** [comment]
I think "match" :)

**Comment by Feichtmeier** [comment]
Works!
image

**Pull request merged**
