### PR TITLE
Redesign Files Icon

### PR DESCRIPTION
**Pull request by elsiehupp**
This is a quick mockup of a concept for maybe fixing https://github.com/ubuntu/yaru/issues/2800. Thoughts? Is this design concept worth pursuing?

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
I think we got told off for changing the Nautilus icon too much 🙂 The grey square with the white folder possibly isn't our most popular icon, but it's probably settled for a little while. There are definitely some icons in the theme that could be improved though, I sort of hate the "characters" app icon with the smiley face on it...

**Comment by elsiehupp** [comment]
FWIW the reason I did the stack of three folders is that it more closely brings to mind [the official GNOME Nautilus icon](https://commons.wikimedia.org/wiki/File:GNOME_Files_icon_2019.svg), which is a file cabinet with three drawers:



(I can’t find for the life of me the source repository that includes this icon, hence why I’m linking to the mirror on Wikipedia.)

For that matter, it wouldn’t be terribly difficult to do a mashup of the above icon and the [Yaru Vertical Oblong Icon Template](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/Vertical%20Oblong%20App%20Icon%20Template.svg):



Would that be more palatable, do you think?

**Comment by elsiehupp** [comment]
Actually, the Wikipedia page links to [the Nautilus Gitlab](https://gitlab.gnome.org/GNOME/nautilus/blob/master/data/icons/hicolor/scalable/apps/org.gnome.Nautilus.svg).

**Comment by Muqtxdir** [comment]
Hi @elsiehupp 👋,

Little late to this 
the current-icon is based on the discussions in the [issue](https://github.com/ubuntu/yaru/issues/1755).

**Comment by elsiehupp** [comment]
> Hi @elsiehupp 👋,
> 
> Little late to this
> the current-icon is based on the discussions in the [issue](https://github.com/ubuntu/yaru/issues/1755).

No worries, and thanks for the explanation! I mainly took the initiative here because there was the open issue on the subject, not because I have any particularly strong preference on the matter.

(My main critique of the existing icon is that it’s a bit ambiguous, but it doesn’t really bother me that much.)

**Pull request closed without merging**
