### PR TITLE
Bring current non-uniform icon set into Yaru

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Okay - this should be the same icon set but without any extra symlinks and without conflicts.

Unfortunately it wasn't as easy as I hoped with the symlinks, it didn't "just work".  But I ran the symlink script one-by-one and believe I've only committed relevant symlinks.  Even so it's a massive lot of commits, over a thousand, because you have ten versions of every new icon and then lots of symlinks for each changed icon.

Suggest we test this one (is it possible to roll back?) due to the sheer number of commits!!

image

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
Also: after I pushed, I deleted all my local Yaru-related folders (including usr/share/icons) and then cloned what I'd pushed to my own laptop and re-built it from there.  So I know it works (it's not like I'm sitting here with a version that works but might have unpushed changes or something).

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1209`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1209` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
I think you missed disk usage analyzer =)

**Comment by ubuntujaggers** [comment]
I'm into it!

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1209`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1209` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
Missing symlink - seems to have fixed it.

**Comment by Feichtmeier** [comment]
@ubuntujaggers package-app is missing and ubiquity :D Could you tackle that? :angel:

**Comment by ubuntujaggers** [comment]
Oops, sorry for missed icons. But yes, I'd be happy to merge this branch if it works (rather than poking it any more!) and then just improve icons and add the few missing ones with normal non-enormous PRs if everyone's happy?

**Comment by Feichtmeier** [comment]
Okay i'll merge this one, Update the issue with the missing icons and close the other pr. 

Thank you very much for this incredible one man work jaggers!!!

**Comment by ubuntujaggers** [comment]
> Thank you very much for this incredible one man work jaggers!!!

No problem at all, I'm very glad we finally found a way forward with icons in Yaru  :)

- Do we want to update the screenshots on the main page of the Github?  I've got to say, when I look at the current screenshots with all the squircles, I think your squircle-free idea was definitely the right one in the end - it just looks a bit better and more polished IMO on my desktop.

- Dare we tip OMG Ubuntu off?  I think the last the wider community heard was that we were sticking squircles on absolutely everything...

**Comment by madsrh** [comment]
> No problem at all, I'm very glad we finally found a way forward with icons in Yaru :)

🎉 +1

> Dare we tip OMG Ubuntu off?  I think the last the wider community heard was that we were sticking squircles on absolutely everything...

Ha ha, good point 😄 They will know on [April 18th](https://wiki.ubuntu.com/DiscoDingo/ReleaseSchedule) 😉 
I'm sorry to bring this up again, but the first question we will be asked is about 3rd party apps and non core Gnome apps. I shared [my thoughts here](https://github.com/ubuntu/yaru/issues/1180#issuecomment-464921377), but are we 100% on the same page here? I think that we need to be and include this in the OMG tip.

**Comment by ubuntujaggers** [comment]
> I'm sorry to bring this up again, but the first question we will be asked is about 3rd party apps and non core Gnome apps. I shared [my thoughts here](https://github.com/ubuntu/yaru/issues/1180#issuecomment-464921377), but are we 100% on the same page here? I think that we need to be and include this in the OMG tip.

From my point of view, the good thing about the non-uniform icon set is we can mix and match.  We have the freedom to make our own Suru-ish icons for third party apps if a) upstream are happy, b) we want to, and c) I or someone else is able to draw something which looks better than the normal icon in the context of Yaru (which won't be always).  But if any of those criteria isn't met, we can just use the upstream icon like everyone else and it won't matter.  When all the criteria *are* met - as in, we've got a green light, we want it, and we've actually got a good-looking icon - I don't think there's anything stopping us?

So in terms of our stated policy on icons we could just leave the door open without committing to particular apps at this stage, other than Shotwell which already ticks the boxes?

**Comment by clobrano** [comment]
I agree, point A is the most important. I don't know how we can make this clearer for upstream  and maintainers, but it would be the best if the idea comes from them first

**Comment by ubuntujaggers** [comment]
@madsrh @Feichtmeier @clobrano: we're already on OMG! Ubuntu!

https://www.omgubuntu.co.uk/2019/02/ubuntu-yaru-icons-non-uniform

**Comment by clobrano** [comment]
Yeah, it didn't take long 😄

**Pull request merged**
