### PR TITLE
Shell: import some changes from 3.36 upstream branch

### PR DESCRIPTION
**Pull request by 3v1n0**
I didn't notice anything wrong with them (no actual changes TBH), so feel free to look at these deeper :)

### CODE REVIEW

**Comment by clobrano** [comment]
LGTM 👍

**Comment by clobrano** [comment]
Do we need this before 20.04 release?

**Comment by 3v1n0** [comment]
> Do we need this before 20.04 release?

Personally I didn't find any difference with or without it... So if you can look better maybe you notice whether it's needed or not.

But from what I see I think we can wait

**Comment by clobrano** [comment]
I don't see differences as well, let's wait

Thank you 😉️

**Comment by clobrano** [comment]
I think we can take this now

**Pull request merged**
