### PR TITLE
Graphite for emblem-symbolic-link

### PR DESCRIPTION
**Pull request by madsrh**
The color was heavily discussed in https://github.com/ubuntu/yaru/pull/1151 and perhaps something was lost in translation, but I figured it would be better to create a PR so we can try it in the real and see how it feels.

Changed the color of emblem-symbolic-link to graphite (#666666) to make it visible on both light and dark backgrounds.

image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1166`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1166` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by eaglersdeveloper** [comment]
It looks very bright. Maybe better `#2d2d2d`?

**Comment by Feichtmeier** [comment]
I think this looks a bit less heavy than those black circles

image

**Comment by madsrh** [comment]
> I think this looks a bit less heavy than those black circles and I would prefer this

+1 It looks a bit odd at first but I've been using it for some days now and it's a much better fit compared to the black IMHO

**Pull request merged**
