### PR TITLE
Add mime icon for Audacity projects

### PR DESCRIPTION
**Pull request by madsrh**
Add mime icon for Audacity projects files 🎧 

image

In the wild:
image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1165`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1165` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
I think I would prefer a less colorful glyph :thinking: It is very bright :D

**Comment by madsrh** [comment]
@Feichtmeier well, that's the color the logo is. We could ofc draw something ourselves if you prefer that

**Comment by ubuntujaggers** [comment]
Teeny bit off centre I think.

Perhaps we could desaturate it a tiny bit, I don't mind it how it is but could be worth trying. Maybe as simple as putting a white square with v low opacity over the logo in the SVG.

**Comment by ubuntujaggers** [comment]
I'm an Audacity user so thanks for picking this one up btw :)

**Comment by ubuntujaggers** [comment]
Aha - the object group for the Audacity logo is centred perfectly, but the logo isn't centred inside the group:

image

**Comment by madsrh** [comment]
Yeah, the (blue part of the) headphones should be centered. Feel free to push any changes you make @ubuntujaggers 👍

**Comment by madsrh** [comment]
> I think I would prefer a less colorful glyph 🤔 It is very bright :D

How about one of these @Feichtmeier ?

image

**Comment by Feichtmeier** [comment]
Much better ! All three look awesome - I can't decide!

**Comment by ubuntujaggers** [comment]
I like blue for recognition, which looks best in context?

**Comment by clobrano** [comment]
Probably the blue in the middle is closer to original icon

**Comment by madsrh** [comment]
> Probably the blue in the middle is closer to original icon

I agree but @Feichtmeier requested a less colorful version

> I think I would prefer a less colorful glyph 🤔 It is very bright :D

What about this one using the dark blue from the suru color palette?

image

image

**Comment by Feichtmeier** [comment]
@madsrh don't mind my request too much. As @clobrano said the dark blue one is very close to the upstream icon. We could surely go with this one
(offtopic but: shouldn't someone help audacity upstream to get a better icon? That one looks really... bad)

**Comment by madsrh** [comment]
I've used the same template as for the other audio files icon, so I have no idea why the border suddenly is so fat :thinking: I'll investigate later (don't merge)

**Comment by Feichtmeier** [comment]
@madsrh I only saw the fat border on .flac
I didn't try this snap yet

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1165`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1165` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
It looks good at any size :+1:

**Pull request merged**
