### PR TITLE
Add Yaru notification symbolic icons

### LINKED ISSUE #2719: Shell no notication asset could be yarufied
Eventually with an outlines version or just something that makes more sense than a bell, since a bell stands for "notifications", isnt it like this?

https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/no-notifications.svg

### PR DESCRIPTION
**Pull request by Jupi007**
**notifications-disabled-symbolic:**

Capture d’écran du 2021-03-12 21-53-15

**message-indicator-symbolic:**

Capture d’écran du 2021-03-12 21-54-13

**no-notifications:**

Capture d’écran du 2021-03-13 13-42-27

This should replace that bell:

Capture d’écran de 2021-03-13 16-23-14

But GS don't want to load it, so I can't test if it works.

Closes #2719

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thanks @Jupi007 
I think this is one of those things loaded via gresource
Maybe @3v1n0  could test this, but I think we can merge it anyways, looks good and the name fits.

**Comment by Muqtxdir** [comment]
@Jupi007, try adding these symbolics into this file under [gnome-shell/src/data/gnome-shell-theme.gresource.xml](https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/data/gnome-shell-theme.gresource.xml) and then doing:

 `meson build ---D gnome-shell-gresource=true`

**Comment by Jupi007** [comment]
> @Jupi007, try adding these symbolics into this file under [gnome-shell/src/data/gnome-shell-theme.gresource.xml](https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/data/gnome-shell-theme.gresource.xml) and then doing:
> 
> `meson build ---D gnome-shell-gresource=true`

I think that don't works:

```
$ meson build ---D gnome-shell-gresource=true
usage: meson [-h] {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite,compile} ...
meson: error: unrecognized arguments: ---D gnome-shell-gresource=true
```

**Comment by Muqtxdir** [comment]
sorry, I pressed extra keys by mistake. try this
```bash
meson meson build -D gnome-shell-gresource=true
```

**Comment by Muqtxdir** [comment]
I think looking at the xml file needed for .gresource, we might need to remove **Yaru-dark** and replace with **Yaru-light**

https://github.com/ubuntu/yaru/blob/f2f15268333f866fc6db58d4ff96924fb78e3138/gnome-shell/src/data/gnome-shell-theme.gresource.xml#L42
https://github.com/ubuntu/yaru/blob/f2f15268333f866fc6db58d4ff96924fb78e3138/gnome-shell/src/data/gnome-shell-theme.gresource.xml#L43

**Comment by Jupi007** [comment]
Bingo 🎉 :

Capture d’écran de 2021-03-13 17-49-54

Thanks @Muqtxdir

**Comment by Jupi007** [comment]
> I think looking at the xml file needed for .gresource, we might need to remove **Yaru-dark** and replace with **Yaru-light**
> 
> https://github.com/ubuntu/yaru/blob/f2f15268333f866fc6db58d4ff96924fb78e3138/gnome-shell/src/data/gnome-shell-theme.gresource.xml#L42
> 
> https://github.com/ubuntu/yaru/blob/f2f15268333f866fc6db58d4ff96924fb78e3138/gnome-shell/src/data/gnome-shell-theme.gresource.xml#L43

@Feichtmeier I fixed that in this PR, it is Ok for you?

**Comment by Feichtmeier** [comment]
Ofc, thanks to you two <3

**Pull request merged**
