### PR TITLE
Testing PR: Jet menus for the Dark GTK theme

### PR DESCRIPTION
**Pull request by Feichtmeier**
screenshot-20181125144230-846x640
image
screenshot-20181125143632-817x526
screenshot-20181125143726-837x544
screenshot-20181125144018-1423x875

Builder search popover
screenshot from 2018-11-25 17-13-36

Discussion can be found here: https://github.com/ubuntu/yaru/issues/980

Post individual issues in here, but please discuss everything else than "fix me" in the issue

- [x] App notifications
- [x] emoji picker
- [x] Move dark menu code to _menu.scss
- [x] Remove double styling (border-radius, padding, margin, etc.)
- [ ] Search popover (see gnome-builder)
- [x] increase hover color brightness

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr989`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr989` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
- [ ] App notifications

- [ ] emoji picker

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr989`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr989` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr989`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr989` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr989`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr989` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by taciturasa** [comment]
This looks really cool for dark theme. Good job!

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr989`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr989` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr989`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr989` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
image

@Feichtmeier I don't know how often this occurs. but [here](https://user-images.githubusercontent.com/15329494/48979813-642f2b00-f0c0-11e8-9789-229c1645916e.png) the submenu and the background color is almost identical. Would it be possible to brighten the hover color or would that open a ton of issues? Just a thought 🤷‍♂️ 

image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr989`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr989` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr989`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr989` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr989`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr989` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr989`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr989` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Paz-it** [comment]
The dark color is good!!! 
I don't know if it's just a prelim test. I would suggest border and separators need some more love..

**Comment by Feichtmeier** [comment]
What love?
Less transparent? More white?

**Comment by Paz-it** [comment]
Less white more tansparent :smile: ... 
More specific: 
Borders: the same color as the background - Now it looks like the menus have a thick frame around them.
Separators : more subtle - they look too thick and too bright.
And it looks like the  menus lost the shadow ...

**Comment by Feichtmeier** [comment]
Hm no they need this bright border to be visible. Also this is a copy style of the shell which was the point of the whole topic

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr989`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr989` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr989`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr989` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Paz-it** [comment]
@Feichtmeier ,If you compare to the light context menus you will notice that the separators are subtle and not wide.

**Comment by clobrano** [comment]
> @Feichtmeier ,If you compare to the light context menus you will notice that the separators are subtle and not wide.

what do you mean? Could you post a pic?

**Comment by Feichtmeier** [comment]
We can reduce the separator lightness
But in the light theme they have exactly the same length

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr989`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr989` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@madsrh could test the colours again?
@Paz-it you were right, the separators were too bright, please test again

**Comment by Paz-it** [comment]
Thanks @Feichtmeier , Tested - better but still too light imo. maybe instead of white you can use black 0.87 or even 0.83 and the same for the borders. just to try ?

**Comment by Feichtmeier** [comment]
@Paz-it the point is, they should look like the shell popups. So darkening the border makes no sense:

image

**Comment by Paz-it** [comment]
They don't :smile: If they do have to look alike the separators should be shorter... with light border and separators, the non pop-up menus look like a cage. the fine crispy look and feel is gone :cry:

**Comment by Paz-it** [comment]
That's fair enough! 
My future tutorial in some forums will have the headline : "How to remove menu borders and separators in Yaru-Awesome-Theme" :woman_shrugging: :smile:

**Comment by Paz-it** [comment]
Just for reference both ambiance and adwita-dark have dark separators with no border at all.

**Comment by Feichtmeier** [comment]
Carlo and me still don't like the implementation so this branch will be prbly closed and I hopefully come up with something more "devastating"

**Pull request closed without merging**
