### PR TITLE
Cabinet drawer-based file manager icon

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Hi everyone,

Here's a PR so you can try it:

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Nice idea. WDYT of changing the colors a bit away from the folder colors so there can't be a "this looks like a folder" argument :) ?
Not blue. But maybe a little bit more metallic gray and no gradients on the folder popping up in the back?

**Comment by ubuntujaggers** [comment]
image

image

Speaking personally I think I prefer the folder colours :thinking:

**Comment by Feichtmeier** [comment]
Another one of my strange ideas. What if you take the original idea of you with the gradient but don't cut out the right third of the folder baseplate? So the role thing looks more like a cabinet without using too many rows of drawers? 🥺 Sorry just brain 🧠 stormy

**Comment by ubuntujaggers** [comment]
So the baseplate is like a normal square baseplate?

**Comment by Feichtmeier** [comment]
Yes. :D

**Comment by Jupi007** [comment]
@ubuntujaggers I really like the new icon from this PR 👍

**Comment by Feichtmeier** [comment]
@ubuntujaggers Oh no I entered Inkscape again :see_no_evil: 
What I meant could be visually translated to "this" :) :
image

**Comment by ubuntujaggers** [comment]
Yep, I got it 🙂 I've got a local version of that and I'll push it for people to try asap, got a busy week but back on it Monday 👍👍

**Comment by madsrh** [comment]
After trying this PR it feels like the icon is kind of dark and - on this screen - falls too much in with the dock background.

> Another one of my strange ideas. What if you take the original idea of you with the gradient but don't cut out the right third of the folder baseplate? So the whole thing looks more like a cabinet without using too many rows of drawers?

What I liked about the initial design was that it's both a folder AND a file cabinet icon, so IMHO changing it too much belittles the idea. Your idea might still have that _folder icon_ association which is the most important thing IMO.

**Comment by ubuntujaggers** [comment]
Current:

image

image

**Comment by jgabriel98** [comment]
> What I liked about the initial design was that it's both a folder AND a file cabinet icon, so IMHO changing it too much belittles the idea. Your idea might still have that folder icon association which is the most important thing IMO.

Agree,
i think the initial design looks better (personal opinion).

Also it still feels like somethins is slightly missing something? maybe the gradient dark colour (the "start" color from the left side) should be less darker.

but still, great design! better then the default one, congrats!.

**Comment by ubuntujaggers** [comment]
How about original design with brighter drawer:

image

image

**Comment by madsrh** [comment]
> How about original design with brighter drawer

👍 I'm very happy with this one!

**Comment by ubuntujaggers** [comment]
Will do this morning - just want to quickly try something first :+1:

**Comment by ubuntujaggers** [comment]
Okay, what I wanted to try very quickly sucked, so I'm pushing as-is :)

**Comment by ubuntujaggers** [comment]
@Feichtmeier @clobrano what do you think?

**Comment by ubuntujaggers** [comment]
I've got to say, this screenshot of the About window looks a lot sweeter than the recent screenshot on OMG:

image

**Comment by Feichtmeier** [comment]
Indeed looks Def. Much better! Thanks for trying

**Comment by clobrano** [comment]
> @Feichtmeier @clobrano what do you think?

This is quite an improvement 🤟

**Comment by ubuntujaggers** [comment]
Magic, I'll merge so we can try it for a while and see if we want to keep it 👍

**Comment by 3v1n0** [comment]
FYI, I've reverted this nice change in the impish branch as we're past UI freeze and this may affect the screenshots, so I'd prefer to land this early when 22.04 gates open.

**Pull request merged**
