### PR TITLE
Remove menuitem transition from context menus and popovers

### LINKED ISSUE #955: Remmina's popover menu items have no bg color change on hover
## Expected Behavior

The background color of menu items should darken when hovered on.

## Actual Behavior

Background color doesn't change.

remmina

## Steps to Reproduce the Problem

  1. Open Remmina
  2. Hover over an item in the popover menu

### PR DESCRIPTION
**Pull request by godlyranchdressing**
Closes #955

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1027`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1027` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by eaglersdeveloper** [comment]
Not understood. What does this look like?

**Comment by clobrano** [comment]
> Not understood. What does this look like?

Look at #955

**Comment by eaglersdeveloper** [comment]
Do you want to get rid of the hovering effect?

**Comment by clobrano** [comment]
Only the transition effect

**Comment by Feichtmeier** [comment]
I would say, though effects are always nice, as long as we don't know which popups have this problem (only Remmina? Is this a Gtk bug? Or a Remmina bug?) we should comment this out like @godlyranchdressing did here. We should keep track of this and eventually bring it back for 19.4 or 19.10

**Comment by godlyranchdressing** [comment]
@Feichtmeier Only Remmina from what I've seen and it might very well be a GTK-related bug from Remmina as there's no weirdness going on with the CSS, and we know it works in other places. 

###### BTW I'm still not sure if I can merge liberally or not.

**Comment by Feichtmeier** [comment]
Let's wait for @madsrh

**Comment by Feichtmeier** [comment]
Ah mads gave his thumb since the last tag :) So you can merge this @godlyranchdressing 
I opened an issue on their Repo https://gitlab.com/Remmina/Remmina/issues/1784
So maybe we are lucky and they fix it any time soon OR give us an information if this is a GTK issue or not

**Comment by antenore** [comment]
> Ah mads gave his thumb since the last tag :) So you can merge this @godlyranchdressing
> I opened an issue on their Repo https://gitlab.com/Remmina/Remmina/issues/1784
> So maybe we are lucky and they fix it any time soon OR give us an information if this is a GTK issue or not

I'll take a look ASAP

**Pull request merged**
