### PR TITLE
Add more emblem icons

### PR DESCRIPTION
**Pull request by madsrh**
image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1191`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1191` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1191`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1191` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Added [Dropbox ](https://www.dropbox.com/help/desktop-web/sync-icons), people and personal emblem icons.

image

There's once again some symlinks missing, but I didn't even try this time - sorry. Can one of you guys run the script?

**FAVORITE** 
As you can see above, I've used the star ⭐️ for favorites because that's what Humanity did, but I now realize that we have a heart ❤️ in the symbolic folder and almost every other theme uses the heart metaphor. I have created a heart emblem icon that I can commit. Which do you prefer @Feichtmeier @clobrano ?

image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1191`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1191` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
I think I'm more a "star" person :)
I tested dropbox emblems, they look fine, but the one used when the folder/file is synchronizing is still in old fashion

**Comment by madsrh** [comment]
> but the one used when the folder/file is synchronizing is still in old fashion

@clobrano Is this with the symlinks? For the sync icon I simply liked the regular sync icon

**Comment by Feichtmeier** [comment]
@clobrano if you have dropbox installed, you could check in /usr/share/icons/hicolor how the dropbox emblems are named

**Comment by clobrano** [comment]
I modified the script, since it didn't work on emblems folder, but I didn't see differences. Tomorrow I'll try again what @feichtmeier suggested

**Comment by madsrh** [comment]
Yes!...or simply rename it to `emblem-dropbox-syncing`

**Comment by clobrano** [comment]
> @clobrano if you have dropbox installed, you could check in /usr/share/icons/hicolor how the dropbox emblems are named

There is no any emblems at all in that directory :|

**Comment by clobrano** [comment]
I tested emblem-people and emblem-dropbox-uptodate succesfully. Synchronizing is still the old one, but maybe it's just my system which is not working. I'll update this PR with the patched script

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1191`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1191` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
> EDIT: moreover, the "favorite" items are those that goes into the "starred" folder?
If that so, we definitely need to stick with the star

I think it's not the case @clobrano 
It looks like 'star' works like a bookmark and is a completely different thing from emblems. So maybe it would be best to use the  💓 to avoid confusion (although I'm a star person too)

**Comment by clobrano** [comment]
Oh, I misunderstood then, you're right

**Comment by Feichtmeier** [comment]
I still need to test it but I prefer the 💓

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1191`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1191` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Looks good from here, but...
1) I find that the Dropbox icons are only working sometimes. This is also the case with Humanity so I think it's a but in the application.
2) emblem-people are perhaps too small

image

**Comment by Feichtmeier** [comment]
from the icons I could check with dropbox, it looks very good @madsrh ! 

image

Any tips how I can check the other icons in this PR?

**Comment by madsrh** [comment]
> Any tips how I can check emblem-dropnbox-infinte and, emblem-danger and emblem-favorite?

Sorry, no. https://github.com/agonzalezro/gnome3-emblems

> Edit: how can I star a file in nautilus? Context-menu didnt elude me so far

...It looks like 'star' works like a bookmark and is a completely different thing from emblems....
Also it will only star files in XDG folders https://gitlab.gnome.org/GNOME/nautilus/issues/243

**Comment by Feichtmeier** [comment]
Okay then - since most emblems work and look awesome - let's merge it?

**Comment by madsrh** [comment]
+1 Yes, let's do that but the people and personal icons are to detailed as a emblem - they work but I'm not 100% happy. Perhaps @ubuntujaggers have an idea how to fix this :)

**Comment by ubuntujaggers** [comment]
Just saw these, they look superb.  I can have a go at people if @madsrh isn't happy with that one but it will be a few days probably, @Feichtmeier's screenshot of it looks good to me?

**Comment by madsrh** [comment]
@ubuntujaggers No rush - they aren't broken or missing, just not perfect. Let's put this on the bottom of your todo list 😉

**Comment by Feichtmeier** [comment]
Okay, merging this now, everything else in following PRs

**Comment by Feichtmeier** [comment]
Note to everyone: please delete your old branches

**Comment by clobrano** [comment]
> Note to everyone: please delete your old branches

Since I didn't know this myself, here is a quick view of your opened branches
https://github.com/ubuntu/yaru/branches

of course, double check the branch is merged or abandoned, before removing it

**Comment by Paz-it** [comment]
I'm following quietly lately, when I have free time. Not much of it as before, sorry! :disappointed:
Nit picking a bit if I may : when looking at the emblems the only one that stand out is the symbolic-link arrow that is not fitting so well in the circle. maybe a bit smaller arrow will be better.
seeing it together with all the new icons in 100% size may emphasize it :
screenshot from 2019-02-26 17-29-36
Otherwise, great work here @madsrh :clap

**Comment by real-amano** [comment]
I think that a heart emblem/icon is some kind of not cool. As are the rainbow and unicorn ones :)

**Pull request merged**
