### PR TITLE
Testing brighter folders

### PR DESCRIPTION
**Pull request by madsrh**
Brighter (and slightly brown) folders

image

image

image

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Cool, more stuff to test 👍 

How does it look on the dark theme window?

**Comment by madsrh** [comment]
> Cool, more stuff to test 👍

I'm guessing that there will be multiple iterations of this 😄 

> How does it look on the dark theme window?

Updated the first post

**Comment by Feichtmeier** [comment]
Hmmm
Can't say that it looks bad on the light window, especially in the default theme with the slightly redish black of the headerbar
But in the dark theme... I don't think it fits very good

**Comment by madsrh** [comment]
> Can't say that it looks bad on the light window, especially in the default theme with the slightly redish black of the headerbar
But in the dark theme... I don't think it fits very good

LOL, I had just the opposite experience 🙈

**Comment by ubuntujaggers** [comment]
Ha, didn't see this! Sorry Mads, would have called mine something more distinct.

**Comment by friendlyapple** [comment]
@madsrh Sorry, I prefer @ubuntujaggers's proposal (#1909). I find that the touch of brown is too "old".

**Comment by madsrh** [comment]
>  I prefer @ubuntujaggers's proposal (#1909). I find that the touch of brown is too "old".

No problem. I prefer @ubuntujaggers proposal as well. It was deliberately old school 😉

**Pull request closed without merging**
