### PR TITLE
add devices/speakers-* to all accented variants

### PR DESCRIPTION
**Pull request by Muqtxdir**

### CODE REVIEW

**Comment by 3v1n0** [comment]
Oh, I thought that would have implied using some magic to get the color done as it happens with symbolic icons that define special paths that can be colored on errors... But adding more svgs that needs to be manually changed all the times it's just too annoying to maintain.

An option we could use is to instead do the replacement ourself and use the SVGs as they are, by using an `accented-scalable` icons maybe. The problem is how to get those icons to be moved to the proper folder...

**Comment by Muqtxdir** [comment]
yeah i used a script to create `devices` dir in all variants and replaced the _magic color_ with respective colors from `common` in for-loop, since these actually are specific to `gnome-control-center` I didn't add another option in the `colorize-dummy-svg.py` as this is too niche

**Comment by Jupi007** [comment]
Can't we just create a source file inside '/src' for those icons?
Even if it is partial.

**Comment by 3v1n0** [comment]
Yeah, this would be my idea: see the rendering path in meson.

So basically the idea is to generate such icons in the build directory and eventually install them, can basically do all at configuration level and use `install_data` + rename to move them in the right spot.

**Comment by flexiondotorg** [comment]
@Muqtxdir Any change coloured version for MATE can be included too? 🧉

**Comment by 3v1n0** [comment]
Let's include this for now, I will generate them on an upcoming refactor...

**Comment by 3v1n0** [comment]
@flexiondotorg mate accente added via 028fd6e5c6c75b74af2205d07a57b56cc946c712

**Pull request merged**
