### PR TITLE
Fix notifications shadow (revert to upstream look)

### PR DESCRIPTION
**Pull request by Jupi007**
Fix notifications shadow (revert to upstream look).

Capture d’écran du 2022-04-06 23-26-26

### CODE REVIEW

**Review by Feichtmeier — APPROVED** [review]
very nice - eventually double check if light still looks good? 🤔

**Comment by Jupi007** [comment]
> eventually double check if light still looks good? thinking

Indeed, I didn't think about it 😅
Thanks for the reminder!

This seems looks good on light theme:

Capture d’écran du 2022-04-06 23-36-14

**Comment by Jupi007** [comment]
Wait, it is a bit strange with a light background:

Capture d’écran du 2022-04-06 23-41-00

It looks imo better to move up the shadow (so it is centered):

Capture d’écran du 2022-04-06 23-45-21

Wdyt?

**Comment by Feichtmeier** [comment]
the border is great. I zoomed like mad, but whats the dif between those two pics?

**Comment by Jupi007** [comment]
It's a very soft change :D

On the second pic, the shadow is 2px upper, so the bottom part of the shadow is less big.

**Pull request merged**
