### PR TITLE
Fix keyboard in light and dark theme

### PR DESCRIPTION
**Pull request by Jupi007**
Fix keyboard in light and dark theme.

**Before:**

Capture d’écran du 2022-02-28 21-29-36
Capture d’écran du 2022-02-28 21-29-50

**After:**

Capture d’écran du 2022-02-28 21-28-44
Capture d’écran du 2022-02-28 21-29-03

## Video:

https://user-images.githubusercontent.com/36476595/156054455-4e85c13b-f121-452e-8867-161264a7fcc3.mp4

### CODE REVIEW

**Review by Feichtmeier — APPROVED** [review]
Oh man! Every damn release. We should upstream this!
thank you so much for going through this again :clap:

**Comment by Jupi007** [comment]
Yeah, something I really don't understand is why GS got some kind of support for light theme, but it's completely broken 🤔

**Comment by Muqtxdir** [comment]
> Yeah, something I really don't understand is why GS got some kind of support for light theme, but it's completely broken 

I think light theme is used in GNOME classic session

**Comment by Feichtmeier** [comment]
Yes. Red hat enterprise uses this gnome classic session as default (among a bunch of gnome shell extensions :shrug: ). Which does not have the overview, so basically only the panel and popovers are "light theme" compatible

**Comment by Jupi007** [comment]
Oh, I didn't know that.
Thanks for the answer guys :)

**Pull request merged**
