### PR TITLE
Remove orange icon overlay

### PR DESCRIPTION
**Pull request by madsrh**
Hopefully this closes https://github.com/ubuntu/yaru/issues/43

### CODE REVIEW

**Comment by friendlyapple** [comment]
Good work! I don't know if you can correct this at the same time: I noticed that these icons may have a focus ring. Would it be possible to delete it ? Example (look around the orange area):

frame_027_delay-0 1s

**Comment by clobrano** [comment]
Great Mads, it works flawlessly!
However, you probably make this  change on top of your previous branch, instead of starting from master and it gives you a conflict.

The new change is only the one under
```
scrolledwindow widget.view:selected {
```
?

**Comment by Feichtmeier** [comment]
1) Carlo is correct the branch has conflicts :)

2) @friendlyapple indeed there is something weird with the edges. Outline colour could be set to transparent. I think we load _tweaks after _apps so the dashed line we once assigned for these icons may be overwritten. Could be wrong. Need to check

**Comment by madsrh** [comment]
I'll make a clean PR 👼

**Pull request closed without merging**
