### PR TITLE
headerbar button active state completely flat

### LINKED ISSUE #750: Improvements to (new) button box styling (or: consolidate toggled buttons)
While its a pitty that Software lost its (fake) stack switcher you came up with a universal, pragmatic and good looking solution for button boxes. 👍 I think it could be further improved by making the toggled state either weaker or stronger.

Currently there are three different styles for toggled header bar buttons which should be consolidated IMHO.

**Regular buttons:**
toggled button regular
**Text Buttons:**
toggled button text
**Button box:**
toggled button box

**1.** Since regular buttons give the clearest and most visible indication of a toggled state I would go that route and make text und box buttons the same: **strong dark shadow plus dark border**. That means removing the grey border for both text buttons and button boxes while toggled. Darkening all four sites would especially improve separation to the left and right element for button boxes.

**2.** If there is some intention behind the more subtle toggled text button style that could be another option for button boxes as I think the current grey plus dark border looks weird. I prefer option 1 though.

### PR DESCRIPTION
**Pull request by clobrano**
closes #750 

examples

image

image

image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr753`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr753` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Sure, I'll do it

Il mer 29 ago 2018, 01:25 Feichtmeier <notifications@github.com> ha scritto:

**Comment by Feichtmeier** [comment]
@clobrano I am not sure if the reason for this fuzzy effect is the transparency or the color difference of border and bg?

**Comment by clobrano** [comment]
I think it's that only the background is highlighted, while the border keeps the same color (the code you posted refers to non-headerbar buttons)

**Comment by Feichtmeier** [comment]
@clobrano found another minor thing after using the snap on my host:
image
The active state for toolbar buttons must be diveded from the changes. I guess with asking for the headerbar_bg_color or something :dancing_men:

**Comment by clobrano** [comment]
Good catch, the Semi flat toolbar

**Pull request closed without merging**
