### PR TITLE
update changelog to show changes made in 21.10.2

### PR DESCRIPTION
**Pull request by Muqtxdir**
- sync debian/changelog from `ubuntu/impish`

### CODE REVIEW

**Comment by Muqtxdir** [comment]
merging this since, it's required for generating `changelog` for next release.

**Comment by Feichtmeier** [comment]
Thank you @Muqtxdir 

Could anyone of you upload a new release to launchpad @3v1n0 @seb128 @didrocks @kenvandine ?

**Comment by seb128** [comment]
The changelog targets impish and it's numbered 21.10.2, is that meant as a SRU? If so we need a launchpad bug to reference and to ensure the changes are compatible with stable update guidelines. Wouldn't it make sense to start by updating the current Ubuntu serie?

**Comment by Muqtxdir** [comment]
Hi @seb128 

This PR was to sync the `changelog`  from [`ubuntu/impish`](https://github.com/ubuntu/yaru/tree/ubuntu/impish) before generating a new changelog for `jammy` as the `master` branch didn't have the current updated changelog.

Please have a look at changelog from `master` branch [here](https://github.com/ubuntu/yaru/blob/master/debian/changelog). It targets `jammy` and is numbered as `22.04.1`

thanks!

**Comment by seb128** [comment]
Thanks, it makes sense now! @3v1n0 could you handle the upload?

**Pull request merged**
