### PR TITLE
new full colour device icon for printer

### PR DESCRIPTION
**Pull request by clobrano**
cherry pick #1602

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1614`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1614` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Could you also push the new documents icons? :angel:

**Comment by clobrano** [comment]
Yes, but since it's made of more than 1 commit, I couldn't do it yesterday

**Comment by Feichtmeier** [comment]
We should eventually could think of the rebase feature of github pull requests:
image
Then we can cherry-pick easier :D 
(or rebase via command line...)

**Comment by clobrano** [comment]
I think that "Squash and merge" would be better for cherry-picking

**Comment by Feichtmeier** [comment]
Yes the second in that drop down, not rebase, sorry 
https://stackoverflow.com/a/43551395

**Comment by clobrano** [comment]
Could someone test this and give feedback?

**Comment by Feichtmeier** [comment]
I will at home

**Comment by Feichtmeier** [comment]
Bildschirmfoto von 2019-11-12 22-47-52

I think this is the new icon, right @ubuntujaggers ?

**Comment by ubuntujaggers** [comment]
Yes it is 🙂 Sorry, I should've cherry picked this myself. I'll do the cherry pick for the document actions today.

**Comment by clobrano** [comment]
No worries, I've already cherry picked the document actions

[carlo - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=8vp1b)	[8vp1b]

On November 13, 2019 at 7:43 GMT, ubuntujaggers <notifications@github.com> wrote:

Yes it is 🙂 Sorry, I should've cherry picked this myself. I'll do the cherry pick for the document actions today.

**Comment by ubuntujaggers** [comment]
Bravo - I'll make sure I remember to do any others after I do the master ones.

**Pull request merged**
