### PR TITLE
Install grab and wait cursors

### PR DESCRIPTION
**Pull request by seb128**
Closes https://github.com/ubuntu/yaru/issues/2451

### CODE REVIEW

**Comment by seb128** [comment]
Tentative fix for #2451 , I don't really understand the build system for cursors though so it's just guess work. Does the win32 build need to be updated the same way (and how does one test the result on windows?)

**Comment by seb128** [comment]
hum, also if not symlinking the watch.ani probably does need to be copied to wait.ani but that isn't in the same file?

**Comment by Feichtmeier** [comment]
Thank you very much @seb128 

CC @ubuntujaggers @Jupiter007-43 please help @seb128  :smiley_cat:

**Comment by Jupiter007-43** [comment]
I think @ubuntujaggers will be much more helpful than me. I had a hard time with my last cursors PR. 😥

**Comment by ubuntujaggers** [comment]
Argh, cursors 😁

I will look at this as soon as I can 👍

**Comment by Feichtmeier** [comment]
Hi @seb128 

Trying this command you've posted

```python
python3 -c "from gi.repository import Gtk,Gdk,GObject; window = Gtk.Window(); window.show_all(); window.get_window().set_cursor(Gdk.Cursor.new_from_name(Gdk.Display.get_default(), 'wait')); Gtk.main()"
```
which pops out the window and the wait cursor. however, with yaru master the wait cursor shows up in 20.10 with yaru master.
when I do the same on my 20.04 host the adwaita cursor shows up.

Trying chromium snap currently has no theming at all. It has that fuzzy x cursor and no yaru theme :| 

Any other idea how I could test this?

**Comment by seb128** [comment]
> with yaru master the wait cursor shows up in 20.10 with yaru master.

Hum, maybe the issue is fixed in master? I'm trying on 20.10 ... is there any package from master I could try (or any other way to opt in for a trunk build?)

**Comment by Feichtmeier** [comment]
you could

```
sudo apt install libgtk-3-dev git meson sassc
git clone https://github.com/ubuntu/yaru.git
cd yaru
meson build
cd build
sudo ninja install
```

**Comment by seb128** [comment]
Ok, I don't understand it, the testcase works also in a VM for me, but also on a focal xubuntu live session when I just tried... need some more investigation

**Comment by seb128** [comment]
seems like gtk has some mapping table 
https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gdk/x11/gdkcursor-x11.c#L623

the extra files might still be required for other toolkit or chromium though?

**Comment by Feichtmeier** [comment]
Sure thing, we can merge it anyways thanks for the work 
Maybe they changed the name in newer versions :) If you tested this yourself and it resolved the missing cursor let's merge it

**Comment by Feichtmeier** [comment]
Okay, let's merge it, eventually we could include this in the yaru SRU to backport it for focal @seb128 ?

**Comment by seb128** [comment]
Sorry for not replying earlier, including in one of the next SRUs should be fine yes, at the same time the main complain we received was with chromium which uses themes from the snap so that's probably low priority

**Pull request merged**
