### PR TITLE
Re-add nautilus-desktop window styling

### PR DESCRIPTION
**Pull request by Feichtmeier**
Re-adding this to master, so we can cherry-pick it into bionic. And after that we should have no difference (hopefully).
Are you okay with this @clobrano even if it is not used for newer nautilus versions?

### CODE REVIEW

**Comment by clobrano** [comment]
I'd prefer not having things in master that we don't use

**Comment by Feichtmeier** [comment]
Then we should also remove the gnome-software green box-shadow ;)

**Comment by clobrano** [comment]
If it's not used sure, but here you want to add something new that we already know it's unused. It doesn't make much sense to me.

**Comment by Feichtmeier** [comment]
it's 5 lines in _apps that are annoying to care about if you sync with master, just like it was remove in last sync. :man_shrugging: 
We also have nemo styling in apps

**Comment by clobrano** [comment]
I understand it's a bit annoying, but the point of having two branches is to keep the differences. We can add some comments to help when updating and also cheery pick should not mess up with these differences

**Comment by Feichtmeier** [comment]
There are no differences in the gtk folders except those nautilus-desktop styling, even though we have other styling in _apps that is not used in master

**Comment by clobrano** [comment]
I think we should remove anything not used in master because it's misleading

**Pull request closed without merging**
