### PR TITLE
Use even checkmark

### LINKED ISSUE #3791: Use even checkmark
See https://github.com/ubuntu/yaru_widgets.dart/pull/351#issuecomment-1295963058

### PR DESCRIPTION
**Pull request by Jupi007**
I don't know where to find a checkbox in GS (except by try to shut-down with updates available).
So sorry but no screenshot for GS.

**Cinnamon**

| Before | After |
| ---------- | ----- |
| Capture d’écran du 2022-12-04 19-14-25 | Capture d’écran du 2022-12-04 19-15-16 |

**Gtk2**

| Before | After |
| ---------- | ----- |
| Capture d’écran du 2022-12-04 19-26-53 | Capture d’écran du 2022-12-04 19-26-16 |

**Gtk3**

| Before | After |
| ---------- | ----- |
| Capture d’écran du 2022-12-04 19-13-01 | Capture d’écran du 2022-12-04 19-13-49 |

**Gtk4**

| Before | After |
| ---------- | ----- |
| Capture d’écran du 2022-12-04 18-08-28 | Capture d’écran du 2022-12-04 19-13-38 |

Closes #3791

### CODE REVIEW

**Review by Feichtmeier — APPROVED** [review]

**Comment by Muqtxdir** [comment]
why the change in checkmark?

**Comment by Jupi007** [comment]
> why the change in checkmark?

To be sync with flutter, see: https://github.com/ubuntu/yaru_widgets.dart/pull/351

**Review by Muqtxdir — APPROVED** [review]
wow, that was a lotta work just to even out the check in checkmark 😅

**Comment by Jupi007** [comment]
> wow, that was a lotta work just to even out the check in checkmark sweat_smile

Yeah, but 99% of the work was just for gtk2 😅

**Pull request merged**
