### PR TITLE
Added symlinks for Evolution app icons

### PR DESCRIPTION
**Pull request by madsrh**
These symlinks are still missing:

```
./generate-symlinks.sh -m evolution-tasks.png
./generate-symlinks.sh -m evolution-mail.png
./generate-symlinks.sh -m evolution-memos.png
./generate-symlinks.sh -m x-office-calendar.png
```

### CODE REVIEW

**Comment by clobrano** [comment]
Is it for these icons?

image

**Comment by madsrh** [comment]
Exactly, could you please test? I've (again) messed something up :facepalm:

**Comment by clobrano** [comment]
I still see the old icons

image

**Comment by clobrano** [comment]
I think I know how to fix it

**Comment by clobrano** [comment]
Okay, it seems that the only icons missing are now calendar and contacts
image

**Comment by madsrh** [comment]
Nice 👍

**Comment by clobrano** [comment]
can I merge?

**Pull request closed without merging**
