### PR TITLE
Add pan-* icons

### PR DESCRIPTION
**Pull request by Jupiter007-43**
**Before:**

Capture d’écran du 2021-02-01 12-05-04
Capture d’écran du 2021-02-01 12-05-15
Capture d’écran du 2021-02-01 12-05-35

**After:**

Capture d’écran du 2021-02-01 11-59-03
Capture d’écran du 2021-02-01 11-59-15
Capture d’écran du 2021-02-01 11-59-50

### CODE REVIEW

**Comment by Feichtmeier** [comment]
damn that's much better :+1: 
kill all the fat icons ^^

**Comment by Jupiter007-43** [comment]
I did smaller icons to fit the size of the original one:

Capture d’écran du 2021-02-01 14-44-55
Capture d’écran du 2021-02-01 14-45-08
Capture d’écran du 2021-02-01 14-46-04

**Review by Feichtmeier — APPROVED** [review]

**Comment by Feichtmeier** [comment]
((( Kinda offtopic, but now that we've finally have our own arrows, upstream removes them from the shell panel :laughing: ! still good to have them in gtk :) )))

**Comment by madsrh** [comment]
> I did smaller icons to fit the size of the original one:

This looks really good @Jupiter007-43 👌

**Pull request merged**
