### PR TITLE
Added hover effect to slider with mark

### LINKED ISSUE #397: Hover effect for sliders, switches and spin boxes
Those elements currently receive a colored border on hover while any other is fully layered by a solid color. Switches have none at all. I suggest:
All of these (sliders, switches and spin boxes) should have the same grey layer effect which check/radio buttons have (or had but currently lack in edge-channel, see #384). Sliders could have colored borders while pressed only.

_Maybe @clobrano can already consider this while working on #44._

hover check-radio hover slider hover spin button hover switch

### PR DESCRIPTION
**Pull request by clobrano**
- changed assets.svg
- regenerated pngs with the render-assets.sh script

closes #397

scale-with-mark-hover

NOTE: when pressed, the handle gets a blue border. I thought about changing it to something else, but being a press effect and not a selection, orange is not necessary (e.g. a button pressed) and I think the blue suits better than any other color since matches with the trough, so I decided to keep it.

EDIT: I noted that the handle in scrolled windows is actually orange when pressed, so I decided to give this a try here, below the result. I am still not convinced though (moreover scrolledwindow handle is never blue)

scale-with-mark-orange-active

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Wow! Did you automatically changed the files?

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr662`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr662` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
> Wow! Did you automatically changed the files?

Yes, lukily it's way easier than I though. I changed the colors on inkscape and then regenerated the pngs with the script

**Comment by Paz-it** [comment]
@clobrano , wow, nice! - I like them both, hard to choose :smiley:

**Pull request merged**
