### PR TITLE
GS: fix light theme invisible text

### LINKED ISSUE #3881: Looking glass hints not readable using light theme
Hi,

Here is the issue. No problem using dark theme.

image

### LINKED ISSUE #3887: gs: context menu unselectable entries are invisible in light
Screenshot from 2023-04-12 01-42-08

### PR DESCRIPTION
**Pull request by Jupi007**
**Before:**

Capture d’écran du 2023-04-12 14-12-31
Capture d’écran du 2023-04-12 14-13-09
Capture d’écran du 2023-04-12 14-13-23

**After:**

Capture d’écran du 2023-04-12 14-02-43
Capture d’écran du 2023-04-12 14-04-32
Capture d’écran du 2023-04-12 14-03-43

Closes #3887, closes #3881

### CODE REVIEW

**Review by Feichtmeier — APPROVED** [review]
💯 Good job!

(( Offtopic: would still safe you a bunch of time, if this could all be upstreamed one day ))
(( Offtopic: the new font looks very nice ))

**Comment by Feichtmeier** [comment]
I think you need to separate the closes issuexyz by new lines and add a closes in front of each issue tag (I could be wrong)

**Review by Muqtxdir — APPROVED** [review]
thanks, better now

**Comment by Jupi007** [comment]
> I think you need to separate the closes issuexyz by new lines and add a closes in front of each issue tag (I could be wrong)

Thanks you was right, I didn't noticed that the second linked issue didn't worked :)

> (( Offtopic: would still safe you a bunch of time, if this could all be upstreamed one day ))

I agree. I will try to ask upstream, if I can find the time to work on (not for now so 😅).
((I think @Muqtxdir reported that they already think about provide a real light theme))

**Pull request merged**
