### PR TITLE
Non-uniform packages-app

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Again, not sure how to test this one - it doesn't have any symlinks, so there aren't any clues as to what app would use it.  Tried installing gdebi but it has its own icon.

image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1225`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1225` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Quiet a no-brainer imho, just what we discussed: squircle->oblong. @madsrh @clobrano ?

**Comment by madsrh** [comment]
Yes!

It also makes sense that it's now the same shape as the archive icon.

**Comment by clobrano** [comment]
Good for me as well

**Comment by clobrano** [comment]
The PNGs are to be generated, right? I can do that

**Comment by Feichtmeier** [comment]
I think they were in the previous commit already

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1225`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1225` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Yes, sorry, the list of changed file in github deceived me

**Comment by clobrano** [comment]
merging it

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1225`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1225` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Pull request merged**
