### PR TITLE
missing-symbolics part2: generic-symbols

### PR DESCRIPTION
**Pull request by Muqtxdir**
related-issue: #3116 

#### to-do:

- [x] chat-none-symbolic.svg
- [x] chat-symbolic.svg
- [x] cigarette-none-symbolic.svg
- [x] cigarette-symbolic.svg
- [x] error-symbolic.svg
- [x] money-none-symbolic.svg
- [x] money-symbolic.svg
- [x] no-violence-symbolic.svg
- [x] nudity-none-symbolic.svg
- [x] nudity-symbolic.svg
- [x] question-round-symbolic.svg
- [x] question-symbolic.svg
- [x] resources-symbolic.svg
- [x] social-network-none-symbolic.svg
- [x] social-network-symbolic.svg
- [x] sound-wave-alt-symbolic.svg
- [x] sound-wave-symbolic.svg
- [x] strong-language-none-symbolic.svg
- [x] strong-language-symbolic.svg
- [x] success-symbolic.svg
- [x] violence2-none-symbolic.svg
- [x] violence2-symbolic.svg
- [x] violence3-none-symbolic.svg
- [x] violence3-symbolic.svg
- [x] violence-none-symbolic.svg
- [x] violence-symbolic.svg
- [x] warning-symbolic.svg

#### adwaita-refrence: [adwaita-generic-symbols](https://gitlab.gnome.org/Teams/Design/icon-development-kit-www/-/tree/master/img/symbolic/generic-symbols)

### CODE REVIEW

**Comment by Muqtxdir** [comment]
@Jupi007 when you are free could you do the guns for `violence3-none-symbolic.svg` and `violence3-symbolic.svg`

**Comment by Jupi007** [comment]
> @Jupi007 when you are free could you do the guns for `violence3-none-symbolic.svg` and `violence3-symbolic.svg`

Okay :)

**Comment by Muqtxdir** [comment]
sorry, I really had a hard time drawing a gun in suru style 😅

thanks for doing it 👍

**Comment by Muqtxdir** [comment]
thanks for fixing the `error-symbolic`. 
I made the following changes:

violence

**Pull request merged**
