### PR TITLE
Adding eye assets with thinner strokes

### LINKED ISSUE #2026: ShellTheme: eye assets could be less bold
With https://github.com/ubuntu/yaru/pull/2025
We will be able to have a complete set of assets in our gnome shell theme, including those:
https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/eye-not-looking-symbolic.svg
image
https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/eye-open-negative-filled-symbolic.svg
image

Do we want to slim them down? Or are they fine like they are? @ubuntujaggers @madsrh @clobrano ?

Edit: they show up in password fields

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Not sure how to test these because my password field on the lock screen doesn't have the eye symbol:

image

Closes #2026

### CODE REVIEW

**Comment by clobrano** [comment]
I can test it

**Comment by clobrano** [comment]
I still see the old one :unamused:

**Comment by ubuntujaggers** [comment]
Damn, wonder why :\

**Comment by Feichtmeier** [comment]
Yes we need the new shell for this. This is a gresource with the new shell. We can merge it

**Comment by Feichtmeier** [comment]
Assets loaded outside of CSS (in gnome shell have script part) could not be changed in yaru until @3v1n0 made a change to gnome shell which makes it possible for us to load the gresources via session (I think)
Same for the spinner

**Pull request merged**
