### PR TITLE
Remove unused underline_focus_headerbar

### PR DESCRIPTION
**Pull request by clobrano**

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Isn't this used in #pathbarbox in the filechoser?

**Comment by clobrano** [comment]
I don't see any occurrence of this

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1034`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1034` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Works!

peek 2018-12-11 18-48

**Pull request merged**
