### PR TITLE
Add icon for backup file

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
Like Humanity, translucent icon:
application-x-trash

### CODE REVIEW

**Comment by madsrh** [comment]
@ubuntujaggers already did a very nice icon (he just needs to push it), so I'm going to close this issue @eaglersdeveloper

image

**Comment by ubuntujaggers** [comment]
@madsrh Happy to push, there was an outstanding question over whether we want to copy the oval proportions of the "circle" from the Copying icon (as per mockup above) or make it a proper circle (as per an actual clock, lol).

**Comment by madsrh** [comment]
I would go with a proper circle, but I'm good with both solutions 🤷‍♂️  If you push one on them, someone will let you know if you chose the wrong one 😉

**Comment by ubuntujaggers** [comment]
Fair point, I'll push tonight or tomorrow  :)

**Comment by eaglersdeveloper** [comment]
Icon by @ubuntujaggers is misleading. Maybe is this icon of system backup or browser history?

**Comment by clobrano** [comment]
Some of the results I got were for files

image

and there is also the Mac folder which has a very similar icon. I think the point is not to find specifically the most used icon for a "backup file", as you said it does not exist in all the systems, but to find an image that might recall the idea of backup. Finally, between an icon with a back in time idea and a translucent text file, I find the first more suitable for the job.

**Comment by eaglersdeveloper** [comment]
Time Machine is a backup tool of macOS.

Time Machine disk icon:



Backup folder icon from photo stock. This icon is not in macOS.

**Comment by madsrh** [comment]
@eaglersdeveloper there seems to be a general agreement about the "clock" idea and IMO it's a good and very common metaphor for backup.

If you have a better suggestion, please post it, but IMHO this PR isn't it.
https://user-images.githubusercontent.com/40228953/50384732-30a4e800-06e2-11e9-895c-61592cc77bec.png

**Comment by clobrano** [comment]
> Time Machine is a backup tool of macOS.

I am aware of that, but as I said point is not to find specifically the most used icon for a "backup file", as you said it does not exist in all the systems, but to find an image that might recall the idea of backup.

Ans as Mads said, this PR is not suitable as backup file.

**Pull request closed without merging**
