### PR TITLE
WIP: Prepare for Ubuntu 20.04 first point release

### PR DESCRIPTION
**Pull request by Feichtmeier**
Get the latest changes from master into Ubuntu 20.04 first point release
 
Here is the changelist, checking the marks when the SRU is created and linked or when no SRU is needed

### Not theme related changes

[ Carlo Lobrano ]
* update README pictures -> **SRU needed**
* build: deduplicate meson.build and introduce Flavours (#1884) -> **SRU needed**
* fix Yaru project name -> **SRU needed**
* Fix spinner typo in tweaks.scss -> No SRU needed, fix and related of #2187
* bootstrap: libgtk-3-dev is needed for building too (#2222) -> **SRU needed**

[ github-actions[bot] ]
* New upstream snapshot for GTK (#2084) -> **SRU needed**

[ Chris Billington ]
* Use MESON_INSTALL_DESTDIR_PREFIX in post_install.py (#2206) -> **SRU needed**

[ John Losito ]
* Check for updates to GitHub Actions every weekday (#2223) ->  **SRU needed**

[ ubuntujaggers ]
* Adding new non-uniform app icon templates #1920 -> **SRU needed**

- [x] Link to "not-design-related" SRU: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887383

__________________________

### gnome-shell and gtk3 theme related changes

[ Feichtmeier ]
- [x] Gtk theme new changes from upstream (#2195) -> **SRU needed**, fix for gtk dialg buttons deforming on hover, Link to SRU: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1881965/comments/2
- [x] Special case  spinners in destructive, suggested action buttons (#2187) -> **SRU needed**, fix for blue spinners on red buttons, Link to SRU: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887298
- [x]  Make wacom overlay visible (#2198) -> **SRU needed**, fix for wacom overlay being invisible, Link to SRU: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887300
- [x]  Shell: revert insensitive fg color change (#2199) -> No SRU needed, fix fpr #2198 
*  Gtk3: increase menu visibility (#2232) -> **SRU needed**, blurry border improvements, 
*  Shell: popup and notification improvements (#2236)  -> **SRU needed**, blurry border improvements
- [x] Link to SRU for menus: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887297

### icon theme related changes

[ ubuntujaggers ]
- [x]  adding second user to system-users (#2209) -> **SRU needed**, fix for the icon to not reflect the plural userS, Link to SRU: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887411
- [x] Some missing icons for Lollypop UI #2235 -> **SRU needed**, Link to SRU: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887419
- [x] Removing green from network-cellular-connected-symbolic #2252 -> **SRU needed**, Link to SRU: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887420
- [x] Rounding corners on avatar-default-symbolic #2253 -> **SRU needed**, Link to SRU: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887419

[ R. David Dunphy ]
- [x]  Nemo selected text highlighting and inactive pane shading (#2220) <- SRU not needed confirmed by @3v1n0 via telegram

[ Jupiter007 ]
- [x]  Add a solid background to microphone icons (#2200) (Closes: #2185) -> **SRU needed**, fix for tiny mic borders, looks blurry, Link to SRU: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887389
- [x]  Re: Fix lock icons twisted path (#2205) (Closes: #2201) > **SRU needed**, Link to SRU: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887393

______________________________

### mimetype icon related changes

[ MadsRH ]
* Added text to img and iso icons (#2213) -> **SRU needed**
* Added mimetype for Lilypond music files (#2230) -> **SRU needed**
* Added icon for QML mimetypes (#2226) -> **SRU needed**
* Added mimetype icon for log files (#2229)  -> **SRU needed**
* Added more mimetype icons again (#2234) -> **SRU needed**
* Added mimetype icon for Scala files (#2231) -> **SRU needed**

[ ubuntujaggers ]
* Adding mimetype for LMMS projects #2249  -> **SRU needed**

[Muqtxdir]
* mimetype application-x-theme #2243 -> **SRU needed**
* Mimetypes application x rss+xml #2248 -> **SRU needed**

[ Ԝеѕ ]
* add application/x-sharedlib alias for x-executable (#2204) -> **SRU needed**
* Use CD image icon for apple disk images #2233 -> **SRU needed**

- [x] Link to  Mimetype SRU: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887388

### CODE REVIEW

**Comment by 3v1n0** [comment]
Could you please create launchpad bugs for the fixed issues you want to address using the [SRU Bug template](https://wiki.ubuntu.com/StableReleaseUpdates#SRU_Bug_Template)

Thanks

**Comment by Feichtmeier** [comment]
Woah this is a big load of work @3v1n0 , until when do we have time for this?

**Comment by 3v1n0** [comment]
Mh, I think one week, otherwise you can just pick the fixes you care the most for now so that we've bugs to address.

Unfortunately, without bugs, the SRU team would reject the upload :(

From what I see the changelog would be

```
[ Carlo Lobrano ]
  * update README pictures
  * build: deduplicate meson.build and introduce Flavours (#1884)
  * fix Yaru project name
  * Fix spinner typo in tweaks.scss
  * bootstrap: libgtk-3-dev is needed for building too (#2222)
 
  [ Feichtmeier ]
  * Gtk theme new changes from upstream (#2195)
  * Special case  spinners in destructive, suggested action buttons (#2187)
  * Make wacom overlay visible (#2198)
  * Shell: revert insensitive fg color change (#2199)
  * Gtk3: increase menu visibility (#2232)
  * Shell: popup and notification improvements (#2236)
 
  [ github-actions[bot] ]
  * New upstream snapshot for GTK (#2084)
 
  [ Ԝеѕ ]
  * icons - add application/x-sharedlib alias for x-executable (#2204)
 
  [ Chris Billington ]
  * Use MESON_INSTALL_DESTDIR_PREFIX in post_install.py (#2206)
 
  [ ubuntujaggers ]
  * adding second user to system-users (#2209)
 
  [ R. David Dunphy ]
  * Nemo selected text highlighting and inactive pane shading (#2220)
 
  [ John Losito ]
  * Check for updates to GitHub Actions every weekday (#2223)
 
  [ Jupiter007 ]
  * Add a solid background to microphone icons (#2200) (Closes: #2185)
  * Re: Fix lock icons twisted path (#2205) (Closes: #2201)
 
  [ MadsRH ]
  * Added text to img and iso icons (#2213)
  * Added mimetype for Lilypond music files (#2230)
  * Added icon for QML mimetypes (#2226)
  * Added mimetype icon for log files (#2229)
  * Added more mimetype icons again (#2234)
```

Each changelog line (or group of lines) that is not an obvious change (as README ones or tiny cleanups) should provide a launchpad bug to be verified.

**Comment by Feichtmeier** [comment]
Nono, I will add those SRUs. Some of those commits are part of something bigger or a fix for a bad PR. And some are really heavy bugs, like the Wacom . Some are not even "visible" changes so prbly do not need a SRU because they only target build stuff, right @3v1n0 ?

**Comment by Feichtmeier** [comment]
@3v1n0 @iainlane @didrocks 
we are done now - please have a look at the opening post / pull request description. All SRU-style launchpad bugs have been created and linked to the post. 
We need your help with the conflict though, could you resolve it? Thanks in advance

**Comment by clobrano** [comment]
@Feichtmeier, could you double check if everything is alright?

**Comment by clobrano** [comment]
If that so, I should be able to update the changelog properly

**Comment by Feichtmeier** [comment]
Master is fine:
grafik

This branch looks also good :+1:

**Comment by clobrano** [comment]
Great, thanks!

**Comment by 3v1n0** [comment]
Thanks a lot for the big work with the SRU bugs, the package is now in [this ppa](https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/4157.1/+packages) waiting for being moved to the [focal queue](https://launchpad.net/ubuntu/focal/+queue?queue_state=1&queue_text=); once it will be there, ping any SRU team member to get it promoted :)

**Comment by 3v1n0** [comment]
Ah, I also did a release from master branch, as we need the fixed bugs to land into ubuntu devel before than hitting a stable version.

**Comment by Feichtmeier** [comment]
> Thanks a lot for the big work with the SRU bugs, the package is now in [this ppa](https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/4157.1/+packages) waiting for being moved to the [focal queue](https://launchpad.net/ubuntu/focal/+queue?queue_state=1&queue_text=); once it will be there, ping any SRU team member to get it promoted :)

I think it's there. Who do we need to ping now? @3v1n0 
grafik

**Comment by 3v1n0** [comment]
You can ask in #ubuntu-release

**Comment by Feichtmeier** [comment]
@3v1n0 Sorry to ping you again, but this still did not land in the regular Ubuntu updater in 20.04 - is there anything else we can do ?

**Comment by iainlane** [comment]
Hey @Feichtmeier 

It looks like https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887420 is not verified yet - I found that by checking the item on https://people.canonical.com/~ubuntu-archive/pending-sru.html.

**Comment by clobrano** [comment]
Hey @iainlane, that SRU link is super cool :smile:
I tested the verified the pending bug :+1:

**Comment by iainlane** [comment]
>  I tested the verified the pending bug +1

Thanks for doing that. It was just missing updating the bug tags so that it goes green in the report. I did that for you now!

**Comment by clobrano** [comment]
Oh thank you!

**Pull request merged**
