### PR TITLE
Remove orange tint on icons

### PR DESCRIPTION
**Pull request by madsrh**
A third (#1831 and https://github.com/ubuntu/yaru/pull/48) attempt at removing the orange tint on the icons in Nautilus.

This is VERY close, but I need the wizard skills of @Feichtmeier or @clobrano to fix the label color when right clicking :disappointed: 
I don't know why, but the label is gray in the dark theme but "invisible" in the light theme.

files

filesdark 01-47

### CODE REVIEW

**Comment by clobrano** [comment]
I think I got it

**Comment by clobrano** [comment]
image

also I fixed the backdrop a little

nautilus

**Comment by Feichtmeier** [comment]
I love when orange becomes gray in the backdrop. Offtopic but it would be so nice if this would become the backdropselectedbgcolor :)

**Comment by madsrh** [comment]
Can I merge this? 😄 

One tiny thing: when right clicking shouldn't the label still be colored? You can't really see which file is selected. Definitely not an issue blocking this PR, but would be nice.

**Comment by clobrano** [comment]
> One tiny thing: when right clicking shouldn't the label still be colored?

It should and it is in the dark variant, but not in the light one, and I am still unsure why. I'll try again tomorrow

**Comment by madsrh** [comment]
@clobrano how would you feel about merging this one now a creating a new issue for the right clicking label?

**Comment by clobrano** [comment]
Yes, sorry didn't really have enough time yesterday, it sounds a good idea :)

**Pull request merged**
