### PR TITLE
review folder structure for easier flatpak

### PR DESCRIPTION
**Pull request by clobrano**
In order to simplify flatpak build for Yaru variants (light and dark) this PR does the following:

1) keep each variant able to build all the needed files by itself dropping the dependencies from the default variant (e.g. symlinks).
2) enable selective components (gtk, gnome-shell, icons, etc.) and variants (default, dark, light) builds. Adding meson options (e.g. `-Ddefault=false`) it's now possible to prevent one component or variant to be built. This will avoid bash magic in flatpak json configuration to modify meson file in order to remove unnecessary components/variants.

Moreover, since current Yaru build does the following mistakes
- release a yaru-light css with the default variant
- release only yaru-light css in Yaru-light variant without support for application with preferred-dark enabled

This change remove yaru-light css generation from the default variant, which does not need it, and add the gtk-dark.css generation into yaru-light variant.

Note: this is a transitory change to enable immediate work to the flatpak builds; a more extensive rework to avoid duplication is already drafted and will be ready ASAP.

### CODE REVIEW

**Comment by clobrano** [comment]
@didrocks, sorry to ping you,  but if you could give a double check here I'd really appreciate

**Comment by didrocks** [comment]
After a quick look, for a temporary intermediate state, this looks fine to me. Nice work! :+1:

**Comment by friendlyapple** [comment]
@clobrano There is an error from this PR.

Here is the error I get when I run the command "meson build":

```
Build started at 2020-01-24T11:32:34.714151
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.47.2
Source dir: /home/hugo/yaru
Build dir: /home/hugo/yaru/build
Build type: native build
Project name: Yaru
Project version: 19.10
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring cursor.theme using configuration
Configuring index.theme using configuration
Program meson/post_install.py found: YES (/home/hugo/yaru/icons/meson/post_install.py)
Program sassc found: YES (/usr/bin/sassc)
Program sassc found: YES (/usr/bin/sassc)
Program install-shell.sh found: YES (/home/hugo/yaru/gnome-shell/src/install-shell.sh)
Configuring index.theme using configuration
Program sassc found: YES (/usr/bin/sassc)
Configuring gtk.gresource.xml using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'
Called `/usr/bin/pkg-config --modversion glib-2.0` -> 0
2.58.1
Called `/usr/bin/pkg-config --cflags glib-2.0` -> 0
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
Called `/usr/bin/pkg-config glib-2.0 --libs` -> 0
-L/usr/lib/x86_64-linux-gnu -lglib-2.0
Called `/usr/bin/pkg-config glib-2.0 --libs` -> 0
-lglib-2.0
Native dependency glib-2.0 found: YES 2.58.1
Program sassc found: YES (/usr/bin/sassc)
Configuring gtk.gresource.xml using configuration
Program sassc found: YES (/usr/bin/sassc)
Configuring index.theme using configuration
Program sassc found: YES (/usr/bin/sassc)
Configuring gtk.gresource.xml using configuration

gtk/src/dark/gtk-3.0/meson.build:201:0: ERROR:  Tried to create target "gtk30_gresource", but a target of that name already exists.
```

**Comment by clobrano** [comment]
This is weird, I just double check and in my environment it works fine. Try to upgrade your meson version, mine is 0.50.1

**Comment by friendlyapple** [comment]
Indeed! Updating meson has corrected my problem. Thank you :)

**Pull request merged**
