### PR TITLE
Updated snap mimetype icon with a more colorful version

### PR DESCRIPTION
**Pull request by madsrh**
Current:
image

Is more colorful better?

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
What's inside that snap file?
Binary or text?

**Comment by madsrh** [comment]
> What's inside that snap file?
> Binary or text?

You're asking me? 😨 

I simply ran with the comment from @clobrano [here ](https://github.com/ubuntu/yaru/issues/2251#issuecomment-658113935) 😄

**Comment by clobrano** [comment]
It's a compressed filesystem with binaries

**Comment by Feichtmeier** [comment]
Okay, I really like the colourful mimetypes.
I would leave mimetype icons for files which include text of any kind (XML, txt, Java code, whatever code, yaml.... ) With a white background though, so you still have the association with the piece of paper - wdyt?

**Comment by madsrh** [comment]
> I would leave mimetype icons for files which include text of any kind (XML, txt, Java code, whatever code, yaml.... ) With a white background though, so you still have the association with the piece of paper - wdyt?

Exactly my thinking! 🤘

**Comment by ubuntujaggers** [comment]
Are we happy to merge this one? I like it 👍

**Pull request merged**
