### PR TITLE
Emoji Picker Buttons: Style button active, hover and checked

### PR DESCRIPTION
**Pull request by Feichtmeier**
Currently the checked button has a background, I think this looks a bit strange.
This changes the checked to have no bg and active to use base_active_color for the second you press and hover base_hover_color

Current:
peek 2018-09-08 17-45

This PR:
peek 2018-09-08 18-43

peek 2018-09-08 17-49

@madsrh @clobrano decide please

### CODE REVIEW

**Comment by clobrano** [comment]
Orange border only is hard to see, but am I wrong or did you fix also the hover effect?

**Comment by Feichtmeier** [comment]
I use the 
base_hover_color for hover
and
base_active_color for active
transparent for checked

I could use the base_hover_color for checked also, if you think this is hard to see

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr797`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr797` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
peek 2018-09-09 09-10

Ah that's why I wanted to remove the active color, too. The Button's edge overlaps in for the first and the last button. That's why I would go for transparent. I think the orange line is quiet good to see.

**Comment by clobrano** [comment]
I see. Alright let's go transparent then :+1:

**Comment by Feichtmeier** [comment]
peek 2018-09-09 09-33

I think I fixed it

**Comment by clobrano** [comment]
Confirmed it's fixed :+1:

**Comment by madsrh** [comment]
In the dark theme the oange border only is hard to see. Could you try a brighter gray (like the light theme)?

**Comment by Feichtmeier** [comment]
image

That low res gifs are often a bit misleading. I think this base_active_color is semi transparent and thus mixing with the background in the end. Is it really hard to see?

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr797`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr797` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
> Is it really hard to see?

I think it's because the picture is really colorful and the orange gets confused

**Comment by Feichtmeier** [comment]
But with a hover effect for checked (I've missed this):
peek 2018-09-09 11-39

**Comment by clobrano** [comment]
Yeah, it's a compromise. To me transparent is good enough

**Comment by madsrh** [comment]
Okay @Feichtmeier, I finally had to time to try this and have noticed three things.

1. (dark theme) Background color: Like the popover menus, I feel that the background would _pop_ more, if we could brighten it.


pop

2. (dark theme) On the light gray background it's very hard to see the orange border. When you press TAB you can easily see it on the darker background, so I guess this is fine.

image

3. (light and dark) Can we remove the hover animation (fadein) for the category? Doesn't it feel slow to you? IMO this is different from buttons, list-boxes, etc.. 
We don't use fadein for Tabs either.

image


As always, feel free to ignore this comment if you disagree 😉

**Comment by Feichtmeier** [comment]
Good point it should use rather menu colour like other pop-ups and menu

I'm not sure about the animation. I like it

**Comment by Feichtmeier** [comment]
Oh lol... no animations in the VM.
But tried the last working snap on my host... and hmhm... it doesn't really lag here O.o

**Comment by madsrh** [comment]
+1 for transparency 😉

**Pull request merged**
