### PR TITLE
Alternative Darker GDM

### LINKED ISSUE #1342: Suggestion: Login screen password box
The white in the password box and cancel button doesn't really fit with the rest of the login screen or the topbar, the dark box as seen in Ubuntu 18.04 without Yaru fits MUCH better.

Current:
alt text

Dark boxes, like 18.04:
alt text

### PR DESCRIPTION
**Pull request by Feichtmeier**
image

image

Peek 2019-05-12 10-19

Closes #1342 

Edit: the user icon looks like this now:
image
image

### CODE REVIEW

**Comment by clobrano** [comment]
It looks good to me, merging it

**Comment by Amr-Ibra** [comment]
Upstream GNOME removed borders around avatars / user images everywhere. Avatars will look inconsistent after login if they had borders before login.
https://gitlab.gnome.org/GNOME/gnome-shell/issues/811

**Comment by real-amano** [comment]
I concur. For conaiytencies sake please drop the border again.

**Comment by clobrano** [comment]
I understand your point, however login view is now special respect many other things now. 
The entry is different, the button is different, so I don't think that the avatar border stands up too much respect the same widget in the rest of the shell.

**Pull request merged**
