### PR TITLE
Replace .window-close assets with scss

### PR DESCRIPTION
**Pull request by Feichtmeier**
Eventually 
closes https://github.com/ubuntu/yaru/issues/1202

I also added the same box-shadow the notification badges on the dock have

@clobrano @madsrh at least one of you please test it on your 18.04 installations
If it works there we could remove the assets and merge it. If not we need an idea for the 18.04 snap :thinking: 

normal
normal

hover
hover

active
active

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1211`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1211` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Nope does not work on 18.04 :|

image

**Comment by clobrano** [comment]
Not sure why, but it does not seem to work in 19.04 too

**Comment by Feichtmeier** [comment]
Works in my vms,... strange

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1211`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1211` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1211`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1211` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
included in #1234

**Comment by Feichtmeier** [comment]
Okay, can't we close this then?

**Comment by clobrano** [comment]
Not yet, let's do it after #1234 is merged

**Pull request closed without merging**
