### PR TITLE
Proposed change to application-x-executable icons

### PR DESCRIPTION
**Pull request by ubuntujaggers**
application-x-executable:

image

application-x-ms-dos-executable:

image

Try it and let me know :+1:

### CODE REVIEW

**Comment by madsrh** [comment]
I think this looks good BUT in my humble opinion this looks more like a settings app icon to me.

I'm a huge fan of the old icon 🙈 What is the reason for wanting to change it?

This is Frederiks comment in the old PR:
Screenshot_20210828-081809

**Comment by Feichtmeier** [comment]
> @ubuntujaggers WDYT about the little idea to add subtle reference to windows in the background-layer for `application-x-ms-dos-executable`?
> ( _see below screenshot of `system-component-application` from PR: #2992 for this_)
> 
> ms-dos

I think this one looks even better :+1:

**Comment by Jupi007** [comment]
It looks very good @ubuntujaggers :)

But maybe keep the window background metaphor only for `application-x-ms-dos-executable`  🤔

**Comment by ubuntujaggers** [comment]
I'll take the folds off the grey one this evening :+1:

**Comment by ubuntujaggers** [comment]
Done :+1:

**Comment by ubuntujaggers** [comment]
I'll merge this because it's better than current, and we can always make further tweaks if we think of any :)

**Pull request merged**
