### PR TITLE
Added icon for midi mime type

### PR DESCRIPTION
**Pull request by madsrh**
Added icon for midi mime type

image

### CODE REVIEW

**Comment by friendlyapple** [comment]
Wrong font family in icons/src/fullcolor/mimetypes/audio-midi.svg ?

**Comment by madsrh** [comment]
> Wrong font family in icons/src/fullcolor/mimetypes/audio-midi.svg ?

Damn, you're fast 😁 Nicely spotted. Thanks

**Comment by Feichtmeier** [comment]
@madsrh  is on :fire: :champagne:

**Comment by Feichtmeier** [comment]
Works

Screenshot from 2020-01-26 11-59-48

**Comment by madsrh** [comment]
Thanks for testing ♥️

**Pull request merged**
