### PR TITLE
Adding missing symlinks for extensions app

### LINKED ISSUE #2096: Extension app: missing symlink
image

@ubuntujaggers nice new icon is not used because the desktop file uses that org.gnome.Extension name

### LINKED ISSUE #2103: Missing symlinks for dialog warning
grafik
grafik

Could be either
```gtk-dialog-warning```
or
```important```
or
```messagebox_warning```
or
```stock_dialog-warning```

that need a symlink to

```dialog-warning```

@ubuntujaggers could you fix that?

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Closes #2096

### CODE REVIEW

**Comment by clobrano** [comment]
@ubuntujaggers, is the issue number a typo? Extensions app issue is #2096

**Comment by ubuntujaggers** [comment]
Fixed, thanks  :)

**Comment by clobrano** [comment]
It works now! :)

@didrocks, @iainlane 

Since this was a bug for which this icon didn't show up at all, and #2145 refreshes the look of this very same icon, can we merge them both, or for #2145 we would need a UIFe?

**Comment by didrocks** [comment]
It’s not shown by default but it’s technically a change, just add it to the existing UIFe bug I would say

**Pull request merged**
