### PR TITLE
add missing categories icon applications-science 

### LINKED ISSUE #2714: The category Applications-Science icon is missing.
The applications-science category icon is missing as shown in the image below.
ubuntu-mate_21 04
OS: Ubuntu-MATE 21.04

### PR DESCRIPTION
**Pull request by Muqtxdir**
Closes #2714

### CODE REVIEW

**Comment by Jupi007** [comment]
Isn't this a dictionary icon 🤔

**Comment by Muqtxdir** [comment]
yes, i didn't re-draw it. I just used @ubuntujaggers icon from PR: #2690

**Comment by Jupi007** [comment]
Personally I would prefer have a icon similar to the related symbolic one because this will conflict with the education one 🤔

**Comment by Muqtxdir** [comment]
ok, I'll change that :+1:

**Comment by Jupi007** [comment]
Thanks a lot 🙂

**Comment by Muqtxdir** [comment]
sorry @flexiondotorg I haven't touched on this one. just having a tight week, so couldn't look into this 😓

**Comment by flexiondotorg** [comment]
@Muqtxdir @ubuntujaggers Any chance this icon might make an appearance soon? 🤞

**Comment by hsbasu** [comment]
> > Personally I would prefer have a icon similar to the related symbolic one because this will conflict with the education one thinking
> 
> @Muqtxdir Any progress on this? Would be great to see add slightly_smiling_face I agree that a science beaker (as used in applications-science-symbolic) would be a good candidate.

I think a *beaker* is a better candidate as science. So I'd second @flexiondotorg 's idea.

**Comment by Muqtxdir** [comment]
sorry for the silence, I don't have the motivation to do a fullcolor icon for application-science. if anyone else is interested to do it and takeover, a new PR is definitely welcomed.

sorry again!

**Pull request closed without merging**
