### PR TITLE
Adding more descriptive gnome characters icon

### LINKED ISSUE #2520: Improve the gnome-characters icon
The upstream icon of gnome-characters, in my opinion, represents the nature of the app better than the Yaru icon. The upstream icon has an Asian character, an Arabic letter, an emoji and a symbol, which are really the things that are searched for in the app. On the other hand, the Yaru icon has only an accented "a" letter. So I think the Yaru icon could be improved.

[Upstream icon](https://gitlab.gnome.org/GNOME/gnome-characters/-/blob/master/data/icons/hicolor/scalable/apps/org.gnome.Characters.svg)
image

[Yaru icon](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/apps/accessories-character-map.svg)
image

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Closes #2520

Happy to work on it some more if people aren't sure :+1: 

image

image

image

### CODE REVIEW

**Comment by Amr-Ibra** [comment]
I think the symbolic icon needs updating too.
https://github.com/ubuntu/yaru/blob/master/icons/Suru/scalable/apps/accessories-character-map-symbolic.svg

**Comment by ubuntujaggers** [comment]
Good point. I'll add it to this branch.

**Comment by ubuntujaggers** [comment]
Dinky symbolic version:

image

**Comment by Jupiter007-43** [comment]
Very nice @ubuntujaggers !

**Comment by Amr-Ibra** [comment]
Very nice! I like it.

**Pull request merged**
