### PR TITLE
Add audio mime type icons

### PR DESCRIPTION
**Pull request by madsrh**
This is my first try with icons, so @ubuntujaggers can you check if this is correct?
Added mime type icons for:

.pls
.m3u
.wav
.mp3
.ogg
.wma

Some symlinks are still missing, because I don't know how to create them.

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Awesome - another Icon contributor 👍 🎉 

This one looks broken:
image

**Comment by madsrh** [comment]
Ahhhhhh, yes - sorry! 🤦‍♂️ I need to do more cleaning before commiting.

**Comment by Feichtmeier** [comment]
For symlinks you need to do two things

1) add 1 line per symlink into the corresponding .list files in https://github.com/ubuntu/yaru/tree/master/icons/src/symlinks/fullcolor and https://github.com/ubuntu/yaru/tree/master/icons/src/symlinks/symbolic
"SRC_ICON_NAME" "TARGET_ICON_NAME" (.svg or .png depending if it's fullcolor or symbolic)
2) run https://github.com/ubuntu/yaru/blob/master/icons/src/symlinks/generate-symlinks.sh with
bash generate-symlinks.sh SRC_ICON_NAME (thanks to the new needle by @clobrano )

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1160`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1160` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Great job @madsrh!
It looks that the bottom part of the icons is a bit too crowded, because of the label. Moreover, labels with characters like "g" or "p" that occupy space also below the label, look too close to the bottom border.

**Comment by madsrh** [comment]
@clobrano I think you are right. My idea was to keep the icon in the same place as the generic icon, so it wouldn't look odd when they are next to each other - but it makes sense to move it 👍  

image

**Comment by eaglersdeveloper** [comment]
I think that better to use symlinks to `audio-x-generic` for all audio formats.

**Comment by Feichtmeier** [comment]
Why is it better? For people working with many audio files it is important to distinguish them fast. So no symlink all types to 1 icon is not better.

**Comment by madsrh** [comment]
I prefer the way it works in Humanity:

image

**Comment by madsrh** [comment]
Can you please check this update @Feichtmeier @clobrano ? It got kind of messy, but I think this should be correct

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1160`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1160` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
I noticed that `audio-x-playlist.png` and `audio-x-scpls.png` are almost the same (the first is actually a little better), is that intended?

**Comment by clobrano** [comment]
There's seems to be something wrong:

- `audio-mpeg` and `audio-x-vorbis+ogg`: have the old version with the label too low  (but there's also a `audio-x-mpeg` which is right)
- `audio-x-playlist` hand `audio-x-mp3-playlist` have thicker lines than  `audio-x-scpls` and `audio-x-mpeg-url`

**Comment by madsrh** [comment]
ahhh 🤦‍♂️ Would it be okay if I closed this PR and created a new? 

Thanks for your patience !

**Comment by eaglersdeveloper** [comment]
Also you updated only raster icons. I don't see updated source icons.

**Comment by madsrh** [comment]
I've got it now, just need to upload. Just a second ⌛️

**Comment by eaglersdeveloper** [comment]
You also should fix background gradient

**Comment by madsrh** [comment]
> You also should fix background gradient

What is wrong with the background? I didn't change that 🤷‍♂️

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1160`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1160` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Okay, this one is almost good, but the symlinks doesn't seem to work.

**Comment by eaglersdeveloper** [comment]
Fix background gradients in your icons, except WAV icon.

**Comment by eaglersdeveloper** [comment]
I can fix this.

**Comment by ubuntujaggers** [comment]
Sorry, I was no help at all here! Busy day. Great to see more vector artists!

**Comment by eaglersdeveloper** [comment]
Also I reduced lines in playlist icon in 48x48 size to make pictogram aligned. Add to my branch, @madsrh?

**Comment by madsrh** [comment]
Sure 😁

**Comment by eaglersdeveloper** [comment]
Done! Switch to `audio-mime-icons` branch and run this command to add my icons:

    git push https://github.com/eaglersdeveloper/yaru.git audio-mime-icons

**Comment by clobrano** [comment]
Shouldn't we pull from your repo, instead of push?

**Comment by eaglersdeveloper** [comment]
I confused `push` with `pull`
@madsrh should run this command to add my commits.

**Comment by clobrano** [comment]
I [cherry-pick](https://git-scm.com/docs/git-cherry-pick)ed @eaglersdeveloper's gradient fix and also fix symlinks. Could you try if it works?

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1160`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1160` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Looks great @clobrano 🎉 
Symlinks works here 👍

**Comment by madsrh** [comment]
And thanks for fixing my mistakes @eaglersdeveloper 👍 

Can we merge this one?

**Pull request merged**
