### PR TITLE
Fix .path-bar button styling

### PR DESCRIPTION
**Pull request by Feichtmeier**
Closes https://github.com/ubuntu/yaru/issues/1086

peek 2019-01-08 10-21

@iainlane please test again

### CODE REVIEW

**Comment by clobrano** [comment]
Looks good to me now (I have a VM with disco and Nautilus 3.30.4)

image

**Comment by Feichtmeier** [comment]
Good news it still works on 18.04 nautilus 3.26:

peek 2019-01-08 10-53

**Comment by iainlane** [comment]
Yep, thanks, this looks great!

@clobrano once this is merged we could do the changelog / tag / upload IMHO

**Comment by clobrano** [comment]
@iainlane, great I'll start updating the changelog asap

**Comment by Feichtmeier** [comment]
Offtopic but still somehow related to nautilus:

The new shell extension styles the selected item color here:
https://gitlab.gnome.org/World/ShellExtensions/desktop-icons/blob/master/stylesheet.css#L12
Which can not be overridden by the shell theme ( I guess because the extension's stylesheet is taken after)

image

The border-radius for example is not styled in the extensions stylesheet, thus I can change it on our shell theme.

Could you either remove the styling from the fork or change the bg color to orange/transparent orange?

**Comment by clobrano** [comment]
I'd really like to revert #1063 before tagging, @Feichtmeier do you think it is possible in a short time?

**Comment by Feichtmeier** [comment]
I think @ubuntujaggers still needs some time to fix stuff so I think we can risk the conflict in his branch. He only needs to copy the part from the SVG into his SVG then. So yes let's do the revert now

**Comment by iainlane** [comment]
There is no fork, if we want to make that themable we should try to figure out how to do that properly upstream.

**Comment by clobrano** [comment]
> Do I just need to manually revert the power glyph in my copy of source-symbolic so it's the bolder one? If so, yes, that's easy, I'll make sure I remember :)

yes, that should do it, thanks!

**Pull request merged**
