### PR TITLE
Add HiDPI variants to XFWM4 theme

### PR DESCRIPTION
**Pull request by JakeIsMeh**
This PR adds HiDPI variants of Yaru for XFWM4 users.

XFWM4 themes are independent of any display scaling that may be applied, thus users on HiDPI displays will suffer from unusably small titlebars and window controls.

The most common solution is to render assets at various DPIs to accommodate users using HiDPI displays.

Tested on:
XFCE 4.16
XFWM4 4.16.1-3
Arch Linux (Rolling)

### CODE REVIEW

**Comment by Muqtxdir** [comment]
Hi @JakeIsMeh 

could you please add before and after screenshots for comparison

**Comment by JakeIsMeh** [comment]
Before, using Yaru-dark:
image

After, using Yaru-dark-xhdpi:
image

**Comment by JakeIsMeh** [comment]
Sorry for the inconvenience.
I wrote the patch on a different computer and transferred over the patches by hand, and did not copy it correctly.

These commits should fix the build error.

**Review by Jupi007 — CHANGES_REQUESTED** [review]
Hi @JakeIsMeh,
thanks a lot for your contribution ❤️

All the assets looks good for me.
Debian and meson part too.
Just the `render-xfwm4-assets.sh` script could be refactored I think. You should add a `ASSETS_DIRS` var and loop on it instead of having separated vars and duplicated code.

Anyway, great job 💪‍

**Comment by Jupi007** [comment]
@Muqtxdir Have you got a VM with xfce to test this PR?

**Comment by Muqtxdir** [comment]
> 

yes, a bit outdated vm but i can try the branch out there 👍

**Comment by Jupi007** [comment]
Thank you, I could create one, but took me too long.

**Review by Muqtxdir — APPROVED** [review]
Thanks for your contributions. just make sure to include @Jupi007 suggestion regarding the script before merge.

**Review by Jupi007 — APPROVED** [review]
Looks perfect :+1: 

Thanks a lot for this @JakeIsMeh

**Pull request merged**
