### PR TITLE
Add icon for missing image

### LINKED ISSUE #1102: imagine-missing.svg
image

There is no Suru/Yaru icon for this one. Would be nice to have it :)

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
Closes #1102
image-missing

### CODE REVIEW

**Comment by Paz-it** [comment]
Since this icon is a kind of warning, the pictogram should remain RED. What do you think?

**Comment by clobrano** [comment]
Yes, I'd like to see the colors inverted. Also because icons for file types
are mainly white

**Comment by madsrh** [comment]
I agree with @clobrano. An inverted version like below would feel much "lighter" IMHO

Image of Yaktocat

**Comment by ubuntujaggers** [comment]
I like this - I would like to see both versions in a realistic screenshot (white on red and then red on white).  White on red is very colourful  :)  but I note that the generic image icon is also colourful:

image

Question: when do you actually get a missing image icon, and are you likely to delete it immediately or fix it or something?  If it's something you'll want to take action on, when you see it in your file manager, it might not be a bad thing for it to be as colourful as the generic image icon but a bit more urgent-looking?

**Comment by Feichtmeier** [comment]
It is shown when an application has no icon in the dock

**Comment by clobrano** [comment]
Then my reference to file types icon is wrong, better a more colorful icon
like this one

**Comment by Feichtmeier** [comment]
Here:
https://i.imgur.com/neiL3pm.jpg

**Comment by ubuntujaggers** [comment]
If it goes on the dock should it be a squircle...?

**Comment by Feichtmeier** [comment]
Ah sorry, i think eaglers could be right about this being based on the image icon shape and BG. It's also used when you add a wrong path to a GtkImage in all your new gtk apps ;0 (little joke because none of us makes gtk apps). But the first part was not a joke. Posting a screenshot later. I even think that's completely right even with that dark BG eaglets pstrd

**Comment by clobrano** [comment]
> If it goes on the dock should it be a squircle...?

Since it can goes in both dock and popups, I think it's better without the squircle

**Comment by Feichtmeier** [comment]
We could also create a symbolic icon for that

image

**Comment by Feichtmeier** [comment]
@eaglersdeveloper could you try a colour inverted version of your icon? Red on white BG? Just to try both, I think there is the desire to try and see it

**Comment by madsrh** [comment]
I tried a quick mockup with gray since the popup background is pure white 🤷‍♂️ Also in the bottom of the dock.

image

**Comment by clobrano** [comment]
I am torn. Grey is probably better in notification, while red in dock :D 
I am ok with both, after all

**Comment by Feichtmeier** [comment]
I would also go for both. Some reply would be great either way ;D

**Comment by clobrano** [comment]
Okay, then red is probably too alarming, slight preference for the white version here

**Comment by madsrh** [comment]
There's also the option of using the same colors as the old/current icon - dark background and red. Perhaps even add a white border similar to the current.

image


image

**Comment by clobrano** [comment]
That would end up with a dark on dark when the dock is opaque

**Comment by Feichtmeier** [comment]
We could something in between. Like inkstone :)

**Comment by ubuntujaggers** [comment]
The red is my favourite Suru colour, but really I'm happy with any of these options *thumbs up*

**Comment by eaglersdeveloper** [comment]
OK, wait.

**Comment by eaglersdeveloper** [comment]
Which one do you like?

image-missing-red image-missing-light image-missing-dark

I like red.

**Comment by Feichtmeier** [comment]
I would prefer black when I see those three beside each other
But as Carlo said the black could be hard to see in the dock
If you would not change the black to be brighter I would go for red, too

**Comment by clobrano** [comment]
I'd like to see @Feichtmeier inkstone on a opaque dock. @eaglersdeveloper could you do this test?

**Comment by clobrano** [comment]
Well, ok if @eaglersdeveloper does not have time to make the last change, I think we can accept the red one. Anyone against?

**Pull request merged**
