### PR TITLE
Add html-template icon

### LINKED ISSUE #2328: Missing Twig template icon
**Actual icon:**

Capture d’écran du 2020-08-19 12-25-00

Mimetype text/x-twig

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Capture d’écran du 2020-08-24 21-33-23

@clobrano what is the mimetype of a jinja file?

And if someone know a template engine please give me the mimetype too, so I can link it to this icon.

Closes #2328

### CODE REVIEW

**Comment by clobrano** [comment]
> @clobrano what is the mimetype of a jinja file?

I couldn't find any information about it. Considering that the Jinja project doesn't even define an official extension name, it probably doesn't have a mime type :(

**Comment by abeautifulpseudo** [comment]
The icon is not bad but it seemed to me that this type of icon must have a white background:

> Files that are primarily opened or viewed as text have a white backplate with subtle watermark (because we want the icon to resemble a page in a document)

https://github.com/ubuntu/yaru/issues/2271#issuecomment-670630167

**Comment by Feichtmeier** [comment]
Damn, you are right @abeautifulpseudo :thinking:

**Comment by Jupiter007-43** [comment]
> The icon is not bad but it seemed to me that this type of icon must have a white background:
> 
> > Files that are primarily opened or viewed as text have a white backplate with subtle watermark (because we want the icon to resemble a page in a document)
> 
> [#2271 (comment)](https://github.com/ubuntu/yaru/issues/2271#issuecomment-670630167)

Indeed, shame on me 😰

So, fixed version:

Capture d’écran du 2020-08-25 10-30-02

**Comment by abeautifulpseudo** [comment]
I just saw your issue, and I find your first proposal nicer https://github.com/ubuntu/yaru/issues/2328#issuecomment-676201616. But I also understand the remarks of @clobrano about this one.

**Comment by Jupiter007-43** [comment]
Using the good baseplate:

Capture d’écran du 2020-08-25 10-44-36



> I just saw your issue, and I find your first proposal nicer [#2328 (comment)](https://github.com/ubuntu/yaru/issues/2328#issuecomment-676201616). But I also understand the remarks of @clobrano about this one.

I agree with you, I also prefer the first one.
It's better to provide a generic icon (as there is plenty of template engine).

But if you have a better idea than this PR, I'm open to suggestion 🙂

**Comment by Jupiter007-43** [comment]
Updated version:

Capture d’écran du 2020-08-26 12-43-19

**Pull request merged**
