### PR TITLE
Added text to img and iso icons

### PR DESCRIPTION
**Pull request by madsrh**
A fix for https://github.com/ubuntu/yaru/issues/2171

I also added the same style icon for squashfs.

image

### CODE REVIEW

**Comment by madsrh** [comment]
We could also do something like this: (inspired by [We10x](https://github.com/yeyushengfan258/We10X-icon-theme/blob/master/src/scalable/mimetypes/application-x-cd-image.svg))

image

**Comment by clobrano** [comment]
+1 for the light version :)

**Comment by clobrano** [comment]
@madsrh, what do you think about moving the label few pixels towards the bottom? If you tried already, or just prefer this way, no worries, I think it's already good :+1:

**Comment by madsrh** [comment]
@clobrano I agree. The placement here is simply taken from the mp3 icon, so I knew the text would render sharp. I could try to move them all slightly down, but @ubuntujaggers is really the pixel-fitting ninja. Perhaps he could take a look?

**Comment by Feichtmeier** [comment]
I agree with carlo moving them a bit down is a good idea @madsrh :)

**Comment by ubuntujaggers** [comment]
Is this text low enough:

**Comment by madsrh** [comment]
Perfect 🎉

**Comment by clobrano** [comment]
Yes 👍

**Comment by ubuntujaggers** [comment]
Pushed :+1:

**Pull request merged**
