### PR TITLE
Add Packages icon

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
Icon for GNOME Packages:

packages-app

### CODE REVIEW

**Comment by eaglersdeveloper** [comment]
Combo!

**Comment by Feichtmeier** [comment]
Nice thanks!
Can you run that export script after you installed optipng and commit it?
Then I don't need to do that in a second PR :D

**Comment by eaglersdeveloper** [comment]
Not understood. Do you mean exporting to raster images? I already did it. See the list of changed files.

**Comment by Feichtmeier** [comment]
Oh sorry. Maybe it was too early in the morning!

**Comment by Feichtmeier** [comment]
Oh sorry. Maybe it was too early in the morning!

**Comment by Feichtmeier** [comment]
This looks really good will it also affect the icon when you right click on a package and choose "install with xyz"?

**Comment by eaglersdeveloper** [comment]
Where?

**Comment by Feichtmeier** [comment]
Here: 

image

**Comment by eaglersdeveloper** [comment]
This is application icon. It's ok.

**Comment by Feichtmeier** [comment]
Yes works :) Tyvm  @eaglersdeveloper 
image

**Pull request merged**
