### PR TITLE
Inverted _headerbar refresh

### LINKED ISSUE #2526: Devel style class seems to be broken/unsupported
**Expected Behavior**
I ran a development build of geary which uses the "devel" style class for its main window. It should either render like the regular version or have a style that indicates it is a development build.

**Actual Behavior**
The theme for the header bar seem to be broken. It renders grey/white text on top of a light gray background.

**Steps to Reproduce the Problem**
Install geary from source or run the flatpak nightly version. (Repository is here https://gitlab.gnome.org/GNOME/geary)

**Yaru version**
 20.10.6.1

**Screenshots**
image

**Upstream check**
Renders fine with adwaita
image

### PR DESCRIPTION
**Pull request by Jupi007**
- Code cleaning and refactoring.
- ~~Remove .selection-mode section (gtk3) by adding :not(.selection-mode).~~
- Add .devel class support - Related to  #2526

### CODE REVIEW

**Comment by Jupiter007-43** [comment]
@Feichtmeier You was talking about factorize button styles into a for loop. But as I removed selection-mode by adding **:not(.selection-mode)** to **headerbar** selector I don't think it's a good idea because it will make the code over complicated for nothing
??

**Comment by Feichtmeier** [comment]
Ok. True 😊 as long as you style each state in foreground and background

I'll need to check this pr with a checklist to not miss anything

**Comment by Feichtmeier** [comment]
:backdrop:checked seem to have the wrong background color and strange backward and forth transition:
Peek 2021-02-11 10-15

**Comment by Jupiter007-43** [comment]
Small mistake from my part, sorry.
It should be fixed now.

**Comment by Feichtmeier** [comment]
nothing to be sorry about, this is why we review each other :)

Works
grafik
grafik

I think the gtk4 checked looks slightly different though
grafik

**Comment by Jupiter007-43** [comment]
> I think the gtk4 checked looks slightly different though

It's because Gtk4 has one more state than Gtk3, is that needs a fix?

**Comment by Feichtmeier** [comment]
No I think we are good to merge. Ah one thing.. need to check that damn selection mode :roll_eyes: 

grafik
works!

okay now the final stage boss of theming gtk apps... gnome contacts! it has it all! selection mode plus multiple headerbars plus hdyviewwidgets
oh no :( 
grafik

**Comment by Jupiter007-43** [comment]
Noooooooooo 😭
I must reinsert full-selection mode...

Can you retest now?

**Comment by Feichtmeier** [comment]
What did you actually change now compared to master? :D

**Comment by Jupi007** [comment]
> What did you actually change now compared to master? :D

Sadly, almost nothing...

**Pull request merged**
