### PR TITLE
Sync GS with upstream - 3665

### PR DESCRIPTION
**Pull request by Jupi007**
**New icon:**

Capture d’écran du 2022-08-11 11-46-57

Related to #3665

### CODE REVIEW

**Comment by Muqtxdir** [comment]
@Jupi007 wdyt about this type of symbolic for `dark-mode`?

dark-symbolic

_it's similiar to the one used as quick-toggle in iOS, but I feel that this might look complicated?_

**Comment by Jupi007** [comment]
Hmm, that would have been a good idea. But I'm afraid it looks messy at 16x16 in the panel 🤔

**Comment by Muqtxdir** [comment]
> Hmm, that would have been a good idea. But I'm afraid it looks messy at 16x16 in the panel 🤔

yep, your initial symbolic would look better in panel 👍

**Review by Muqtxdir — APPROVED** [review]

**Comment by Jupi007** [comment]
I just Yaru-ified the upstream one :D

**Pull request merged**
