### PR TITLE
Added device icon for media-flash

### PR DESCRIPTION
**Pull request by madsrh**
Okay this is a bit of a longshot because I can't test this icon. I tried to adapt [the Suru++ icon](https://github.com/Bonandry/suru-plus-ubuntu/blob/master/Suru++-Ubuntu/devices/scalable/media-flash.svg), but I couldn't reuse the standard Yaru template borders, so I added a stroke. 

@ubuntujaggers could you have a look?

image

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
Will check the edging tonight 👍

**Comment by ubuntujaggers** [comment]
Do you have your heart set on the little cutaway on the right?  I'm in the process of refactoring into Suru-style edging:

image

**Comment by madsrh** [comment]
> Do you have your heart set on the little cutaway on the right? 

No 😄 I'm sure it isn't even visible with the small sizes.

Are you able to test it?

**Comment by ubuntujaggers** [comment]
No, lol.  Shall I push?

**Comment by madsrh** [comment]
> No, lol. Shall I push?

Yes, please 😃 

What do you think about the testing @Feichtmeier ?

**Comment by clobrano** [comment]
LGTM :+1: 
image

**Comment by Feichtmeier** [comment]
> > No, lol. Shall I push?
> 
> Yes, please 
> 
> What do you think about the testing (or lack of) @Feichtmeier ?

Not sure - does it have the same highlights as the other device icons?

**Comment by madsrh** [comment]
Awesome, you had a SD card reader @clobrano 😄 but the PR you tested was not the tweaked version because @ubuntujaggers didn't push his changes yet.

Glad to see it worked 👍

**Comment by ubuntujaggers** [comment]
image

Give it a whirl...

**Comment by clobrano** [comment]
I'll have a go tomorrow :+1:

**Comment by madsrh** [comment]
So much sharper! Thank you!

**Comment by clobrano** [comment]
Here is the new icon
image

image

Again, my only concern is that the gray gradient seems stronger respect the other device icon, but It's not a major one, good work :+1:

**Comment by ubuntujaggers** [comment]
I think this is an optical illusion... both the background gradient and the secondary grey are taken from the drive icons. However, because there's a big area of darker grey rather than a fine glyph, maybe the overall impression is a "darker" icon?

**Comment by clobrano** [comment]
Oh, it might be indeed, sorry then :D

**Comment by ubuntujaggers** [comment]
Optical illusions are still a factor - we can try tweaking either shade and see if it restores visual balance 👍

**Comment by clobrano** [comment]
Well, only if you think it's a problem as well, otherwise feel free to
merge it

**Comment by Feichtmeier** [comment]
@madsrh @ubuntujaggers are you sure that the shadows and highlights are correct? I'm not sure :thinking:

**Comment by ubuntujaggers** [comment]
The baseplate is the same width, but more of the colour is bleeding into the next pixel:

image

Looks like this is due to a slight error in 48px - try now?

Also the highlight was 30% opacity instead of 40% opacity - try now  :)

**Comment by ubuntujaggers** [comment]
@clobrano 

I think the juxtaposition with the server icon is problematic in the screenshot - the server has folds which make it brighter than average.

If you set it by the hard drive, it looks right to me:

image image

...so maybe the problem is the server being too bright?

**Comment by Feichtmeier** [comment]
@ubuntujaggers 
Okay then it was only the glitch + some optical illusion :)

About the highlights: didn't we have highlights here in other icons?
image

**Comment by ubuntujaggers** [comment]
Oh, I see what you mean - there doesn't seem to be a hard and fast rule in Suru, some pictogram elements have edging and some are completely flat, but I like highlights and am always happy to try adding some  :)

**Comment by clobrano** [comment]
> ...so maybe the problem is the server being too bright?

Yes, I think you are right. HD and sdcard are quite aligned and server looks a bit brighter

**Comment by ubuntujaggers** [comment]
Try this:

image

**Comment by Feichtmeier** [comment]
Imo this looks good :thums_up:

**Pull request merged**
