### PR TITLE
Nautilus: keep gray rows until gtk4 port

### LINKED ISSUE #3277: Keep gray rows for nautilus
We should revert this for nautilus only. It looks like the gtk4 port will take much longer. It is kind of easy what to expect in those rows and upstream does it too:

https://github.com/ubuntu/yaru/blob/13e18b5c27c5893520b5617a411a18d549373ca2/gtk/upstream/nautilus/Adwaita.css#L76-L95

_Originally posted by @Feichtmeier in https://github.com/ubuntu/yaru/pull/3271#issuecomment-999931364_

It's the most opened gnome app on the desktop app we can risk an exception imo. Gnome settings gtk4 port is done I think, so this one will have Grey rows, too

### PR DESCRIPTION
**Pull request by Feichtmeier**
grafik

grafik

Closes #3277

### CODE REVIEW

**Comment by Jupi007** [comment]
I say yes :+1: 

What about also revert treeview tweaks here?

**Comment by Feichtmeier** [comment]
better not there was some usability issue to whether this small row is selected or hovered

**Comment by Jupi007** [comment]
This can be fixed imo. If we use a very very light one for hover.
And honestly, it is easy to know if a row if hovered, as you have your cursor on it 😅

**Comment by Feichtmeier** [comment]
I am fine with this but maybe you make the push then. Last time I tried we had someone opening an issue about the treeview hover/selection ^^

**Comment by Jupi007** [comment]
> Edit: on the other hand would you have a "inconsistency" between the icon view selection and the treeview selection shrug

Well, let's make it grey too :)

```css
widget.view:selected {
  background: grey;
}
```

**Comment by Jupi007** [comment]
I only works in inspector :/
Well, let's keep treeview and regular view selection orange so.

**Review by Jupi007 — APPROVED** [review]

**Pull request merged**
