### PR TITLE
Sync symbolic icons with libadwaita upstream #3733

### PR DESCRIPTION
**Pull request by Jupi007**
**Linked icons:**

- actions/view-pin-symbolic.svg adw-tab-unpin-symbolic.svg
- ui/checkbox-symbolic.svg adw-tab-counter-symbolic.svg

**New one:**

Capture d’écran du 2022-09-27 19-26-56

Related to #3733

### CODE REVIEW

**Comment by Muqtxdir** [comment]
hi @Jupi007 i see some changes to mimetype icons in this branch as well, was this intentional?

**Comment by Jupi007** [comment]
Hmm, no this is not normal. I didn't noticed that 🤔

**Review by Muqtxdir — APPROVED** [review]
Thanks and sorry for the late review!

**Comment by Jupi007** [comment]
No problem, thanks :)

**Pull request merged**
