### PR TITLE
Revert "Terminal additions"

### PR DESCRIPTION
**Pull request by clobrano**
image

### CODE REVIEW

**Comment by madsrh** [comment]
> ...change the default variant of the terminal to dark...

IMO the is the best solution. The current white one is horrible and I really don't spent much time in the Terminal.

Alternatively we could change the color scheme [like suggested earlier](https://github.com/ubuntu/yaru/issues/29). I think the Unity 8 colors work better (_not perfect, just better_) with the light headerbar. Something like:

image

**Comment by didrocks** [comment]
As stated on IRC, I still think that the aubergine terminal is a strong branding asset for ubuntu and should be kept, I will let other commenting

**Comment by 8none1** [comment]
Yes, I'm a big +1 on aubergine.  Blue is moving too far away from our brand IMO.

**Comment by clobrano** [comment]
Do you mean aubergine in both light and dark variant? Or, as suggested previously, only in dark variant (as it is now), but setting Terminal to prefer dark variant (so that it will show aubergine by default)?

**Comment by 8none1** [comment]
I think that aubergine in both is the right call.

**Comment by Feichtmeier** [comment]
Merging after talking to @iainlane

**Pull request merged**
