### PR TITLE
Don't include entry:focus and entry selection in the jetpopoverwildcard

### PR DESCRIPTION
**Pull request by Feichtmeier**
Closes https://github.com/ubuntu/yaru/issues/1122

peek 2019-01-17 07-20

@madsrh and/or @clobrano please test

### CODE REVIEW

**Comment by clobrano** [comment]
Looks good :+1:

**Comment by clobrano** [comment]
> @clobrano I think something happened to that docker container, could you try to fix it? Or could you tell me how I can fix it? Is there some CLI connection possible to that container?
> I think there are also a bunch of branches/snaps opened
> The guy from snapcraft said that the more snaps we have the worse the performance becomes. I'll clean up some branches, would be good if you could also make a cleaning :D
> (Though the error seems to be connected to some apt stuff but the builds take quiet long currently)

Error seems just a timeout of operations. I'll retry to build first

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1123`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1123` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
everything seems right now, merging it

**Pull request merged**
