### PR TITLE
New full colour legacy actions for documents

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Hi guys,

Please test this PR if you can...  it includes document-save, -print, -new and open in six sizes.

I haven't done the 2x sizes but can if they're used.

Inkscape takes the 16px ones and Keepass takes the 22px...  if anyone knows any other apps that use them, please check they work!  (Or tell me and I will.)

image

image

I still think the printer is crap, but I'll redo document-print if I ever come up with a better full colour device icon  :)  and make sure they're consistent with each other.

These icons a little bit weird in terms of housekeeping... the script to generate pngs doesn't work on them, and even if it did, the source files include a non-standard size (22px).  I'm happy to make the pngs manually for these icons (it's a five min job) but we'll have to warn anyone else that there's a bit of a "gotcha" for these icons only.

### CODE REVIEW

**Comment by clobrano** [comment]
I tested with a few applications (transmission, keepassx, inkscape) and everything looks fine, great job! When you're ready, remove the "DON'T MERGE" disclaimer :)

**Comment by ubuntujaggers** [comment]
I changed it back to "DON'T MERGE" because I'll change the printer icon to match the new design.

**Comment by ubuntujaggers** [comment]
Okay, I've pushed this new document-print icon:

image

image

I'll make a PR for the matching device icon :+1:

**Comment by ubuntujaggers** [comment]
One sec, spotted an issue with 22px.

**Comment by Feichtmeier** [comment]
Double tested those - looks very nice!
image

image

**Comment by Amr-Ibra** [comment]
Please also push it to Bionic.

**Pull request merged**
