### PR TITLE
apps/nautilus: make infobar more visible

### PR DESCRIPTION
**Pull request by clobrano**
Closes: #1989

### CODE REVIEW

**Comment by Feichtmeier** [comment]
What I don't understand is, that I believe you want the users to actually see this better, but isn't a yellow color more visible than a gray color? :thinking:

**Comment by clobrano** [comment]
My point is to make visible that there is a label there, so just a different color is enough I think. Yellow is a warning color, I wouldn't use it

**Comment by Feichtmeier** [comment]
I don't have strong feelings on this and can live with both
Proceed as you wish :+1:

**Comment by clobrano** [comment]
Okay, I'll wait for @madsrh feedback, since he requested the change in the first place

**Comment by madsrh** [comment]
> For the trash I think it is a little bit more "dangerous" and the yellow fits, imo.

That's funny - IMO the yellow doesn't fit in Trash 😄 because it acts more like a header, where in Templates in highlights the actual information the users should read 🤷‍♂ 

What I was thinking (but failed to illustrate in the initial mockup) was something subtle like #fff4c9

image

It's pretty annoying that we can't target only Templates and not Trash, so gray might work better for both. That was a long way of saying +1 for this PR

**Pull request merged**
