### PR TITLE
Add GTK mate and mate-dark variants into master

### PR DESCRIPTION
**Pull request by Jupi007**
Add Gtk **mate** and **mate-dark** variants from `mate/jammy` branch into the `master` one.

**Note:** I also noticed the `GtkRange::slider-width` value in **default** variant was different from all other variants so I synced it.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Nice - I like the symlink approach 👍 
Better let @clobrano double check though

**Comment by Jupi007** [comment]
**Important note:** if you want to build this, be sure to delete the previous `build` folder, and also enable **mate** and **mate-dark** options in `meson_options.txt` !

**Review by Feichtmeier — APPROVED** [review]

**Comment by clobrano** [comment]
> **Important note:** if you want to build this, be sure to delete the previous `build` folder, and also enable **mate** and **mate-dark** options in `meson_options.txt` !

So, giving `$ meson setup build --reconfigure` is not enough?

I only checked the meson.build files and it looks good to me

**Review by clobrano — APPROVED** [review]

**Comment by Jupi007** [comment]
> So, giving `$ meson setup build --reconfigure` is not enough?

I tried to reconfigure the build on my computer but it fails, so I removed the `build` folder.

**Pull request merged**
