### PR TITLE
Added icon for subtitles

### PR DESCRIPTION
**Pull request by madsrh**
image

### CODE REVIEW

**Comment by clobrano** [comment]
Hey @madsrh, nice idea. I wonder if moving the balloons closer to each other would make it look more a chat related icon than a subs one?

**Comment by madsrh** [comment]
I don't really like the balloons 

Could something as simple as this work?

image

**Comment by Feichtmeier** [comment]
Wow, the second one is neat!

**Comment by madsrh** [comment]
Pushed new icon. Ready for merge if it's ok

image

**Pull request merged**
