### PR TITLE
Improving calendar-app-symbolic

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Current calendar symbol is a slightly unsuccessful 16px version of the app icon:

image

This is especially bad if it appears at a larger size in a notification:

image

This suggested PR changes it to the standard calendar appointment symbol used elsewhere:

image

image

Any thoughts/preferences?

### CODE REVIEW

**Comment by Feichtmeier** [comment]
I must admit that I like he difference between the app and the "function" ... Hmmm. Let's see what the others say

**Comment by clobrano** [comment]
I like this PR, also it is more in line with upstream approach

**Comment by Jupiter007-43** [comment]
I think the calendar looks better indeed.

**Comment by ubuntujaggers** [comment]
Any objections to merging?

**Pull request closed without merging**
