### PR TITLE
Sync Gtk4 with Libadwaita

### PR DESCRIPTION
**Pull request by Jupi007**
This is that I understand: Gtk theme is renamed to Default (was Adwaita) and will be simplified. So Libadwaita (which is a Gtk4 port of Libhandy) is now a superset of Gtk with more widgets. It is named Adwaita.
I compared Libadwaita scss with the Gtk one and it is exactly the same. Libadwaita just add more code for his own widgets.
So, Adwaita = Gtk default + Libadwaita (libhandy).

---

- Use Libadwaita repo as target for Gtk4 Actions
- Update Gtk4 upstream folder
- Import Libadwaita scss
- Reapply Yaru changes
- Import and update Gtk3 Libhandy Yaru changes
- Fix some problems

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thanks @Jupi007 
No time to review but I will schedule time for this!

I can confirm your observation from talking to the libadwaita maintainers!

**Comment by Jupi007** [comment]
> I can confirm your observation from talking to the libadwaita maintainers!

I was going to do it so it's good that you did it. Thanks :)

**Comment by Feichtmeier** [comment]
They also plan to split the big _common.scss file into smaller files for each widget in the future. But currently they only clean up _common.scss and add new widgets

**Comment by Jupi007** [comment]
All good news 😃

**Comment by Feichtmeier** [comment]
Just a general note to reduce your work, IMO we do not need to reproduce all of _tweaks here. If it looks different but is not broken, just keep it from upstream.
Maybe soon  is the time to discuss if we should change anything but the _colors file in the future

**Comment by kenvandine** [comment]
@3v1n0 Can you please help review this?

**Comment by 3v1n0** [comment]
I can give a look at the integration side, but I'll leave all the theming side to the Yaru guys

**Comment by Feichtmeier** [comment]
Thanks @3v1n0 for taking a look. As said on the other PR, @Jupi007 needs somehow to double check this - also from a theming perspective - as I am currently unable to spend much time on yaru and carlo is also AFK for yaru currently. I bet there is not much to fix, but yet, 4 eyes see more than 2 :D

**Review by Feichtmeier — APPROVED** [review]

**Pull request merged**
