### PR TITLE
Add drive-harddisk-system icon

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
You can see this icon in PCManFM-Qt, in Computer folder:

pcmanfm

Below my icon:
drive-harddisk-system

### CODE REVIEW

**Comment by clobrano** [comment]
In any case it loses any reference to the fact that represents a drive. -1 for me as well

**Comment by eaglersdeveloper** [comment]
Don't spoil my New Year mood 😞

**Comment by eaglersdeveloper** [comment]
I confine to Humanity icons.

**Comment by eaglersdeveloper** [comment]
> We could use the same icon the Toshiba drive uses instead

What is this icon?

**Comment by clobrano** [comment]
driver-harddisk.svg

**Comment by clobrano** [comment]
Closing this now, feel free to reopen if you think is right

**Pull request closed without merging**
