### PR TITLE
Remove floating particles from process-working icon

### LINKED ISSUE #2298: process-working-symbolic icon has floating particles

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Closes #2298

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
Do we need to test this one or does it "just work"?

**Comment by Jupiter007-43** [comment]
I really don't have any idea of where this icon should appears.
Theoretically, as I don't modified the shape it should working correctly.

**Comment by madsrh** [comment]
> I really don't have any idea of where this icon should appears.

I believe this is the one you'll find in the GTK inspector, but as you can see [here ](https://github.com/ubuntu/yaru/issues/1938#issuecomment-589927068)@Feichtmeier is the spinner master 😄

**Comment by Jupiter007-43** [comment]
> I believe this is the one you'll find in the GTK inspector,

Do you mean this one:

**Comment by madsrh** [comment]
Soorrryyyy 🙈 it's ofc the Widget Factory 🤦‍♂️ but I see you got it

**Comment by Jupiter007-43** [comment]
It seems to be all right!

**Comment by Feichtmeier** [comment]
If you want to see it live in action in a very big scale, you can open gnome-disks
Bildschirmfoto von 2020-07-31 12-03-01

**Comment by Jupiter007-43** [comment]
Thanks @Feichtmeier, the spinner looks ok on this app!

By the way, it is named Baobab 😉
This is Gnome-disks:

Capture d’écran du 2020-07-31 12-28-43

**Pull request merged**
