### PR TITLE
Revert Gtk4 theme to vanilla

### LINKED ISSUE #3704: Revert Gtk4 theme to vanilla
As Libadwaita apps aren't themable, it makes no more sense to base our theme on it.
Furthermore, it could create bugs in pure Gtk4 apps.

### PR DESCRIPTION
**Pull request by Jupi007**
Closes #3704

### CODE REVIEW

**Comment by Jupi007** [comment]
Current state:

image

Looks buggy, but upstream got the same look (upstream problem so).

**Comment by Jupi007** [comment]
Capture d’écran du 2022-09-15 12-30-30
Capture d’écran du 2022-09-15 12-30-22
Capture d’écran du 2022-09-15 12-30-16
Capture d’écran du 2022-09-15 12-29-59

Good news, yaru tweaks fixed all Gtk4 theme glitches!

**Comment by Feichtmeier** [comment]
Thank you for your work!

I am confused by the last screenshots? So this is how gtk4 looks now without libadaitwa?

**Comment by Jupi007** [comment]
Yes, gtk4 is very close to gtk3.
But it is imo necessary to use the vanilla gtk4 theme because it is that vanilla apps expects.

**Review by Feichtmeier — APPROVED** [review]

**Pull request merged**
