### PR TITLE
Post cosmic release: Suru icon updates

### PR DESCRIPTION
**Pull request by Feichtmeier**
- New icons from SNWH
Closes https://github.com/ubuntu/yaru/issues/821
- New icons from jaggers
Closes https://github.com/ubuntu/yaru/issues/861
Closes 
https://github.com/ubuntu/yaru/issues/923

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr901`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr901` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@didrocks can we merge this one and https://github.com/ubuntu/yaru/pull/899 ? Just wanted to double check...

**Comment by didrocks** [comment]
This is still quite large and have some color changes which is too much of an impact for a SRU IMHO.

I would prefer that we keep master cosmic-compatible for a couple of weeks (there is already one SRU I'm going to handle today), as this is the period we'll do most of uploads. The idea is to not add any additional maintenance for those 2 first weeks by committing to master + backporting to a separate cosmic branch.

After that, we can go crazy ;)

**Comment by Feichtmeier** [comment]
Updated with new shotwell icon by @ubuntujaggers

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr901`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr901` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
I seem to have lost the ability to use the snap since I updated to 18.10 - I can refresh it, so it's still there, but it doesn't change the gui.  Does the largest Shotwell icon look good when it's scaled down to app grid size?  That's the one bit I can never quite mock up!

**Comment by Feichtmeier** [comment]
@ubuntujaggers maybe login to the other session? :thinking: Didn't try the snap on cosmic yet

**Pull request merged**
