### PR TITLE
Replace disk image symbolic pictograms by fullcolor ones

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Related to #2271

Capture d’écran du 2020-07-23 10-43-09

### CODE REVIEW

**Comment by madsrh** [comment]
Look good to me 👍

**Comment by ubuntujaggers** [comment]
Interesting idea :+1: I personally would reduce the strength of the disc outline on the smaller icons, we don't normally use edging that strong inside the icon itself (although we sometimes do around the icon edge).  What do others think?

**Comment by Feichtmeier** [comment]
After you've said that this icon is the first mimetype that doesn't use the watermark I actually agree that we should revert the look to a more watermark icon. Though I don't know how we could apply this

**Comment by madsrh** [comment]
By "watermark" you mean monochrome?

**Comment by Feichtmeier** [comment]
No, less 3d. Like the other mimetypes :)

**Comment by Jupiter007-43** [comment]
I reduce small size shadows:

Capture d’écran du 2020-07-28 20-32-28

**Comment by Jupiter007-43** [comment]
Also remove the big size shadow:

Capture d’écran du 2020-07-28 20-39-19

**Comment by madsrh** [comment]
I wonder if flatter would be better?

image

**Comment by Feichtmeier** [comment]
Yes and then add the fold back I think. Then we'll get closer to the other mimetypes

**Comment by Jupiter007-43** [comment]
I did a flattest version:

Capture d’écran du 2020-07-29 10-41-30

I think we should keep reflections to avoid any confusion with other things.

**Comment by Feichtmeier** [comment]
That's cool. Could you try to add the folds back?

**Comment by Jupiter007-43** [comment]
With the folds:

Capture d’écran du 2020-07-30 10-37-07

**Comment by madsrh** [comment]
Let's merge the one without the folds, right @Feichtmeier ?

**Comment by Jupiter007-43** [comment]
Maybe just add the corner:

**Pull request merged**
