### PR TITLE
Add symlink for python3 files

### LINKED ISSUE #1167: Missing symlink for python3
Missing symlink for python3

image

### PR DESCRIPTION
**Pull request by madsrh**
closes #1167

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1169`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1169` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by eaglersdeveloper** [comment]
Add also symlink for `application-x-python-bytecode`

**Comment by madsrh** [comment]
> Add also symlink for `application-x-python-bytecode`

Let's merge this one and create a new PR for `application-x-python-bytecode`

**Comment by eaglersdeveloper** [comment]
...or create special icon

**Comment by clobrano** [comment]
Not sure about a special one for python byte code. Byte code is byte code,
the user usually don't mind much about these files

**Comment by Feichtmeier** [comment]
@madsrh :thinking: 
Some python3 files are not using the icon
image

**Comment by madsrh** [comment]
Can you check the file properties like here: https://user-images.githubusercontent.com/3986894/52527949-fadbb300-2cd1-11e9-8bd2-a5b3c8a511e8.png

**Comment by Feichtmeier** [comment]
image

**Comment by eaglersdeveloper** [comment]
> Not sure about a special one for python byte code. Byte code is byte code, the user usually don't mind much about these files

But what if user won't notice `.pyc` extension, open file and be surprised when see hexadecimal numbers?

**Comment by clobrano** [comment]
maybe I'm wrong, but I remember that there's already an icon for data or
non-text files

**Comment by clobrano** [comment]
maybe there's something wrong
screenshot from 2019-02-10 17-12-38

**Comment by clobrano** [comment]
It seems to work now, no clue what happend

image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1169`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1169` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Works! 
image

**Pull request merged**
