### PR TITLE
Add mime-icon for GIMP

### PR DESCRIPTION
**Pull request by madsrh**
Added mime icons for xcf and the compressed version. I've tried my luck with the symlinks 🤞 

I guess in most cases Nautilus will generate a preview of the GIMP file rather than use the icon. 

image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1179`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1179` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
There must be a problem with the rendering, the images are not visible, I'm trying to fix it

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1179`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1179` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
image

Both versions work for me (yeah.. nice file names right?)

**Pull request merged**
