### PR TITLE
symbolic: folder-open

### PR DESCRIPTION
**Pull request by Muqtxdir**
the current symbolic used for `folder-open` is to similar to `folder-drag-accept`, so re-did it to look more like opening folder

| current  | pr |
| ------------- | ------------- |
| folder-open-symbolic | folder-open-symbolic |

### CODE REVIEW

**Comment by Jupi007** [comment]
Thanks for the rework @Muqtxdir 
I really prefer your design over the previous one.

But I don't really see where this icon is used, can you provide a context screenshot, please?

**Comment by Muqtxdir** [comment]
@Jupi007 i don't actually have an idea where this icon is used generally. I refreshed it because _Adwaita_ refreshed it sometime ago in this release.

| adwaita (refreshed) | iteration1 | iteration2 (pr) |
| ------------- | ------------- | ------------- |
| folder-open-symbolic | folder-symbolic2 | folder-open-symbolic |

**Comment by Jupi007** [comment]
Honestly, I prefer the version 2. It looks more Yaru-ish :D

And what do you think of something like that:

image

**Comment by Muqtxdir** [comment]
>And what do you think of something like that:
image

it looks congested for me on 16x16 size and bit similar to closed folder?

**Comment by Jupi007** [comment]
Another idea:

image Capture d’écran du 2022-08-27 17-00-22  

_In fact I'd like to have a similar look to the fullcolor icon.
I really like your icon @Muqtxdir , but I have the feeling it doesn't fit because it doesn't look like the fullcolor one._

**Comment by Muqtxdir** [comment]
>_In fact I'd like to have a similar look to the fullcolor icon.
I really like your icon @Muqtxdir , but I have the feeling it doesn't fit because it doesn't look like the fullcolor one._

right i understand, we need to keep it consistent with full-color. could you push that here in this branch?

**Comment by Jupi007** [comment]
I'm really sorry @Muqtxdir, I didn't noticed that there was `folder-drag-accept-symbolic` and `folder-open-symbolic` 🙈
So I propose to keep your current proposal for `folder-open-symbolic`, and I'll push my version for `folder-drag-accept-symbolic`.

Wdyt ?

**Comment by Muqtxdir** [comment]
not a problem that you got confused. I'm okay with your suggestion. so you can push this for `drag-and-accept`

**Review by Jupi007 — APPROVED** [review]

**Comment by Muqtxdir** [comment]
thanks again! @Jupi007

**Pull request merged**
