### PR TITLE
Add missing icon for mimetype message-rfc822

### PR DESCRIPTION
**Pull request by madsrh**
image

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Wow nice lots of work there!

I'm not sure... This looks a little bit different from the other icons. The highlights and shadows and and so on. Could you reinvestigate this?

**Comment by madsrh** [comment]
@Feichtmeier sure, I just got tired of the white document with a gray symbol on, so I tried something more colorful.

I asked @ubuntujaggers to review (and edit / delete) the icons, to be sure that they are of the same style and quality.

**Comment by Feichtmeier** [comment]
The colours are great!

**Comment by madsrh** [comment]
> The colours are great!

$linkblue 😜

**Comment by madsrh** [comment]
image

**Pull request merged**
