### PR TITLE
gtk: grey selected filemenu item

### PR DESCRIPTION
**Pull request by clobrano**
Use popover hover color for menuitems inside the menu bar

see #1703 

image
image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Looking at your tab PR... Would MPT still be okay if we make the hovered menu items look like active tabs?

**Comment by clobrano** [comment]
This means making the menu grey?
I remember the idea was dropped in London though

**Comment by Feichtmeier** [comment]
No making the menu items look like your new tabs from your pr I meant

**Comment by clobrano** [comment]
However, to have the selected menu like the new tab, the rest of the menu should be gray as the unselected tabs are

image

**Comment by Feichtmeier** [comment]
Alright - sorry to diverge the discussion - if this is what MPT wanted then feel free to merge :+1:

**Comment by madsrh** [comment]
@clobrano are you sure that the orange line is needed? 🤔

**Comment by clobrano** [comment]
I think it helps differentiate the menu from the item selected in the drop down

**Comment by madsrh** [comment]
> I think it helps differentiate the menu from the item selected in the drop down

Okay, I think it's a bit like having belt and braces but NP. Perhaps it's because the gray is too dark (I know it's the same as in the menus). Especially comparing it to the Nautilus sidebar.

**Comment by clobrano** [comment]
Let's have it for a little while, then we can rethink about it

**Pull request merged**
