### PR TITLE
Making image mimetypes landscape

### PR DESCRIPTION
**Pull request by ubuntujaggers**
The generic image mimetype is landscape, but the mimetypes for svg, xcf and kra (all images) are portrait.  I've asked whether they should also be landscape.  This is a draft PR so you can try them in landscape and see if you like them, to help us make a decision.

image

image

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
Oh, and the Krita files are also landscaped:

image

**Comment by Feichtmeier** [comment]
Really cool idea. I think this is very intuitive!

**Comment by madsrh** [comment]
This is a good idea. It makes totally sense, but it still takes some getting used to.

I tried the opposite - rotating the generic image to portrait, but just feels odd.

I'm going to test this PR for a while a see how it feels, but for now I'm definitely  +1 😃

**Comment by ubuntujaggers** [comment]
Magic - I'll look at the other mimetypes, and if anyone can think of any others that are images or videos, name them here and I'll add them to the branch.

I'll also make the video icon have the same ratio as the image mimetypes. Then we'll have one mimetypes "rule" made consistent 👍

**Comment by ubuntujaggers** [comment]
(You will likely have to turn off thumbnails in Nautilus to test.)

**Comment by madsrh** [comment]
> if anyone can think of any others that are images or videos

3D files (stl or blender) comes to mind, but I think that's a different category.

> I'll also make the video icon have the same ratio as the image mimetypes. Then we'll have one mimetypes "rule" made consistent

Nice 🎉

**Comment by Jupiter007-43** [comment]
Really good idea 👍
It looks very cool and consistent!

**Comment by ubuntujaggers** [comment]
I added the Blender and Karbon mimetypes 👍

**Comment by ubuntujaggers** [comment]
Anyone object to me merging?

**Pull request merged**
