### PR TITLE
common/scale circular slider: made border transparent in dark variant

### PR DESCRIPTION
**Pull request by clobrano**
In the dark variant, gtkscale slider border looks fuzzy, probably due to
the different contrast between a dark background (in the light variant
the background is brighter and the border does not look fuzzy).

With this commit, the gtkscale slider border is set to transparent to
dark variant only to have a sharper border.

NOTE: a similar change is to be made to the 'scale with marks', however
that is a svg image and belongs to the gtk/dark folder which has not yet
landed on master.

see #885

### CODE REVIEW

**Comment by Feichtmeier** [comment]
I'm curious: doesn't this make the whole knob smaller?

**Comment by clobrano** [comment]
I thought the same at first, but the border is above the background, not
aside, so making it transparent just shows the background color. Making the
border white, instead, produce some glitches, this is why I opted for
transparent.

**Comment by Feichtmeier** [comment]
Awesome!

Can we merge to master again btw?

**Comment by clobrano** [comment]
I think so, however we probably need to change the CI scripts to build snaps for cosmic

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr909`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr909` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Pull request merged**
