### PR TITLE
Finalize changelog

### PR DESCRIPTION
**Pull request by clobrano**

### CODE REVIEW

**Comment by didrocks** [comment]
Excellent! +1 for me :)

**Comment by Feichtmeier** [comment]
Is this the last time this repo will be merged into 19.4?

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1093`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1093` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
I don't have gpg set up in this machine tough, so I can only tag this "normally"

**Comment by iainlane** [comment]
> Is this the last time this repo will be merged into 19.4?

Unlikely, but this follows the 18.10 convention:

```
2018-10-22 15:57:30 +0200  (tag: 18.10.7)
2018-10-10 10:36:15 +0200  (tag: 18.10.6)
2018-10-01 14:11:21 +0200  (tag: 18.10.5)
2018-09-12 17:03:01 +0200  (tag: 18.10.4)
2018-09-05 17:28:30 +0200  (tag: 18.10.3)
2018-08-17 18:00:26 +0200  (tag: 18.10.2)
2018-08-01 16:33:29 +0200  (tag: 18.10.1)
2018-07-25 12:11:43 +0200  (tag: 18.10)
```

@clobrano I'll do a signed tag when uploading, you can pull that from my fork - will ping you when that's done.

**Comment by clobrano** [comment]
Ready again :+1: 

@iainlane, not sure about the workflow. Once the tag is ready, I have to merge this PR in master and then...? :)

**Comment by iainlane** [comment]
Like this:

  * You can merge now please
  * I check / build, if OK then I'll make a signed tag
  * I'll push that to my fork on github
  * You can grab the signed tag from there and push it to here

I like this way because the tag is signed by the person who releases to Ubuntu.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1093`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1093` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Ok (I didn't know I can pull a tag from a fork, good news :) )

Merging now

**Comment by iainlane** [comment]
@clobrano thanks, I just uploaded to disco. You should be able to do something like (untested): `git fetch git@github.com:iainlane/yaru.git --tags && git push origin 19.04` assuming `origin` is the main repository.

:man_dancing:

**Comment by clobrano** [comment]
@iainlane, changed protocol to https, but done! :+1:

**Pull request merged**
