### PR TITLE
Use Aubergine as second accent color instead of blue

### LINKED ISSUE #1723: Shell slider color must be visible with hover
We should pick a color for the shell sliders that has good contrast against the background and also when hovered. A border might also help.

Current:
image

`#8e3773` with a border
image

### PR DESCRIPTION
**Pull request by clobrano**
As per PR title, this change is a try for replacing the blue with aubergine. The color relationships between the widget that used blue are kept the same, that is:

- checkradio, switch and progress bar share the same dark tone (aubergine in this case)
- focus ring is a lighter variant than the color for the widgets above
- **link color is still blue**, since aubergine is usually used for "visited link" and might be misunderstood  

TODO:
- [x] fix #1723
- check what gtk2 is using (probably only orange, but let's double check) -> see #1730 
- [x] shell dark: slider handle is too dark
- gtk dark: slider-has-mark... is too dark (review the assets) -> see #1728
- [from @madsrh] consider #6e3c61 as base aubergine (for checkboxes, sliders, switches) -> see #1731 
- [x] fix scrollbar through color on osd

EDIT: to avoid blocking development too much, I opened bug/discussion tickets for the remaining open points, so that we can merge this PR if you also think it's ready.

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
Looks great!  Are volume and brightness sliders in the top right still meant to be dark blue?  They are for me...

**Comment by Feichtmeier** [comment]
Yeah I guess it's not in the shell yet

**Comment by flexiondotorg** [comment]
Testing this branch, looks fab. Just need the shell to get some aubergine to complete to look :-)

**Comment by clobrano** [comment]
I'll complete it with the shell part :+1:

**Comment by clobrano** [comment]
image

**Comment by Feichtmeier** [comment]
Could you set the 
```$switch_border_color: darken($switch_bg_color, 35%)```
Before you merge?
It improves the crispness of the switches in the dark gtk theme :D

**Comment by Feichtmeier** [comment]
@clobrano I think the not checked sliders also need some tiny color corrections. Background, border and the knob looks brighter for the light theme in gtk I think
But maybe this whole nit picking can be done after this PR, even though I do not think we are in a hurry at all

**Comment by ubuntujaggers** [comment]
Loving the purple sliders :+1:

**Comment by clobrano** [comment]
After having synchronized the slider colors between gtk and shell, and more specifically the color of the through, I noticed this side effect

image

now the through's color is the same as the background of the osd. Mind if I lighten up the osd to match the shell popovers?

**Comment by Feichtmeier** [comment]
I would rather use osd_fg_color or a slightly darkened white for the active trough
The purple doesn't have a good contrast on the dark and if you brighten up more, it's magenta

**Comment by clobrano** [comment]
I'll try it. It might clash with the overdrive, but let's see

**Comment by clobrano** [comment]
to avoid blocking development too much, I opened bug/discussion tickets for the remaining open points, so that we can merge this PR if you also think it's ready.

**Pull request merged**
