### PR TITLE
Adapted icon `application-x-theme`

### PR DESCRIPTION
**Pull request by gusbemacbe**
Hello @clobrano , @eaglersdeveloper , @Feichtmeier, @madsrh, @ubuntujaggers and @vitalkanev

In reference to #1159 ...

Following Sam Hewitt's colours and grid rules, I have just updated the icon `application-x-theme`, but I let you choose the alternatives. The first alternative must be good, but is not legible. 

alt 1

Maybe purely Suru, but not legible:

alt 2

Now better, blue is one of the most pleasant colours, but Yaru is not orange...

alt 3

Well, purple/violet is symbol of elegance and nobleness, used more in the clothing by elegant people, so themes are designed to keep the OS beautiful and elegant:

alt 4

Conservative, common, legible and traditional:

alt 5

Finally, maybe, purely Suru and Yaru, so Ubuntu and Yaru are orange:

alt 6

### CODE REVIEW

**Comment by clobrano** [comment]
Hi @gusbemacbe, nice job! I like the purple one. Just one question, is there a specific reason to have the "change tone line" not centered?

**Comment by gusbemacbe** [comment]
> Just one question, is there a specific reason to have the "change tone line" not centered?

Are you referring to folder effect or the brush's holder? The brush followed the original icon's height size and original icon's y position. I will test, redoing.

**Comment by clobrano** [comment]
Yes, the fold effect. Looking better, it's probably because the "page" is folded by a half, but the image is not symmetrical, so it's not possible to have the fold cutting it in a perfect half, so no worries

**Comment by Feichtmeier** [comment]
I would prefer the grey because most mimetypes are rather conservatively grery (I think)
But could live with any of them

**Comment by madsrh** [comment]
> I would prefer the grey because most mimetypes are rather conservatively grery (I think)

The purple is nice, but I was thinking the same.

**Comment by gusbemacbe** [comment]
Hi @madsrh , are you meaning the half in the icon with folder effect...

application-x-theme-half

Is it like what you wanted exactly?

**Comment by gusbemacbe** [comment]
Scusami, ma @clobrano, dove stai tu?

**Comment by gusbemacbe** [comment]
Hey @Feichtmeier and @madsrh , let me ask you. Which one of brush icons: asymmetrical or symmetrical?

**Comment by Feichtmeier** [comment]
@gusbemacbe symmetrical! :)

**Comment by gusbemacbe** [comment]
@Feichtmeier, OK, does the last image look symmetrical for you?

**Comment by Feichtmeier** [comment]
Yes!

**Comment by clobrano** [comment]
> Scusami, ma @clobrano, dove stai tu?

I'm from Italy, but let's keep the discussion on the icon :D

**Comment by gusbemacbe** [comment]
> I'm from Italy, but let's keep the discussion on the icon :D

No, I am meaning "where are you?", because you have disappeared. But let's focus on the icon... Does the last image look symmetrical for you?

**Comment by clobrano** [comment]
LOL, I misunderstood ;D

My reply about the fold is [here](https://github.com/ubuntu/yaru/pull/1358#issuecomment-491618038), but I do prefer the symmetrical one

**Comment by Feichtmeier** [comment]
@gusbemacbe could you also provide the exported PNGs? We are still on the PNG train because ubuntu uses the 48px dock size by default

**Comment by gusbemacbe** [comment]
OK, I will prepare the redesign. 

@Feichtmeier 

I will be cautious to export, because I am afraid of running `/yaru/icons/src/symlinks/generate-symlinks.sh` because this script breaks and destroys the icons in the Suru folder, so I did it once.

**Comment by gusbemacbe** [comment]
Ready, I have just updated the redesign and provided the PNG icons cautiously.

**Comment by gusbemacbe** [comment]
Observe that I do not know how to generate icons, applying @2x in Inkscape.

**Comment by gusbemacbe** [comment]
Done and ready. :-)

**Comment by Feichtmeier** [comment]
Thank you !
@clobrano pimped the suru scripts so you can now pass 1 icon name as the argument and you don't generate thousands of other symlinks you didn't want to generate

We'll test this and merge it if everything is fine! Thank you very much

**Comment by clobrano** [comment]
> Thank you !
> @clobrano pimped the suru scripts so you can now pass 1 icon name as the argument and you don't generate thousands of other symlinks you didn't want to generate
> 
> We'll test this and merge it if everything is fine! Thank you very much

I'll update it again to show the functionalities, since it's hard to spot them otherwise

**Comment by clobrano** [comment]
Thanks @gusbemacbe, nice work :+1: 
Could we try a brighter gray, though? It feels too strong close to the other mimetypes

image

**Comment by gusbemacbe** [comment]
I will redesign now.

**Comment by gusbemacbe** [comment]
Which is a bit brighter grey?

application-x-theme-alt1

application-x-theme-alt2


application-x-theme-alt3

**Comment by clobrano** [comment]
The last one? @madsrh, @ubuntujaggers @Feichtmeier

**Comment by madsrh** [comment]
Yes, the last fits best IMO

**Comment by gusbemacbe** [comment]
Sorry for the late, I was in the gym. I will update the colour now.

**Comment by gusbemacbe** [comment]
Ready and done.

**Comment by Feichtmeier** [comment]
Tested - looks nice !
image

image

**Comment by Feichtmeier** [comment]
Okay, thank you very much @gusbemacbe !

Merging that

Todo after:

- [ ] cherry pick this into the bionic branch

**Pull request merged**
