### PR TITLE
Add configure icons

### LINKED ISSUE #2471: Configure action icon
## Icon Request

**Name:** `configure` action.
**Category:** Actions.
**Description:** This action usually used to display settings toolbutton in various applications.
**Examples:** [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/24x24/actions/configure.svg), [Breeze](https://github.com/KDE/breeze-icons/blob/master/icons/actions/32/configure.svg).

Can be linked to existing `system-settings` icon.

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Symlink document-properties-symbolic icon to configure-symbolic one.

@Shatur95 Can you test this PR please?

Closes  #2471

### CODE REVIEW

**Comment by Shatur95** [comment]
Can you provide also `configure` icon (e.g. without `-symbolic`)? Most icon themes usually provides such icon.

**Comment by Jupiter007-43** [comment]
I've added it.

**Comment by Shatur95** [comment]
Thank you! Maybe it will be better to just symlink `configure` with `system-settings`?

**Comment by Jupiter007-43** [comment]
> Thank you! Maybe it will be better to just symlink `configure` with `system-settings`?

In fact I cannot because it is located in another folder (**action** for configure and **apps** for system-settings). Our symlink script doesn't permit to do that.

**Comment by Shatur95** [comment]
Okay, thanks!

**Pull request merged**
