### PR TITLE
Tone down accents from quick settings

### LINKED ISSUE #3716: White text on orange background in GNOME 43 quick settings
**Expected Behavior**

Nice and readable colors

**Actual Behavior**

Low contrast - white text on orange background

**Steps to Reproduce the Problem**

1. Run the latest Ubuntu 22.10 Kinetic Kudu
2. Open quick settings
3. Toggle some of the buttons on

**System information**

- Shell version: GNOME Shell 43.beta
- OS version: Ubuntu 22.10 Kinetic Kudu (development branch)

**Yaru version**

22.10.1

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Jupi007**
**Before:**

Capture d’écran du 2022-09-01 11-16-24
Capture d’écran du 2022-09-01 11-16-11

**After:**

Capture d’écran du 2022-09-01 11-07-51
Capture d’écran du 2022-09-01 11-08-17

Fixes #3716

### CODE REVIEW

**Comment by Feichtmeier** [comment]
I personally think this is much better - how does the light theme look?

**Comment by Jupi007** [comment]
I also think so. This looks very much better!
I'm currently not at home, I'll share light theme screenshots this evening.

**Comment by Jupi007** [comment]
Here they are :)

Capture d’écran du 2022-09-01 22-10-29
Capture d’écran du 2022-09-01 22-10-12

**Comment by Feichtmeier** [comment]
Hm this is hard. Even though the orange burns your eyes you can be sure that orange means ON
Wheras in the light theme it is a tough call 🤔

**Comment by Jupi007** [comment]
I agree, I also have mixed feelings about this...

What about something like this:

Capture d’écran du 2022-09-01 22-50-55

**Comment by Muqtxdir** [comment]
> What about something like this:

This looks a good compromise for the aggressive orange

**Comment by Feichtmeier** [comment]
> I agree, I also have mixed feelings about this...
> 
> What about something like this:
> 
> Capture d’écran du 2022-09-01 22-50-55

This looks good
But how does this work with the white text in the dark theme? :see_no_evil:

**Comment by Jupi007** [comment]
Looks like this in dark theme:

Capture d’écran du 2022-09-02 10-39-58

**Comment by Feichtmeier** [comment]
I think this is a good compromise. Double check with the team better

**Comment by Jupi007** [comment]
Works also very well with other colors:

Capture d’écran du 2022-09-02 11-15-58
Capture d’écran du 2022-09-02 11-15-50
Capture d’écran du 2022-09-02 11-15-14
Capture d’écran du 2022-09-02 11-15-04
Capture d’écran du 2022-09-02 11-13-44
Capture d’écran du 2022-09-02 11-12-55

**Review by Feichtmeier — APPROVED** [review]

**Comment by Jupi007** [comment]
@Feichtmeier wait I didn't pushed the new changes :)

**Comment by Feichtmeier** [comment]
Woops sorry 😁

CC @madsrh @clobrano @ubuntujaggers @Muqtxdir 
Could you please take a look if this solution is okay for you?

**Comment by Muqtxdir** [comment]
>CC @madsrh @clobrano @ubuntujaggers @Muqtxdir
Could you please take a look if this solution is okay for you?

sure, I'll tryout this branch whenever @Jupi007 pushes. 😀

**Comment by Jupi007** [comment]
Oh, sorry I totally forgotten 😅
I still need to find the correct implementation, but I'll push the wip state which works fine.

**Comment by Jupi007** [comment]
Done I pushed the WIP implementation.
The only WIP part is the hover/active state which aren't looking good.
But the normal color should be the definitive one :)

CC @madsrh @clobrano @ubuntujaggers @Muqtxdir

**Comment by Muqtxdir** [comment]
@Jupi007 I'll test this out today evening

**Comment by madsrh** [comment]
This looks good @Jupi007 👍

**Review by Muqtxdir — APPROVED** [review]
as mentioned by others here in this pr, this is indeed a better solution for quick toggles. I've tried both light and dark themes from across our accent-colors palette and I feel except for `sage` all of them look visually better.

**Comment by Jupi007** [comment]
How doe, it looks with `sage`?

**Comment by Muqtxdir** [comment]
### bark:
image
image

### sage:
image
image

**Comment by Muqtxdir** [comment]
It's alright in `dark`, but in `light` they both mix very very little bit with some of grey shades

_anyways, it's more like a nitpick. do you think the same?_

**Comment by Jupi007** [comment]
Hmm, I think I can find solution.
Maybe compute the saturation of the accent, then interpolate the opacity...

**Comment by Jupi007** [comment]
Final version:

Capture d’écran du 2022-09-14 23-28-04
Capture d’écran du 2022-09-14 23-27-57
Capture d’écran du 2022-09-14 23-27-49
Capture d’écran du 2022-09-14 23-27-42

@Muqtxdir I interpolated the opacity from the accent saturation.

**Review by Feichtmeier — APPROVED** [review]

**Comment by Jupi007** [comment]
Merging, we need this before the UI freeze.
Small adjustments can be done after, once the global looks is freeze.

**Pull request merged**
