### PR TITLE
Add geary icons

### LINKED ISSUE #2238: Missing icons into Geary
Some icons into Geary are missing:

Capture d’écran du 2020-07-09 13-24-37

Complete list here: https://gitlab.gnome.org/GNOME/geary/-/tree/mainline/icons
There are many so I can help if you want.

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Sorry for committing so much, but like that I can revert easily to a clean source file. I can collapse them if you want.

Here are all new icons:

Capture d’écran du 2020-07-17 16-37-06

And a screenshot of Geary:

Capture d’écran du 2020-07-17 16-42-21

@ubuntujaggers I put all these icons into the Actions layer, it is right?

Closes #2238

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Really cool work, thank you!

**Comment by ubuntujaggers** [comment]
Superb work!!

**Comment by ubuntujaggers** [comment]
Built the branch, the icons look beautiful in the app :+1:

**Comment by Jupiter007-43** [comment]
Thank you very much 😊

**Pull request merged**
