### PR TITLE
Add text on archives icons

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Related to #2271

This PR adding descriptive text on archives icons.

Capture d’écran du 2020-07-27 13-43-17

### CODE REVIEW

**Comment by madsrh** [comment]
Thank you @Jupiter007-43

**Comment by Jupiter007-43** [comment]
Capture d’écran du 2020-07-27 14-40-11

I used `#232629` text color for zip because I didn't know which one use. It is good or should I modify it?

**Comment by Jupiter007-43** [comment]
With a lighter grey (`#5d5d5d`):
Capture d’écran du 2020-07-27 14-44-31

**Comment by madsrh** [comment]
👌 Much better with the lighter text. Ready for merge?

**Comment by Jupiter007-43** [comment]
I'm ready!

**Pull request merged**
