### PR TITLE
[WIP] Add cinnamon theme

### PR DESCRIPTION
**Pull request by ItzSwirlz**
I want to put the yaru-cinnamon theme as a built in the official yaru source package (which would prevent me from having to ask for it in my PPU application), or at least have cinnamon theme support for Yaru. For now, theme support for cinnamon.

Obviously i'll push a lot but I'll be eventually soft resetting to put it one push. The cinnamon theme is straight forward, it just requires (like unity) a theme folder named cinnamon inside of it. You can see the current theme files at https://github.com/Ubuntu-Cinnamon-Remix/yaru-cinnamon, so I'll be busy :P  

IRC is ItzSwirlz, in -devel, -flavors and -desktop.

The cinnamon theme contains icons and a folder with CSS similar to gnome-shell (which is a minor blessing) with some icons to round it up.

- [ ] cinnamon.css generation with Sass (@Jupi007?)
- [ ] Symlinking cinnamon theme icons
- [ ] /usr/share/ symlinked icons
- [ ] Dark/light theme
- [ ] Connect everything above to the meson build
- [ ] Debian packaging

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Hi @ItzSwirlz !
thanks for your PR :)

@Jupi007 just landed a change so we have a proper organisation of app specific scss code inside a apps sub dir in gtk3.20 dir. 
Could you update your PR to those changes?

Thanks and best regards

**Comment by ItzSwirlz** [comment]
I could try but this will still take a while. If you look at the cinnamon theme folder there is common assets and dark assets-the cinnamon folder will have to be managed like a gnome-Shell folder because it's not all icons. I am likely going to need help with this and this is kind of a hard thibg. I already have Yaru-Cinnamon done but it has to be integrated into the main repo so I'm following the instructions but it needs additional work.

I couldn't see how the hirsute/mate branch would have helped me because it didn't have a MATE theme folder or anything, just icons which will likely be easier. But for now I have to deal with Scss stuff.

This is going to be hard and this will prevent two source packages but it will be worth it.

**Comment by Feichtmeier** [comment]
Okay! As long as the app specific scss code is located in a dedicated file in the new apps dir, an additional dir for cinnamon is totally fine!

**Comment by ItzSwirlz** [comment]
Initu Castilhos, who commonly helps a lot with yaru-cinnamon added some help with apps.scss

**Comment by Jupi007** [comment]
If you want I can help you a little for the scss part, just ping me :)

Just a note for your new icons: you should add a template inside `/src` to facilitate updates. `/Suru` only contain bitmaps generated from `/src`.

**Comment by ItzSwirlz** [comment]
> If you want I can help you a little for the scss part, just ping me :)

Awesome, I was just thinking about the libreoffice stuff too. hah. i'll keep it local until later.



> Just a note for your new icons: you should add a template inside `/src` to facilitate updates. `/Suru` only contain bitmaps generated from `/src`.

y i k e s, not really any since cinnamon is Mint but there is some cs icons I can put in.

**Comment by ItzSwirlz** [comment]
Wow, I found not just the icons you suggested but also main cinnamon theme upstream files (like unity/gnome-shell's upstream folder)!

Now, some of the icons don't fit with the color.. where a lot of them are placed are in folders where all of them are just gray/transparent color, but it's what upstream had. I guess we can issue them if we need.

**Comment by ItzSwirlz** [comment]
Realizing it, I will replace the brown cinnamon settings (cs) icons with the normal purple ones that was taken I believe from some project called Yaru-For-All. Then when we can produce a #DD682A version of the theme.. we'll get to that later.

**Comment by ItzSwirlz** [comment]
With the Libera transition and all, and I kind of forgot what I was doing so I pushed up the cinnamon assets. Lets work from there, and get the icons going. Remember that I want normal Ubuntu yaru theme support for Cinnamon, then have a #DD682A variant.

**Comment by ItzSwirlz** [comment]
I've noticed the cinnamon-settings icons (cs-*) are a .png but the symlink list is all .svg, except for fullcolor which is not what we have. Can I still symlink .pngs anyways?

**Comment by Muqtxdir** [comment]
Hi @ItzSwirlz the full colors icons should be symlinked to **.png** files and symbolic icons should be symlinked to **.svg** files

**Comment by Jupi007** [comment]
> @Jupi007 i guess i'm ready for scss :)

Okay, I'm currently downloading a cinnamon iso, so I can create a virtual machine :)
What kind of help do you need?

**Comment by ItzSwirlz** [comment]
> What kind of help do you need?

Only the cinnamon.css in gtk/src/default and gtk/src/light. I'll take care of everything else unless it's super hard and I need help (I should learn Sass too :))

Thanks again for offering to help!

**Comment by Jupi007** [comment]
So you want I convert the css files into Sass, no problem :)
I created a Cinnamon VM yesterday, maybe I'll also do the meson part, so I can try in real if everything build and works as expected.

**Comment by Jupi007** [comment]
@ItzSwirlz I'm currently looking at all this cinnamon stuff, and shouldn't all these files be moved to a root subfolder (just like gnome-shell), because it's really not related to Gtk. What do you think of?

**Comment by Muqtxdir** [comment]
@Jupi007 I suggest you to start a fresh in another PR because most of the parts contribute by @ItzSwirlz seems not in the right place for meson and take parts from this PR as you proceed. WDYT ?

**Comment by Muqtxdir** [comment]
also @ItzSwirlz please provide a list of **_icon-names_** that need to be symlinked for cinnamon maybe in a separate issue-ticket so that way @Jupi007 can use them

**Comment by Jupi007** [comment]
Yes, a fresh PR could be better. But I would prefer let him have the possibility to push directly on the correct PR, so @ItzSwirlz should create a new branch on his fork and then create a fresh PR.

@ItzSwirlz Sorry, but can you create a new PR, and put all cinnamon css and assets files inside a new `/yaru/cinnamon/src/default/` folder for light variant and a new `/yaru/cinnamon/src/dark/` folder for dark variant?

**Comment by ItzSwirlz** [comment]
Hey guys. I can definitely do all of that.



> @ItzSwirlz I'm currently looking at all this cinnamon stuff, and shouldn't all these files be moved to a root subfolder (just like gnome-shell), because it's really not related to Gtk. What do you think of?

Yes. That's what I wanted to do, but with the Sass and common assets and meson I figured it'd be a bit crazy, so I thought that Cinnamon (and Unity too!) could be put in it's own root subfolders in another PR after



> also @ItzSwirlz please provide a list of **_icon-names_** that need to be symlinked for cinnamon maybe in a separate issue-ticket so that way @Jupi007 can use them

I was working on that. One issue is that the cinnamon-settings icons are actually marked in /apps, not /categories. This is because they can be launched from Start, so some more advanced symlinking (e.g. ../categories/) may be needed and I'm testing to see if that works.



> Yes, a fresh PR could be better. But I would prefer let him have the possibility to push directly on the correct PR, so @ItzSwirlz should create a new branch on his fork and then create a fresh PR.
> 
> @ItzSwirlz Sorry, but can you create a new PR, and put all cinnamon css and assets files inside a new `/yaru/cinnamon/src/default/` folder for light variant and a new `/yaru/cinnamon/src/dark/` folder for dark variant?

Sure thing! I won't delete the cinnamon-theme branch so we have it for reference.

**Pull request closed without merging**
