### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Feichtmeier**
Add ruby dependency, which is needed to export the symbolic icons

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1236`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1236` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Not sure it's necessary in this level. The dependency is already reported in `icon/src/scalable/README.md`. Maybe it is enough to say to read `icon/CONTRIBUTING.md` if interested in icons

**Comment by Feichtmeier** [comment]
But it's nice to have the string ready to copy paste on a new installation :) doesn't hurt tbh

**Comment by clobrano** [comment]
I know it does not hurt (isn't ruby preinstalled?), but I find it misleading. One needs ruby only if he/she wants to work on symbolic icons

**Comment by Feichtmeier** [comment]
No it's not preinstalled :D

Same logic could be applied for inkscape and optipng though

But who would not want to work on the icons if he wants to become a contributor?

**Comment by clobrano** [comment]
> But who would not want to work on the icons if he wants to become a contributor?

Well, anybody who doesn't know how to change icons :D 

Ok, fine for me

**Comment by Feichtmeier** [comment]
Or we could remove the three icon packages and and some handy strings for lazy People at the bottom of the file :)

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1236`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1236` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Okay like this @clobrano ?

**Comment by clobrano** [comment]
Great!

**Pull request merged**
