### PR TITLE
apps/nautilus: fixed circular button backdrop transition

### LINKED ISSUE #840: Nautilus circular stop button issues
The ring is slightly visible when the window is in the foreground (super soft ring)
The ring is visible when switching to backdrop

peek 2018-09-19 16-09

### PR DESCRIPTION
**Pull request by clobrano**
closes #840

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr842`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr842` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
peek 2018-09-20 11-45
The ring in the backdrop transition is gone! :+1: 

But there is still a super hard to see ring in the active window... I know this is really hairsplitting. But if you can easily fix it would be great. If not just merge
image

**Comment by clobrano** [comment]
I'm unable to check the hover effect, but circular ring should be fine now

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr842`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr842` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
peek 2018-09-20 12-33
Looks good!

**Comment by clobrano** [comment]
It's weird, I don't see the border in hover. However I pushed a change similar to the one I pushed before in hover state.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr842`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr842` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
peek 2018-09-20 17-20

**Comment by clobrano** [comment]
Oh, could it be the box-shadow effect that buttons have

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr842`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr842` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
peek 2018-09-20 22-50
Fixed!

**Pull request merged**
