### PR TITLE
Adding colour icons for headphones and headset

### LINKED ISSUE #1930: Full color headset icon is missing
image

### PR DESCRIPTION
**Pull request by ubuntujaggers**
I have no idea if this will look any good in context - would someone with bluetooth headphones mind testing?  It shouldn't be this saturated in reality, the images are compressed here:

image

image

It's extremely hard to come up with a Yaru-styled image that works at the small sizes too  :(

Closes #1930

### CODE REVIEW

**Comment by madsrh** [comment]
I'm really not a fan of the colored backplate. I haven't got a better suggestion, but just wanted to mention it.

**Comment by Feichtmeier** [comment]
Bildschirmfoto von 2020-03-03 21-25-14
I disagree - I like it, especially when you see it in the app. Only the colors are a bit too strong as discussed

**Comment by Feichtmeier** [comment]
Bildschirmfoto von 2020-03-03 21-31-24
Bildschirmfoto von 2020-03-03 21-33-39

I like it ^^

**Comment by clobrano** [comment]
What might be against the colored backplate is that on a light background it kinda stole the attention from the actual icon, but as Mads I didn't have a better option, and this is anyway a good one, so :+1:

**Pull request merged**
