### PR TITLE
Yaru legacy actions for Inkscape - work in progress

### PR DESCRIPTION
**Pull request by ubuntujaggers**
@Feichtmeier expressed some enthusiasm for doing legacy actions after all, so here's a work-in-progress branch that people can test  :)

Joint credit to @bonandry (and thanks to @gusbemacbe to sharing) because I used some of his svgs with minor amendments.  The flipping and layer tools along the top left were really nice :+1: and are used here.

It's not complete yet, and some of the icons need further work, but let's start the testing and feedback now.

image

### CODE REVIEW

**Comment by gusbemacbe** [comment]
Hello, @ubuntujaggers 

Actually @Bonandry has finished and completed the icons pack, including both dark and light. Sorry for my late. I was very sick, needed to rest for some hours, in my grandparents' house, had to help a lot my mother, my grandparents' pet and take care of their house. But here is his pack:

[complete-inskcape-icons.zip](https://github.com/ubuntu/yaru/files/4263686/complete-inskcape-icons.zip)

light

dark

**Comment by ubuntujaggers** [comment]
I like these and might will that zip for the svgs!

image

**Comment by Amr-Ibra** [comment]
I noticed that in this PR there are -symbolic icons, which already exist in Yaru. I think this duplication is not necessary.

**Comment by madsrh** [comment]
I'm really loving this @ubuntujaggers 🎉 You're off to a good start 💪 The only tiny bit of feedback I have, you can just throw away if you feel different 😄 

I really couldn't tell what the calligraphy tool icon was 🙈 What do you think about something like the one on the right from Numix?
image
 It works in both light and dark 
image

**Comment by gusbemacbe** [comment]
Hello @Feichtmeier, @madsrh and @ubuntujaggers !

Here are latest two previews that @Bonandry has redesigned and improved;

image

image

**Comment by ubuntujaggers** [comment]
@amr-ibra you're right - just got this up so people could try them, will clean up the branch before I take it out of draft :) they're just in the folder at the minute for my personal reference

**Comment by ubuntujaggers** [comment]
Thanks @gusbemache, I've got my eye on a few of those and will harmonise the highlights etc.

**Comment by ubuntujaggers** [comment]
Latest:

Screenshot from 2020-03-01 14-56-10

**Comment by gusbemacbe** [comment]
Hello @ubuntujaggers 

@Bonandry has completed three icons. Here is: 
[da_aggiungere.zip](https://github.com/ubuntu/yaru/files/4275928/da_aggiungere.zip)

**Comment by ubuntujaggers** [comment]
I've just pushed the latest changes.  All the ones along the top (now including the transform options) are lightly adapted from icons by @bonandry.  I've also added the dialogue icons that are visible in this screenshot and the last couple on the right hand bar that were missing.

Screenshot from 2020-03-02 21-28-40

Among other tweaks, I've coloured the transform options so they show up nicely in both light and dark theme:

image

image

**Comment by gusbemacbe** [comment]
HI @ubuntujaggers !

Here are the previews of icons in dark environment, made by @Bonandry and the pack:

[16-colour.zip](https://github.com/ubuntu/yaru/files/4279699/16-colour.zip)


- Asunder

asunder

- Synpatic

synpatic

- Evolution

evolution

- Inkscape

inkscape

**Comment by Feichtmeier** [comment]
@ubuntujaggers while you are in the legacy berserk modus :P could you also tackle those two icons here? https://github.com/ubuntu/yaru/issues/1758

**Comment by ubuntujaggers** [comment]
I pushed a load of work a minute ago - just a reminder: please change to a different icon set, wipe Yaru, and rebuild to test this (or the old legacy icons will remain in your icons folder and take precedence for some reason).  Tomorrow I will focus on getting the icons that have already been done in a mergeable state so we can get them in master tomorrow night :+1:

**Comment by gusbemacbe** [comment]
Hello @madsrh !

Your icon image is from https://www.onlinewebfonts.com/icon/469874. It is licensed under CCBY 3.0, but it requires a attribution.

Instead of taking the images from DuckDuckGo or Google Images, I recommend to take only from Pixabay which contains only open source arts and does not require attribution. 

Please avoid Flaticon (it belongs to Freepik) and Freepik. Freepik is like GettyImages, and a malevolent company and a big enemy of Linux community and has already menaced the designers with copyright infringement sues, while Freepik claims that Google and Twitter icons, which are under open source licences, are theirs and under closed source licence, ie, Google and Twitter icons can not be modified. Freepik also claims that they are authors of @joypixels' icon and @icons8's icons.

**Comment by madsrh** [comment]
> Instead of taking the images from DuckDuckGo or Google Images, I recommend to take only from Pixabay which contains only open source arts and does not require attribution.

👍 

> Your icon image is from https://www.onlinewebfonts.com/icon/469874. It is licensed under CCBY 3.0, but it requires a attribution.

This is not a Yaru icon. You are missing the point I think 😃 The image is only to illustrate how an image can work on both light and dark background - it is not an actual icon 😉

**Pull request merged**
