### PR TITLE
Recolour Universal Access toggles to dark

### LINKED ISSUE #669: Switches in popups should use darktheme styling
The gray background on "off" switches seems too light to me. Since the popup background is dark, wouldn't it make sense to style switches in popups similar to the dark theme switches?

image

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
Closes #669

### CODE REVIEW

**Comment by madsrh** [comment]
In the screenshot above, it looks like the "off" switches has no background. IMO they should have a gray background like before, just darker ;)

**Comment by eaglersdeveloper** [comment]
Good?

**Comment by Feichtmeier** [comment]
Keep bad contrasted screens in mind

**Comment by eaglersdeveloper** [comment]
This is `#6c6767` !

**Comment by clobrano** [comment]
Sorry, I can't confirm this is working because in my VM they're still the old versions. Can someone else double check if it's only a problem in my VM?

**Comment by Feichtmeier** [comment]
It's not working for me, neither =/

image

**Comment by Feichtmeier** [comment]
@eaglersdeveloper if you use new assets you must add it to the meson.build file in gnome-shell/src/

**Comment by clobrano** [comment]
@Feichtmeier I think he did it correctly, this is why I though my system was bugged

**Comment by eaglersdeveloper** [comment]
🙁
I checked meson.build, everything is fine.

**Comment by clobrano** [comment]
Found the problem: you changed only _toggle-on-intl.svg_ file, which is used (for some reason) on your system, while on our system _toggle-on-us.svg_ is used instead, but this file has not changed.

I can't push on this branch because you worked on your fork, if you would please

1. delete _toggle-on-us.svg_ 
2. make a copy of _toggle-on-intl.svg_ and rename it _toggle-on-us.svg_

commit, push and we'll retest again

...or, I can push a new branch myself, but I prefer to keep your contribution ;)

**Comment by eaglersdeveloper** [comment]
Ready to merge

**Comment by Feichtmeier** [comment]
Works!:

image

+1 for merge ty very much @eaglersdeveloper

**Comment by eaglersdeveloper** [comment]
I could not do without @clobrano

**Comment by clobrano** [comment]
Please go on, it's enough if one of us tested it :+1:

**Pull request merged**
