### PR TITLE
Ubuntu Mate: full colour icon for preferences-desktop-keyboard-shortcuts

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Hi all,

How's this:

image

???

### CODE REVIEW

**Comment by Jupiter007-43** [comment]
Nice one @ubuntujaggers 
Maybe increase the contrast a bit on 16px version?
On my screen it is unreadable at this size.

**Comment by ubuntujaggers** [comment]
I'll have another go at the 16px :+1: 

Out of interest, what size are these normally shown at?  If 16px is the main one, I should redo this (and the previous one) in the style we used for legacy buttons...

**Comment by ubuntujaggers** [comment]
> Out of interest, what size are these normally shown at? If 16px is the main one, I should redo this (and the previous one) in the style we used for legacy buttons...

Don't suppose anyone knows the answer to this, do they...?

**Comment by Feichtmeier** [comment]
My tip is 32 but I dont know sorry :(

**Comment by Jupi007** [comment]
I just installed a Mate VM for testing all this awesome Yaru Mate stuff.

> Out of interest, what size are these normally shown at? If 16px is the main one, I should redo this (and the previous one) in the style we used for legacy buttons...

It looks like it use 24px version into the menu and 32px one into settings app.

**Comment by ubuntujaggers** [comment]
Thanks guys :)

**Comment by ubuntujaggers** [comment]
:facepalm: 

You know I've been complaining that the images are embedding slightly bigger than 100%? Turns out my browser was zoomed to 110%, lol.

I've added more contrast to the 16px version and took the opportunity to improve the shape of the red outlines on the full size version (to be fair it's a microscopic change that you're unlikely to notice):

image

??

**Comment by Jupi007** [comment]
Much better, I clearly see that it's a keyboard.
Good job @ubuntujaggers 👌 👍

**Pull request merged**
