### PR TITLE
symlinks for #2997

### PR DESCRIPTION
**Pull request by Muqtxdir**
### TO-DO:

- [ ] account-logged-in-symbolic
- [ ] applications-chat-panel-symbolic

#### audio:
- [x] audio-input-microphone-high-symbolic
- [x] audio-input-microphone-high-panel-symbolic
- [x] audio-input-microphone-low-zero-symbolic
- [x] audio-input-microphone-low-zero-panel-symbolic
- [x] audio-input-microphone-medium-symbolic
- [x] audio-input-microphone-medium-panel-symbolic
- [x] audio-input-microphone-muted-symbolic
- [x] audio-input-microphone-none-symbolic
- [x] audio-input-microphone-none-panel-symbolic
- [x] audio-volume-high-symbolic
- [x] audio-volume-high-panel-symbolic
- [x] audio-volume-low-symbolic
- [x] audio-volume-low-panel-symbolic
- [x] audio-volume-low-zero-symbolic
- [x] audio-volume-low-zero-panel-symbolic
- [x] audio-volume-medium-symbolic
- [x] audio-volume-medium-panel-symbolic
- [x] audio-volume-muted-symbolic
- [x] audio-volume-muted-panel-symbolic

#### battery:
- [x] battery-000-symbolic
- [x] battery-000-charging-symbolic
- [x] battery-020-symbolic
- [x] battery-020-charging-symbolic
- [x] battery-040-symbolic
- [x] battery-040-charging-symbolic
- [x] battery-060-symbolic
- [x] battery-060-charging-symbolic
- [x] battery-080-symbolic
- [x] battery-080-charging-symbolic
- [x] battery-100-symbolic
- [x] battery-100-charging-symbolic
- [x] battery-caution-symbolic
- [x] battery-caution-charging-symbolic
- [x] battery-charged-symbolic
- [x] battery_charged-symbolic
- [x] battery-empty-symbolic
- [x] battery-empty-charging-symbolic
- [x] battery-full-symbolic
- [x] battery_full-symbolic
- [x] battery_plugged-symbolic

#### bluetooth:
- [x] blueberry-tray-symbolic
- [x] blueberry-tray-active-symbolic
- [x] blueberry-tray-disabled-symbolic
- [x] blueman-active-symbolic
- [x] blueman-disabled-symbolic
- [x] blueman-tray-symbolic
- [x] blueman-tray-active-symbolic
- [x] blueman-tray-disabled-symbolic
- [x] bluetooth-active-symbolic
- [x] bluetooth-disabled-symbolic
- [x] bluetooth-paired-symbolic
- [x] empathy-available-symbolic
- [x] empathy-away-symbolic
- [x] empathy-busy-symbolic
- [x] empathy-extended-away-symbolic
- [x] empathy-offline-symbolic
- [x] empathy-pending-symbolic
- [x] gnome-do-symbolic.svg

#### gpm:
- [x] gpm-ac-adapter-symbolic
- [x] gpm-battery-000-symbolic
- [x] gpm-battery-000-charging-symbolic
- [x] gpm-battery-020-symbolic
- [x] gpm-battery-020-charging-symbolic
- [x] gpm-battery-040-symbolic
- [x] gpm-battery-040-charging-symbolic
- [x] gpm-battery-060-symbolic
- [x] gpm-battery-060-charging-symbolic
- [x] gpm-battery-080-symbolic
- [x] gpm-battery-080-charging-symbolic
- [x] gpm-battery-100-symbolic
- [x] gpm-battery-100-charging-symbolic
- [x] gpm-battery-charged-symbolic
- [x] gpm-battery-empty-symbolic
- [x] gpm-battery-missing-symbolic
- [x] gpm-keyboard-000-symbolic
- [x] gpm-keyboard-020-symbolic
- [x] gpm-keyboard-040-symbolic
- [x] gpm-keyboard-060-symbolic
- [x] gpm-keyboard-080-symbolic
- [x] gpm-keyboard-100-symbolic
- [x] gpm-mouse-000-symbolic
- [x] gpm-mouse-020-symbolic
- [x] gpm-mouse-040-symbolic
- [x] gpm-mouse-060-symbolic
- [x] gpm-mouse-080-symbolic
- [x] gpm-mouse-100-symbolic
- [x] gpm-primary-000-symbolic
- [x] gpm-primary-000-charging-symbolic
- [x] gpm-primary-020-symbolic
- [x] gpm-primary-020-charging-symbolic
- [x] gpm-primary-040-symbolic
- [x] gpm-primary-040-charging-symbolic
- [x] gpm-primary-060-symbolic
- [x] gpm-primary-060-charging-symbolic
- [x] gpm-primary-080-symbolic
- [x] gpm-primary-080-charging-symbolic
- [x] gpm-primary-100-symbolic
- [x] gpm-primary-100-charging-symbolic
- [x] gpm-primary-charged-symbolic
- [x] gpm-ups-000-symbolic
- [x] gpm-ups-000-charging-symbolic
- [x] gpm-ups-020-symbolic
- [x] gpm-ups-020-charging-symbolic
- [x] gpm-ups-040-symbolic
- [x] gpm-ups-040-charging-symbolic
- [x] gpm-ups-060-symbolic
- [x] gpm-ups-060-charging-symbolic
- [x] gpm-ups-080-symbolic
- [x] gpm-ups-080-charging-symbolic
- [x] gpm-ups-100-symbolic
- [x] gpm-ups-100-charging-symbolic
- [x] gpm-ups-missing-symbolic
- [x] gsd-xrandr-symbolic
- [x] gtg-panel-symbolic
- [x] im-message-new-symbolic
- [x] indicator-messages-symbolic
- [x] indicator-messages-new-symbolic
- [x] nm-adhoc-symbolic
- [x] nm-device-wired-symbolic
- [x] nm-device-wired-autoip-symbolic
- [x] nm-device-wired-secure-symbolic
- [x] nm-no-connection-symbolic
- [x] nm-secure-lock-symbolic
- [x] nm-signal-0-symbolic
- [x] nm-signal-00-symbolic
- [x] nm-signal-0-secure-symbolic
- [x] nm-signal-00-secure-symbolic
- [x] nm-signal-25-symbolic
- [x] nm-signal-25-secure-symbolic
- [x] nm-signal-50-symbolic
- [x] nm-signal-50-secure-symbolic
- [x] nm-signal-75-symbolic
- [x] nm-signal-75-secure-symbolic
- [x] nm-signal-100-symbolic
- [x] nm-signal-100-secure-symbolic
- [x] nm-vpn-active-lock-symbolic
- [x] nm-vpn-connecting-symbolic
- [x] nm-vpn-connecting12-symbolic
- [x] nm-vpn-connecting13-symbolic
- [x] nm-vpn-connecting14-symbolic
- [x] nm-vpn-lock-symbolic
- [x] notification-disabled-new-symbolic.svg
- [x] notification-new-symbolic.svg
- [x] notification-symbolic.svg
- [x] system-restart-panel-symbolic
- [x] system-shutdown-panel-symbolic
- [x] system-shutdown-panel-restart-symbolic
- [x] user-available-panel-symbolic
- [x] user-away-panel-symbolic
- [x] user-busy-panel-symbolic
- [x] user-idle-panel-symbolic
- [x] user-invisible-panel-symbolic
- [x] user-offline-panel-symbolic
- [x] user-status-pending-panel-symbolic
- [ ] xfce4-mixer-muted-symbolic
- [ ] xfce4-mixer-no-muted-symbolic
- [ ] xfce-newmail-symbolic
- [ ] xfce-nomail-symbolic
- [ ] xfpm-ac-adapter-symbolic
- [ ] xfpm-keyboard-000-symbolic
- [ ] xfpm-keyboard-030-symbolic
- [ ] xfpm-keyboard-060-symbolic
- [ ] xfpm-keyboard-100-symbolic
- [ ] xfpm-mouse-000-symbolic
- [ ] xfpm-mouse-030-symbolic
- [ ] xfpm-mouse-060-symbolic
- [ ] xfpm-mouse-100-symbolic
- [ ] xfpm-primary-000-symbolic
- [ ] xfpm-primary-000-charging-symbolic
- [ ] xfpm-primary-020-symbolic
- [ ] xfpm-primary-020-charging-symbolic
- [ ] xfpm-primary-040-symbolic
- [ ] xfpm-primary-040-charging-symbolic
- [ ] xfpm-primary-060-symbolic
- [ ] xfpm-primary-060-charging-symbolic
- [ ] xfpm-primary-080-symbolic
- [ ] xfpm-primary-080-charging-symbolic
- [ ] xfpm-primary-100-symbolic
- [ ] xfpm-primary-100-charging-symbolic
- [ ] xfpm-primary-charged-symbolic
- [ ] xfpm-primary-missing-symbolic
- [ ] xfpm-ups-000-symbolic
- [ ] xfpm-ups-000-charging-symbolic
- [ ] xfpm-ups-020-symbolic
- [ ] xfpm-ups-020-charging-symbolic
- [ ] xfpm-ups-040-symbolic
- [ ] xfpm-ups-040-charging-symbolic
- [ ] xfpm-ups-060-symbolic
- [ ] xfpm-ups-060-charging-symbolic
- [ ] xfpm-ups-080-symbolic
- [ ] xfpm-ups-080-charging-symbolic
- [ ] xfpm-ups-100-symbolic
- [ ] xfpm-ups-100-charging-symbolic
- [ ] xfpm-ups-charged-symbolic
- [ ] xfpm-ups-missing-symbolic

### CODE REVIEW

**Review by Jupi007 — APPROVED** [review]
LGFM :+1:

**Comment by Muqtxdir** [comment]
@Jupi007 do I bring all the missing_icons under this PR or separate them into smaller PRs (_would make it easier for others to review, since the list is quite big_)

**Comment by Jupi007** [comment]
If it's symlinks yes because it is easily reviewable.
If you add brand new icons, maybe doing this in another PR :)

**Comment by Muqtxdir** [comment]
ok, i'll add the symlinks then make this PR ready for review

**Comment by Jupi007** [comment]
Sorry I didn't noticed it was a draft 😅

**Comment by Muqtxdir** [comment]
most of the mentioned icons that are being added and symlinked in this PR for mate and xfce have been added under `panel` directory in later PR's as both dark and light variants. So it doesn't make sense to have symlinks of symbolic-icons as both mate and xfce can already make use of the icons present under `panels` (_fullcolor_).

closing this pr based on the above.

**Pull request closed without merging**
