### PR TITLE
Grey and purple folders from design fest, for testing

### PR DESCRIPTION
**Pull request by ubuntujaggers**
As discussed...

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
The grey looks great.

That strong gradient... No I'm really not a fan. There's isn't any other icon doing those multi colour icons in the theme

**Comment by ubuntujaggers** [comment]
I've just realised I accidentally left the corners on which weren't on the provided svg.  We couldn't get it it render the pngs so I used it as a reference and edited the existing folders.svg.  We can always take the corners off, that wasn't a deliberate design choice.

**Comment by ubuntujaggers** [comment]
Some things we can also try:

- Softening the darkening effect on the gradient (something closer to the desktop icon)
- Adding a very subtle gradient to the grey so it's more like other Suru icons
- I think some changes to the edging would help because the orange bleeds through the edge of the grey a tiny bit, when it's on a dark background (you can see it at the bottom of the "stuart" icon on the default wallpaper)

**Comment by Feichtmeier** [comment]
Yes please, get them as much as a regular yaru / Suru icons as possible. Even if the means to somehow change the gradients

Something different: is it an optical illusion or is the base icon actually the icon with the opened folder now?

**Comment by ubuntujaggers** [comment]
How about this version with minimal changes for starters:

image

Gradient is softer and probably matches the desktop icon a bit more:

image

Also tidied up the bottom edge and added a very subtle gradient to the grey.  Not pushed because I only did the screenshotted icons for illustration.

**Comment by Feichtmeier** [comment]
That is def. a big improvement regarding style consistency with the rest of the theme!
I think it would be nice get everything together to test this - @clobrano 's purple branch and this one and then test it for some hours

**Comment by ubuntujaggers** [comment]
Hi guys,

I've finished and pushed the slightly revised icons here - I can push them to the purple branch if you like?

**Comment by madsrh** [comment]
@ubuntujaggers I was wondering if we could make the color less "cold" 🤷‍♂ 

image

image

image

**Comment by Feichtmeier** [comment]
> Hi guys,
> 
> I've finished and pushed the slightly revised icons here - I can push them to the purple branch if you like?

Yeah nice!
Eventually wait until @clobrano is done with his branch and then we can merge this one right after into master?

@madsrh I think the first one of your two proposals could be an improvement. Could we eventually get one colour out of the Vanilla / Canonical or Suru palette for the gray?

**Comment by clobrano** [comment]
I agree that's better to have this different branch only for the icons. Great work @ubuntujaggers!

**Comment by ubuntujaggers** [comment]
Hi guys,

The current grey (at least the start of the gradient) is $color-mid-dark off Vanilla.

The greys on the Suru palette IMO are quite different but we could try the darkest one, or a darkened version of the darkest one:

![image](https://user-images.githubusercontent.com/38893390/72180897-166aa480-33e0-11ea-8aae-01a0f477afd0.png

**Comment by Feichtmeier** [comment]
Just tried your branch imho this looks really good :+1: 
And this comes from one of the people that was pretty sceptical about the multicolor gradient :dancing_men: 
Merged carlos branch locally (wont! push! it! :) )
grafik

**Comment by ubuntujaggers** [comment]
@madsrh  suggested trying without orange:

image

**Comment by madsrh** [comment]
> madsrh suggested trying without orange

Thanks for giving it a try. Another idea would be to add some shadow or is that not in the Yaru/Suru icon style? 

Ikke-navngivet-1

**Comment by ubuntujaggers** [comment]
> Another idea would be to add some shadow or is that not in the Yaru/Suru icon style?

A dark shadow would be unique in the theme and would effectively turn it into a strong south --> north gradient, but we can certainly try a shadow of some sort :+1:

**Comment by friendlyapple** [comment]
Why you want to change folders ? The current folders are so beautiful with this orange :)
The macOS directories have their identity with the blue color and Ubuntu folders also have their identity with the orange. It's my opinion of course.

**Comment by ubuntujaggers** [comment]
@madsrh 

With shadow:

image

**Comment by ubuntujaggers** [comment]
> Why you want to change folders ? The current folders are so beautiful with this orange :)
> The macOS directories have their identity with the blue color and Ubuntu folders also have their identity with the orange. It's my opinion of course.

I also like orange folders, but using these they look really cool  :)  and are probably even more distinctive than current.  This is a concept that came out of the (just finished) London design fest.

**Comment by madsrh** [comment]
Thanks for giving [this ](https://github.com/ubuntu/yaru/pull/1712#issuecomment-573317517)a try @ubuntujaggers 
I like it, but what do you think?

**Comment by friendlyapple** [comment]
Ok :) it's just my personal opinion, but I find these folders less harmonious by combining a gradient with gray. The gray color is really sad and cold.

**Comment by madsrh** [comment]
> Ok :) it's just my personal opinion, but I find these folders less harmonious by combining a gradient with gray. The gray color is really sad and cold.

@friendlyapple It looks like you created your Github account just now, to provide this feedback for us 👍 Cool, thank you! 

If you have suggestions for a less sad version please do share them - this is a collaborate effort.

**Comment by friendlyapple** [comment]
I have no design proposal because the current folders (orange) are the most beautiful, all OS combined :heart:

**Comment by Feichtmeier** [comment]
The shadow looks good so far. My only concern with it is that it eventually looks a little bit more empty/ more 3d

**Comment by ubuntujaggers** [comment]
I'm finding it very very hard to decide whether I prefer current orange or this new design, _and_ whether I prefer the new design with or without shadow.

**Comment by Feichtmeier** [comment]
We could also try that gray folders without the highlight at all

**Comment by Feichtmeier** [comment]
Merging it with the current version https://github.com/ubuntu/yaru/pull/1712#issuecomment-573181167
As discussed with @flexiondotorg on the telegram group.

Any refinements or even back to orange in different PR's then

**Pull request merged**
