### PR TITLE
Trying to catch wacom buttons with stage

### PR DESCRIPTION
**Pull request by Feichtmeier**
Testing this on bionic on my host because I can plug in a wacom here
Keeping this as a test branch and a draft until I know how we can fix it

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr2141`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr2141` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
It's getting a little better
grafik
Now at least everything can be seen
Don't know maybe the disabled buttons at the bottom could need a general improvement in the light theme
WDYT @madsrh ?

**Comment by Feichtmeier** [comment]
grafik

**Comment by madsrh** [comment]
Nice. +1 for (if possible) fixing the button at the bottom

**Pull request closed without merging**
