### PR TITLE
Proposed tweak for Wine Tricks icon

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Hi guys,

The blurry raimbow is a bit unusual for Yaru, I wondered what you thought of this.

**Current**

image

image

**Proposed**

image

image

### CODE REVIEW

**Comment by Muqtxdir** [comment]
The proposed icon is definitely an improvement to the current one

**Comment by Jupi007** [comment]
It's me who did this icon, sorry.
I remember it has given me hard time to found a good looking icon 😅

Your one looks definitely better.
But maybe make the gradient a bit more colorful?

**Comment by ubuntujaggers** [comment]
> But maybe make the gradient a bit more colorful?

Try now:

image

image

**Comment by Jupi007** [comment]
Better :)

**Pull request merged**
