### PR TITLE
Created org.gnome.Snapshot Link Targetting the camera-app icon. 

### PR DESCRIPTION
**Pull request by ochi12**
Ubuntu replaced cheese in favor of gnome-snapshot since 24.04.
<br>
## FROM
image

## TO
image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
I think this is a good change but let the others have a look, too!

**Review by Muqtxdir — COMMENTED** [review]
hi @ochi12

thanks for looking into this issue, I think it would be nice to have a separate icon for snapshot rather than symlinking to the cheese icon. I know few people coming from past ubuntu releases have both apps installed so it would be confusing

my suggestion would be to have the round lens icon for snapshot without camera body

**Comment by ochi12** [comment]
> hi @ochi12
> 
> thanks for looking into this issue, I think it would be nice to have a separate icon for snapshot rather than symlinking to the cheese icon. I know few people coming from past ubuntu releases have both apps installed so it would be confusing
> 
> my suggestion would be to have the round lens icon for snapshot without camera body

Well I might work on it but my guess is camera-app.png is made as a link for any camera app that ships with ubuntu by default. 

It should be the other way arround, removing the cheese links instead

**Comment by Muqtxdir** [comment]
please go with your suggested option1

**Comment by ochi12** [comment]
@Muqtxdir @Feichtmeier new changes...

Tested it alongside other yaru icons to see if it fits the aesthetics.
image

**Review by Muqtxdir — APPROVED** [review]
thanks 🧡

**Comment by ochi12** [comment]
@Feichtmeier I need some approval in symbolic icon changes

**Review by Jupi007 — APPROVED** [review]
LGTM, thanks a lot @ochi12 !

**Pull request merged**
