### PR TITLE
Add fullcolor icon for .savedSearch folders

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
folder-saved-search

[Read more](https://www.howtogeek.com/192360/how-to-create-saved-search-folders-on-windows-linux-and-mac-os-x/)

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Looks perfect!

Where is this icon used? (Sorry I really don't know)

**Comment by Feichtmeier** [comment]
Ah one thing: why do you commit all the other PNGs again?

**Comment by eaglersdeveloper** [comment]
This was done by render-bitmaps.py. Git noticed a changes.

**Comment by eaglersdeveloper** [comment]
OK, I will repush PR with only .savedSearch icon

**Comment by eaglersdeveloper** [comment]
@Feichtmeier, will you merge this PR?

**Comment by Feichtmeier** [comment]
Yes! Only need to test this first sorry didn't have much time lately

**Comment by eaglersdeveloper** [comment]
You can test via Icon Browser

**Comment by clobrano** [comment]
Ok, thanks
There is also a common use of this? Or this icon appears only in icon browser?

**Comment by clobrano** [comment]
@eaglersdeveloper, is there a different use case other than Icon browser?

**Comment by eaglersdeveloper** [comment]
Adwaita have this icon, but even I don't know why it is needed 🤷‍♂️
Maybe .savedSearch virtual folders was removed in Nautilus.

**Comment by Feichtmeier** [comment]
I tried to create that folder on 18.04 with nautilus 3.26 but I failed : /
I mean... we could merge it it does no harm but if it is actually not a feature anymore it feels a bit strange (though the icon looks great)

**Comment by clobrano** [comment]
It's the same doubt I have. I like the icon, but since it doesn't seem we need it, I'd say drop it

**Comment by Feichtmeier** [comment]
@eaglersdeveloper thanks for the PR - I am pretty sure this feature was removed from nautilus, so I don't see a reason to add this (but the icons looked great <3 )

**Comment by eaglersdeveloper** [comment]
Thank you. But if this icon isn't needed, then why is it in Adwaita? 🤔

https://gitlab.gnome.org/GNOME/adwaita-icon-theme/blob/master/Adwaita/512x512/places/folder-saved-search.png

**Comment by Feichtmeier** [comment]
Good question! I'll ask one of the gnomers

**Pull request closed without merging**
