### PR TITLE
Miscellaneous mimetype icons

### PR DESCRIPTION
**Pull request by madsrh**
PLEASE check thoroughly! ⚠️ 

I need help figuring out the symlinks. This PR contains only the .svg files. Is the font size too big? (compared to the audio files)

Closes https://github.com/ubuntu/yaru/issues/1163 
Closes https://github.com/ubuntu/yaru/issues/1374

The firmware icon very rough, but perhaps @ubuntujaggers can give it a makeover.

image

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
If you haven't done the pngs or the symlinks I'm happy to pull this branch to my laptop and finish it when I review it. Do we know what the symlinks should be and it's just a case of making them?

**Comment by madsrh** [comment]
> I'm happy to pull this branch to my laptop and finish it when I review it. 

@ubuntujaggers I properly should learn this myself but for now, that would be amazing. I'll update the PR with a few more icons later today.

I know this isn't critical work, but it's "low hanging fruit" and amt I have some free time.

**Comment by madsrh** [comment]
@ubuntujaggers If you feel some of theses aren't up to the same quality as the rest of the set, feel free to alter or delete some of them.

image

**Comment by ubuntujaggers** [comment]
Looking at this now :+1:

**Comment by ubuntujaggers** [comment]
I pushed the pngs so people can test.  The only change I made was tidying up and pixel-fitting the firmware one and making sure they all fitted inside the boundaries of the icon.

Before:

image

After:

image

@madsrh, if you pull this and build it you will be able to see if it works as expected on any files you have handy :+1: and I'll do the same.

**Comment by madsrh** [comment]
Okay, I've tried this and I can't make it work. Only the translation icon is working.

I followed [this guide](https://help.ubuntu.com/community/AddingMimeTypes), but running `update-mime-database` just deletes my changes. Adding the lines in `etc/mime.types` does nothing either.

There's a bunch more of icons that I would like to add support for, so maybe we should sit down together and look at this or if someone can write a newbie guide :o)

**Comment by ubuntujaggers** [comment]
Hmm, the 7z one was working for me... how are you building the branch to test?

**Comment by madsrh** [comment]
> Hmm, the 7z one was working for me... 

Sorry, I was a bit too fast. Yes 7z, certificate, po, jar and gz was working too, but these are all listed in etc/mime.types so I expected them to work - unlike Xmind, Docker.
We already have a Flatpak icon in Yaru (just not .ref) but I can't even get that working :man_shrugging: 

> how are you building the branch to test?

`git clone --branch miscellaneous-mimetypes https://github.com/ubuntu/yaru.git`

and 

`./render-bitmaps.py`

and just copying the files into `/usr/share/icons/Yaru`

**Comment by ubuntujaggers** [comment]
> We already have a Flatpak icon in Yaru (just not .ref) but I can't even get that working

Hmm, I think the problem is we need to work out how to get the Yaru theme to expand the supported mimetypes - otherwise we're providing an icon and the user has to edit etc/mime.types to see them?

**Comment by Trine4** [comment]
Happy new year!
I just saw your work. I love these new icons! However, would it be possible to reduce the font size?
Besides, I don't know if this is normal but the font size for the midi audio file is different from the others.

**Comment by madsrh** [comment]
Hi @Trine4 🎊 
Absolutely, I've had [the same thought](https://github.com/ubuntu/yaru/pull/1683#issue-357931716). I'll see if I can do that without breaking all of @ubuntujaggers 's work

**Comment by Feichtmeier** [comment]
But... Are the letters really bigger than the ones on other mimetype icons?

**Comment by madsrh** [comment]
> Are the letters really bigger than the ones on other mimetype icons?

Yes. I've started unifying them but it's WIP.

**Comment by Feichtmeier** [comment]
@madsrh tested all except the firmware no idea how to test this

Bad news :/ none is working except the JAR :/

Screenshot from 2020-01-22 11-36-08

**Comment by madsrh** [comment]
@Feichtmeier I know. I've been wanting to clean up this PR for a while. It's on my todo list for tonight. Thanks for reminding me!

Acutally, the translation is working too.

**Comment by friendlyapple** [comment]
Can you add an icon for PYC files (pre-compiled Python files)? Here is the current icon:
pyc

Here's what it might look like (I used the application-octet-stream.svg and text-x-python.svg icons):
test

Thank you :)

**Comment by friendlyapple** [comment]
Or:
test2

**Comment by madsrh** [comment]
Thanks @friendlyapple Let me know if you've come across other types that you are missing. 

@Feichtmeier don't you think it would be best to just close this PR and create a new one? It's a bit of a mess. I would rather start a fresh 😃

**Comment by friendlyapple** [comment]
No it's the only missing icon :)

**Comment by Feichtmeier** [comment]
@madsrh i don't know :) depends on your way of fixing this
If you don't lose any data go ahead and make a new branch

**Pull request closed without merging**
