### PR TITLE
GTK2 assets and Yaru-dark build

### LINKED ISSUE #732: Add official Dark Theme variant
Please add a dark theme variant. For instance, GNOME provides _Adwaita_ and _Adwaita-dark_

It's fairly easy to add this since Yaru already supports a dark version for the apps that opt into it. But the idea here is to let people use _GNOME Tweaks_ to select the dark version for all apps.

This was requested in #653 but I'm splitting this out into a separate targeted bug.

## Specifications

- Ubuntu 18.10
- yaru-theme 18.10.2

### PR DESCRIPTION
**Pull request by clobrano**
This PR provides the missing gtk2 assets and configuration for Yaru-dark, and enables the build of a Yaru-dark independent theme (only building from sources)

image

This PR is still incomplete. I decided to push it now, since I need some help/hints on how to proceed with the following issues

### main open issues
- [x] background bleeding in entries.
- [x] treeview headerbar hover is white
- [x] review menu's bg, arrows and separator according to the new dark menus in master
- [x]  release communitheme-dark in snap
- [x] uses gtk2 dark assets in place of the light ones

### nice to fix but not showstoppers

- [x] white border in "some places", e.g. Gimp's "progress-bars"
- [ ]  spinbutton border is sometimes missing (only observed in Inkscape so far, e.g. "Fill & Stroke" section)
- [ ] little gap in notebook tab (only the one with tab on the left)

in the next comments I'll put some pictures to show the open issues

closes #732

### CODE REVIEW

**Comment by clobrano** [comment]
**Background bleeding in entries**

this is the most important issue. You can see below that the background color bleeds over the dark border

image
image

however this is the vector image, which has nothing outside the border

image

don't pay attention to that white slice at the top, since it is another vector image (which I don't know the meaning), but I've already tried to remove it or recolor it and nothing seems to change

**Comment by clobrano** [comment]
**white border in "some places", e.g. Gimp's "progress-bars"**

image

**Comment by Feichtmeier** [comment]
Holy shit that amount of commits <3

**Comment by clobrano** [comment]
**treeview headerbar hover is white**

It's the treeview in file chooser, so it's important as well this one

image

the "name", "size", "modified" sections get white when hover

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
**spinbutton border is sometimes missing** (only observed in Inkscape so far, e.g. "Fill & Stroke" section)

image

this is a double problem.
- The entry of the spinbutton is actually called notebook-entry and it's different than the one of the previous issue. It's not wonderfull, but I think it's fine
- the spinbuttons however does not have borders, while the spinbuttons linked to entries do have it, see below

image

**Comment by clobrano** [comment]
Nor sure I understood. I didn't test the snap, my pictures come from
installation from source

Il sab 22 set 2018, 19:25 Paz-it <notifications@github.com> ha scritto:

**Comment by madsrh** [comment]
AMAZING @clobrano 💃

**Comment by Paz-it** [comment]
@clobrano , Probably it is me who didn't understand. My question is how can I test it?

**Comment by clobrano** [comment]
> @clobrano , I think there is no treeview headerbar hover asset, at least not in my gtk2-dark theme.

Yes, I found no asset as well, this is why it's complicated

**Comment by Paz-it** [comment]
I can't see a reason it should be there. If you agree, you can remove the reference of it in the main.rc file in both light/dark.

**Comment by clobrano** [comment]
@Paz-it there is no reference to treeview-header-button hover in main.rc, but that's the problem, since I don't know how to set the color to be dark and not white

**Comment by clobrano** [comment]
notice that the entry's bleeding background is present also in light variant. It's just almost invisible  
image

**Comment by Paz-it** [comment]
> @Paz-it there is no reference to treeview-header-button hover in main.rc, but that's the problem, since I don't know how to set the color to be dark and not white

In the gtkrc : 
 There shouldn't be any fiddling with them in the theme files themselves in
# order to not mess up the dark theme.

# Text/base
gtk-color-scheme = "text_color:#f7f7f7\nbase_color:#3d3d3d"
# Foreground/background
gtk-color-scheme = "fg_color:#f7f7f7\nbg_color:#2b2929"
# Selected foreground/background
gtk-color-scheme = "selected_fg_color:#ffffff\nselected_bg_color:#E95420"
# Insensitive foreground/background
gtk-color-scheme = "insensitive_fg_color:#969696\ninsensitive_bg_color:#383838"
# Menus
gtk-color-scheme = "menu_color:#353535\nmenubar_bg:#2b2929"
gtk-color-scheme = "menubar_fg:#F7F7F7\nmenubar_insensitive_fg:#CCCCCC"
# Links
gtk-color-scheme = "link_color:#2194bd\nvisited_link_color:#c97c5b"
# Treeview headers
gtk-color-scheme = "column_header_color:#353535\nhover_column_header_color:#636769"
# Window decoration
gtk-color-scheme = "menu_hover_color:#3d3d3d\nwindow_color:#f4f4f4"
# Tooltips
gtk-color-scheme = "tooltip_fg_color:#f7f7f7\ntooltip_bg_color:#353535"

that's for the dark ( play the the colors to match of course)

**Comment by clobrano** [comment]
Wow, I didn't remember that!

However, I tried the following and nothing seems to fix this

- set the color in `style "treeview_header_button"`
- set both color to the same (dark) value
- remove the usage of the asset in style "treeview..."
- change all gtk2 colors to a dark tone (to see whether it was taking the wrong color by mistake)

**Comment by Paz-it** [comment]
> notice that the entry's bleeding background is present also in light variant. It's just almost invisible
> image

In the main.rc : 


notice that the entry's bleeding background is present also in light variant. It's just almost invisible
image
 

notice that the entry's bleeding background is present also in light variant. It's just almost invisible
image

**Comment by clobrano** [comment]
I have those, but you pointed me to the right direction anyway, thanks :+1:

**Comment by clobrano** [comment]
Alirght, at the end of the day, bleeding background had a different cause, but it's fixed

**Comment by clobrano** [comment]
I updated the to-do list. Unfortunately I won't have time to work on these the next days, so this won't be part of Cosmic release I believe

**Comment by clobrano** [comment]
Hey @godlyranchdressing, any chance you can have a look a this :) , above all about the treeview header issue reported in the first post

**Comment by godlyranchdressing** [comment]
@clobrano no problem! I updated the spinbuttons, but still no luck with the entry bleed. I'll keep trying though.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Paz-it** [comment]
@clobrano, I feel lost a bit and want to clarify : 
Do you have Yaru-dark folder separate from the Yaru theme in /themes?
It should be a separate folder that include our gtk3 dark and gtk-2.0 that contains only the dark parts.
If your answer is yes, where can I get it to download? so I can test it.
If the answer is no, then it explains your issues with it.

**Comment by clobrano** [comment]
> If your answer is yes, where can I get it to download? so I can test it.

the answer is actually yes, because this branch has the installer to put all the files in the right place, the instructions are in the post just above yours :wink: 

    snap refresh communitheme --channel=edge/yaru-pr852

if you still are on Bionic

**Comment by Paz-it** [comment]
@clobrano , What I meant is : - do you have it separeted like this: 
screenshot from 2018-10-20 14-46-06
under /usr/share/themes when each folder contained only light/dark respectfully ?

**Comment by clobrano** [comment]
> under /usr/share/themes when each folder contained only light/dark respectively ?

yes, trust me :smile: 

> When downloading and testing your gtk2-dark folder(copy pasting it in MY Yaru-DARK, replacing the orig with it) it works

What you do manually (copy/paste), the installation script does it automatically.

I did not test the snap, it might actually miss the dark part

**Comment by Paz-it** [comment]
OK... :smile: :+1: 
So in my test, only the arrows in menus and menu-item colors remain undone from your original issues list.

**Comment by clobrano** [comment]
Tested again: there is simply no way to fix everywhere :smile:
 
- colored "bleeding" (current master): deluge NOT OK, inkscape OK
- transparent "bleeding": deluge OK, inkscape NOT OK

**Comment by Paz-it** [comment]
That's the reason for the hacks.rc file >>> to hack all the exceptional cases  
faint

**Comment by godlyranchdressing** [comment]
It'd help if we could find a way to apply styles only to those edge cases though. I gave [gtkparasite](https://github.com/chipx86/gtkparasite) a try but it isn't working, I don't know if I'm doing something wrong but nothing's happening. I just get an unknown module error.

**Comment by clobrano** [comment]
Wps suite has the dame issue gtkparasite has, but only when opening children windows, like the fikechooser

**Comment by clobrano** [comment]
This issue is in common with gtk2 light, do you mind open a new bug?

**Comment by clobrano** [comment]
>  If you still have my assets folder you can see the correct .svg image there next to the wrong one:

I cannot use your svg, if you remember the file to be modified is assets.svg which contains all the assets together. If you can re-do the same changes in that file would be different

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Paz-it** [comment]
Tested!
Your commits solved this issues (Dark/Light) 
Thank you @godlyranchdressing .

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
The main problems are fixed thanks to @godlyranchdressing. I think we can ship this now
@Paz-it, @godlyranchdressing, @Feichtmeier could you please have a look and confirm that everything looks right?

Thanks

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
image

Super tiny issue found: in inkscape preferences I found a "Spinbutton" where the right border is missing. Wouldn't be a blocker to merge imho

**Comment by Paz-it** [comment]
@clobrano Very well done :clap: 
Tested it and I have two major issues: 
1. The toolbar_menu  
2. The menu_color
I believe it will be better that the toolbar menu will have the same color as the bg. that way it will remain at the same color when in fallback state :
current:
screenshot from 2018-11-19 00-35-00
My suggestion: 
screenshot from 2018-11-19 00-43-52
I wish we could go back to a darker menu (both gtk3/gtk2). Not only because it is beautiful, main reason is better contrast and in gtk2 it compensate for the lucking of shadow for the menus.
Example:
2018-11-19-012526_1920x1080_scrot

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Paz-it** [comment]
The gk2-dark is not implemented. I think snap session is not pointing to it .
That's the part that I see there now:
`gtk2_communitheme="/snap/communitheme/current/share/themes/Communitheme/gtk-2.0/gtkrc"
if [ -z "$GTK2_RC_FILES" ]; then
    GTK2_RC_FILES=$gtk2_communitheme
elif [ -n "${GTK2_RC_FILES##*$gtk2_communitheme*}" ]; then
    GTK2_RC_FILES=$gtk2_communitheme:$GTK2_RC_FILES
fi
export GTK2_RC_FILES`

**Comment by Paz-it** [comment]
I know It is a test, and I'm testing :smile: 
The reason is probably what I wrote ^^. In snap session it is pointing to /snap/communitheme/current/share/themes/Communitheme/gtk-2.0/gtkrc" but not to communitheme-dark.

screenshot from 2018-12-02 15-46-26

**Comment by clobrano** [comment]
> I know It is a test, and I'm testing

Yes, but lately this PR has changed from incomplete to not working, I should have said that.

**Comment by Paz-it** [comment]
Oh, I see. It means for the time been I should not test it and wait for your further instructions?

**Comment by clobrano** [comment]
> Oh, I see. It means for the time been I should not test it and wait for your further instructions?

Of course not, help is always welcome :D 
But I should not waste the tester time, if I already know that there's a problem I have to write it to point the people in the right direction.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Paz-it** [comment]
I tested now! as I looked at your change I thing the first "IF" is talking about the dark and the "elif" is talking about the light. so maybe : 
  gtk2_communitheme="/snap/communitheme/current/share/themes/Communitheme-dark/gtk-2.0/gtkrc"
if [ -z "$GTK2_RC_FILES" ]; then
    GTK2_RC_FILES=$gtk2_communitheme<<<<<SHOULD BE DARK
elif [ -n "${GTK2_RC_FILES##*$gtk2_communitheme*}" ]; then
    GTK2_RC_FILES=$gtk2_communitheme:$GTK2_RC_FILES
fi
export GTK2_RC_FILES

**Comment by clobrano** [comment]
in bash, `-z` flags tests for variable existence, so

    if [ -z $var ]

is true if $var is defined, false otherwise.

`-n` flag tests the string length

the expression

    ${VAR##PATTERN}

is a *parameter substitution* that removes from VAR the *longest* part of $PATTERN that matches the front end of $VAR

e.g.

    var=this_is_a_test
    echo ${var##this_is_}
    a_test

so the script

    gtk2_communitheme="/snap/communitheme/current/share/themes/Communitheme-dark/gtk-2.0/gtkrc"
    if [ -z "$GTK2_RC_FILES" ]; then
        GTK2_RC_FILES=$gtk2_communitheme
    elif [ -n "${GTK2_RC_FILES##$gtk2_communitheme}" ]; then
        GTK2_RC_FILES=$gtk2_communitheme:$GTK2_RC_FILES
    fi
    export GTK2_RC_FILES
    # fi <- not needed, there is 1 "fi" for each "if"

if `$GTK2_RC_FILES` is not defined,
    defines it with `$gtk2_communitheme` var
else, if `$GTK2_RC_FILES` is defined, but it does not contain `$gtk2_communitheme` path, adds it
finally, export the newly defined var `$GTK2_RC_FILES`

so, the script does not contains any reference to -dark path

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Same, partially working ~~sh*t~~ stuff

image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
> As @didrocks mentioned in a discussion about the dark them switch - it 's suppose to be one line switch.
> Maybe he can shad a light and show us the magic-line for it. I need to find that discussion link.

do you mean [this](https://discourse.ubuntu.com/t/yaru-dark-variant/7936/3)?

We discussed this on IRC. As of today, it seems that startup session can set one gtk2 source file location only (that's why we had such a mix between dark and light), so a fallback solution could be to read the gsetting at startup and set the appropriate light/dark gtk2 location

**Comment by Paz-it** [comment]
Yes! that's link I was looking for, thanks!
So it means:
>  This support also simplifies the GTK2 support once needed: it’s only a question of dropping a folder + uncommenting one line. So we are all ready once the GTK2 dark theme is almost there.his support also simplifies the GTK2 support once needed: it’s only a question of dropping a folder + uncommenting one line. So we are all ready once the GTK2 dark theme is almost there.

We can take it with a  grain of salt?
That surely make things complicated for us to test it .

**Comment by clobrano** [comment]
I made already all of that, but it's not enough. There's still something missing

**Comment by Paz-it** [comment]
I know you did!
 Did you get an answer of what to do next? Or maybe, he or snapcraft people can?

**Comment by Paz-it** [comment]
Breaking my head here with some ideas :smile: 
Maybe we need two separate snap session:
1. comunitheme
2. comunithem-dark
separate meson builds.
When logging in you can choose:
1.Ubuntu with comunitheme
2. ubuntu with comunitheme-dark
Dose it make any sense? :thinking:

**Comment by clobrano** [comment]
It would, but we can't have a second session. However, we can set the right
path according to the grafting that holds the name of the theme set

Il giorno mar 4 dic 2018, 22:04 Paz-it <notifications@github.com> ha
scritto:

**Comment by clobrano** [comment]
I meant to include in snap/session script a call to get the currently set
theme. You can get it with

    gsettings get org.gnome.desktop.interface gtk-theme

then the output would be 'Yaru' or 'Yaru-dark' (well, in 18.04
s/Yaru/communitheme/) and then we can export the right gtk2_communitheme
path

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Do NOT test this, is currently broken

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Fixed now and gtk2-dark works. However, since the gtk2 resource path is set per session, one needs to logout/login after changing theme

**Comment by Paz-it** [comment]
That's leads to my conclusion about two separate sessions :thinking: 
If we can't use GTK2_RC_FILES session-wide. I wonder if there is a better module to replace it to serve our needs...

**Comment by clobrano** [comment]
# gtk2-dark-recap

Brief recap:

Currently it's implemented a solution to set the GTK2_RC_FILE env per session and according to currently set theme (only Communitheme or Communithem-dark).

It "works", with the following observations

1. Setting GTK2_RC_FILE session-wide is not suggested, since it's read by GTK3 as well (who knows why, since it's called GTK2...)
2. When a different theme is set at login, GTK2_RC_FILE is not changed. This cause gtk2 apps to have a mix of current theme and Yaru (now that I'm writing this, I can think of unsetting GTK2_RC_FILE if the theme is not Yaru, however as per point #1, this is still a cause of possible issues).

As @paz-it noted, gtk-common-themes does not ship Yaru-dark nor Communitheme-dark. @didrocks,  @jhenstridge do you think this is because of #953?
It is not totally clear to me how gtk-common-themes is shipped now, because of #953 (we build a new gtk-common-themes snap for each Yaru version?) and also because GTK2_RC_FILE in snap/session points to a Yaru folder, while I expect it to be pointing to the gtk-common-themes now.

Is it possible that adding Yaru-dark/Communitheme-dark to `gtk-common-themes-part.yaml` things will start working better?

**Comment by didrocks** [comment]
I think it's unrelated to #953 , which is a separate issue that Ken & James will fix by deprecating what we are doing, but still enabling us to build per-PR gtk-common-themes, once they have the time to look at this.

I think there are 2 sides of it:
- https://github.com/ubuntu/yaru/blob/master/build-helpers/gtk-common-themes-parts.yaml#L26 which is the reason why -dark doesn't ship in the snap produced by master builds on Yaru. As you fixed it in this PR, I think it will be now shipped, correct? (If not, someone needs to look at what removes the missing bits, but yeah, you got the right file).
- the other one is the gtk-common-themes `snapcraft.yaml` (in gitlab) that Ken/James are maintaining which does a similar thing IIRC. This is for automated official builds.

**Comment by clobrano** [comment]
>     * https://github.com/ubuntu/yaru/blob/master/build-helpers/gtk-common-themes-parts.yaml#L26 which is the reason why -dark doesn't ship in the snap produced by master builds on Yaru. As you fixed it in this PR, I think it will be now shipped, correct?

Yaru (or Communitheme in 18.04) snap does ship -dark now, but not gtk-common-themes

>  (If not, someone needs to look at what removes the missing bits, but yeah, you got the right file).

I'll check that

**Comment by clobrano** [comment]
Yes, I expected the gtk-common-themes to have "-dark" versions in it, but that's not the case even in this PR where the line https://github.com/ubuntu/yaru/blob/master/build-helpers/gtk-common-themes-parts.yaml#L26 has been removed.

**Comment by Paz-it** [comment]
Maybe I'm asking a stupid question but I'll ask anyway since I don't understand fully how it works?
@clobrano , Isn't it your brunch only and should be shipped to Yaru/Communitheme master first before it can be builds into gtk-common-themes?

**Comment by clobrano** [comment]
It's not a stupid question at all, I asked myself the same. However, I expect each PR updates gtk-common-themes and this parte of @didrocks reply confirm that

> [...] still enabling us to build **per-PR gtk-common-themes**, once they have the time to look at this.

**Comment by Paz-it** [comment]
I red @didrocks answers many times to make sure I understand what exactly the meaning of what he said  and some how I thought maybe by telling you that now after you corrected the theme and it's ready to ship it to the master. Maybe I'm wrong though...

**Comment by Paz-it** [comment]
The way  I look at it - This PR is open now. if all is well and working LGTM :smiley:

**Comment by clobrano** [comment]
> At present gtk-common-themes includes the following in the yaru part of its snapcraft.yaml

In this PR that line has been commented out, so I expect the gtk-common-themes should be built accordingly with -dark variant, however, if we have specific PR snaps build for Yaru, do we do the same for gtk-common-themes?

**Comment by Paz-it** [comment]
@clobrano  - I think I found the culprit  faint

   # don't support dark variant until it's ready
      rm -r $SNAPCRAFT_PART_INSTALL/share/themes/*-dark    <<<<<<< This one should be commented out.

**Comment by clobrano** [comment]
That line has been commented out

**Comment by Paz-it** [comment]
OK. I didn't see well (too pale) and the '-' singe is not present .
I hope @didrocks  @kenvandine @jhenstridge  will have time to look at it again.

**Comment by clobrano** [comment]
Looking at the build logs on Travis, it looks like I misunderstood (or there's some issue) and actually the builds on master are different than the ones in PR and gtk-common-themes are not refreshed.

This is last master build https://travis-ci.org/ubuntu/yaru/builds/468057358:  
communitheme snap is build, then pushed and so the same goes for gtk-common-themes

This is the last gtk2-dark PR build https://travis-ci.org/ubuntu/yaru/builds/463783976: communitheme snap is build, and that's all

I am going to add some debug logs in preprare-build script just to clarify this and if that so, merging the PR on master

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Everything is fixed and ready to test.
To see the effect of a theme change in gtk2 you still need to logout/login, but with the last commit, changing to a non-yaru theme do not mess up the gtk2 theme

**Comment by Paz-it** [comment]
Tested -- working great now! :clap: 
Just there is a need to change menus color to be the same with gtk3.

**Comment by clobrano** [comment]
> Tested -- working great now! clap
> Just there is a need to change menus color to be the same with gtk3.

oh, right

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
image
image

Awesome work! I think only the border is missing ;D It's ~ lighten(inkstone,1%) if there is no transparency possible

**Comment by clobrano** [comment]
Not sure it's there any border in gtk2. The only asset called "menu_border"
is already very bright and should be visible if available. I try to double
check whether is to be added in the rc file

**Comment by clobrano** [comment]
I don't really know how to set a different color for menu borders only

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr852`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr852` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Is everybody good in merging this?

**Pull request merged**
