### PR TITLE
Full colour icon for printer

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Hi everyone,

Let me know if there are any problems!  Fingers crossed this looks good when it's in use...

image

### CODE REVIEW

**Comment by clobrano** [comment]
First merge of the year!

**Comment by Feichtmeier** [comment]
Thank you @ubuntujaggers 

Oh man... I feel a bit stupid and guilty... ubuntu 18.10 whihc uses gtk 3.30 prefers symbolic icons 
image

:see_no_evil: I am sorry... but at least we will have it in bionic :blush:

**Comment by ubuntujaggers** [comment]
Lol!! At least we won't have to worry about the perspective ;)

**Comment by Feichtmeier** [comment]
I think those are adwaita symbolic icons. Would you be in a mood to provide a symbolic icon for the printer and the network printer? :see_no_evil: 
I am so sorry for stealing your time :(

**Comment by eaglersdeveloper** [comment]
Your icon can be used in other DEs, where symbolic icons aren't preferred.

**Comment by Feichtmeier** [comment]
@ubuntujaggers it works, thank you :) No symlinks needed
image

**Comment by eaglersdeveloper** [comment]
@Feichtmeier, is this screenshot from Ubuntu 18.04 or 18.10?

**Comment by Feichtmeier** [comment]
18?04

**Pull request merged**
