### PR TITLE
Icon theme upstream sync

### PR DESCRIPTION
**Pull request by Jupi007**
Symlink a lot of icons, but also add some new ones:

image

### CODE REVIEW

**Comment by Muqtxdir** [comment]
hi @Jupi007 

thanks for taking this up 🙂
I'll review the pr later tomorrow

**Comment by Jupi007** [comment]
Thanks @Muqtxdir 
Take your time, that's not hurry at all :D

**Comment by 3v1n0** [comment]
Lovely thanks!

I'm getting this in since it seems worth it and I'm preparing an upload now, but @Muqtxdir feel free to address any problem in a new issue in case you've review comments.

@Jupi007 please, when have some time give a look if we missed some yaru-styled icons in the shell too, since I did a few without much _science_ :)

**Comment by Jupi007** [comment]
@3v1n0 I just checked the shell icons, there wasn't any missing one, but every new icons was using the wrong styling indeed :)
See #4138

**Pull request merged**
