### PR TITLE
Fix crooked wheel tooth on settings-app-symbolic.svg

### LINKED ISSUE #1865: Crooked wheel tooth on settings-app-symbolic.svg
## Expected Behavior

Capture d’écran du 2020-02-07 18-08-32

## Actual Behavior

The highest tooth is crooked

Capture d’écran du 2020-02-07 18-08-16

### PR DESCRIPTION
**Pull request by Jupiter007-43**
This PR fix the crooked wheel tooth on settings-app-symbolic.svg and system-settings-symbolic.svg

closes #1865

### CODE REVIEW

**Comment by madsrh** [comment]
Absolutely  awesome @Jupiter007-43 🥇 
There is no greater joy than to see an issue with a pull-request attached 😄 Thank you!

**Comment by Jupiter007-43** [comment]
It was a pleasure 😊

**Comment by Feichtmeier** [comment]
Hey thank you very much for this! 

How did you produce the SVG?
Could it be the you manually fixed the SVG inside the Suru folders?
If no then sorry :(

If yes, you should rather change it inside the big source-symbolic file in our source folder and then run the script to export the icon. 

Please don't be discouraged by this. Feel free to ask so we get this in :)

**Comment by ubuntujaggers** [comment]
Oh, I see Jupiter is already on it! Let us know if you need help 👍

**Comment by Jupiter007-43** [comment]
Thank you for your help. 👍

@Feichtmeier Yes I manually fixed the SVG inside the Suru folders...
It's much better to compile!

I edited source-symbolic to fix each wheel and add applications-system icon which was missing.
I think everything's in order now.

**Comment by ubuntujaggers** [comment]
Looks good to me!  Everything in source-symbolic is correctly named and grouped.  The only missing ingredient is, you forgot to correct the wonky tooth on system-settings in source-symbolic.  Otherwise, perfect :+1:

**Comment by Jupiter007-43** [comment]
Fixed !
I had checked several times, though... sorry

**Comment by Feichtmeier** [comment]
@ubuntujaggers are we done here? If yes please use "squash and merge" and find a fitting commit message

**Comment by ubuntujaggers** [comment]
Merge is greyed out for me?

**Comment by ubuntujaggers** [comment]
Oh wait, it's back, lol

**Pull request merged**
