### PR TITLE
Add border and focus ring on GDM buttons

### LINKED ISSUE #3012: GDM: add a border to buttons
IMO the buttons need a subtle border like the entry and the popup

FLAMESHOT_2021-09-15_12-49

@Jupi007 could you eventually take care for this one for 21.10? :angel:

### PR DESCRIPTION
**Pull request by Jupi007**
I added border on GDM/lock screen buttons, and updated background colors.
In bonus, I added a focus ring on focused buttons (using `tab`).

@Feichtmeier can you post a screenshot for me here, I don't have a VM within easy reach. Also tell me if you don't like the focus ring :)

Closes #3012

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thank you @Jupi007 !
Looks fine in the lock screen!
FLAMESHOT_2021-09-16_00-10
The login screen is somehow not changeable via our build but it will be fine, telling from this one button in the lower right

**Review by Feichtmeier — APPROVED** [review]

**Comment by LinuxLlama** [comment]
I love this! Much appreciation towards the consistent colors between the input field and buttons

**Comment by Jupi007** [comment]
Sorry, I pushed a new commit because I had forgotten the `insensitive` state (really minor change).

@Feichtmeier If you want to apply the gdm theme to the login screen you can use this (@LinuxLlama found it): https://github.com/realmazharhussain/gdm-tools

**Comment by Feichtmeier** [comment]
Hmmm that doesn't really work. Only default and Yaru-dark are availible. However, since the one button is okay, the other two will also be okay :) So feel free to merge

**Comment by Muqtxdir** [comment]
@Jupi007 looks good.

#### dark:

https://user-images.githubusercontent.com/54065734/133646521-a37e52a1-a5df-4e7a-b2fa-551ae679fc59.mp4

#### default:

https://user-images.githubusercontent.com/54065734/133646582-9b54e618-20d3-48cb-b405-425f24ad6251.mp4

**Pull request merged**
