### PR TITLE
Remove orange on icons

### PR DESCRIPTION
**Pull request by madsrh**
**THIS** PR should be better and fix the orange spill that @friendlyapple mentioned.

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@madsrh I am still not sure - at least on the picture it still looks like the edges are cut off except the corners :thinking:

**Comment by madsrh** [comment]
Sorry, I'm stupid. The picture is the one posted by @friendlyapple (https://github.com/ubuntu/yaru/pull/1830#issuecomment-580624553) to illustrate what the problem was - very misleading 🤦‍♂️ 

Is there anything else you are concerned about?

**Comment by Feichtmeier** [comment]
Holy smiffelz you fixed it really
image
image

BUT :( !

Currently you assigned it outside of 
.nautilus-window { }

This means it is assigned for all widgets in scrolled windows, not only nautilus :(

((( And nitpicking: don't use $orange and $ash there. Try to use colors from _colors, like $selected_bg_color )))

**Comment by madsrh** [comment]
Excellent advice BUT I can't make it work inside` nautilus-window ` 😭 Would you mind just pushing the correct changes? 👼 

>  And nitpicking: don't use $orange and $ash there. Try to use colors from _colors, like $selected_bg_color

`$orange` should obviously have been `$selected_bg_color` 👍 but I don't think there's a way to replace the `$ash`.

**Comment by Feichtmeier** [comment]
Hm didn't work for me :(. I'll check tomorrow if you didn't find a solution until then :D

**Comment by clobrano** [comment]
It's weird, under `.nautilus-window` it seems that only the label color can be changed, while icon background is forced to `@theme_selected_color` when the windows has focus and to some grey when in backdrop

**Comment by Feichtmeier** [comment]
@madsrh 

Just tried it again myself. This seems to work:

.nautilus-window widget.view { background-color: rgba(255, 255, 255, 0.1); }

Peek 2020-02-11 21-59

**Comment by madsrh** [comment]
:man_facepalming: Moved to a new PR  #1900 #SorryGitNewbieHere

**Pull request closed without merging**
