### PR TITLE
Mimetype for application-x-python-bytecode

### PR DESCRIPTION
**Pull request by madsrh**
...to replace the Humanity fallback.

Fixes https://github.com/ubuntu/yaru/issues/1781

image

### CODE REVIEW

**Comment by friendlyapple** [comment]
Apparently the Python logo is a bit blurry on the .pyc icon (compared to the .py icon).

Click to zoom:
pyc-icons

The easiest way to correct this problem would be to take the Python logos from text-x-python.svg.
I'm sorry to add more work to you. It's really great what you do :)

Later I will try to help you to create the svg icons directly but at the moment I don't have the necessary software.

**Comment by madsrh** [comment]
I've added a white border/stroke to the python logo because it looked a bit "messy" on top of the 0101. Is that what you're seeing?

The logo shouldn't be blurry because it's simply copy and paste from the text-x-python.

**Comment by friendlyapple** [comment]
No, the white border is a good idea. However the Python logo on the small icons are not identical.
For example, there is no white border between the two snakes on the smallest icons.

Example (click to zoom):
demo

**Comment by madsrh** [comment]
@friendlyapple 
I think I know what happened 🙄 I added the stroke _inside_ the logo, so hopefully this one should be better.

image

**Comment by friendlyapple** [comment]
Awesome! I will love the Python even more with such beautiful icons :D

**Comment by madsrh** [comment]
@friendlyapple Thanks, but you do know that I didn't actually draw anything? :laughing: 

You've got a hawk-eye and we're always hoping more people will contribute to the project, so thank you for taking the time to create and comment so detailed on these issues. If you would like to help even more, we would love a PR (I can see that you know how to edit an image). Just let us know and we can help you with Github, Inkscape, ...

**Comment by friendlyapple** [comment]
@madsrh Thank you :)

Currently, I'm running out of time (I finish my studies) but it will be with pleasure that I will do PR in the future (near future I hope) 😃

**Pull request merged**
