### PR TITLE
tweaks: no borders for checkmarks in file menus and context menus

### PR DESCRIPTION
**Pull request by clobrano**
see #1703 

image
image

### CODE REVIEW

**Comment by madsrh** [comment]
LGTM

**Comment by Feichtmeier** [comment]
Looks nice!
Do you think Mpt would think that the ring of checks also should be removed together with this?

**Comment by madsrh** [comment]
> Do you think Mpt would think that the ring of checks also should be removed together with this?

I was considering the same

**Comment by clobrano** [comment]
That's why I screenshotted the radios too :D

**Comment by clobrano** [comment]
These are the radios without border

image

**Comment by madsrh** [comment]
Yes, let's  do that. You can test this in Solitaire.

**Comment by clobrano** [comment]
image

**Pull request merged**
