### PR TITLE
GTK4 upstream sync

### LINKED ISSUE #2599: GitHub Action for GTK4 (master) branch observation
Hi @didrocks 
Sorry for shamelessly assigning you to this :smile_cat: 

So, as we already observe GTK-3-24, gnome-shell and libhandy repos via GitHub Actions, we need another action to observe the GTK repo but this time the master branch, or in the future a gtk4 branch, if they again chose to create GTK5, 6, 7, ... GTK-n (with ```n ∈ ℕ``` :trollface: )

Would be nice to get this rolling before GTK4 hits Ubuntu.
Anyone else feel free to grab it from Didier.

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Closes #2599

### CODE REVIEW

**Comment by didrocks** [comment]
Is this really ready to be reviewed? It seems the CI job is failing

**Comment by Jupiter007-43** [comment]
There's a problem with the Gnome-Shell part: the **gnome-shell-theme.gresource.xml** file is missing into **/gnome-shell//upstream/data**.
I'll add it from upstream.

**Comment by didrocks** [comment]
:+1 This looks good to me and CI is passing :) Thanks! Approving

**Review by didrocks — APPROVED** [review]

**Comment by Jupiter007-43** [comment]
There's still a problem with the gnome-shell part (https://github.com/ubuntu/yaru/runs/1837890589) 😓

**Pull request merged**
