### PR TITLE
Bionic: New symbolic icons for application-x-appliance and applications-science

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Cherry pick of #1414 for Bionic.

image

image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1418`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1418` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Strangely that didn't work for bionic 
Maybe they are called differently there, I'll check

**Comment by ubuntujaggers** [comment]
Damn :(

**Comment by Feichtmeier** [comment]
Well it's just bionic. So... Not that important if it doesn't work :D thanks anyways!

**Comment by Paz-it** [comment]
> Well it's just bionic. So... Not that important if it doesn't work :D thanks anyways!

Hopefully you're joking @f

**Comment by Feichtmeier** [comment]
Yes ofc I'm joking. I'll check what icon name is needed

**Comment by ubuntujaggers** [comment]
This is a tough one because the snap store is a snap. So there's something weird to do with a version of Yaru that's baked into snap? There's no way to test it, I just found the Adwaita icons that were being used and copied the names.

**Comment by Feichtmeier** [comment]
No, the icons should be sucked from within the yaru theme I hope. At least that works for stuff like titlebuttons in other gnome snaps (and that snap store looks pretty much like a gnome software fork)

We need to find out the correct icon names, I try to find time for this soon

**Comment by Feichtmeier** [comment]
So I checked again the names, they are correct.
grafik
grafik

The science symbol is also not working with adwaita and it is sucking up the help symbol like in our theme:
grafik

So there is no error in this PR and I will simply merge it.
Let's continue the with gnome-software for the next gnome release with the categories and see what's missing there. Everything else... snap issues... bionic issues can be fixed after. Thank you!

**Pull request merged**
