### PR TITLE
Changed symbolic download icon to better match folder download

### PR DESCRIPTION
**Pull request by madsrh**
This fixes (only) the download icon in #2012 - which also is the most eye catching one.

image

image

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
Can we try a halfway house, making the hollow part of the stalk 3px instead of two? In that case, to ensure the image is sharp and aligned with the grid, you would then have to make the horizontal line across the bottom only 15px, and have the whole design either to the left or right of the canvas - whichever looks more balanced when the icon is in use (lots of symbols actually only use 15 of the px to allow an odd-numbered element to be cleanly centred).

**Comment by ubuntujaggers** [comment]
Oh wait... was it already like that ☺️

**Comment by friendlyapple** [comment]
Wouldn't it be better to leave the sidebar icon and change the folder icon? The download icon looks "compressed"

**Comment by clobrano** [comment]
Indeed, the folder glyph seems a bit out of proportion, like too tall
respect the wide, but I'm basically ok with it, if you prefer to keep this
style.

**Comment by ubuntujaggers** [comment]
@madsrh , maybe:

image

image

??

Tweaks:

- arrow stalk is 5px across (grey, white, white, white, grey) and the top of the stalk is lowered by 1px
- horizontal line is made to match the new arrow
- whole image is slightly to the right;

image

**Comment by madsrh** [comment]
@ubuntujaggers This looks good 👍 I'm still AFK, but could you make a pull request for that (since you've already made it 😄)?

**Comment by Feichtmeier** [comment]
Fixed by Stuart in the other pr

**Pull request closed without merging**
