### PR TITLE
Visible scrollbar trough improve slider visibility

### LINKED ISSUE #1096: Firefox scrollbars have transparent background, making them almost invisible in PDF viewer
I am using Yaru on Ubuntu 18.10 with Firefox 64.0. In Firefox, scrollbars have transparent background. This appears to be deliberate, due to issue #735. However, this makes them almost invisible in Firefox’s internal PDF viewer, as seen in the attached screenshots, because the color of the scrollbar is almost identical to the color of the viewer’s background.
screenshot0
screenshot1

### PR DESCRIPTION
**Pull request by clobrano**
On dark backgrounds the scrollbar slider visibility is very low.

Reenable trough's background color, but with high transparency
to fix this behavior without loosing the elegant effect in
light backgrounds

closes #1096 

Dark bg
image

Light bg
image

I double checked and the dark variant does not have the original issue and with this change it is good as well

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1097`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1097` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Hm, why don't we only change this for 
https://github.com/ubuntu/yaru/blob/master/gtk/src/light/gtk-3.20/_apps.scss#L541
?

**Comment by clobrano** [comment]
Because it is the `scrollbar trough` background color that should be colored, not `scrollbar` only.
In both cases the change it's the same, I can put in on _apps.scss or in _common.scss, but I expect that somehow it might be useful to fix this use case at a general level more than specifically to firefox.

**Comment by clobrano** [comment]
Normal Gtk apps won't be affected anyway, but Ok

**Comment by Feichtmeier** [comment]
Not? Then sorry, I should probably test stuff before commenting

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1097`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1097` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Tried and tested. It is a solution for the firefox issue.
Could you try to increase the visibility of the not selected slider instead? So that the slider is always visible and not the trough

**Comment by clobrano** [comment]
Better now?

image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1097`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1097` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by MatevzFa** [comment]
Hello,
after using `snap refresh communitheme --channel=edge/yaru-pr1097˙, I still don't see the change. Are there any other steps required to see the changes?
I'm on ubuntu 18.10, and had installed Communitheme using `snap install communitheme` before moving to `edge/yaru-pr1097`.

**Comment by clobrano** [comment]
Hi @MatevzFa, sorry for the late reply, light theme does not seem affected by this problem

dark variant
image

light variant
image

are you experiencing a different behavior?

**Comment by MatevzFa** [comment]
Yes. On the light theme, the scrollbar is practically invisible, and becomes orange when held with the mouse cursor.

**Comment by clobrano** [comment]
It looks quite visible to me and the orange on press is by design

**Comment by MatevzFa** [comment]
Here are some screenshots

When Firefox window is active:
active


When it is inactive:
inactive

When held:
held

**Comment by clobrano** [comment]
Do you use a dark theme for Firefox? This is not Yaru light for fure, the firefox toolbar is dark

**Comment by MatevzFa** [comment]
Oh ok. Thought installing communitheme with snap would resolve this issue.

**Pull request merged**
