### PR TITLE
New emblem-symbolic-link (smaller arrow)

### LINKED ISSUE #1218: Emblem lcons feedback and small issue
I'm following quietly lately, when I have free time. Not much of it as before, sorry! :disappointed:
Nit picking a bit if I may : when looking at the emblems the only one that stand out is the symbolic-link arrow that is not fitting so well in the circle. maybe a bit smaller arrow will be better.
seeing it together with all the new icons in 100% size may emphasize it :
screenshot from 2019-02-26 17-29-36
Otherwise, great work here @madsrh :+1:

_Originally posted by @Paz-it in https://github.com/ubuntu/yaru/pull/1191#issuecomment-467492449_

### PR DESCRIPTION
**Pull request by ubuntujaggers**
image

image

Closes #1218

**EDIT:** What a pillock, I screenshotted the current arrow.  Fixed!

### CODE REVIEW

**Comment by madsrh** [comment]
Thank you @ubuntujaggers 👏

**Comment by clobrano** [comment]
It looks very good :+1:

**Comment by clobrano** [comment]
just waiting for @Feichtmeier approval before merging

**Comment by Feichtmeier** [comment]
Haven't pulled the branch yet but it looks very nice

**Pull request merged**
