### PR TITLE
WIP: Add all missing symbolics icons

### LINKED ISSUE #2745: Missing symbolics icons
# List of missing symbolics icons

**Actions:**

- [x] address-book-new-symbolic.svg
- [x] chat-message-new-symbolic.svg
- [x] document-print-preview-symbolic.svg
- [x] edit-select-symbolic.svg
- [x] help-about-symbolic.svg
- [x] list-remove-all-symbolic.svg
- [x] mail-mark-junk-symbolic.svg
- [x] mail-mark-notjunk-symbolic.svg
- [x] mail-message-new-symbolic.svg
- [x] media-view-subtitles-symbolic.svg
- [x] sidebar-hide-symbolic.svg
- [x] sidebar-show-symbolic.svg
- [x] system-switch-user-symbolic.svg
- [x] view-conceal-symbolic.svg
- [x] view-list-bullet-symbolic.svg
- [x] view-list-ordered-symbolic.svg
- [x] view-mirror-symbolic.svg
- [x] view-reveal-symbolic.svg

**Apps:**

- [x] <del>accessories-dictionary-symbolic.svg</del>
- [x] help-contents-symbolic.svg
- [x] help-faq-symbolic.svg
- [x] preferences-color-symbolic.svg
- [x] <del>preferences-desktop-accessibility-symbolic.svg</del>
- [x] <del>preferences-desktop-apps-symbolic.svg</del>
- [x] preferences-desktop-font-symbolic.svg
- [x] <del>preferences-desktop-keyboard-shortcuts-symbolic.svg</del>
- [x] preferences-desktop-remote-desktop-symbolic.svg
- [x] preferences-desktop-screensaver-symbolic.svg
- [x] preferences-system-network-proxy-symbolic.svg
- [x] preferences-system-parental-controls-symbolic.svg
- [x] user-info-symbolic.svg

**Devices:**

- [x] ac-adapter-symbolic.svg
- [x] auth-sim-symbolic.svg
- [x] auth-smartcard-symbolic.svg
- [x] camera-web-symbolic.svg (_symlinked to camera-video-symbolic_)
- [x] colorimeter-colorhug-symbolic.svg
- [x] display-projector-symbolic.svg
- [x] modem-symbolic.svg
- [x] network-cellular-symbolic.svg
- [x] pda-symbolic.svg
- [x] phone-old-symbolic.svg
- [x] <del>scanner-symbolic.svg</del>
- [x] tv-symbolic.svg
- [x] uninterruptible-power-supply-symbolic.svg
- [x] <del>video-joined-displays-symbolic.svg</del>
- [x] <del>video-single-display-symbolic.svg</del>

**Emotes:**

- [x] emote-love-symbolic.svg
- [x] face-angel-symbolic.svg
- [x] face-angry-symbolic.svg
- [x] face-confused-symbolic.svg
- [x] face-cool-symbolic.svg
- [x] face-crying-symbolic.svg
- [x] face-devilish-symbolic.svg
- [x] face-embarrassed-symbolic.svg
- [x] face-glasses-symbolic.svg
- [x]  face-kiss-symbolic.svg
- [x] face-laugh-symbolic.svg
- [x] face-monkey-symbolic.svg
- [x] face-plain-symbolic.svg
- [x] face-raspberry-symbolic.svg
- [x] face-sad-symbolic.svg
- [x] face-shutmouth-symbolic.svg
- [x] face-sick-symbolic.svg
- [x] face-smile-big-symbolic.svg
- [x] face-smile-symbolic.svg
- [x] face-smirk-symbolic.svg
- [x] face-surprise-symbolic.svg
- [x] face-tired-symbolic.svg
- [x] face-uncertain-symbolic.svg
- [x] face-wink-symbolic.svg
- [x] face-worried-symbolic.svg
- [x] face-yawn-symbolic.svg

**Legacy:**

- [x] <del>battery-caution-charging-symbolic.svg</del>
- [x] <del>battery-caution-symbolic.svg</del>
- [x] <del>battery-empty-charging-symbolic.svg</del>
- [x] <del>battery-empty-symbolic.svg</del>
- [x] <del>battery-full-charged-symbolic.svg</del>
- [x] <del>battery-full-charging-symbolic.svg</del>
- [x] <del>battery-full-symbolic.svg</del>
- [x] <del>battery-good-charging-symbolic.svg</del>
- [x] <del>battery-good-symbolic.svg</del>
- [x] <del>battery-low-charging-symbolic.svg</del>
- [x] <del>battery-low-symbolic.svg</del>

**Mimetypes:**

- [x] application-certificate-symbolic.svg
- [x] application-rss+xml-symbolic.svg
- [x] <del>application-x-executable-symbolic.svg</del>   (_already exists in `scalable/src/apps`_)
- [x] application-x-firmware-symbolic.svg
- [x] font-x-generic-symbolic.svg
- [x] package-x-generic-symbolic.svg
- [x] x-office-address-book-symbolic.svg
- [x] x-office-drawing-symbolic.svg
- [x] x-office-presentation-symbolic.svg
- [x] x-office-spreadsheet-symbolic.svg

**Places:**

- [x] start-here-symbolic.svg

**Status:**

- [x] airplane-mode-symbolic.svg
- [x] auth-sim-locked-symbolic.svg
- [x] auth-sim-missing-symbolic.svg
- [x] bluetooth-hardware-disabled-symbolic.svg
- [x] call-incoming-symbolic.svg
- [x] call-outgoing-symbolic.svg
- [x] camera-disabled-symbolic.svg
- [x] camera-hardware-disabled-symbolic.svg
- [x] computer-fail-symbolic.svg
- [x] contact-new-symbolic.svg
- [x] content-loading-symbolic.svg
- [x] daytime-sunrise-symbolic.svg
- [x] daytime-sunset-symbolic.svg
- [x] image-loading-symbolic.svg
- [x] location-services-active-symbolic.svg
- [x] location-services-disabled-symbolic.svg
- [x] microphone-disabled-symbolic.svg
- [x] microphone-hardware-disabled-symbolic.svg
- [x] network-cellular-2g-symbolic.svg
- [x] network-cellular-disabled-symbolic.svg
- [x] network-cellular-hardware-disabled-symbolic.svg
- [x] network-no-route-symbolic.svg
- [x] network-vpn-no-route-symbolic.svg
- [x] network-wireless-disabled-symbolic.svg
- [x] network-wireless-hardware-disabled-symbolic.svg
- [x] orientation-landscape-inverse-symbolic.svg
- [x] orientation-landscape-symbolic.svg
- [x] orientation-portrait-left-symbolic.svg
- [x] orientation-portrait-right-symbolic.svg
- [x] screen-shared-symbolic.svg
- [x] <del>system-lock-screen-symbolic.svg</del>
- [x] touch-disabled-symbolic.svg
- [x] weather-tornado-symbolic.svg

**UI:**

- [x] checkbox-checked-symbolic.svg
- [x] checkbox-mixed-symbolic.svg
- [x] checkbox-symbolic.svg
- [x] focus-legacy-systray-symbolic.svg
- [x] focus-top-bar-symbolic.svg
- [x] focus-windows-symbolic.svg
- [x] list-drag-handle-symbolic.svg
- [x] pan-end-symbolic-rtl.svg
- [x] pan-start-symbolic-rtl.svg
- [x] pan-up-symbolic.svg
- [x] radio-checked-symbolic.svg
- [x] radio-mixed-symbolic.svg
- [x] radio-symbolic.svg
- [x] selection-end-symbolic-rtl.svg
- [x] selection-end-symbolic.svg
- [x] selection-start-symbolic-rtl.svg
- [x] selection-start-symbolic.svg

### PR DESCRIPTION
**Pull request by Jupi007**
I plan to add as much icons as possible to this PR. If anyone want to help, feel free to push to this branch (after indicating what you will be working on to avoid any clash).
The list of missing icons is here: #2745.

---

First wave of icons with **UI** ones.

**Checkboxes and radios:**

Capture d’écran du 2021-04-24 20-12-30
Capture d’écran du 2021-04-24 20-12-49

**Selection:**

Capture d’écran du 2021-04-24 20-13-07

**Focus:**

Capture d’écran du 2021-04-24 20-15-01

Closes #2745

### CODE REVIEW

**Comment by Muqtxdir** [comment]
@Jupi007 If it's alright with you I'll have a go at devices-icons

**Comment by Jupi007** [comment]
> @Jupi007 If it's alright with you I'll have a go at devices-icons

Alright 👍 Thanks a lot @Muqtxdir 
Currently I'm working on **"Actions"** ones.

**Comment by Muqtxdir** [comment]
added the following **devices**-icons:

devices

**Comment by Jupi007** [comment]
I'm really sorry @Muqtxdir, just noticed that we already have a **scanner-symbolic** icon into **"Apps"** 😥

Capture d’écran de 2021-04-22 22-49-52

**Comment by Jupi007** [comment]
New "actions" icons:
-

**"-new" icons:**

Capture d’écran du 2021-04-25 16-13-16

**Mail junk icons:**

Capture d’écran du 2021-04-25 16-18-37

**Sidebar icons:**

Capture d’écran du 2021-04-25 16-19-17

**All other ones:**

Capture d’écran du 2021-04-25 16-19-59

**Comment by Jupi007** [comment]
Next, I'll work on "apps".

**Comment by Jupi007** [comment]
New "apps" icons
--

**Preference icons:**

Capture d’écran du 2021-04-25 18-22-26

**Comment by Muqtxdir** [comment]
Woah, that was quick! And also the icons are 👌👌

**Comment by Jupi007** [comment]
> Woah, that was quick! And also the icons are ok_handok_hand

Thanks a lot 😊
Next will be **"emotes"** icons.

**Comment by Muqtxdir** [comment]
added the following **devices**-icons:

- [x] colorimeter-colorhug-symbolic.svg
- [x] network-cellular-symbolic.svg
- [x] modem-symbolic.svg
- [x] pda-symbolic.svg
- [x] phone-old-symbolic.svg
- [x] uninterruptible-power-supply-symbolic.svg

devices2





_Note: The icons are presently only in `src`, and have not been rendered under `Suru`_

**Comment by Muqtxdir** [comment]
next I'll work on **mimetypes**

**Comment by Muqtxdir** [comment]
added the following **mimetypes** icons:

- [x] application-certificate-symbolic.svg
- [x] application-rss+xml-symbolic.svg
- [x] <del>application-x-executable-symbolic.svg</del>   (_already exists in `scalable/src/apps`_)
- [x] application-x-firmware-symbolic.svg
- [x] font-x-generic-symbolic.svg
- [x] package-x-generic-symbolic.svg
- [x] x-office-address-book-symbolic.svg
- [x] x-office-drawing-symbolic.svg
- [x] x-office-presentation-symbolic.svg
- [x] x-office-spreadsheet-symbolic.svg

mimetypes

_Note: The icons are presently only in `src`, and have not been rendered under `Suru`_

**Comment by Muqtxdir** [comment]
added following **places** icons:

- [x] start-here-symbolic.svg

places



_Note: The icons are presently only in `src`, and have not been rendered under `Suru`_

**Comment by Jupi007** [comment]
Really good job @Muqtxdir 💪

But I have some comments to make:

- The **x-office-drawing-symbolic** shouldn't be folded, only human-readable files mimetypes should be folded.
- The **x-office-presentation-symbolic** is horizontal but our fullcolor version is vertical, all these kind of office files use a vertical icon.
- Using the Ubuntu font for **font-x-generic-symbolic** is a good idea but I think that we should symlink **applications-fonts-symbolic** instead (because there is two kind of font, so it looks more like a generic icon): 
Capture d’écran du 2021-04-26 12-08-19

Anyway good work :)

**Comment by Muqtxdir** [comment]
Hi @Jupi007,

So sorry about the  **x-office-drawing-symbolic**, **x-office-presentation-symbolic** and **font-x-generic-symbolic** icons not following the guidlines. I'll modify them according to your suggestions ( _Thanks for the tips!_ )

**Comment by Muqtxdir** [comment]
corrected the following **mimetype-icons:**
- x-office-drawing-symbolic
- x-office-presentation-symbolic 
- font-x-generic-symbolic

corrected-mimetypes

**Comment by Jupi007** [comment]
Looks perfect IMO. Do you want I render them?

**Comment by Muqtxdir** [comment]
> Looks perfect IMO. Do you want I render them?

ok :+1:

**Comment by Jupi007** [comment]
Done, but my commit message is 🤪

**Comment by Jupi007** [comment]
> @Jupi007 I've moved all the mentioned battery-icons from **status** to **legacy** under `src` and `Suru`

Perfect, thanks!

**Comment by Muqtxdir** [comment]
added the following **devices**-icons:

- [x] auth-smartcard-symbolic
smart-card


 
_Note: The icons are presently only in `src`, and have not been rendered under `Suru`_

**Comment by Jupi007** [comment]
Looks perfect @Muqtxdir

**Comment by Jupi007** [comment]
New emotes icons
---

Capture d’écran du 2021-04-26 20-23-04

**Comment by Jupi007** [comment]
New network "status" icons
---

Capture d’écran du 2021-04-27 11-31-14

**Comment by Jupi007** [comment]
All other new "status" icons
---

Capture d’écran du 2021-04-27 19-47-27

And that's it, Yaru symbolic icons are now fully synced with Adwaita 🎉

**Comment by Muqtxdir** [comment]
Awesome job @Jupi007 for completing this huge effort, totally liking with the new symbolics

**Comment by Jupi007** [comment]
New upstream "status" icons
---

Capture d’écran du 2021-04-29 11-49-27

**Pull request merged**
