### PR TITLE
Improve menu, popover and window borders

### PR DESCRIPTION
**Pull request by Feichtmeier**
Before:
image
image

After
image
image

@madsrh @clobrano look closely at the edge between the menubar and when the menu pops up
There is a super small overlapping of the box-shadow
Looks a bit blurry

Please test this if you have time ;)

Closes https://github.com/ubuntu/yaru/issues/1117

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1131`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1131` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1131`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1131` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Wow, great find @Feichtmeier 🔍 

The top looks better for sure 👍 

You've also changed the border and I'm not sure about this darker version. It looks kind of strong compared to the separator lines 🤷‍♂️  

untitled-2

**Comment by Feichtmeier** [comment]
Yes it is the whole border around the menu"window"

When I reduce the transparency of the black, the border becomes even stronger. If you mean less strong, that is how it looks with 0.1 more transparency (too much imho):

image

**Comment by Feichtmeier** [comment]
Yes I need to restructure the code anyways. Since some lines are unnecessary

**Comment by clobrano** [comment]
Looks good to me as well :+1:

**Comment by Feichtmeier** [comment]
Nice! But please don't merge yet. Need to make this a bit less confusing with that variables and assignments all over the place

**Comment by clobrano** [comment]
Ok, no problem

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1131`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1131` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Pull request merged**
