### PR TITLE
Adding a pgp mime icon

### PR DESCRIPTION
**Pull request by madsrh**
Add a mime icon for pgp keys:

application-pgp-keys

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1161`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1161` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by eaglersdeveloper** [comment]
What about key icon as pictogram?

**Comment by madsrh** [comment]
@eaglersdeveloper I tried that too but it doesn't look good at small sizes.

I'm fine with both solutions, but I think this one IMHO works best (although it isn't actually a key 😆)

**Comment by eaglersdeveloper** [comment]
Turn it over :)

**Comment by madsrh** [comment]
What do you think?

image

**Comment by clobrano** [comment]
I still prefer the lock. Maybe it's just my problem, but the vertical key is a bit less recognizable

**Comment by Feichtmeier** [comment]
I prefer the lock, too! :dancer: 
I think the vertical key looks like a cyclope-elephant on smaller sizes but that's only my stupid brain not working correctly :D

**Comment by madsrh** [comment]
Allright the lock it is 👍 

image

**Pull request merged**
