### PR TITLE
Gtk theme: darker dark theme

### LINKED ISSUE #2227: Gtk3: Different font colors in backdrop in listbox/sidebar rows
White text should be "dimmed" equally in backdrop:

gif

The combobox text almost looks disabled in backdrop 🤷‍♂️

### PR DESCRIPTION
**Pull request by Feichtmeier**
- base the whole gtk dark theme on $jet `#181818` instead of $inkstone `#3b3b3b`
- as a result everything is now a bit darker
- another result is that the dark gtk theme is now closer to the shell popups/dialogs/notifications
- the gtk theme however does not use half transparent borders to avoid glitches
- gtk4 is adapted to this change (should be the same result ideally)

WIP: up-to-date screenshots can be followed through in the conversation below

Everyone please have a look and share your feedback.

Closes #2227

### CODE REVIEW

**Review by madsrh — COMMENTED** [review]
This looks good @Feichtmeier 
I wonder if the backdrop also should have the sidebar background:

image

**Comment by Muqtxdir** [comment]
hi, 

this darker-theme looks nice and beautiful. however, for me the backdrop is where this is getting tricky.
In some apps, there is no problem in backdrops but a few have minor-nitpicks. so far I've only used this for couple of hours and **gnome-web(epiphany-browser)** sticks out here (i'll add more of the backdrop-issue cases when I come across but please do keep in mind this are very very minor-nitpicks):

### current-dark theme:
before

### darker-dark theme:
after

**Comment by Feichtmeier** [comment]
Thanks @Muqtxdir 
Considering that we went much lighter with yaru dark than Adwaita dark in 20.04 I wonder how Adwaita dark themes the contrast in the backdrop? I am not at the computer right now but I think that yaru light and Adwaita don't use much contrast in the backdrop by design. This doesn't mean than we can and should do what we think is correct though

**Comment by elioqoshi** [comment]
Thanks @Feichtmeier !

This looks good to me and I'd consider this an improvement on the first sight. However what @Muqtxdir is a good point. We should probably not sacrifice eligibility here. Is there a way to have the best of both worlds?

> I wonder if the backdrop also should have the sidebar background color:

I'd think it's good the way it is as it contrasts with the background and sets foreground and background apart better.

P.S: Is it fine if I add myself to reviewers? Just so I can cover Yaru during my work time.

**Comment by Feichtmeier** [comment]
> Thanks @Feichtmeier !
> 
> This looks good to me and I'd consider this an improvement on the first sight. However what @Muqtxdir is a good point. We should probably not sacrifice eligibility here. Is there a way to have the best of both worlds?
> 
> > I wonder if the backdrop also should have the sidebar background color:
> 
> I'd think it's good the way it is as it contrasts with the background and sets foreground and background apart better.
> 
> P.S: Is it fine if I add myself to reviewers? Just so I can cover Yaru during my work time. Let me know if you prefer a process.

Sure thing - very much appreciated to have you reviewing!

Best of both world should be possible.
The upstream theme we rely on has various vars connected to the base colors and then darkening / lightening it appropriately in the backdrop/active/and so on. But those functions have their limits. Or maybe we could say that they are not "linear".
Eventually I need to fix the backdrop colors, but if we do this, it needs to be in _colors.scss or _drawing.scss and not special casing more stuff in _tweaks.scss :)

**Comment by Feichtmeier** [comment]
Okay, so let's take a look at Adwaita light first - the idea here is to have the backdrop fade out and only show a minimal difference between element states:

adwaitalight

We follow with yaru-light 100% here and I think this works great:
adwaitalight

Adwaita dark also has a minimal difference in backdrop between the states:
adwaitadark

Current Yaru-dark actually is pretty similar to Adwaita dark
yarudarkcurrent

Proposed Yaru-dark is not very far away from it 
proposedyarudark

So I think those issues happen specifically in the apps you've shown @Muqtxdir 

It's the PDF viewer and the web browser right?
The webbrowser uses libhandy styling though. So maybe this is an app specific issue after all

**Comment by Muqtxdir** [comment]
Thank-you @Feichtmeier, for pointing out the comparision between yaru-backdrop and adwaita-backdrop here

> It's the PDF viewer and the web browser right?

yes those two, I use them regularly so it caught my eye but  can't say about other apps

> The webbrowser uses libhandy styling though. So maybe this is an app specific issue after all

does the work done by @Jupi007 for adding libhandy-styling to gtk not overwrite the default libhandy-styling?

**Comment by Feichtmeier** [comment]
I think we can get closer to what we had by just lightening up the backdrop overall a little bit, so the button functions don't overreact so much:

Here everything is a little bit lighter plus the popovers rely on the regular backdrop border color @madsrh 
grafik

**Comment by Muqtxdir** [comment]
pulled in the latest commit changes and the backdrop definitely improves, lightening up the colors in backdop improves the eligibility on the app's I've tried 👍
### before darker-theme backdrop:
darker-screenshot
### latest darker-theme backdrop:
new-dareker-screenshot

thanks !

**Comment by Feichtmeier** [comment]
Thanks @Muqtxdir glad it works

A little improvement to backdrop insensitive buttons in the backdrop, now they change bg color accordingly 
grafik

**Comment by madsrh** [comment]
Sorry @Feichtmeier we've misunderstood each other again 😄💬 What I was trying to say was, that these two have the same color in focus, so shouldn't they also have that in backdrop?

image

**Comment by Feichtmeier** [comment]
> Sorry @Feichtmeier we've misunderstood each other again smilespeech_balloon What I was trying to say was, that these two have the same color in focus, so shouldn't they also have that in backdrop?
> 
> image

hehe np

Is this the case only in my change? Because I didn't touch any text / forground color vars :thinking: 
Or do you mean in general? If yes then we should maybe set up an extra issue for this

Or do you mean the same background color?
If yes, then I would rather adjust the background color of the sidebar of nautilus in backdrop

**Comment by elioqoshi** [comment]
@Feichtmeier Looking solid! I am wondering that maybe it can be a bit clearer which window is in the background by slightly making the icon and text colour darker on the backdrop window. It could help emphasize which window is currently focused, what do you think?

**Comment by Feichtmeier** [comment]
> @Feichtmeier Looking solid! I am wondering that maybe it can be a bit clearer which window is in the background by slightly making the icon and text colour darker on the backdrop window. It could help emphasize which window is currently focused, what do you think?

Do you mean the color of the text and the color of symbolic icons in the backdrop in the sidebar of nautilus and gnome control center?

**Comment by elioqoshi** [comment]
> Do you mean the color of the text and the color of symbolic icons in the backdrop in the sidebar of nautilus and gnome control center?

Yep

**Comment by Feichtmeier** [comment]
Yes you are right, the light theme actually fades out much more
grafik
grafik

Will fix this later - thanks! :+1:

**Comment by Jupi007** [comment]
I tested this PR the whole day and I didn't noticed any problem.
I think it looks very good!
Good work @Feichtmeier 💪

**Comment by Feichtmeier** [comment]
@elioqoshi is this okay or too much?

grafik
grafik

But that gray in the orange rows is not so sexy.
Maybe we can fix #2408 with this PR too


#2227 is now fixed @madsrh :)

**Comment by madsrh** [comment]
> #2227 is now fixed @madsrh :)

🎉 

> But that gray in the orange rows is not so sexy.

+1 maybe just use white with 50% opacity

**Comment by elioqoshi** [comment]
> @elioqoshi is this okay or too much?

I think this is too little in fact.

> +1 maybe just use white with 50% opacity

How about 30% white? Disabled states of web elements usually use 30% of the default state

**Comment by madsrh** [comment]
> How about 30% white? Disabled states of web elements usually use 30% of the default state

I'm good with anything but gray 😄 ...but the "button" isn't actually disabled - it's just not in focus 😉 

image

**Comment by elioqoshi** [comment]
> but the "button" isn't actually disabled - it's just not in focus 😉

You might be right, although functionally there is not much of a difference of something currently being disabled and not being in focus. In both case you can't interact with it. Interacting with an unfocused window brings it into focus but doesn't register any interaction on that window in itself.

**Comment by Feichtmeier** [comment]
There is even :backdrop:disabled and crazy states like this in gtk ^^ 

Let's try transparent whites for the dark themes backdrop color 
grafik
grafik

WDYT @elioqoshi @madsrh ?

**Comment by elioqoshi** [comment]
@Feichtmeier I do think that looks good. Is that 50% white? My first intuition would be to make it even more transparent, but I might be biased as I checkeed on macOS and ttheyy apprroximately fade out 50% of unfocused UI elements too.

**Comment by Feichtmeier** [comment]
> @Feichtmeier I do think that looks good. Is that 50% white? My first intuition would be to make it even more transparent, but I might be biased as I checkeed on macOS and ttheyy apprroximately fade out 50% of unfocused UI elements too.

It's 35% and 45%
Depending if it is drawn on $backdrop_base_color or $backdrop_bg_color

**Comment by Feichtmeier** [comment]
Anything else or can I merge @elioqoshi @madsrh ?

**Comment by madsrh** [comment]
This looks good 👍

**Comment by elioqoshi** [comment]
Looking good, thanks!

**Pull request merged**
