### PR TITLE
appearance: add accent colors to yaru

### PR DESCRIPTION
**Pull request by Muqtxdir**
_Note: This just sets-up the necessary files under `gtk` for accent-colors, Colors used in this PR are temporary and acts as placeholder._

### TO-DO:

- [ ] gtk-2.0 (_symlinked at the moment_)
- [x] gtk-3.0 
- [x] gtk-4.0
- [x] icons for recolor by `accent_colors`:
     - [x]  filemanager-app (_provide another SVG as it needs a black/white gradient_)
     - [x] gnome-tweak-tool
     - [x] software-updater
     - [x] emblem-symbolic-link
     - [x] folders-* (_provide another SVG as it needs a black/white gradient_)
     - [x] user-desktop (_provide another SVG as it needs a black/white gradient_)
     
     _Note: also look into symlinks for fullcolor-icons_ 

#### screen-reocord:
https://user-images.githubusercontent.com/54065734/155732402-1b8355a4-33ec-4e33-a0e3-bfdd61e92a85.mp4

### CODE REVIEW

**Comment by rafaelmartines** [comment]
The UI Freeze from Ubuntu is tomorrow right? That's mean that if this PR won't be accepted until tomorrow this PR won't be in in 22.04?

**Comment by 3v1n0** [comment]
@rafaelmartines we're working hard to get in before UI freeze, in case there are still exceptions, but we're confident to upload it in time :)

**Comment by Muqtxdir** [comment]
@3v1n0 is it possible to have `gdm` use `gnome-shell-dark.css`?

**Comment by Jupi007** [comment]
Yes, it could better to have the dark variant on gdm screen, as the bg use a dark grey.

**Comment by rafaelmartines** [comment]
Oh my god, okay it's happening!!!

**Comment by 3v1n0** [comment]
@Muqtxdir, @Jupi007 gdm is now dark by default, added new options to control this though :)

**Comment by 3v1n0** [comment]
Soo... It has been a bit intense, but I think we got good results, thanks a lot  @Muqtxdir for proposing this and @elioqoshi and @Jupi007 for helping on the design front.

There are still things to improve and gnome-shell light theme is a bit broken (not in-usable, but not great...), but I think we can proceed with a first release now that all the pieces are in ubuntu, and yaru is the only missing bit :).

Soooo... Merging!

**Comment by ItzSwirlz** [comment]
Y'all are living legends, great job. I wish I could be intelligent enough to theme things!

**Comment by Muqtxdir** [comment]
Thank you to all who were involved in the process of making this possible! It's really been great to help with this feature

**Comment by Jupi007** [comment]
Thanks everybody who worked on this ❤️
Ubuntu 22.04 will be awesome!

**Comment by rafaelmartines** [comment]
Just tested it on daily build and it's amazing thanks everyone :D

**Comment by mzur** [comment]
I'm curious what happened to the original colors proposed above. I quite like the livelier colors (e.g. aqua, yellow). However, in Ubuntu 22.04, I see these choices, where many of the green/gray variants look mostly the same to me (with slight deuteranopia):

Screenshot from 2022-04-29 09-37-00

**Comment by mzur** [comment]
Many thanks for the explanation! I see that the colors were carefully chosen. And great to see how easy it is to add custom colors! I've maintained my own forked themes before just to change the highlight color but there is no need for that any more. Thank you all for your great work!

**Pull request merged**
