### PR TITLE
Split _apps into multiple files

### LINKED ISSUE #2393: Better organisation for gtk3+gtk4 app specific scss code
- [ ] create the directory `apps` in https://github.com/ubuntu/yaru/tree/master/gtk/src/default/gtk-3.20

- [ ] create one scss file, i.e. `_nautilus.scss`, for each app currently styled in `_apps.scss`

- [ ] include all app scss files inside `_apps.scss`

- [ ] adapt meson build to the new files

### PR DESCRIPTION
**Pull request by Jupi007**
Split _apps into multiple files for a better organization.

Closes #2393

### CODE REVIEW

**Comment by clobrano** [comment]
Hi @Jupi007, it seems to me that the `@import apps` line in  `gtk-3.20\gtk.scss` won't import the new files under `apps` folder.

**Comment by Jupi007** [comment]
`gtk.scss` import `_apps.scss` which import all files into `apps/`:

https://github.com/ubuntu/yaru/blob/f00fa0593425cbf2fd2fd31fe6244691ad0702d1/gtk/src/default/gtk-3.20/_apps.scss#L1-L19

**Comment by Feichtmeier** [comment]
wanting to test this but my shell always hangs in the VM :crying_cat_face: 
I will not give up! :laughing:

**Comment by clobrano** [comment]
> `gtk.scss` import `_apps.scss` which import all files into `apps/`:
> 
> https://github.com/ubuntu/yaru/blob/f00fa0593425cbf2fd2fd31fe6244691ad0702d1/gtk/src/default/gtk-3.20/_apps.scss#L1-L19

Ok sorry, I missed that file

**Comment by Feichtmeier** [comment]
Bildschirmfoto von 2021-05-19 22-20-37

Tested most of the apps we've tweaked, works :+1:

**Review by Feichtmeier — APPROVED** [review]

**Pull request merged**
