### PR TITLE
Darken border_bottom_color less in the dark variant for btn hover

### PR DESCRIPTION
**Pull request by Feichtmeier**
peek 2018-08-29 11-33

Closes https://github.com/ubuntu/yaru/issues/755

@ya-d like this?

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr756`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr756` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Paz-it** [comment]
The current is better imo.

**Comment by Feichtmeier** [comment]
I am not sure. Maybe ya-d is right
Any other opinions @madsrh @c-lobrano

**Comment by clobrano** [comment]
Honestly, I like this, but it introduces it a complex code, so I'd keep the current as well

**Comment by Feichtmeier** [comment]
Lets wait for ya-d and mads and then eventually close it

**Comment by ya-d** [comment]
I like it as it tones down the naturally black shadow. 👍 Thanks for the pr, @Feichtmeier !

**Comment by madsrh** [comment]
Sorry for not being much help here, but I'm good with both solutions.

This PR looks slightly better (more elegant IMO) but I didn't notice the all black shadow before ya-d mentioned it.

**Comment by clobrano** [comment]
Alright, if we agree that the effect is good, the complexity can be reduced (even later). I was thinking about doing something like that anyway after UI Freeze :snowflake:

**Comment by Feichtmeier** [comment]
This way we don't need to change the border color. Because I think it is already at the contrast edge. I wonder if this clashes with the other pr because it is almost in the same part

**Comment by Feichtmeier** [comment]
I could reduce the inner if else with an inline  if check. The rest is needed because we have the dark header bar and a dark and light variant with the same headerbar color. That's why we need to check this three possibilities so often in drawing. Actually we should remove all these lightness checks all together of we stay with our dark headerbar (which I hope and which I don't think anyone wants to change)

**Comment by clobrano** [comment]
Yes I agree, but let's do it in another PR, taking advantage of the UI freeze time, when all the changes won't affect the general style

**Pull request closed without merging**
