### PR TITLE
Add distributor logo icon

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
distributor-logo

I took the idea from the Scopes app:

### CODE REVIEW

**Comment by Feichtmeier** [comment]
I am quiet sure we have something similar somewhere in the src :thinking:

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/apps/welcome-app.svg

**Comment by eaglersdeveloper** [comment]
`apps/welcome-app`?
welcome-app

**Comment by eaglersdeveloper** [comment]
You are faster than me

**Comment by eaglersdeveloper** [comment]
But my icon looks better.

**Comment by madsrh** [comment]
Releated to https://github.com/snwh/suru-icon-theme/issues/80 ?

What is this icon for @eaglersdeveloper? Is it to replace the Welcome app?

**Comment by eaglersdeveloper** [comment]
This icon appears in the "Sorry, Ubuntu 18.10 has experienced an internal error" error.



Also thought that the error really appeared?

Also I think that the "Welcome to Ubuntu" application uses this icon (distributor-logo).

**Comment by clobrano** [comment]
> This icon appears in the "Sorry, Ubuntu 18.10 has experienced an internal error" error.
> 
> 
> 

If that so, I am unsure a suru icon fits well in this context. It should be mainly for application icons, not symbols in some window

**Comment by Feichtmeier** [comment]
I think it's also used in gnome settings when you click on info of your system

But as Carlo said, that's really the logo of Ubuntu and it is not in this Suru shape so I'm -1 for changing this one.

I can think it would be okay to replace the welcome app icon though. If @ubuntujaggers is okay with it and Mads and Carlo also like it

**Comment by clobrano** [comment]
> I can think it would be okay to replace the welcome app icon though. If @ubuntujaggers is okay with it and Mads and Carlo also like it

+1

**Comment by eaglersdeveloper** [comment]
> I think it's also used in gnome settings when you click on info of your system

In Settings used `ubuntu-logo-icon`, not `distributor-logo`

default

**Comment by eaglersdeveloper** [comment]
This icon is only in 256x256 folder.

**Comment by galgalesh** [comment]
-1 for changing it from me too. I think `distributor-logo` should show the unmodified logo itself. Even though I like your version.

Also note that there are some strict guidelines on how to display the Ubuntu logo.

https://design.ubuntu.com/brand/ubuntu-logo/

**Comment by ubuntujaggers** [comment]
Hi all,

The final version of the Welcome app was actually done by snwh, and he didn't want to "overly stylize it since it is a logo."  I think it's pretty smart and respectful to the vanilla-est version of the CoF.

I also like the white-on-orange look (nice vector, @eaglersdeveloper) but there's a minor point around the fact that Ubuntu already has the Software icon on the launcher by default, which is also white on orange.  So that's another small advantage of having orange on white in this context.  It's just a bit of variety on the launcher when you're setting up for the first time.

**Comment by Feichtmeier** [comment]
So, if we keep the distributor logo and don't want to change the welcome-app logo, any other place where this icon might fit? It looks well made for sure.

**Comment by Feichtmeier** [comment]
hmhm, anyone still around here?
If we do not want to merge this, I see no point in keeping this one opened.

To summ it up
- this looks nice
- if it would be the welcome-app logo, it would be the second orange icon on the dock beside gnome-software
image
- it should be used as the distributor logo, since this one should stay as canonical designed it

**Comment by clobrano** [comment]
The icon is very nice, but if there is no way to apply it, let's close this PR

**Pull request closed without merging**
