### PR TITLE
Add Podcasts icon

### PR DESCRIPTION
**Pull request by eaglersdeveloper**
New icon for GNOME Podcasts:

podcasts-app

### CODE REVIEW

**Comment by eaglersdeveloper** [comment]
Happy 1000th issue and PR!

**Comment by eaglersdeveloper** [comment]
Anyone merge this?

**Comment by eaglersdeveloper** [comment]
@Feichtmeier, this pull request ready to merge.

**Comment by clobrano** [comment]
I like it, however it's far away from the original design and it looks more like a radio app. No strong feelings against it though, let's see what mads says

**Comment by madsrh** [comment]
Looks great! 

> why didn't upstream want it? 

+1

**Pull request merged**
