### PR TITLE
Emblem for documents, downloads and photos

### PR DESCRIPTION
**Pull request by madsrh**
While investigating #1903 I found that there's a few more of the common emblems that we're missing. Can anyone help test these?

image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thanks @madsrh !

I don't know how to test it, but from the pictures it loosk good and the commits look also fine.

**Comment by ubuntujaggers** [comment]
Well done Mads!

**Comment by madsrh** [comment]
image

**Comment by Feichtmeier** [comment]
I think they look good - are you done here @madsrh ?

**Pull request merged**
