### PR TITLE
Remove the livepatch icon from the yaru repository

### PR DESCRIPTION
**Pull request by Feichtmeier**
To re-add it in the ubuntu repository

### CODE REVIEW

**Comment by clobrano** [comment]
Do we need to wait until Ubuntu includes the patch before merging this?

**Comment by Feichtmeier** [comment]
I think sebastian bacher is currently looking for a way to keep the yaru icon in yaru and but then let the livepatch indicator use it's correct icon. They have different names so it should be possible. So eventually we can just close this PR when he is successful. The reason is that they may not want the yaru icon in their repo is that the livepatch is also used in different distros which do not use yaru

**Comment by clobrano** [comment]
I see, thanks

**Comment by Feichtmeier** [comment]
Seb fixed it, so this is not needed: https://launchpadlibrarian.net/472380880/update-notifier_3.192.30_source.changes

**Pull request closed without merging**
