### PR TITLE
Add cinnamon variants

### PR DESCRIPTION
**Pull request by Jupi007**
- [x] Add cinnamon variant files ;
- [x] Use cinnamon color sheme.

### CODE REVIEW

**Comment by Jupi007** [comment]
VirtualBox_Ubuntu cinnamon 21 04_11_02_2022_12_05_08

**Comment by Jupi007** [comment]
@ItzSwirlz and/or @hsbasu can you test this and add your review please?

**Comment by hsbasu** [comment]
sorry, on my `impish` I am getting the following error:

```
 dpkg-buildpackage -us -uc -ui -S -d
dpkg-buildpackage: info: source package yaru-theme
dpkg-buildpackage: info: source version 22.04.1
dpkg-buildpackage: info: source distribution jammy
dpkg-buildpackage: info: source changed by Muqtadir <muqtadir5555@gmail.com>
 dpkg-source --before-build .
 fakeroot debian/rules clean
dh clean --buildsystem=meson --with migrations
dh: error: unable to load addon migrations: Can't locate Debian/Debhelper/Sequence/migrations.pm in @INC (you may need to install the Debian::Debhelper::Sequence::migrations module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at (eval 13) line 1.
BEGIN failed--compilation aborted at (eval 13) line 1.

make: *** [debian/rules:5: clean] Error 25
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -S -d failed
```

**Comment by ItzSwirlz** [comment]
look whos ugly butt forgot! If I remember (I better..) I'll test it tonight. The screenshot looks good!

> debuild -S -d -us -uc
>  dpkg-buildpackage -us -uc -ui -S -d
> dpkg-buildpackage: info: source package yaru-theme
> dpkg-buildpackage: info: source version 22.04.1
> dpkg-buildpackage: info: source distribution jammy
> dpkg-buildpackage: info: source changed by Muqtadir <muqtadir5555@gmail.com>
>  dpkg-source --before-build .
>  fakeroot debian/rules clean
> dh clean --buildsystem=meson --with migrations
> dh: error: unable to load addon migrations: Can't locate Debian/Debhelper/Sequence/migrations.pm in @INC (you may need to install the Debian::Debhelper::Sequence::migrations module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at (eval 13) line 1.
> BEGIN failed--compilation aborted at (eval 13) line 1.

Because you specified -d, it skipped the dependency check. You are missing dh-migrations, a debhelper module (to help the build process) with package migrations

**Comment by ItzSwirlz** [comment]
The cinnamon desktop theme part of the variant got installed, the icons/other stuff didn't but I think those are still WIP

**Comment by Jupi007** [comment]
I only added two variants on the `cinnamon` component.
I'll add `Gtk` and icon theme variants later, in separated PRs.

**Pull request merged**
