### PR TITLE
Adapting GTK  menus and GtkPopover to GNOME shell popups resulting in $jet gtkmenus/popovers

### PR DESCRIPTION
**Pull request by Feichtmeier**
Since @didrocks mentions an realistic chance to get this into cosmic ( https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1794942 )
The yaru team would like to test this PR since screenshots are not enough to find all issues.

Screenshots:

image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr876`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr876` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
UIF has already happened a couple of weeks ago (see the threads on the forum), what I requested multiple times is someone to file an UIF *exception*: https://wiki.ubuntu.com/FreezeExceptionProcess#UserInterfaceFreeze_Exceptions. I suggest this is filed ASAP and tell we aim to upload that on Monday. (also, if there are any other chances currently in master which may be impacted by it, please state in the same bug as well).

**Comment by madsrh** [comment]
@didrocks Will do, just need to test it to make sure it's good ;)

**Comment by madsrh** [comment]
@Feichtmeier Can we change the color of deactivated items? They almost look like the active ones atm. 
IMO (almost) matching the border color would be good:

dd

**Comment by didrocks** [comment]
@madsrh thanks! https://wiki.ubuntu.com/UserInterfaceFreeze for more general info (and you need to get an approval for the release team). I'm happy to ping the release team if you point me to the bug :) (but I let you informing the documentation team. I don't think the translation team is impacted).

You can tell as well that the menu changes is suggested by mpt (I think it was, correct?)

**Comment by Feichtmeier** [comment]
> You can tell as well that the menu changes is suggested by mpt (I think it was, correct?)

mpt and trevinho some weeks earlier (but trevinho though more of the great usability of ambiance menus, so basically we have 2 arguments now 1) mpt: consistency shell/gtk 2) ambiance -> yaru transistion for users)

**Comment by didrocks** [comment]
@Feichtmeier sounds good to me, please mention them in the report ;)

**Comment by Feichtmeier** [comment]
image

Missing treeview styling in popovers

**Comment by madsrh** [comment]
This one is really difficult to see when there's a bright/white window background behind. Sure the popover is easily distinguishable from the window behind, but IMO much worse usability inside the popover than the white ones.
I'm not sure if it's the popover background, entry border or entry background that needs tweaking here 🤷‍♂️ 

The background of the **Title** field and the **Description** field isn't the same color.


image

Totally unrelated to this PR, shouldn't the textview  **Description** field have rounded corners, like the entry above?

**Comment by Feichtmeier** [comment]
https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1794942

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr876`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr876` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr876`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr876` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
peek 2018-09-28 14-27
@madsrh like this?

**Comment by madsrh** [comment]
> like this?

Nope, we need the separator lines - especially since these entries have two lines.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr876`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr876` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr876`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr876` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
image
Fixed firefox, shadows, colors and border colors, most things discussed with @madsrh outside of this PR

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr876`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr876` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by taciturasa** [comment]
I'm incredibly disappointed in this design decision. The decision upstream to have different context/popover colors for shell and app elements wasn't made without consideration; it was designed so that users could differentiate between content and system controls and data. Not to mention the fact that this causes issues with plenty of elements, as toolkit popvoers are much more complex than a context menu and it means you have to store and maintain two separate styles for the same sort of content. It was also designed so that popovers could still feel consistent with the rest of the interface; so that they would still feel like part of the application and content, instead of a separate entity operating on a completely different level.

Especially with the beautiful looking removal of titlebar for modal popups within apps, as well as the light colored portala nd system wide dialogs, it feels particularly inconsistent and poorly thought out. I only see a large potential of issue and complications arising with this design decision, and very little in the way of reasoning in the way of function over form, or advantages of going forward with this. As the default then to the largest distribution of Linux period, directly changing and modifying basic interaction decisions from upstream I think sets a dangerous precedent for the project going forward as well as the community's relationship with gnome in the future.

**Comment by Feichtmeier** [comment]
1) the user doesn't care if it is gnome shell or an app. I know if you are a full-time Linux lover like me and you one tend to think that everyone should appreciate the shell and so on. But in the end if you get a little distance... No one cares what is the shell.
It's just your operating system.
2) the usability is much better since the contrast is better
3) we currently have three different menu colours a) light b) Gray c) black
That's too much

**Comment by Feichtmeier** [comment]
> changing and modifying basic interaction decisions from upstream I think sets a dangerous precedent for the project going forward as well as the community's relationship with gnome in the future.

Highly exaggerated, sorry.

Taking the drama away, let's continue to talk about this on the hub.
It has become a bad habit  since some days to highjack PRs for offtopic talk.

This is came directly from a canonical designer by the way. 

Just post on the hub about your concerns and let's discuss it.

Due to technical risks we are not sure if this will happen anyways. This will be decided tomorrow

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr876`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr876` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
Feedback: I like this, but when I try the PR channel posted by didrocks above, the menus in Inkscape change in an unforeseen/undesired way.  The menus are white but the text is light grey, to the extent where all the options seem "greyed out" and unavailable.  Clicking them works normally, but it looks odd and is a little confusing (because all items seem disabled) and is slightly harder to read.  The change survives a laptop restart and is undone when I switch back to the edge channel.

Weirdly, I can't seem to take a screenshot when I have an Inkscape menu open (?!) but it would be worth checking your own installs to see if this occurs for everyone.

**Comment by Feichtmeier** [comment]
Postponed to the next release cycle - thus closing this Pull request, no need to keep it open at the moment
Thanks for the feedback

**Comment by Feichtmeier** [comment]
Don't delete the branch please ;)

**Pull request closed without merging**
