### PR TITLE
icons: reorganize `org.gnome.Settings*` symbolic icons

### PR DESCRIPTION
**Pull request by Muqtxdir**
#### changes:
- since couple of past few releases settings has quite few re-orgs with icon dir and icon-names and it was not easy to track the changes/diff to upstream, hence all symbolic-icons associated with settings have been moved under `org.gnome.Settings` directory to track it one place.
- removed symlinks as these icons have been updated/touched in recent cycles, better to have them distinct.
- added missing symbolics and updated few symbolics to match upstream representation :)

#### screenshots:
| icons | screenshot |
| -------- | ---------------- |
|system, region, date, about| Screenshot from 2024-04-01 02-06-25 |
| privacy* | Screenshot from 2024-04-01 02-06-33 |

### CODE REVIEW

**Review by Feichtmeier — APPROVED** [review]
Thank you!
LGTM

**Comment by Feichtmeier** [comment]
Does this failed test has any relevance to the icons changed?

 The following packages have unmet dependencies:
 gnupg2 : Depends: gnupg (>= 2.4.4-2ubuntu15) but it is not installable

**Review by Jupi007 — APPROVED** [review]
Great job, LGTM !
Thanks a lot @Muqtxdir

**Comment by Muqtxdir** [comment]
thanks everyone!

**Pull request merged**
