### PR TITLE
missing symbolic-icons for libhandy and libadwaita

### PR DESCRIPTION
**Pull request by Muqtxdir**
fixes issue: #3023
@Jupi007 please have a look at this and add Github actions

### CODE REVIEW

**Comment by Muqtxdir** [comment]
Thanks @Jupi007

**Comment by Jupi007** [comment]
Thanks @Muqtxdir it looks much better with Yaru icons :)
But imo we should prefer use `pan-down` instead of `go-down`.

**Comment by Muqtxdir** [comment]
I used go down beacuse in about page the symbol at hostname for expander is go-right

**Comment by Jupi007** [comment]
Yes because the `go-*` arrow are used to navigate to another screen - on the info page it open a popup :)

IMO this could rather be compared to the color page:

Capture d’écran du 2021-09-22 21-12-50

Or with the system menu:

Capture d’écran de 2021-09-23 10-51-48

Where on both, the `pan` icon is used to explain an expandable box.

**Comment by Muqtxdir** [comment]
sorry, this makes sense now to me. Please change then

**Comment by Jupi007** [comment]
Done :)

Can you review, just in case?

**Comment by Muqtxdir** [comment]
looks good

**Pull request merged**
