### PR TITLE
Test PR: Toned-down folder icons (1)

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Before:

image

After:

image

Glyph folders:

image

Thoughts?

### CODE REVIEW

**Comment by madsrh** [comment]
I haven't tried this yet, but I'm a fan 😁 This looks much more balanced IMO!

**Comment by clobrano** [comment]
Tried and :+1:, it doesn't change a bit the Ubuntu way :)

**Comment by Feichtmeier** [comment]
Do we still need the backdrop opacity hack then?
And it looks nice

**Comment by madsrh** [comment]
> Do we still need the backdrop opacity hack then?

IMO the backdrop is unrelated to the folder icon color.

**Comment by ubuntujaggers** [comment]
Do you chaps also want to see the second suggested tones?

**Comment by madsrh** [comment]
> Do you chaps also want to see the second suggested tones?

If it's easy as pie 🥧 then yes that would be great

**Pull request merged**
