### PR TITLE
Darker disabled text for dark theme

### PR DESCRIPTION
**Pull request by madsrh**
Sorry, I didn't create an issue for this first. I made this PR with 33% but might I actually prefer 25%. What do you guys think?

Current (50%): 
image

This PR 33%:
image

Or 25%:
image

### CODE REVIEW

**Comment by clobrano** [comment]
Current 50% seems easier to read than the others. Something in between 50
and 33 percent, maybe?

**Comment by madsrh** [comment]
Alrighty then, this is 40% @clobrano 
image

**Comment by clobrano** [comment]
It looks good to me :+1:

**Comment by Feichtmeier** [comment]
image

I don't understand what's exactly wrong with the current dark insensitive color?

**Comment by madsrh** [comment]
> I don't understand what's exactly wrong with the current dark insensitive color?

It's just to make the difference more pronounced / more obvious.

**Comment by Feichtmeier** [comment]
I fear that it will look invisible elsewhere. Did you check the invisible fg colour in other widgets and other apps?
I think it's perfectly fine currently

**Comment by madsrh** [comment]
I've been using it here for some days and I haven't noticed any issues, but I did notice that the light/mixed theme could benefit from this too 🙈 I really find the current disabled/insensitive text to be too close to the regular text. This makes it easier to see what is disabled at a glance and IMO the text is still easily readable.

50% current vs. 40%
image

**Comment by Feichtmeier** [comment]
You better check on your thinkpad ;)

If you two guys like it - merge it :man_shrugging:

**Comment by madsrh** [comment]
> If you two guys like it - merge it 🤷‍♂

I wonder if that is me and @clobrano or me and @friendlyapple ?

Before you comment Carlo, please consider also the light theme (not in this PR) 👇 

> I've been using it here for some days and I haven't noticed any issues, but I did notice that the light/mixed theme could benefit from this too 🙈 I really find the current disabled/insensitive text to be too close to the regular text. This makes it easier to see what is disabled at a glance and IMO the text is still easily readable.

**Comment by clobrano** [comment]
Honestly, I see enough difference between normal and disabled in current, but as said above, it might just be my display.

**Comment by madsrh** [comment]
Okay, Frederik is 👎 so let's close this one. You can't win them all 😄

**Comment by friendlyapple** [comment]
@madsrh Personally, I liked the 40% 😄

**Pull request closed without merging**
