### PR TITLE
The very last non-uniform full colour icons: two missing "categories"

### PR DESCRIPTION
**Pull request by ubuntujaggers**
I de-squircled most of the full colour icons under "Categories" and then stopped because Ubuntu seemed to use the symbolics for this.  However, it turns out one of the missing ones (preferences-color) has a Gnome colour management app symlinked to it.  So, here's the non-uniform one:

image

Weirdly, even when I install the app, it shows on the launcher when I launch it from Software Centre, but the app is nowhere to be found in my shell app grid.  So, here are screenshots showing all five pngs on the launcher:

image

image

image

image

image

In the interests of full disclosure, the Suru icon for this was quite complex and the way I cropped it into the circles for the four small sizes was "hacky".  It's not a well-executed svg at all.  But as you can see, the pngs it produces are fine.  Don't worry if you don't want to merge this before the UI freeze because it's not a common or pre-installed app.

That just left literally one full colour icon that hadn't be de-squircled, preferences-desktop-accessibility.  I've found no instance of this that uses the full colour icon, but here it is while I'm working on the categories to make the complete set:

image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1250`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1250` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
Actually, don't merge, let me do the colour one properly or all the other svg people will laugh at me.

**Comment by ubuntujaggers** [comment]
SVG has been fixed, so test/merge as you see fit  :)

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1250`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1250` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Very nice thank you! Feel free to merge @clobrano

**Pull request merged**
