### PR TITLE
Added more mimetype icons again

### PR DESCRIPTION
**Pull request by madsrh**
Sorry for the vague description. More icons...

image

### CODE REVIEW

**Comment by madsrh** [comment]
Do you guys think we could use [the ebook above](https://raw.githubusercontent.com/ubuntu/yaru/e99bcc6939b44ff942ae692fcef1cf59bb44ecc7/icons/Suru/256x256/mimetypes/application-x-mobi8-ebook.png) as a generic ebook icon and replace this:
image

...and also symlink the Kindle ebook 📖 
It has the same format at a document and also the paper fold at the bottom, so I hope that it's clear that this is not an app.

**Comment by clobrano** [comment]
I think  I like the simplicity of the original ebook mimetype icon :(

**Comment by clobrano** [comment]
I can't test this mimetypes, but I think they are all alright, so feel free to merge them.
In the merge commit, please list the names of the mimetypes added :wink:

**Comment by madsrh** [comment]
Like that? 🙈

**Comment by clobrano** [comment]
Perfect 👍  thanks

**Pull request merged**
