### PR TITLE
Mate flavour

### PR DESCRIPTION
**Pull request by clobrano**
Initial proposal for a Yaru MATE gtk flavour

image

### CODE REVIEW

**Comment by clobrano** [comment]
@flexiondotorg, I tried to split the initial PR in commits to highlight the minimal steps, but feel free to ask any question :+1:

**Comment by clobrano** [comment]
PR #2332 might be helpful here

**Comment by clobrano** [comment]
Hey @flexiondotorg, this is the branch with the base for the Mate Yaru version.

**Comment by flexiondotorg** [comment]
Hi @clobrano, thanks for making a start on the MATE variation :+1: 

We've started the [hirsute/mate](https://github.com/ubuntu/yaru/tree/hirsute/mate) branch and things are starting to take shape. Is there any from this branch that should be merged into `hirsute/mate`?

**Comment by clobrano** [comment]
Let me have a look

**Comment by clobrano** [comment]
Ok, if I get it right, you used the `gtk/.../default` folder for Mate flavour, and applied your changes.
If that so, the meson changes in this branch are not necessary, and the style changes are already the ones you want in your branch, so this one is not necessary anymore.

**Comment by Feichtmeier** [comment]
Thanks @clobrano for your work on the flavours! Closing this then

**Pull request closed without merging**
