### PR TITLE
gtk: Add gtk-2.0 theme assets (light & dark) for accent color themes. Closes #3516

### LINKED ISSUE #3516: GTK2 components are missing for the new color selections in 22.04.
**Expected Behavior**

GTK2 applications should follow the selected color setting, or at least not look broken.

**Actual Behavior**

Light themes aside from the default orange revert to the orange GTK2 scheme in GTK2 applications, and dark variants look completely broken.

**Steps to Reproduce the Problem**

Open a GTK2 application when you've selected any accent color but orange. You can also switch to dark mode to see the broken elements as pictured below.

**Software that presents the issue**

Any GTK2 application.

**Yaru version**

22.04.2

**Screenshots**

(Note: Dark Sage scheme was selected for these examples, but it will happen the same way on any of the dark ones)

Screenshot from 2022-03-19 21-28-08

Screenshot from 2022-03-19 21-24-22

**Upstream check**

Not applicable to Adwaita.

### PR DESCRIPTION
**Pull request by flexiondotorg**
This pull requests adds gtk-2.0 assets for all the accent color themes. It also updated the mate gtk-2.0 assets to be consistent the the other accent colors. Light and Dark themes are correctly rendered.

This fixes #3516

### CODE REVIEW

**Comment by flexiondotorg** [comment]
Here are some examples:

## Yaru-blue

image

## Yaru-blue-dark

image

**Comment by flexiondotorg** [comment]
The Launchpad issue is related:

🐞 https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1965659

**Comment by 3v1n0** [comment]
Thanks for looking at this, however I'd really would like to avoid having such themes to be hardcoded, as themes may change any time and maintaining them is quite annoying.

So, my idea was to basically generate them as we do with the shell and Gtk 3/4 themes or `accented` icons, ideally using just an `accented` asset where we replace the relevant colors.

Could you look on that or should I handle it?

**Comment by flexiondotorg** [comment]
I do agree that what your propose is the best approach 👍

I don't have the time to integrate it with meson at the moment, which is why I did the quick fix 🙂 I would be happy to refactor it in the near future to work as you describe though.

You can merge what I provided, create an issue to request a refactor, and I will clean it up in the future or you can work on a more elegant solution.

Here is how I generated the gtk-2.0 assets:

```bash
#!/usr/bin/env bash

# gtk-2.0
# Calcualtions for prelights and lowlights

#           High contrast   Low constrast
# Hover:    SAT-10          VAL+5
# Activ:    HUE+10
# Insen:    SAT=20          VAL+5 SAT=10
# Insen Dk: VAL=30

for THEME in bark blue magenta mate olive prussiangreen purple red sage viridian; do
  case ${THEME} in
    bark)
        accent="#787859"
        hover="#858562"
        active="#737859"
        insensitive="#858577"
        insensitive_dark="#4D4D39"
        ;;
    blue)
        accent="#0073E5"
        hover="#177EE5"
        active="#004CE5"
        insensitive="#B8CFE6"
        insensitive_dark="#00264D"
        ;;
    magenta)
        accent="#B34CB3"
        hover="#B35DB3"
        active="#B34CA2"
        insensitive="#B38FB3"
        insensitive_dark="#4D204D"
        ;;
    mate)
        accent="#87A556"
        hover="#8DA566"
        active="#7AA556"
        insensitive="#98A584"
        insensitive_dark="#3F4D28"
        ;;
    olive)
        accent="#4B8501"
        hover="#51850F"
        active="#368501"
        insensitive="#79856A"
        insensitive_dark="#2B4D01"
        ;;
    prussiangreen)
        accent="#308280"
        hover="#3D8280"
        active="#307682"
        insensitive="#688281"
        insensitive_dark="#1C4D4B"
        ;;
    purple)
        accent="#7764D8"
        hover="#8979D8"
        active="#8B64D8"
        insensitive="#B4ADD8"
        insensitive_dark="#2A234D"
        ;;
    red)
        accent="#DA3450"
        hover="#DA4A62"
        active="#DA3434"
        insensitive="#DAAEB6"
        insensitive_dark="#4D121C"
        ;;
    sage)
        accent="#657B69"
        hover="#6F8773"
        active="#657B6D"
        insensitive="#7A877C"
        insensitive_dark="#3F4D41"
        ;;
    viridian)
        accent="#03875B"
        hover="#10875F"
        active="#038771"
        insensitive="#6C877E"
        insensitive_dark="#024D34"
        ;;
  esac

  mkdir -p gtk/src/${THEME}/gtk-2.0/
  mkdir -p gtk/src/${THEME}-dark/gtk-2.0/
  rsync -a --delete gtk/src/default/gtk-2.0/ gtk/src/${THEME}/gtk-2.0/
  rsync -a --delete gtk/src/dark/gtk-2.0/ gtk/src/${THEME}-dark/gtk-2.0/

  # DEFAULT
  sed -i "s|#E95420|${accent}|g" gtk/src/${THEME}/gtk-2.0/gtkrc
  sed -i "s|#19B6EE|${accent}|g" gtk/src/${THEME}/gtk-2.0/gtkrc     #link
  sed -i "s|#0b7196|${active}|g" gtk/src/${THEME}/gtk-2.0/gtkrc     #visited link

  # Accent
  sed -i "s|#f85731|${accent}|g" gtk/src/${THEME}/gtk-2.0/assets.svg
  sed -i "s|#f85731|${accent}|g" gtk/src/${THEME}/gtk-2.0/assets-external.svg
  # Hover
  sed -i "s|#f96640|${hover}|g" gtk/src/${THEME}/gtk-2.0/assets-external.svg
  # Active
  sed -i "s|#e55730|${active}|g" gtk/src/${THEME}/gtk-2.0/assets.svg
  sed -i "s|#c34113|${active}|g" gtk/src/${THEME}/gtk-2.0/assets.svg
  sed -i "s|#c74729|${active}|g" gtk/src/${THEME}/gtk-2.0/assets-external.svg
  # Insensitive
  sed -i "s|#fea691|${insensitive}|g" gtk/src/${THEME}/gtk-2.0/assets.svg
  sed -i "s|#f1a78d|${insensitive}|g" gtk/src/${THEME}/gtk-2.0/assets.svg
  sed -i "s|#f6b6a0|${insensitive}|g" gtk/src/${THEME}/gtk-2.0/assets.svg
  sed -i "s|#f1a78d|${insensitive}|g" gtk/src/${THEME}/gtk-2.0/assets-external.svg

  cd gtk/src/${THEME}/gtk-2.0
  ./render-all-assets.sh
  ./render-assets-external.sh

  cd "${YARU_DEV}"
  # DARK
  sed -i "s|#E95420|${accent}|g" gtk/src/${THEME}-dark/gtk-2.0/gtkrc
  sed -i "s|#2194bd|${accent}|g" gtk/src/${THEME}-dark/gtk-2.0/gtkrc     #link
  sed -i "s|#c97c5b|${active}|g" gtk/src/${THEME}-dark/gtk-2.0/gtkrc     #visited link

  # Accent
  sed -i "s|#f85731|${accent}|g" gtk/src/${THEME}-dark/gtk-2.0/assets.svg
  sed -i "s|#f85731|${accent}|g" gtk/src/${THEME}-dark/gtk-2.0/assets-external.svg
  # Hover
  sed -i "s|#f96640|${hover}|g" gtk/src/${THEME}-dark/gtk-2.0/assets-external.svg
  # Active
  sed -i "s|#e55730|${active}|g" gtk/src/${THEME}-dark/gtk-2.0/assets.svg
  sed -i "s|#c34113|${active}|g" gtk/src/${THEME}-dark/gtk-2.0/assets.svg
  sed -i "s|#c74729|${active}|g" gtk/src/${THEME}-dark/gtk-2.0/assets-external.svg
  # Insensitive
  sed -i "s|#bf6a57|${insensitive}|g" gtk/src/${THEME}-dark/gtk-2.0/assets.svg
  sed -i "s|#bf6a5f|${insensitive}|g" gtk/src/${THEME}-dark/gtk-2.0/assets.svg
  sed -i "s|#b56d54|${insensitive}|g" gtk/src/${THEME}-dark/gtk-2.0/assets.svg
  sed -i "s|#92442e|${insensitive_dark}|g" gtk/src/${THEME}-dark/gtk-2.0/assets-external.svg
  cd gtk/src/${THEME}-dark/gtk-2.0
  ./render-all-assets.sh
  ./render-assets-external.sh
done
```

**Comment by 3v1n0** [comment]
> Just be aware is takes absolutely ages to generate all the gtk-2.0 assets hourglass_flowing_sand So you don't want to do this on every build.

No, of course... Just would like to integrate it in the CI jobs that handle rendering of icons... For example see https://github.com/ubuntu/yaru/pull/3547

So meson will only handle the logic, as it's all integrated there already, but it won't be used in targets that are normally used for normal builds.

Thanks for sharing the script though, I will integrate it.

**Comment by 3v1n0** [comment]
Same here... Let's include this for now, I will generate them on an upcoming refactor.

**Pull request merged**
