### PR TITLE
DON'T MERGE Test PR with non-uniform Suru icons

### PR DESCRIPTION
**Pull request by ubuntujaggers**
Not for merging - just a test PR with seven new non-uniform Suru icons, using the same vector graphic at all sizes, so we can see how it looks on the launcher and in the app grid.

If it doesn't look great we'll refine the template further ( <-- most likely outcome!) and if it _does_ look great, I'll write up the template as a style guide and finish/tidy up the base svgs  :)

The guinea pigs are:

**accessories-text-editor:**

image

**clock-app:**

image

**gallery-app:**

image

**help-app:**

image

**rhythmbox:**

image

**system-monitor-app:**

image

**system-settings:**

image

I haven't included software centre because we weren't thrilled with the circular background.  Note: one of the shapes in the new mixed icon set would still be the Suru squircle, so I recommend including file manager and a couple of other Suru icons on the launcher when you test these, to see if they play nicely together.

Snaps don't work for me because I upgraded - it would be brilliant if someone had five mins to try the snap, when it appears, and screenshot the app grid and launcher  :)

Edit by @Feichtmeier : current progress should/could be written down here: https://github.com/ubuntu/yaru/issues/1180 thanks to @madsrh for the list <3

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1164`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1164` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
One of the things I will propose when/if I write this up and make the templates is that we retire the layers in the svg apart from two: baseplate and icon.  The layers make no difference to the script output and are just quite fiddly.  Also, I'm not sure of the value of having separate layers for the shape (previously squircle) and pictogram when some of the icons are objects that take up the whole shape?  It seems like an extra bit of admin with not much gain.

**Comment by Feichtmeier** [comment]
Testing now - I'm thrilled :clinking_glasses: 

Rythmbox works but there seems to be something leaking out of the grey ring
image

Gallery app looks great too 
image

Help works too and looks great imho
image

Settings, gedit, clocks, systemmonitor dont work currently. Maybe the symlinks are wrong? :thinking:

**Comment by ubuntujaggers** [comment]
Bah!  Symlinks!  Of course!

Thanks for screenshotting, investigating now  :)

**Comment by ubuntujaggers** [comment]
Hmm, this is weird - looking at the symlinks list I seem to have the right names, and when I open the symlinks in file explorer I get the right (new) icon:

image

Found/fixed the problem with Rhythmbox, but I'm scratching my head about the others.

Do the ones that worked look okay in app grid too?

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1164`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1164` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Can't test today but how does it look on your Ubuntu system?

**Comment by ubuntujaggers** [comment]
> 
> 
> Can't test today but how does it look on your Ubuntu system?

Dunno, I never worked out how to test things without snap but I found your instructions here https://github.com/ubuntu/yaru/pull/1082#issuecomment-452016043 and will try to follow them now  :)

**Comment by Feichtmeier** [comment]
If you are using the a VM: remove the communitheme snap and then....

ow the instructions in the README.md.

### Needed before install 
sudo apt install libgtk-3-dev git meson sassc 
### Download the repository from github git clone https://github.com/ubuntu/yaru.git 
cd yaru 
### Initialize build system (only required once per repo) 
meson build --prefix=/usr
cd build 
### Build and install
sudo ninja install

Reboot and select Yaru session
Now every time you want to install new icon changes run
sudo ninja install
Again and eventually toggle the icon theme Bacj and forth of the cache isn't updating

**Comment by ubuntujaggers** [comment]
@Feichtmeier you legend!  Not sure why I couldn't get it working before, but after following these steps I'm now in business :+1:  Thanks as always for helping me with the technical bits.

This is the first time I've seen any of my icons for real, what a treat.

Okay, not all the icons have worked yet, and I can't work out what app actually shows the gallery icon, I just seem to have Shotwell (polaroid icon) and EOG (monochrome icon with magnifying glass).  **But** looking at the icons that are working, I think this approach is a roaring success.  Non-uniform Suru icons look nice together:

image

And IMO they look less weird mixed with third party apps:

image

And also I think they look fine in app grid as well as launcher:

image

image

image

They don't even look terrible at smaller launcher sizes, although they will never be crystal clear (this is unavoidable, especially when we switch to one svg):

image

Personally, despite having opposed non-squircle icons when they were first suggested  :)  I'm now very much in favour of picking this approach and choosing it for Yaru.

**Comment by Feichtmeier** [comment]
Nice!
I honestly prefer those to the unified form approach because as you said they look much less weird when you mix them with non-suru icons
For the gallery app you could install gnome-photos

**Comment by ubuntujaggers** [comment]
> For the gallery app you could install gnome-photos

Yep, that worked perfectly :+1:  I didn't spot that one in software centre.

I've started writing up the beginning of a Yaru app icon style guide:


**MISSION STATEMENT**

Yaru app icons curate and expand the pictogram designs from Suru.

Yaru reconfigures these so the squircle is no longer a unifying device.  Yaru app icons still have backgrounds, and the backgrounds still have Suru-style highlights and folds.  However, we using a mix of shapes instead of just one.

We use Suru pictograms where possible, and draw new pictograms in the same style using the same palette, following the Suru style guide for elements such as drop shadows.

As with Suru, there will be two kinds of design: ones that show a pictogram on a shape (e.g., Help) and ones where the whole shape is decorated to make an object of that shape (e.g., Rhythmbox).

**FILES**

A Yaru app icon is designed as a single svg in a 192px square, aligned to a 4x4 grid.  This means that the svg is optimised for sharpness at multiples of 48px, which is the size of the Ubuntu launcher.  This 192px svg is the **source file** for the icon.

Each of the core shapes (see below) will have a blank template at 192px.  The template will have at most two layers (one for the icon and one for a "baseplate" if required).

When working from an existing Suru icon, we start with the 48px one, because this is optimised for Ubuntu's preferred sizes (unlike the 256px one, which scales better to 64px and 32px).

After Gnome switches to having a single svg for full colour icons, we'll either ship the source files as they are or rescale them to 128px (as per Gnome guidelines) if this turns out to be necessary.

While Yaru is still using the "five sizes" template from Suru with multiple pngs, we'll simply scale the source files and insert them into the template at each size.  We won't "pixel fit" or optimise the smaller sizes, because this will create false expectations of quality that won't survive the switch to one svg.  Rather than making new versions of the Suru template with the different shapes in five different sizes, we'll ask icon designers to create their icons in the 192px templates, and simply paste them into the Suru one for as long as we need to use it.

**BACKGROUND SHAPES**

There are two types of shape for Yaru app icons: core and non-standard.

**Core**

The core shapes for Yaru app icons are:

**Squircles.**  These should be used for square-ish pictograms, as well as designs that simply don't suit any of the other shapes (example: file manager).

**Horizontal oblongs.**  These are the same shape as the generic image mimetype.  Horizontal oblongs should be used for app icons where the design evokes any of the following:

- An image, or any other landscape-orientated document (example: gallery)
- A monitor or screen (example: system-monitor-app)
- An open app window (example: terminal)
- A real world object that normally approximates this shape (example: camera)

**Vertical oblongs.**  These are the same shape as the document mimetypes and the recycle bin.  Vertical oblongs should be used for app icons where the design evokes any of the following:

- A text document, or any other portrait-orientated document (examples: notepad, PDF viewer)
- A real world object that normally approximates this shape (examples: Rhythmbox, address book)

**Circles.**  These should be used for round-ish pictograms, and also pictograms that are based on alphanumeric characters or glyphs of no particular shape (example: help).

**Non-standard**

We have the option of creating other simple geometric shapes when it suits the design (example: a triangular warning sign for alerts, and possibly a simple shopping bag for software centre).

**Comment by ubuntujaggers** [comment]
Okay, I ran the symlink script and all new icons are working in this branch, **but** I now have a billion changes when I do git status :sob: 

Still: don't want to blow me own trumpet, but I think these look great.  Just Yaru:

image

...and mixed in with third party icons:

image

So, that's what it'll look like, and I actually love it.  Is it an official thumbs-up from the Yaru team: @madsrh, @clobrano, @Feichtmeier?

**Comment by ubuntujaggers** [comment]
Yaru terminal  :)

image

**Comment by Feichtmeier** [comment]
> **but** I now have a billion changes when I do git status

Yes, @clobrano upgraded the script and now you can specify which src-icon should have symlinks created
./generate-symlinks.sh SRC_ICON_NAME DEST_ICON_NAME

You could revert all with your Git-gui-tool and then use the script again for specific icons only

Ontopic: I prefer this icons, too - but would like to see more of the pre-installed (gnome)-apps de-squircled before we can be sure + also remove the "politically critical"-icon overwrites like polari, thunderbird, firefox and LO :)

**Comment by ubuntujaggers** [comment]
A few more - backups-app, disk-usage-app and docviewer-app:

image

...and here they are in the app grid:

image

image

**Comment by Feichtmeier** [comment]
Wow I love the disks icon!
Deja-dup (backup) and the PDF viewer look also nice

**Comment by Feichtmeier** [comment]
For files... what about this?

image

**Comment by ubuntujaggers** [comment]
I need to work out how to remove Firefox and LibreOffice.  I tried deleting all the pngs for those icons from the various folders and running ninja install but they're still there.  When I work out how to get rid of them I'll post a screenshot showing Yaru icons with upstream Firefox and LO.

Also...  do we definitely need to use the 100% upstream icons for LO.  I only ask because we already have beautiful mimetypes in the right shape and style to be used as new Yaru app icons, which also look great on the launcher.  Didrocks seemed relaxed/happy for us to have our own (respectful) icons for LibreOffice, and there was no uproar on OMG! Ubuntu! when Joey posted the squircle screenshots showing themed icons for LibreOffice.  So maybe we could now use the mimetypes as app icons  :)  :pray: 

Additional: just saw your post for files, I'll give it a whirl  :)

**Comment by Feichtmeier** [comment]
@ubuntujaggers yes they are still there because you 

1) create SVGs (inside the yaru git folder)
2) export PNGs (inside the yaru git folder)
3) use ninja to install them into /usr/share/icons
and there the icons are still there
you need to remove the suru icon folder 
First change to a different icon theme so you system to crashes, then
sudo rm -r /usr/share/icons/Yaru
then ninja install again

**Comment by ubuntujaggers** [comment]
Yet again you've saved me from my Linux incompetence  :)  Worked a treat.

**Comment by ubuntujaggers** [comment]
What do you think:

image

?

**Comment by ubuntujaggers** [comment]
@Feichtmeier:

image

image

image

Since we're not doing squircles, we could also just reuse the orange folder icon that you actually see in file manager?

**Comment by ubuntujaggers** [comment]
...and here's the default out-of-the-box launcher, so far:

image

:)

**Comment by Feichtmeier** [comment]
I am a fan so far :clinking_glasses: 

When you found time to push a new commit, let's sit back and test it on our machines!

**Comment by ubuntujaggers** [comment]
Since we're not actually going to merge this test branch, can I just commit-all and work out which symlinks I need when we do it for real?  Because then you could try it instantly through the snap  :)

**Comment by Feichtmeier** [comment]
If it's not double work for you okay we can do it this way.
Otherwise maybe we could work out what happened if you post a screenshot of your git-gui-tool you've chosen

**Comment by madsrh** [comment]
So, what is the goal for 3rd party apps? That they keep their untouched upstream icon or _just_ that now they don't look so out of place when mixed with suru icons? (maybe I missed some discussion here)

If we're keeping suru LO icons (or was that only mime?), would something like this also be possible?

image

**Comment by ubuntujaggers** [comment]
> Otherwise maybe we could work out what happened if you post a screenshot of your git-gui-tool you've chosen

I'm embarrassed to report that I chose Gitkraken and couldn't understand it, and haven't yet got round to learning it (sorry).  So I'm just using terminal and pressing up arrow to use the commands that I already know.  I'll go through the user guide for Gitkraken.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1164`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1164` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
> So, what is the goal for 3rd party apps?

Current proposal (key word proposal) is to leave them untouched, and everyone will feel better about the resulting mix because you no longer have the square, square, square, triangle problem.

I guess if we were going to add background to third party icons we could stick with squircles  :)

The snap is there now - have a go and see what you think.  I've got to say, using it for real, the (natural) mix of Yaru and third party icons looks pretty good on my launcher, to me at least.

**Comment by Feichtmeier** [comment]
If we have the chance to get rid of the uniform shapes and dodge the third party politics with this concept we should not modify tb,FF and lo imho

**Comment by Feichtmeier** [comment]
@ubuntujaggers testing it now: I wonder  why are some borders so thick? Even in the 256px icons in the shell's app grid? It looks like some or all outer borders are now 4x as thick
image

**Comment by ubuntujaggers** [comment]
> @ubuntujaggers testing it now: I wonder why are some borders so thick? Even in the 256px icons in the shell's app grid? It looks like some or all outer borders are now 4x as thick

So, this is basically something we have to decide.

One thing I've done is use exactly the same vector for all sizes, to simulate what it will be like when we switch to one svg - rather than designing different svgs for the different sizes like I did in the past.

Using the one svg approach, if we want a 1px border on the launcher, we have to accept a slightly thick-looking border when the icon is bigger, on the app grid.  Alternatively, if we make it so the border is less bold on the app grid, it will be <1px on the launcher, so likely vanish entirely or look low-quality (anti-alias = non-sharp edges).

There's no easy answer to this - it's precisely why things won't be quite as good when we just have a single svg.  Manually working on five different icons meant you had different borders for each size, that were suitable for that size.  I guess Gnome's point of view was that it was too much to ask of icon designers.  This is possibly why they've gone for a bold look with their new icons (without fine 1px details).

I do think a clear 1px border at 48px helps with visibility, especially on lighter backgrounds, like when the icon has a glow around it:

image

...which is why I prioritised that for this first experiment.

**Comment by Feichtmeier** [comment]
Yes experiments are what we do!

I think this fat border for all sizes approach looks really not that visually appealing and doesn't fit to the sharp look of yaru with the thin lines and so on
Could we also make a test where you use the 256px icons for all sizes?

**Comment by ubuntujaggers** [comment]
> Could we also make a test where you use the 256px icons for all sizes?

Yes, these first icons have done the "48px style" at all sizes, next we can try the "256px style" at all sizes.

Although it might be better to do some svgs in the "256px style" in a size that's a multiple of 48px, so the pictograms lines don't blur on the launcher.

**Comment by ubuntujaggers** [comment]
@feichtmeier @madsrh here's a quick preview.  Two notepads on the launcher.  Top is what it looks like when we base the single svg on the 48px style.  Bottom is what it looks like when we base the single svg on the 256px style.  The pictogram is a bit different because the 256px notepad has fainter lines and slightly darker paper than the ones I did in the new icon, but try to mentally filter that out - we can make the lines and shape whatever colour we prefer.  The key thing to consider is the edging on the icon:

image

Here they are with highlights around them:

image

This was possibly not the best icon to try first :) because it's too pale to have a visible highlight at the top - but, if this was a dark or colourful icon, the white shine would also be missing or much less visible at the top when it appeared on the launcher - I mean this bit:

image

...although we could try to do a "hybrid style" that has the 48px-style highlight without the 48px-style border?

Here are both the notepads in the app grid:

image

At the risk of sounding like the voice of doom: if/when we switch to one svg, either the launcher icons _or_ the app grid icons will look a little bit worse than they do now, because we won't have different icons optimised for each context.  So, we would have to make a decision about which one is more important  :(

**Comment by Feichtmeier** [comment]
> At the risk of sounding like the voice of doom: if/when we switch to one svg, either the launcher icons _or_ the app grid icons will look a little bit worse than they do now, because we won't have different icons optimised for each context. So, we would have to make a decision about which one is more important :(

We could alternatively keep the current png_for_all_sizes solution until we have a working alternative. For example a solution where the standart dock size is optimized for a new svg approach and so on. 
The text editor works indeed because the outline is transparent black. But the black baseshapes have the transparent white as their outline and those looks really really bulky (system monitor, backups etc)

**Comment by ubuntujaggers** [comment]
"The text editor works indeed because the outline is transparent black."

Could explore having one template for pale icons and one for dark ones?

**Comment by ubuntujaggers** [comment]
> We could alternatively keep the current png_for_all_sizes solution until we have a working alternative. For example a solution where the standart dock size is optimized for a new svg approach and so on.

You know, I think I would be in favour of keeping the png-for-all-sizes approach forever?

I guess that Gnome will need to know how to display pngs indefinitely, for legacy and abandoned apps that people still use (because those won't get a new icon any time soon).  So, could we consider sticking with the current implementation?  Then we can have the beautiful sharply-edged icons on the app grid and also keep the more button-y icons on the launcher, exactly as we do today.  Otherwise we have to choose one design for all sizes.

There are two advantages to multiple sized icons.  One is that you can reduce antialiasing, and you're right that changing the dock size would help when we lose that option.

But the second advantage is you can just "reimagine" the icon a bit for different sizes, so it looks great big and small.  Example: having fine details that are 1px on the big icon and also 1px on the small icon.  If you have one svg for all sizes, there's no solution to that.  Either you make the details chunky in the large size (so they're 1px in the small size) or you make them 1px in the larger size, and accept that they won't be visible or will blur a bit in the smaller size.  Gnome's new icon set seems to be going with the former, which is why they look a bit cartoonish to us.

I would say that Gnome has definitely, consciously decided that ease of icon creation is more important than super-sleek-looking icons, and the new HIG approach has ease of creation in mind rather than eye candy.  But I know that we like eye candy  :)

So, is it 100% necessary to switch to one svg for all sizes?  I'm more than happy to do five-size templates for the new shapes and make the non-uniform icons in those.  It will be more time consuming, but it will look better (as good as current) and is definitely worth it if we continue to use the other sizes in Yaru.

**Comment by Feichtmeier** [comment]
> So, is it 100% necessary to switch to one svg for all sizes? I'm more than happy to do five-size templates for the new shapes and make the non-uniform icons in those. It will be more time consuming, but it will look better (as good as current) and is definitely worth it if we continue to use the other sizes in Yaru.

From my point of view it is not necessary. I would even say from my observation the ubuntu desktop is not ready for that. Maybe bleeding edge modern gnome apps without a dock extension (=vanilla gnome 3.32) could be ready for that, but imho ubuntu not. There are several programs which use the small icons full color icons and ship with ubuntu for at least 2 version from now on. 
What are @madsrh and @clobrano opinion on that question?

**Comment by clobrano** [comment]
I agree. It's enough for us to be ready for when it will be the standard, but now let's keep shipping 5 sizes

**Comment by madsrh** [comment]
I agree - lets strive for beautiful sharp icons

**Comment by ubuntujaggers** [comment]
This is brilliant news! It will take a bit longer but non-uniform Suru will be beautiful this way, and it's not like we have any third party apps to do :)

**Comment by Feichtmeier** [comment]
@ubuntujaggers take your time! Could you add back the thunderbird symbolic icon though? Unlike firefox, thunderbird does not come with a symbolic icon by default 🤷‍♂️

**Comment by ubuntujaggers** [comment]
Bizarrely, if Yaru has a symbolic icon but no full colour icon, it seems to use the symbolic icon on the app grid! It's like it tries its best to use an icon from theme, even when the theme only has an inappropriate one. So not sure (yet) how to have a symbolic icon when we don't have a full colour one anymore.

**Comment by ubuntujaggers** [comment]
Here's another sneak preview.  Current Suru icon for notepad in all five sizes:

image

...and here's the work-in-progress non-uniform version with different sizes:

image

It's shaping up to have exactly the same advantages of each size - it's got nice borders on the smaller sizes but is almost "edgeless" in the full size version  :)

**Comment by ubuntujaggers** [comment]
Here are the templates so far for two of the new shapes:

image

image

**Comment by ubuntujaggers** [comment]
Okay, a bit of a comparison using terminal and notepad.

Current Suru launcher:

image

Non-uniform five sizes Suru launcher (WIP):

image

Current Suru app grid:

image

Non-uniform five sizes Suru app grid (WIP):

image

??

**Comment by Feichtmeier** [comment]
Pretty nice imho! Awesomeness.

**Comment by madsrh** [comment]
Very nice @ubuntujaggers :tada:

**Comment by ubuntujaggers** [comment]
@Feichtmeier @madsrh @clobrano 

I think (hope!) you'll really like this...  screenshots of non-uniform five size approach.

Launcher with 48px pngs:

image

Icons in app grid with 256px pngs:

image

image

image

image

image

Bigger 256px versions in app search results:

image

image

Although the icons take a little longer to do in five sizes, we make a time saving elsewhere with this approach: the icons we leave as squircles won't need reconfiguring as single-svg versions, so we can just leave the src files and pngs exactly as they are for those icons.  So, once we have a set of icons we're happy with in a test branch, we can just replace some of the existing icons one-by-one (through individual PRs) to mix the shapes up  :)

**Comment by madsrh** [comment]
Great work again @ubuntujaggers
I love that things are moving forward even though I am interrupting you all the time :)
I know that a [squircle watch](https://www.watchingclocks.co.uk/ekmps/shops/watchingclocks/images/Retro-Square-Black-Silent-Sweep-Wall-Clock-1058-p.jpg) exist, but how about making the Clocks app round 😆  🕙

**Comment by ubuntujaggers** [comment]
Interrupt as much as you like, the more people using Inkscape for Yaru the better  :)

Here's your clock:

image

...and I did camera-app too:

image

:)

**Comment by ubuntujaggers** [comment]
image-viewer:

image

**Comment by ubuntujaggers** [comment]
And back where I started, with gnome-aisleriot:

image

**Comment by ubuntujaggers** [comment]
image

**Comment by Feichtmeier** [comment]
So much better than squircles! I think this is the right solution for our problems great work thank you!

**Comment by Feichtmeier** [comment]
Shouldn't we make a check list for preinstalled gnome apps at this point!? :)

**Comment by clobrano** [comment]
Wonderful work!

**Comment by madsrh** [comment]
> Shouldn't we make a check list for preinstalled gnome apps at this point!? :)

I've listed apps from the grid [here ](https://github.com/ubuntu/yaru/pull/1164#issue-251695051) but some preinstalled application like Vim (isn't the Clock preinstalled 🤔 ). Please, feel free to edit the list.

**Comment by Feichtmeier** [comment]
@madsrh they plan to pre install it. It's definitely not gnome branded and a generic core app (that's how they list it)
So I guess it is unproblematic but needs double check

**Comment by ubuntujaggers** [comment]
Quick response from me: cheers for doing the list, will update it  :)

Just an experiment, how do you feel about another shape for more variety, I'm calling this "square" (less rounded than the squircle):

image

image

I was wondering if this might help when you get a run of three or four square-ish icons together due to alphabetical ordering, maybe it won't look as much like a group of un-updated icons if some are "squares" and some are Suru squircles?  Just a thought.

**Comment by Feichtmeier** [comment]
Nice idea with the fourth shape
I wonder if we need the regular squircles at all? I wonder if people will still think the theme is incomplete because they associate the old squircle only approach?

**Comment by ubuntujaggers** [comment]
> I wonder if we need the regular squircles at all? I wonder if people will still think the theme is incomplete because they associate the old squircle only approach?

Me too, but it's like a mental block because of what I'm used to, I don't know whether that's a feeling that will last and whether new users will feel the same.  I was thinking the same thing about the squircles and I'm just not sure.  One possibly advantage of both is that we have five core shapes rather than just four.  Also some icons are just gorgeous as they are (one of my favourites is Calendar).  Let me rustle up a snap and then we can all try it for real.

**Comment by madsrh** [comment]
> I wonder if people will still think the theme is incomplete because they associate the old squircle only approach?

The attention on OMG was really bad timing. Suru has changed a lot and there's so many variants with that same name. 

- Suru for Ubuntu Touch initially by Matthieu James
- Suru by Sam Hewitt
- Suru++
- Suru in Ubuntu 18.10 by Yaru

I've said before that because of the new direction, I think we should rename the iconset to _Yaru_ or _Suru 2.0_ or whatever. It might have be mentioned as a joke, but maybe it's a good idea 🤷‍♂️ (Isn't it already called Yaru in Tweaks?)

**Comment by Feichtmeier** [comment]
Yes the theme name is Yaru
Only the Folder and the snap icon name are still Suru
there is a second PR, can we close this one @ubuntujaggers? Just to not diverge the channels

**Comment by madsrh** [comment]
@Feichtmeier 

> I've said before that because of the new direction, I think we should rename the iconset to _Yaru_ or _Suru 2.0_ or whatever. It might have be mentioned as a joke, but maybe it's a good idea 🤷‍♂️ (Isn't it already called Yaru in Tweaks?)

I meant this one:

image

**Pull request closed without merging**
