### PR TITLE
Fix system-lock-screen twisted path

### LINKED ISSUE #2201: System-lock-screen icon has  twisted path
Capture d’écran du 2020-06-05 19-05-40

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Closes #2201

### CODE REVIEW

**Comment by Feichtmeier** [comment]
:wave:  Thank you very much!

In which order should we merge those files to avoid a conflict in source-symbolic.svg?

Best regards

**Comment by Jupiter007-43** [comment]
I did this pull in last, so I think you should merge it in last too.

**Comment by Jupiter007-43** [comment]
I deleted by mistake the commit... 😓
Should I create a new pull request?

**Comment by Feichtmeier** [comment]
Yes, sure =) Just make a new one ,  and thank you!

**Pull request closed without merging**
