### PR TITLE
New symbolic app icons, plus missing image

### PR DESCRIPTION
**Pull request by ubuntujaggers**
For testing...

image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1245`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1245` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
Also, does image-missing work?  Not sure how to test it...

**Comment by Feichtmeier** [comment]
Yeah, we don't know

**Comment by Feichtmeier** [comment]
Could you also add a symbolic icon for that new applications row in settings?
image

**Comment by eaglersdeveloper** [comment]
> Could you also add a symbolic icon for that new applications row in settings?

How about Software icon for it?

Apple uses App Store logo for Applications folder:

**Comment by Feichtmeier** [comment]
Good idea! We need the name though 🤔 didn't find it yet

**Comment by Feichtmeier** [comment]
And another request @ubuntujaggers : could you also add "color-select" and "font-select" under "actions" ? :D Those are missing in yaru
image
image

**Comment by ubuntujaggers** [comment]
Just pushed the following:

- Actions for font-select and color-select
image

- An icon cloning software "A" which, based on the names of other icons, I've called preferences-system-applications (I can't test it because I don't have it yet, but we can try -apps and other names if it doesn't work :) )

- An improvement to all horizontal oblong symbols that can't be perfectly centred vertically because it's an odd number of pixels.  These are now 1px low instead of 1px high, which aligns much better with the name of the app.

**Before:**
image

**After:**
image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1245`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1245` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
image

Works! Thank you!

That apps-icon does not seem to work :( but
I don't find that apps-icon here :( https://gitlab.gnome.org/GNOME/adwaita-icon-theme/blob/master/src/symbolic/gnome-stencils.svg

**Comment by ubuntujaggers** [comment]
I'll try pushing a slightly different name

**Comment by ubuntujaggers** [comment]
Tried two different names...

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1245`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1245` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Yay @ubuntujaggers I found it in papirus ^.^

image

application-x-executable-symbolic.svg

**Comment by ubuntujaggers** [comment]
Does it work...?

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1245`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1245` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Works!

image

**Comment by ubuntujaggers** [comment]
Just made a small correction to usage-app symbol.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1245`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1245` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
...and small improvements to scanner and e-book reader.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1245`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1245` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by ubuntujaggers** [comment]
Apologies for the garbled commit message, "ironicallygitstatus" was meant to say "ironically!!".

Push image-missing, apologies, don't know how that was left out.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1245`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1245` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Pull request merged**
