### PR TITLE
Fix legacy 16x16 mail icons twisted paths

### LINKED ISSUE #2100: Legacy 16x16 mail icons have twisted paths
I missed the legacy mail icons:

Capture d’écran du 2020-03-21 15-26-43

### PR DESCRIPTION
**Pull request by Jupiter007-43**
Closes #2100

### CODE REVIEW

**Comment by ubuntujaggers** [comment]
Thank you!

**Comment by Jupiter007-43** [comment]
You're welcome!

**Comment by clobrano** [comment]
@ubuntujaggers, do you agree on merging this?

**Comment by ubuntujaggers** [comment]
Yep sorry

**Comment by clobrano** [comment]
Oh, no need to say sorry :)

Thanks @Jupiter007-43 :+1:

**Pull request merged**
