### PR TITLE
misc. changes to gnome-shell assets

### PR DESCRIPTION
**Pull request by Muqtxdir**
This PR does:

- [x] Make the switch-toggles present in GNOME- shell look similar to GTK4 switch-toggles
     - [x] dark switch-toggles compared alongside dark GTK4 switch-toggles (*see GIF*)
     Peek 2021-08-08 18-15
     - [x] light switch-toggles compared alongside light GTK4 switch-toggles (*see GIF*)
     Peek 2021-08-08 18-16

- [x] Removed other .SVG files not present under upstream.

Thanks!

### CODE REVIEW

**Comment by Jupi007** [comment]
@Muqtxdir I agree with all your changes except the barlevel height because it looks blurry (see #2737), I'm sorry.
But if you found a way to increase the size without this blurred look I would say yes at once.

**Comment by Muqtxdir** [comment]
oh, sorry wasn't aware of the blurry issue with the sliders. reverting that commit :+1:

**Comment by Jupi007** [comment]
No problem, thanks :)

**Review by Jupi007 — APPROVED** [review]
Everything looks okay, and those switches are so gorgeous :)
So OK for merge (except if @Feichtmeier want to veto 😉).

**Comment by Feichtmeier** [comment]
LGTM 👍

**Pull request merged**
