### PR TITLE
New pushed button effect

### PR DESCRIPTION
**Pull request by godlyranchdressing**
[Seen here](https://github.com/ubuntu/gtk-communitheme/issues/302#issuecomment-384310559). 

It's still open for discussion and finetuning. No rush, since I'm not sure if this fits into what @ya-d was looking for and for some reason line 254: 

`border-color: if($c==$headerbar_bg_color, lighten($_border, 5%), $_border);` 

Doesn't seem to work and I'm not sure why. $c _is_ $headerbar_bg_color.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Maybe set a second variable? Not sure about how powerful sass is there since you use the lighten function in the if

**Comment by clobrano** [comment]
> for some reason line 254:
>     border-color: if($c==$headerbar_bg_color, lighten($_border, 5%), $_border);
> Doesn't seem to work and I'm not sure why

What is the expected behavior? Considering $_border definition at the top

    $_border: if($c == $button_bg_color, $borders_color, darken($c, 10%));

I would expect $_boder to be like `darken($headerbar_bg_color, 5%)`

**Comment by Feichtmeier** [comment]
God I love this, really. Sorry for for much emotion but I think this gives the theme the final cut 
peek 2018-04-26 12-33

@godlyranchdressing that review: carlo is the one for this, I don't even understand everything you did there =)

**Comment by CDrummond** [comment]
I like these changes too - I even think that with this change both #260 and #288 can be closed. Especially #260 - as with less of a shadow, the blurry-ness goes.

**Comment by godlyranchdressing** [comment]
Nevermind, I didn't spot $c being reassigned to something else and making my if statement conditions wrong. I just moved my statement earlier and it's working now. This should be okay to merge if everyone is fine with the outcome:
b
a

**Pull request merged**
