### PR TITLE
Set top-panel always full opaque

### LINKED ISSUE #1201: GNOME Shell 3.31.90 top bar always translucent
- yaru version 19.04

gnome-shell 3.31.90 is now in disco-proposed so I installed it.

GNOME Shell turned off the top-bar translucency feature and made it always opaque. This works in the GNOME session but in the Ubuntu session, the top bar is now always translucent even if an app is maximized.

I suspect the Yaru GNOME Shell theme will need to be updated to fix this issue.

### PR DESCRIPTION
**Pull request by clobrano**
gnome-shell 3.31.90 removed top-bar translucency feature in a way that the
settings we use for the `.transparent` class are used when the windows are
maximized.

This commit sets the transparency for top-bar at zero always. Since the comeback
of this feature is currently discussed, it is better to keep al the logic in place
so that it will be easy to reuse it later.

closes #1201

## known issue
~- [ ] [EDIT: in 19.04 only ] dashtodock is totally black when windows is maximized~

### CODE REVIEW

**Comment by clobrano** [comment]
Full dark dock on maximized windows is a different issue, so feel free to review the PR :)

**Comment by Feichtmeier** [comment]
Hmmm built your branch in disco daily, now the dock is always opaque, too. But when I maximize a window there is a jumping back to transparent and then becoming opaque again (that's the old transition I guess) which is still left.
Updating the VM now and seeing if there is any update for dashtodock, otherwise this might need more work

**Comment by Feichtmeier** [comment]
Maybe here: https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/gnome-shell-sass/_dock.scss#L103
And here: https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/gnome-shell-sass/_dock.scss#L109

@clobrano maybe since they removed the style class for the panel, it's also gone for the dock?

**Comment by clobrano** [comment]
I believe it's different. The panel is by default in "transparent" mode (which is now totally opaque, regardless the name) and had a class to style it when `solid`, while the dock had both.

I'll fix the transition

**Comment by Feichtmeier** [comment]
So fully opaque panel and dock is the desired behaviour? 
If desired or not I must admit that it looks quiet good :thinking: 
At least better than I imagine a black panel and a transparent dock looks

**Comment by clobrano** [comment]
> So fully opaque panel and dock is the desired behaviour?

Yes, I think it's better have them work the same way

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1207`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1207` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
I think it looks good now with non-maximized and maximized windows.
But I really loved the opaque look when you press the super button/click activities, i.e. activate the dash :(
Any idea how we can keep that? Now everything is opaque, in dash view and out of dash view

**Comment by clobrano** [comment]
Right, I'll check if it's possible to keep the transparency in overview mode

**Comment by clobrano** [comment]
I adjusted overview state as @Feichtmeier suggested. Please test it, I'm not 100% sure the colors are exactly the same

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1207`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1207` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@clobrano 
The overview mode is exactly like in master and the transition is working as expected :+1: perfetto!
peek 2019-02-27 19-10


But! :D the dock has a darker color than the top panel in maximized mode:
image

**Comment by clobrano** [comment]
That's what I said ;D it's a problem in dock

**Comment by Feichtmeier** [comment]
You mean that that is a new "issue" with dashtodock we can't solve from our side? Or is it "only" a problem of finding a fitting color?

**Comment by clobrano** [comment]
I meant that I have this same problem using master branch, so I suppose it
does not depend on my PR. Could you reproduce it as well on master?

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1207`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1207` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Still black

image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1207`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1207` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/yaru-pr1207`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/yaru-pr1207` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
included in #1234

**Comment by clobrano** [comment]
not necessary anymore (see #1234)

**Pull request closed without merging**
